>AILMEGL192392_1_2.PE9                 429 CDS /gene="ENSAMEG00000010121" /gene_family="HOG000059539" /pro
ATGGCTTGCAGTCTGGTCGCCAGCAACCTGGATCTCAAACCTGGGAAGGGCCTCAGAGTG
CAGGGCGAGGTGGCCCCCGAAGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCGAC
AACCTGTGCCTGCACTTCAACCCTCGCTTCGAAGCACACGGGGACGTCAACACCATCGTG
TGTAACAGCAAGGTCGGCGGGGCCTGGGGCGAGGAGCATCGCGAGTCTACCTTCCCCTTC
CTGCCGGGGAGTGTCATGGTCCCTTCTCCACCCCATCCCCAGGTGTGCATCTCCTTCGAC
CAGGCCGACCTGACCATCAAGCTGCCAGATGGATACTCATTCAAGTTCCCCAACCGCCTT
AACCTGGAGGCCATCAACTACCTGGCAGCTGATGGCGACATGAAGATCAAGTGTCTGGCC
TTTGACTGA
>ANOCA5_3.PE19                         399 CDS /gene="ENSACAG00000015643" /gene_family="HOG000059539" /protei
GGATTTCTTTGCACCAACCTCAATATTCCACCTGGTCGACGCATTGCTATGAAAGGAAAT
CTTTCAGCAGGAGCTAAGAGCTTTGTAGTTAACTTGGGCAAAAACAAAGATGACTTTATA
CTGCATTTCAACGGACGTTTCGATGCTCATGGTGACACAAGGACCATTGTCTGCAATTCC
AAGAGCAAAGGGCAGTGGGGCACAGAACTGAGAGAGAGCCACTTTCCCTTCCAAGAGGGC
AGCCCTGCTGAGCTGTTCTTTACTCATGATAAAAAAGAAGTGACCATCACGCTGCCAGGC
AACCATCAATTCAAGTTCCCTAATGCCTTGGCCGCAGAAGGCATTGAATTTATCTGTGTA
GAAGGCGACATTGATGTCACAGGAATCTCATTTGCTTAA
>CALJA1_209.PE24                       408 CDS /gene="ENSCJAG00000012495" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTCGAGGCCAGCAACCTGAATCTCAAACCTGGGGAGTGCCTCCGAGTG
CGGGGCGAGGTGGCCCCTGACGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACTTGTGCCTACACTTCAACCCTCGCTTCAATGCCCACGGGGACGCCAACACCATCGTG
TGCAACAGCAAGGACGGCGGCGCCTGGGGGGCCGAGCAGCGGGAGGCTGCCTTTCCCTTC
CAGCCTGGGAGCATCGCAGAGGTGTGTGTCAGCTTCGACCAGGCAGACCTGACCATCAAG
CTGCCAGATGGATACGAATTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAC
ATGGCAGCTGACGGCGACTTCAAGATCAAGTGTGTGGCCTTTGACTGA
>CALJA1_209.PE25                       408 CDS /gene="ENSCJAG00000012495" /gene_family="HOG000059539" /prot
GCTTGTCTGTGCAGGGTCGCCAGCAACCTGAATCTCAAACCTGGGGAGTGCCTCCGAGTG
CGGGGCGAGGTGGCCCCTGACGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACTTGTGCCTACACTTCAACCCTCGCTTCAATGCCCACGGGGACGCCAACACCATCGTG
TGCAACAGCAAGGACGGCGGCGCCTGGGGGGCCGAGCAGCGGGAGGCTGCCTTTCCCTTC
CAGCCTGGGAGCATCGCAGAGGTGTGTGTCAGCTTCGACCAGGCAGACCTGACCATCAAG
CTGCCAGATGGATACGAATTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAC
ATGGCAGCTGACGGCGACTTCAAGATCAAGTGTGTGGCCTTTGACTGA
>CANFA10_31.PE15                       408 CDS /gene="ENSCAFG00000001487" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTGGTCGCCAGCAATCTGAGTCTCAAACCTGGGCAGTGCCTCAGAGTG
CAATGCGAGGTGGTCCCCGAAGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACGGGGAC
AACCTGTGCCTGCACTTCAACCCTCGCTTTGAAGCCCATGGCGACGTCAACACCATTGTG
TGTAACAGCAAGGATGGCGGGGCCTGGGGCGAGGAGCTTCGAGAGTCCGCCTTCCCCTTC
CAGCCCGGGACTGTCACAGAGGTGTGCATCTCCTTCGACCAGGCTGACTTGACCATCAAG
CTGCCAGATGGATACACCTTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAGCTAC
CTGGCAGCTGATGGTGACATGAAGATCAAGTGCCTGGCTTTTGACTAA
>CAVPO28_24.PE6                        408 CDS /gene="ENSCPOG00000006267" /gene_family="HOG000059539" /prote
TTTGCGCAGGGTCTGGTCGCCAGCAACCTGAACCTCAAGCCTGGGGAGTGCCTCCGAGTG
CGGGGCGAGGTGGCCCCCGAAGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGCCTACACTTCAACCCTCGCTTCAGCGCGCACGGGGACACCAACACCATCGTG
TGCAACAGCAAGGACGGCGGCGCCTGGGGGACAGAGCATCGTGAGCCCGCCTTCCCCTTC
CAGCCCGGGAGCGTGGTGGAGGTCTGCATCTCCTTTGACAAGACTGACCTGACCATCACA
CTGCCCGATGGACACCAATTCAAGTTCCCCAACCGTCTCAACCTGGAGGCCATCAACTAC
TTGGCAGCTGATGGTGACTTCAAGATCAAGTGTATGGCCTTTGAGTGA
>CHICK1.PE869                          390 CDS /gene="ENSGALG00000003213" /gene_family="HOG000059539" /protein
ATGTTCGAAATGTTCAACCTGGATTGGAAGTCTGGGGGCACCATGAAGATCAAAGGCCAT
ATATCTGAGGATGCTGAAAGCTTTGCCATCAATCTCGGCTGCAAGTCCTCGGATCTGGCG
CTTCACTTCAACCCCCGCTTCAATGAGTCCGTCATCGTCTGCAACTCCTTGTGCTCTGAC
AACTGGCAGCAGGAGCAACGCGATAAACATTTCAATTTCTACAAGGGCTCCACTGTCAAG
TATATCATCGTTGAATTCCTGGGAGACAAATTCCTGGTGAAACTACCAGATGGGCATGAA
GTGGAGTTCCCCAACCGGCATGGCTATGACAAGATCAGCTACTTGAACATTCTTGGAGGA
TTCAAGGTTACCTCCTTCAAGGTGGAGTGA
>CHOHO369089.PE1                       306 CDS /gene="ENSCHOG00000004628" /gene_family="HOG000059539" /prot
TTTAAGATTGATCTGGGCCAGAGACCTGAGAAGATAGACCTGCACTTCAACCCACGCTTC
AGCCAGGGCTTCATTGCCTGCAACTCCTGGGATGGCAGCTGGGGGCAGGAGCAGCGGGAA
TGTCACCTAGGTTTTGGCCCAGGGTCAGAGATCAAGCTCATGGTGAGGTTTGAGTGTTGC
GGATTCAATGGGACGCTACCAGATGGGTACCAGTTTACATTTCCTTCAAGGATGGGCTCT
TGCTGCCTGAGCTATCTGCGCGTGACGAGTGGGCTCAGCCTCACCTGCTTCAAGTTCGAA
GGATAG
>DANRE3_31.PE1                         399 CDS /gene="ENSDARG00000088711" /gene_family="HOG000059539" /protei
ACTGTGCTTATACAGAATATGGCCTTTAAGGTTGGACAGACTCTGACTCTTACAGGAGTC
CCCAAGCCTGAATCCCCAGAGTTTACCATTGACATTGGTAACAGCTCTGAAGACATCGCT
CTCCACATAAATCCCCGATTTGATGCCCATGGGGACCAGTGCATTATAGTGTGCAATACA
TTCCAGAATGACTGCTGGTGTGAGGAGCACAGAGACGAAAACTTTCCATTTGTTCAGGGC
GAGGAGTTTCAGATAAAAATCACATTCACCAATGAAGAATTTCTGGTGACTCTTCCTGAT
GGTTCGGAAATCAACTTCCCTAACCGTCAAGGCTCAGAGAAGTACAAGTATATGAATTTT
ACAGGCCAAGCCAGGATCCAAGGGATTGAAATTAAATAG
>DANRE3_31.PE2                         405 CDS /gene="ENSDARG00000054942" /gene_family="HOG000059539" /protei
ATGGCCGGTGTGCTTATACAGAATATGTCCTTCAAAGTTGGACAGACTCTGACTATAACA
GGAGTTCCAAAGCCTGATTCCACAAATTTTGCTATTAACATTGGTCACAGCCCTGAAGAC
ATCGCTCTCCACATGAATCCCCGATTTGATGCCCATGGGGACCAGTGCACTATAGTGTGC
AATTCATTCCAGAGCGGCAGCTGGTGTGAGGAGCACAGAGACAACAACTTTCCATTTATT
CAGGACAAGGAGTTTCAGATAAAAATCACATTCACCAATGAAGAATTTCTGGTGACTCTT
CCTGATGGTTCTGAAATCCACTTCCCGAACCGTCAAGGCTCAGAGAAGTATAAGTATATG
CATTTCGAAGGCGAAGTCAGGATCCAAGGGGTTGAAATTAAATAG
>DASNO103521.PE1                       318 CDS /gene="ENSDNOG00000004493" /gene_family="HOG000059539" /prot
GAGACATGTGAGGCTGCGAATATGGCCATGAAGTTGGGGACAACCCTGATGATCAAGGGC
AAAATTGCCAAAGATGTTGATCGGTTTGTGATTAATCTGGGCTGTGGCCCCGAGAAGCTG
GGCCTACACTTCAACCCTTGCTTCAGCGAGTCCACCGCCTGCAACTCGAGGACTGGCAGC
TGGGGGGAGGAGCTTCGGGAAAGTCACCTGTACTTTGACTCAGGGTCAGAGACCAAGCTC
ACTGTGGCCTTTGAGAGAGACGGATTCAAGGTGACGCTCTCCGATGGGCACCAGTTTAGC
CTCCATGACAGCCTGGGG
>DASNO110364.PE1                       300 CDS /gene="ENSDNOG00000025396" /gene_family="HOG000059539" /prot
TTTGCGATTAATCTGGGTGCAGGGCCCAAGAAGGTGGGCCTGCACTTCAACCCTCGCTTC
GACCAGTCCACCATTGTCCTCAACTCGTTTGATGGCGAATGGGGGAAGGAGGTTGTGGTA
GATCATCTGCGCTTTTCCCAAGGGTCAGAGATCATGGTCACAGTGGCCTTTGATAGTGAC
GGATTCAAGGTGATGCTGCCAGACGGGCACCAGATCAGCTTCCCTAACAGGCTGGGCCTC
TGCCAGCTGCCCTACCTGAGCAGGGGGGTCAGCATCACCTCCCTGAAGTTTGAAGAGAAA
>DASNO16616.PE4                        306 CDS /gene="ENSDNOG00000025872" /gene_family="HOG000059539" /prote
TTTGCGATTAATCTGGGTGAAGGGCCCGAGAAGCTGGGCCTGCACTTCAACCCTCGCTAC
GACCAGTCTGTCATTGTCCTCAACTCGTTTGACGGCGGATGGGGGAAGGAGGTTGTGGTA
GATCATCTGCGCTTTGTCCGAGGGTCAGAGATCACGGTCATAATGACCTTTGATAGTGAC
GGATTCAAGGTGATGCTGCCAGACTTGCACCAGATCACCTTCCCTAACAGGCTGGGCCTC
TCCCAGGTGCCCTACCTGAGCGTGGAGGGGGGGTTCACCATCACCTCCATGAAGTTTGAA
GAGGAA
>DASNO213470.PE1                       303 CDS /gene="ENSDNOG00000024548" /gene_family="HOG000059539" /prot
TTTGCGATTAATCTGGGTGAAGGGCCCGAGAAGCTGGGCCTGCACTTCAACCCTCGCTAC
GACAGGTCCTCCATTGTCCTCAACTCGTTTGACGGAGAATGGGGGAAGGAGCTTGTGGTC
AATCATCTGTGCTTTGCCCAAGGGTCAGAGATCACGGTTGTAATGACCTTTGATAGTGAC
GGATTCAAGGTGACGCTGCCAGACGGGCACCAGATCAGCTTCCCTAACAGGCTGGGCCTC
TCCCAGCTGCCCTACCTGAGAGTGGAGGGGATCAGCATCTCCTCCCTGAAGTTTGAAGAG
GAA
>DASNO57683.PE1                        306 CDS /gene="ENSDNOG00000025793" /gene_family="HOG000059539" /prote
TTTGCGATTAATCTGGGTGAAGGGCCCGAGAAGCTGGGCCTGCACTTCAACCCTCGCTAC
GACCAGTCCACCATTGTCCTCAACTCGTTTGACGGCGAATGGGGGAAGGAGCTTGTGGTA
GATCATCTGCGCTTTGCCCGAGGGTCAGAGATCACGTTGATAGTGACGGATAAGAGTGAT
GGATTCAAGGTGACGCTGCCAGATGGGCACCAGTTCAGCTTCCCTAACAGGCTGGGCCTC
TGCCAGCTGCCCTACCTGAGAGTAGACGGTGGGTTCAGCATCTCCTCCCTGAAGTTTGAA
GAATAA
>DASNO73725.PE3                        303 CDS /gene="ENSDNOG00000024915" /gene_family="HOG000059539" /prote
TTTGCGATTAATCTGGGTGCAGGGCCCAAGAAGGTGGGCCTGCACTTCAACCCTCGCTTC
GACCAGTCCACCATTGTCCTCAACTCGTTTGATGGCGAATGGGGGAAGGAGGTTGTGGTA
GATCATCTGCGCTTTTCCCAAGGGTCAGAGATCATGGTCACAGTGGCCTTTGATAGTGAC
GGATTCAAGGTGATGCTGCCAGACGGGCACCAGATCAGCTTCCCTAACAGGCTGGGCCTC
TCCCAGGTGCCCTACCTGAGAGTGGAGGGGATCAGCATCTCCTCCCTGAAGTTTGAAGAG
AAA
>DASNOGS_1062.PE1                      408 CDS /gene="ENSDNOG00000007659" /gene_family="HOG000059539" /pro
ATGGCCTGCGGTCTGGTCGCCAGCAATCTGAACCTCAAACCCGGGGAGTTCCTCAGAGTG
CGGGGCGAGGTGGCCCCTGACGCCAAGAGCTTCGTGCTGAACCTGGGCAAGGATAAAGAC
AACCTGTGCCTGCACTTCAACCCTCGCTTCAACGCCCACGGGGACACCAACACCCTCGTG
TGTAACAGCAAGGATGGCGGGGCCTGGGGGGCTGAGCACCGCGAGCCTGTCTTCCCCTTC
CAGCCTGGAAGCGTTACAGAGGTGTGCATCTCCTTCGACCAGGCAGACCTGACCATCAAG
ATGCCAGATGAGCACACGTTCAAGTTCCCCAACCGTCTCAACCTGGAGGCCATCAACTAC
CTGGCAGCTGATGGCGACTTCAAGATCAAGTGCGTGGCCTTTGACTAA
>DIPORGS_2542.PE2                      396 CDS /gene="ENSDORG00000006380" /gene_family="HOG000059539" /pro
ATGTCGGGAACACTGGAGCTCACAAATATGGACATGAAGCCAGGGACAACCCTGAAGCTC
AAGGGGCGCATCGCCAGCGATGCGAGCAGCTTCACCATTAACCTGGGACAGGACAAGAAC
CAGCTGGACCTGCATTTTAACCCGCGCTTCAGCGAATCTACCATTGTCTGCAACTCATTC
AGTGGCGGTAGCTGGGGACCAGAGCAAAGGGACAGTAACTTGTGTTTCAGCCCCGGGTCA
GAAGTCAAGATCACTGTGGCTTTCCAGAAGGATGAGTTCAAGGTGACCTTACCAGATGGG
TACCAGCTGACCTTCCCCAACAGGCTGGGCCACGACCACATGAGCTACCTGGGCCTGGAC
CAGCTCCACCTCTCCTCTTTCAAGCTGGAGGAATAA
>FUGRU206.PE50                         405 CDS /gene="ENSTRUG00000011722" /gene_family="HOG000059539" /protei
ATGCCAAATAAAAACGTCAGGGACATGTCATTCAAGGAGGGGAAGGAGCTGAAGGTCCGG
GTGAAGCCCAGCGATTGCTGCTCCAACTTCTCCATCAACATCGGCCATGACCCCGACAAC
CTGGCCCTGCACTTCAACCCCCGCTTTGACTTCGGCCATGACGTCAACACCATCGTCATG
AACTCGCTGTCAGGGGGGTCCTGGGCTGACGAGCAACACGAGGGAAATTTCCCCTTTACG
CGTGGGGAGGAGGCTAAGTGCTACATCAACTTCAACATGGAACAGTTTTACATCAAGCTT
CCTGACGGCTGCATGATCAACTTCCCCAACCGCCTGGGCGACGTCAAGTACGACTACTTT
GACATCCGCGGCGAGGCCAAGGTGATCGGCATCAAGATCAAATGA
>FUGRU206.PE51                         414 CDS /gene="ENSTRUG00000011722" /gene_family="HOG000059539" /protei
CGAAGTGGAATGCTGATCCAGAACGTCAGGGACATGTCATTCAAGGAGGGGAAGGAGCTG
AAGGTCCGGGTGAAGCCCAGCGATTGCTGCTCCAACTTCTCCATCAACATCGGCCATGAC
CCCGACAACCTGGCCCTGCACTTCAACCCCCGCTTTGACTTCGGCCATGACGTCAACACC
ATCGTCATGAACTCGCTGTCAGGGGGGTCCTGGGCTGACGAGCAACACGAGGGAAATTTC
CCCTTTACGCGTGGGGAGGAGGCTAAGTGCTACATCAACTTCAACATGGAACAGTTTTAC
ATCAAGCTTCCTGACGGCTGCATGATCAACTTCCCCAACCGCCTGGGCGACGTCAAGTAC
GACTACTTTGACATCCGCGGCGAGGCCAAGGTGATCGGCATCAAGATCAAATGA
>FUGRU206.PE52                         408 CDS /gene="ENSTRUG00000011722" /gene_family="HOG000059539" /protei
ATGATAAACCAGCAGAACGTCAGGGACATGTCATTCAAGGAGGGGAAGGAGCTGAAGGTC
CGGGTGAAGCCCAGCGATTGCTGCTCCAACTTCTCCATCAACATCGGCCATGACCCCGAC
AACCTGGCCCTGCACTTCAACCCCCGCTTTGACTTCGGCCATGACGTCAACACCATCGTC
ATGAACTCGCTGTCAGGGGGGTCCTGGGCTGACGAGCAACACGAGGGAAATTTCCCCTTT
ACGCGTGGGGAGGAGGCTAAGTGCTACATCAACTTCAACATGGAACAGTTTTACATCAAG
CTTCCTGACGGCTGCATGATCAACTTCCCCAACCGCCTGGGCGACGTCAAGTACGACTAC
TTTGACATCCGCGGCGAGGCCAAGGTGATCGGCATCAAGATCAAATGA
>FUGRU206.PE53                         408 CDS /gene="ENSTRUG00000011722" /gene_family="HOG000059539" /protei
CAAACTGGTGGACTGAACGTCAGGGACATGTCATTCAAGGAGGGGAAGGAGCTGAAGGTC
CGGGTGAAGCCCAGCGATTGCTGCTCCAACTTCTCCATCAACATCGGCCATGACCCCGAC
AACCTGGCCCTGCACTTCAACCCCCGCTTTGACTTCGGCCATGACGTCAACACCATCGTC
ATGAACTCGCTGTCAGGGGGGTCCTGGGCTGACGAGCAACACGAGGGAAATTTCCCCTTT
ACGCGTGGGGAGGAGGCTAAGTGCTACATCAACTTCAACATGGAACAGTTTTACATCAAG
CTTCCTGACGGCTGCATGATCAACTTCCCCAACCGCCTGGGCGACGTCAAGTACGACTAC
TTTGACATCCGCGGCGAGGCCAAGGTGATCGGCATCAAGATCAAATGA
>FUGRU238.PE35                         411 CDS /gene="ENSTRUG00000007259" /gene_family="HOG000059539" /protei
ATGATTAAGAGTGGGATGACCATCAAGAACATGTCCTTCAAGGTGGGGCAGACCATGACC
ATCGTCGGAGTCCCCACCCCTAATCCTTCAAATTTTGCAGTGAACGTTTGCCAGAACGAG
CAGGAGATCACCATGCACCTAAACGCCCGCTTCAACGCGCACGGGGATGAAAACAAGGTG
GTCTGCAACTCCTACCTGGGGGGCAAATGGTGTGAGGAGGTGCGGGAGGGAGGCTTTCCG
TTCCAACAGGGCGAGGAGTTTAAGATGGTCATCGAGTTCACCCCCGCAGAGTTCTTGGTG
AAGCTGTCCGACGGCTCTGTCATCCGCTTCCCCAACCGGATGGCCGCAGAGAAATACGCC
TTCTTCAACTTCGACGGGGACCTGCGCATCAAAAGCATTGAAATCAAGTAA
>GORGO22_23.PE10                       399 CDS /gene="ENSGGOG00000003754" /gene_family="HOG000059539" /prot
ATGACGGGGGAACTTGAGGTTAAGAACATGGACATGAAGCCGGGGTCAACCCTGAAGATC
ACAGGCAGGATCGCCGATGGCACTGATAGCTTTGTAATTAATCTGGGCCAGGGGACAGAC
AAGCTGAACCTGCATTTCAACCCTCGCTTCAGTGAATCCACCATTGTCTGCAACTCATTG
GACGGCAGCAACTGGGGGCAAGAACAACGGGAAGATCACCTGTGCTTCAGCCCAGGGTCA
GAGGTCAAGTTCACAGTGACCTTTGAGAGTGACAAATTCAAGGTGAAGCTGCCAGATGGG
CACGAGCTGACTTTTCCCAACAGGCTGGGCCACAGCCACCTGAGCTACCTGAGCGTAAGG
GGCGGGTTCAACATGTCCTCTTTCAAGTTAAAAGAATAA
>GORGO22_23.PE15                       408 CDS /gene="ENSGGOG00000011360" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCTGGAGAGTGCCTTCGAGTG
CGAGGCGAGGTGGCCCCTGACGCTAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGCCTGCACTTTAACCCTCGCTTCAACGCCCACGGCGACGCCAACACCATCGTG
TGCAACAGCAAGGACGGCGGGGCCTGGGGGACCGAGCAGCGGGAGGCTGTCTTTCCCTTC
CAGCCTGGAAGTGTTGCAGAGGTGTGCATCACCTTCGACCAGGCCAACCTGACCATCAAG
CTGCCAGATGGATACGAATTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAC
ATGGCAGCTGACGGTGACTTCAAGATCAAATGTGTGGCCTTTGACTGA
>HORSE28_37.PE23                       408 CDS /gene="ENSECAG00000006745" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCCGGGGAGTGCCTCCGAGTG
CGGGGCGAAGTGGCCCCCGACGCCAAGAGCTTTGTGCTGAACCTGGGCAAAGACAGCGAC
AACCTGTGCCTGCACTTCAACCCTCGCTTCAACATGCACGGGGACGCCAACACCATTGTG
TGCAACAGCAAGGATGGTGGGGCCTGGGGGACCGAGCAACGGGAGTCGGCCTTCCCCTTC
CAGCCTGGAAGTGTCATGGAGGTGTGCATCTCCTTCGACAAGGCAGACCTGACCATCACG
CTGCCGGATGGCTACTCGTTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCGTCAACTAC
CTGTCGGCCAACGGCGACTTCAAGATCAAGTGTGTGGCCTTTGAGTGA
>HS22.PE1557                           399 CDS /gene="ENSG00000100079" /gene_family="HOG000059539" /protein_id=
ATGACGGGGGAACTTGAGGTTAAGAACATGGACATGAAGCCGGGGTCAACCCTGAAGATC
ACAGGCAGCATCGCCGATGGCACTGATGGCTTTGTAATTAATCTGGGCCAGGGGACAGAC
AAGCTGAACCTGCATTTCAACCCTCGCTTCAGCGAATCCACCATTGTCTGCAACTCATTG
GACGGCAGCAACTGGGGGCAAGAACAACGGGAAGATCACCTGTGCTTCAGCCCAGGGTCA
GAGGTCAAGTTCACAGTGACCTTTGAGAGTGACAAATTCAAGGTGAAGCTGCCAGATGGG
CACGAGCTGACTTTTCCCAACAGGCTGGGTCACAGCCACCTGAGCTACCTGAGCGTAAGG
GGCGGGTTCAACATGTCCTCTTTCAAGTTAAAAGAATAA
>HS22.PE1584                           408 CDS /gene="ENSG00000100097" /gene_family="HOG000059539" /protein_id=
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCTGGAGAGTGCCTTCGAGTG
CGAGGCGAGGTGGCTCCTGACGCTAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGCCTGCACTTCAACCCTCGCTTCAACGCCCACGGCGACGCCAACACCATCGTG
TGCAACAGCAAGGACGGCGGGGCCTGGGGGACCGAGCAGCGGGAGGCTGTCTTTCCCTTC
CAGCCTGGAAGTGTTGCAGAGGTGTGCATCACCTTCGACCAGGCCAACCTGACCGTCAAG
CTGCCAGATGGATACGAATTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAC
ATGGCAGCTGACGGTGACTTCAAGATCAAATGTGTGGCCTTTGACTGA
>LOXAF73_8.PE29                        408 CDS /gene="ENSLAFG00000028162" /gene_family="HOG000059539" /prote
TCTGCGCAGGGTCTGGTCGCCAACAACCTGAATCTCAAACCCGGGGAGTGCCTCCGAGTG
CGGGGCGAGGTGGCCCCTGACGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGTCTACACTTTAACCCTCGCTTCGATGCCCACGGGGACGTCAATGTTATCGTG
TGTAACAGCAAGGACGGTGGGGCCTGGGGTACCGAGCAGCGAGAGTCAGTCTTCCCCTTC
CAGCCTGGCAGCGTTGTGGAGGTGTGCATCTCCTTCGACCAGGCTGACCTGAGCATCAAG
CTGCCAGATGGATACTCATTCAAGTTCCCTAACCGCCTCGACCTAGAGGCCATCAGCTAC
ATGGCGGCCGACGGCGATTTCAAAGTCAAGTGTGTGGCCTTTGAGTGA
>MACEUGS_1536.PE1                      306 CDS /gene="ENSMEUG00000012176" /gene_family="HOG000059539" /pro
TTCTCTATTAACCTGGGCAGTGGTCCCGGAGATCTGGCACTGCATTTCAACCCTCGATTT
GAGGAGAATGTCATTGTCTGCAACTCCCAAAATGGTGGCACCTGGGAGCAGGAGCATCGA
GATGATCATATGTGCTTTAGACCAGGGATGGAGATAAAACTGATCATGACCTTTGAGGAA
GATGAATTTCAGGTGAAACTTCCCGACGGTCACCAGGTGAAATTCCCCAACCGTGGGAGG
CACAGCCACCTCCCCTACTTCTGTGTGAAGGGGGGAATCCACCTCACCTCCTTCAAGCTG
GAGAGG
>MACMU10_84.PE9                        399 CDS /gene="ENSMMUG00000002866" /gene_family="HOG000059539" /prote
ATGATGGGGGAACTTGAGGTTAAGAACATGGACATGAAGCCGGGGTCAACCCTGAAGATC
ACAGGCAGGATCGCTGATGGCGCTGATGGCTTTGTAATTAACCTGGGCCAGGGGACAGAC
AAGCTGAACCTGCATTTCAACCCTCGCTTCAGCGAATCCACCATTGTCTGCAACTCACTG
GATGGCAGCAACTGGGGGCAAGAACAACGGGAAGATCACCTGTGCTTCAGCCCAGGGTCA
GAGGTCAAGTTCACGGTGACCTTTGAGAGTGACAAATTCAAGGTGAAGCTGCCAGATGGG
CATGAGCTGACCTTTCCCAACAGGCTGGGCCACAGCCACCTGAGCTACCTGAGCGTGAGG
GGCGGGTTCAACACGTCCTCTTTCAAGTTAAAAGAATAA
>MONDO8_96.PE14                        411 CDS /gene="ENSMODG00000000457" /gene_family="HOG000059539" /prote
TGGTCTCTTCAGGAAATACTTGCCTCTAACTTGAACCTCAAGCCTGGAGTCTGTGTGAGA
ATAGTGGGAGATGTTCTGCCTGATGCCAAGAGCTTTAGACTGAACCTGGGCAAAGACCAC
GAAAACCTCGCCTTGCATTTCAACCCACGTTTTGACTGCTTTGATGATACCAACGTCATC
GTCTGCAACTCCAGGCAGGAAGGCTCATGGGGCGCAGAACAAAGGGAGACCAGTTTCCCT
TTTTTGCCAGGGAGCCAAGTAGAGGTTTGCTTCGCCTTTGAAGGGAGTCATTTTACAGTG
AGGCTGCCTGATGGCTCCGAGTTCAAGTTCCCAAATCGCCTTAACTTAGACACTATCAAC
TTCCTGGAAGCCAATGGTGACTTCAAGCTAAGATCAGTGAATTTTGATTGA
>MOUSE15.PE806                         408 CDS /gene="ENSMUSG00000068220" /gene_family="HOG000059539" /protei
ATGGCCTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCTGGGGAATGTCTCAAAGTT
CGGGGAGAGGTGGCCTCGGACGCCAAGAGCTTTGTGCTGAACCTGGGAAAAGACAGCAAC
AACCTGTGCCTACACTTCAATCCTCGCTTCAATGCCCATGGAGACGCCAACACCATTGTG
TGTAACACCAAGGAAGATGGGACCTGGGGAACCGAACACCGGGAACCTGCCTTCCCCTTC
CAGCCCGGGAGCATCACAGAGGTGTGCATCACCTTTGACCAGGCTGACCTGACCATCAAG
CTGCCAGACGGACATGAATTCAAGTTCCCCAACCGCCTCAACATGGAGGCCATCAACTAC
ATGGCGGCGGATGGAGACTTCAAGATTAAGTGCGTGGCCTTTGAGTGA
>MYOLUGS_2708.PE1                      408 CDS /gene="ENSMLUG00000014277" /gene_family="HOG000059539" /pro
ATGGCTTGTAATCTGGTCGCCAGCAACCTGAATCTCAAACCTGGGGAGTGCCTCCGAGTG
CGGGGCGAGATAGCTCCCGACGCCAAGAGCTTCGCGCTGAACCTGGGCAAAGATGACAAC
AATATGTGCCTGCACTTCAACCCTCGCTTCAATATACATGGAGACATCAACACCATTGTG
TGTAACAGCAAGGATGGCGGGGCCTGGGGGGCTGAGCAGCGGGAGACTGCCTTCCCCTTC
CAGCCGGGAAGTGTTGCAGAGGTGTGCATCTCCTTCGACCAGGCCGACCTGACCATCAAG
CTGCCAGATGGATACTTGTTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAATTAC
CTGACAGCTGAAGGTGACTTCAAGATCAAGTGTGTGGCCTTTGATTGA
>OCHPRGS_714.PE7                       405 CDS /gene="ENSOPRG00000013346" /gene_family="HOG000059539" /prot
ATGGCCGGTCTTGAAGCCAGCAACCTCAATCTGCAACCAGGACAGAGCATCTGTGTGCGA
GGCGGGGTGGCCCCTGATGCCAAGAGCTTCGTGCTGAACCTGGGCCAAGACAGCAACAAC
TTGTGCCTGCACTTCAACCCCCGCTTCAACTGCCACGGGGACGCCAACACCATCGTGTGC
AACAGCAAGGAGAACAGCGTCTGGGGCAAGGAGCACCGGGAGCAAGCCTTTCCCTTCCAG
CCGGGCAGCGACGTGGAGGTGTCCATCACCTTCGACAAGGCCGAGCTGACCATCAAGCTG
CCCGATGGGTACACGTTCAAGTTCCCCAACCGCCTCAATCTGGAGGCCATCAACTACCTG
TCAGCCAATGGTGAATTCAAGATTAAAGCTGTGACCTTCGAGTGA
>ORYLA8_15.PE3                         411 CDS /gene="ENSORLG00000010697" /gene_family="HOG000059539" /protei
TTTGTGCAGAATATGGTGATCCAGAATATGCCCTTCAAAGTTGGACAGACCGTGGCTATT
GCGGGAACTAACACACCCAATGCAGCCAATTTCTCTGTGAATTTTGGCCACAATGATGAG
AACTATGCCTTACACCTGAATCCACGTTTTGATGCCTGTGGACAGAGGAACACGATTGTC
TGTAACTCTTTGGAAAAAGGCTGCTGGAAGGAGGAAGTTTTTCCTGGGGGCTTTGCTTTC
TTCAAAGGAGAGAACTTCAAGATCATCATTAAACTGACCTGTGGAGGATTTTTGATTACC
TTACCAGATGGCTTTCAATTCACTTTCCCCAACCGCCTGCATTCAGATGAATACTCTTAC
TTCTGCTTTGTTGGTGATGGTCACCATGGAAATGCGTGGAGAAAAAAAGAG
>ORYLA8_15.PE4                         408 CDS /gene="ENSORLG00000010700" /gene_family="HOG000059539" /protei
ATGGCCCCTAATATGGTGATCCAGAATATGCCCTTCAAAGTTGGACAGACCGTGGCTATT
GCGGGAACTAACACACCCAATGCAGCCAATTTCTCTGTGAATATTGGCCACAATGATGAG
AACTATGCCTTACACCTGAATCCCCGTTTTGATGCCTGTGGACAGAGGAACACGATTGTC
TGTAACTCTTTGGAAAAAGGCTGCTGGAAGGAGGAGGTTTTTCCTGGGGGCTTTGGTTTC
TTCAAAGGAAAGAACTTCAAGATCATCATTAAACTGACCTGTGGAGGATTTTTGATTACC
TTACCGGATGGCTTTCAATTCACTTTCCCCAACCGCCTGCATTCAGATGAATACTCCTAC
TTCTGCTTTGTTGGTGATGTTAGCATCAGGAGCGTTGAGATTTACTGA
>ORYLA8_15.PE5                         411 CDS /gene="ENSORLG00000010710" /gene_family="HOG000059539" /protei
TTTTCTGCCCAGGGGATGATCGTTAAAAATATGTCCTTCAAAGTTGGACAAACTCTGACT
GTCGTTGGAGTAGCTAAACCCGACGCAACCAATTTTGCTTTAAATATCGGCCCCAACGAG
CAGGACATCGCCTTTCATCTCAACCCTCGCTTCAACGCCCACGGAGATGAAAACACAGTT
GTCTGCAACTCGTATGAAGGAGGCTGCTGGGGTGAGGAAGTCAGAGATGGAGGCTTTCCT
TTCCAACAAGGGCAGGAGTTCAAGATCAGGATTGAATTCCGATCTACTGAGTTTGTGGTG
ACCTTATCAGATGGATCCACGATCTTCTTCCCCAACCGCATGGGTGCAGAGAAATACTCA
GCCCTCAGCTTTGAAGACGAAGCTCGCATCACGAGCATTGAGATCAAATAA
>ORYLA8_15.PE6                         408 CDS /gene="ENSORLG00000010715" /gene_family="HOG000059539" /protei
AATACTTTACTTTTCGAGCTCAGAAACACAATTTTAGGACTTGGACAATCCATGGCCATT
GTTGGAACTATTAAACCTGATGCTGCCAATTTCTCTGTGAATATTGGTAACAATGATCAG
AACATTGCCTTGCACCTGAATCCCCGTTTTGATGCCTTTGGAGAAAGAGACACGATCGTC
TGTAACTCTCAGCAACAAGGCATGTGGCAGCAGGAGGTTCGGCCTGGGGGCTTTTGTTTC
TTCAGAGGAGAGAACTTCAAGATCATCATTAAATTGACCTCTACAGGATTTGTGGTGACC
TTACCGAATGGCTCTAAGATCTGTTTCCCCAACCGCTTCAATTCAGATAAATACTCCTTC
TTTCGCTTTGATGGTGATGTTCGCATCAAAAGCTTTGAGATTTACTGA
>OTOGA72724.PE1                        408 CDS /gene="ENSOGAG00000010715" /gene_family="HOG000059539" /prote
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCTGGGGAATGCCTCAGAGTA
CGGGGCAAGGTGGCTCCTGACGCCAAGAGCTTTGTACTGAACTTGGGCAAAGACAGCAAC
AACCTGGGCCTGCATTTCAACCCCCGCTTTGATGCCCACGGGGATGCCAATACTATCATG
TGCAACAGCAAGGACGGCGAGGCCTGGGGGGCTGAGCAGCGGGAGGCTGCCTTTCCCTTC
CAGCCTGGAAGTGTCGTGGAGGTGTGCATCAGCTTTGACCAGGCAGACCTGACCATCAAG
CTGCCAGATGGTTACATATTCAAGTTCTCTAAGGGCCTTAACCTGGAAGCCATCAACTAC
ATGACAGCTGATGGTGACTTCAAGATCAAGTGTGTGGCCTTTGATTGA
>PANTR22_38.PE11                       399 CDS /gene="ENSPTRG00000014338" /gene_family="HOG000059539" /prot
ATGACGGGGGAACTTGAGGTTAAGAACATGGACATGAAGCCGGGGTCAACCCTGAAGATC
ACAGGCAGCATCGCCGATGGCACTGATGGCTTTGTAATTAATCTGGGCCAGGGGACAGAC
AAGCTGAACCTGCATTTCAACCCTCGCTTCAGCGAATCCATCATTGTCTGCAACTCATTG
GACGGCAGCAACTGGGGGCAAGAACAACGGGAAGATCACCTGTGCTTCAGCCCAGGGTCA
GAGGTCAAGTTCACAGTGACCTTTGAGAGTGACAAATTCAAGGTGAAGCTGCCAGATGGG
CACGAGCTGACTTTTCCCAACAGGCTGGGCCACAGCCACCTGAGCTACCTGAGCATAAGG
GGCGGGTTCAACATGTCCTCTTTCAAGTTAAAAGAATAA
>PANTR22_38.PE21                       408 CDS /gene="ENSPTRG00000014343" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCTGGAGAGTGCCTTCGAGTG
CGAGGCGAGGTGGCCCCTGACGCTAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGCCTGCACTTCAACCCTCGCTTCAACGCCCACGGCGACGCCAACACCATCGTG
TGCAACAGCAAGGACGGCGGGGCCTGGGGGACCGAGCAGCGGGAGGCTGTCTTTCCCTTC
CAGCCTGGAAGTGTTGCAGAGGTGTGCATCACCTTCGACCAGGCCAACCTGACCGTCAAG
CTGCCAGATGGATACGAATTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAC
ATGGCAGCTGACGGTGACTTCAAGATCAAGTGTGTGGCCTTTGACTGA
>PIG5_7.PE19                           408 CDS /gene="ENSSSCG00000000125" /gene_family="HOG000059539" /protein_
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCGGGAGAGTGCCTCAAAGTG
CGGGGTGAGGTGGCTCCGGACGCCAAGAGCTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGCCTGCACTTCAACCCTCGCTTCGACATGCACGGAGACATTAACACCATCGTG
TGCAACAGCAAGGACGGCGGGGCCTGGGGGGCCGAGCAGCGGGAGTCGGCCTTCCCCTTC
CAGCCTGGAAGTGTCGTGGAGGTGTGCATCTCCTTTGGCCAGACAGACCTCACCATCAAG
CTGCCAGATGGGTACGAATTCAGTTTCCCCAACCGCCTCAACCTGGAGGCCATCGAGTAC
CTGGCGGCCGATGGCGACTTCAAGATCAAGTGTGTGGCCTTTGAGTGA
>POEGU1A_53.PE16                       384 CDS /gene="ENSTGUG00000010581" /gene_family="HOG000059539" /prot
GGAAATATTGAAATCTTAAACCTGAATATGAAGCCTGGGAACACCCTGAAGGTGAAGGGC
AAAATATTTGCCGATACTGTTGGCTTCAGCATCAATCTTGGCTACAGCTCAAGAGATCTG
GCACTTCACTTCAATCCCCGCTTCAATGAGTCTGTCATCGTCTGTAACTCCAAGTGCTCC
GATTGCTGGCAGGCGGAACACCGTGACCGCCACCTCCCTTTCTTCAGGGGTTGCACTGTC
AAGTTCTTCATTGAAATGCTGTCAGACAAATTCCGTGTGAAACTGCCGGATGGTCACGAA
GTGTGCTTCCCCAACCGGCACGGCTACCACAATATCAACTACATAAGCATCGTGGGAGGC
TTAAAGATCATCTCCTTCAAGATG
>PONPY22_34.PE6                        393 CDS /gene="ENSPPYG00000011796" /gene_family="HOG000059539" /prote
GGGGAACTTGAGGTTAAGAACATGGACATGAAGCCGGGGTCAACCCTGAAGATCACAGGC
AGGATCGCCGATGGCACTGATGGCTTTGTAATTAATCTGGGCCAGGGCACAGACAAGCTG
AACCTGCATTTCAACCCTCGCTTCAGCGAATCCGTCATTGTCTGCAACTCACTGGACGGC
AGCAACTGGGGGCAAGAACAACGGGAAGATCACCTGTGCTTCAACCCAGGGTCAGAGGTC
AAGTTCACAGTGACCTTTGAGAGTGACAAATTCAAGGTGAAGCTGCCAGATGGGCACGAG
CTGACTTTTCCCAACAGGCTGGGCCACAGCCACCTGAGCTACCTGAGCATAAGGGGCGGG
TTCAACATGTCCTCTTTCAAGTTAAAAGAATAA
>PROCAGS_1155.PE4                      408 CDS /gene="ENSPCAG00000000858" /gene_family="HOG000059539" /pro
ATGGCATGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCCGGGGAGTGCCTCCGAGTG
CGGGGCGAGGTGGCCCCTGACGCCAAGAGCTTCGTGCTCAACCTGGGCAAAGACAGCAAC
AACCTGTGCCTGCACTTCAACCCTCGTTTCAATGCTCACGGGGACGTCAACGTCATCGTG
TGTAACAGCAAGGACGGCGGGGCCTGGGGTACTGAGCAGCGAGAATCGGCCTTCCTCTTC
CAGCCTGGCAGCGTCGTGGAGGTGTGCATCACCTTCGACCAGGCTGACCTGAGTGTCACG
CTGCCAGATGGGTACACATTCAAGTTCCCTAACCGCCTCAACCTGGAAGCCATCAGCTAC
CTGGCCGCAGACGGAGACTTCAAAGTCAAGTGTATGGCCTTTGAGTGA
>PTEVAGS_1381.PE6                      396 CDS /gene="ENSPVAG00000010096" /gene_family="HOG000059539" /pro
ATGGCTTGTGGTCTGTTCGCCAGCAACCTGAATCTCAAATATGGGGAGTGTATCAGAGAG
GTGGCCCCCGACGCCAAAAGCTTCGTGCTGAACCTGGGCAAAGACAGCAACAACGTGTGC
CTGCACTTCAACCCTCGCTTCGATATACACGGAGACATCAACACCATTGTGTGTAACAGC
AAGGATGGCGGGGCCTGGGGGACCGAGCAGCGGGAGTCTGTCTTCCCCTTCCAGCCTGGA
AGTGTCGCAGAGGTGTGCATTTCCTTCGACCAGGCCGACCTGACCATCAAGCTGCCAGAT
GGTTACACATTCAAGTTCCCCAACCGCCTCGACCTGGCCATCAACTACCTGGCGGCAGAA
GGTGACTTTAAGATCAAATGTGTGGCCTTCGAATGA
>SPETRGS_848.PE1                       408 CDS /gene="ENSSTOG00000003912" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAACCTCAAACCCGGAGAGTGCCTCAGAGTG
CGCGGCGAGGTGGCTCCCGACGCCAAGAGTTTCGTGCTGAACCTGGGCAAAGACAGCAAC
AACCTGTGTCTGCACTTCAACCCGCGCTTCAACGCCTTCGGGGACGCCAACACCATCGTG
TGCAACAGCAAGGATGGCGGGGCCTGGGGGGCCGAGCACCGGGAGCCCGCCTTCCCCTTC
CAGCCTGGGAGTGTCGTGGAGGTGTTCTTCTCCTTTGACCAGACGGACCTGACCATCAAG
CTGCCAGATGGACACGAGTTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAT
GTGGCAGCGGACGGCGACTTCAAGATCAAGTGCTTAGCCTTCGAGTGA
>TETNG18.PE778                         402 CDS /gene="ENSTNIG00000018815" /gene_family="HOG000059539" /protei
TCTCCGCAGAAAATCAAGAACTTCTCATTCAAGGAGGGGTCGGAGTTGAAAGTGCGGGTG
AAGCCCAAGGATGGCTGCTCTTGCTTCTCCATCAACATCGGCCACGACCCCGACAACCTG
GCCCTGCACTTCAACCCCCGCTTCGACTACGGCGGCGATCACAACACCATCGTCTTCAAC
ACGCTGTCGGGGGGGTGCTGGGGTGACGAGCACCGCGAGGGAAACTTCCCCTTTGCACAG
GGGGATGAGGCCAAGTGCTACATCAACTTCAACATGGAGCAGTTCTACATCAAGCTTCCC
GACGGCCACATGCTGAACTACCCCAACCGACTGGGCGACGTCAAGTACGACTACTTTGAC
ATCGGCGGCGATGCTGAGTTGATCGGCTTCAAGATAAAATGA
>TETNG3.PE515                          411 CDS /gene="ENSTNIG00000012631" /gene_family="HOG000059539" /protein
ATGATTCAGAGCGGGCTGATCGTCAAGAACATGTCCTTCAAGGTCGGGCAGACCATGACC
ATCGTGGGCGTCCCCAGTCCTGACGCTTCAAACTTTGCAATCAATATTTGCCAGAACGAG
CAGGAAATCACCATGCACTTCAACGCCCGTTTCAACGCGCACGGAGACGAAAACAAGGTG
GTCTGCAACTCCTACCAGGGGGGCAACTGGTGTGGGGAGGTGAGAGAGGGAGGCTTTCCG
TTCCGCCAGGGCGAGGAGTTCCAGCTGACCATCGAGTTCACCCCCGCAGAGTTCTTGGTG
AAGTTGTCCGACGGCTCTGTCATCCACTTCCCCAACCGGGTGGGCGCAGAGAAATACGCC
CTTCTCAACTTCGATGGAGACGTCCGCATCAAAGGCATCCGCATTGAGTGA
>TUPGB116458.PE2                       399 CDS /gene="ENSTBEG00000009873" /gene_family="HOG000059539" /prot
GGTCTGGTCGCCAGCAACTTAAACCTCAAACCTGGGGAGTGCCTCAGAGTGCGGGGCGAG
GTGGCCCCGGACGCCAAGAGCTTCGTGCTGAACCTGGGCAAGAACAGCGACAACCTGTGC
CTGCACTTCAACCCTCGCTTCGACGCCCACGGTGACTCCAACACCATCGTGTGCAACAGC
AAGGACGGCGGGGCCTGGGGGGCCGAGCAACGGGAAGCTGCCTTCCCCTTCCAGCCTGGG
AGTGTCGTGGAGGTGTGCGTCTCCTTCGACCAGGCAGACCTAACCATCCAGCTGCCGGAC
GGATACACCTTCAAGTTCCCCAACCGCCTCAACCTGGAAGCCATCAACTACTTGGCAGCT
GATGGTGACTTCAAGATCAAATGTGTGGCCTTCGAGTGA
>TURTRGS_482.PE3                       399 CDS /gene="ENSTTRG00000004779" /gene_family="HOG000059539" /prot
ATGTCGGGGAAATTTGAGATTATGAACATGGACATGAAGGTGGGGACAACCCTGAAGATC
AAGGGCAAGATTGCAGACTGTGCTGATGGCTTTGTGATTAATCTGGGCCAGGGGACAGAT
AAACTGAACCTGCATTTCAACCCACGTTTCGATGAATCCACCATCGTCTGCAACACATGG
GATGACAACTGCTGGGGGCAGGAGCAACGGGACAGTCACATGAGCTTCACACCGGGATCA
GAGGTCAAGCTCCTCGTGACCTTCGAGAACAACGAATTCAAGGTGAAGATGCCAGACGGG
CACCAGTTGACCTTTCCCAACAGGCTGGGCCACAACCACTTGAGATACCTGAGTGTGCAG
GGCGGGTTCAGCATCTCCTCCTTCAAGCTAGAAGAACGC
>TURTRGS_482.PE7                       408 CDS /gene="ENSTTRG00000004798" /gene_family="HOG000059539" /prot
ATGGCTTGTGGTCTGGTCGCCAGCAACCTGAATCTCAAACCTGGGGAGTGCCTCAGAGTG
CGGGGCGAGGTGCCCCCGGACGCCAAGAGCTTCGTGCTGAACATGGGCAAAGATGGCAAC
AACCTGTGCCTGCACTTCAACCCCCGCTTCGACGCGCACGGGGACACCAACACCATCGTG
TGTAACAGCAAGGATGGCGGGGCCTGGGGGGCTGAGCAGCGGGAGTCCGTCTTCCCCTTC
CAGCCTGGAAGTGTTGTGGAGGTGTGCATCTCCTTCGACCAGGCAGACCTAACCATCCAG
CTGCCTGGTGGATACGATTTCAAGTTCCCCAACCGCCTCAACCTGGAGGCCATCAACTAC
CTGGCAGCCGATGGCGACTTCAAGATCAAGTGCGTGGCCTTTGAGTGA
>XENTR88_2.PE1                         405 CDS /gene="ENSXETG00000015998" /gene_family="HOG000059539" /protei
TTTCTGACACAGGATGTTACGATAACCAACCTCTCTCTGCATAAAGGACACCGTGTGGAA
GTAAGAGGACGTATTTTAAAAGACACTAAGAGATTTGCTGTTGATATGGGAGCAGACGCT
GAGAATTTGATCATGCACTGCAACCCTCGATTTGAATTTTCTGTGGATAAAAACACCATC
ATTTTTAACTCAAAGCAAAACGGTGTCTGGGGGACCGAACAGAAGGAAACAGCGTTCCCA
TTCCAGGCAGGTTCAGAAACCATGCTGATTTTTGAATTTGAAGACTGCATCACGGTGCTT
TTACCTGATGGCACAGAAGTCCCTTTCACCTGCCGGTTCCCCATAGATGTGATTAATTAC
CTGGCTCTCTATAACCTTGAGCTCATTTCAATCTCAGTTCATTAA
>XENTR88_2.PE4                         396 CDS /gene="ENSXETG00000016012" /gene_family="HOG000059539" /protei
ATACAGGAGCAATTTGAGCTTGTAAACCTAGAACTGAAGCGTGGAGAGTCTTTGAAGATT
AAGGGAGCCCTCTCAGGCAATGCTAAGAACTTCTCCTTCAACTTAGGCAAGAGCGCAACA
GATATTGGGTTACATTTCAACCCTCGTCTACATGAGAATACAATTGTGTGCAACTCCAAA
CGCAGCAACAACTGGGAGTCAGAACAGAGGTCAGGGCACATGTGCTTTACACCTGGAGCA
GAGGCCAAGATATCCATCAAGTTCAATGGAGATAATTTTGAAGTGAAGCTCCCAGATGGA
CATGAAATCACTTTCCCAAACCGCCACGGCTATGACAAAATGACTTATCTCTCTGTGAAA
GGCGACTTCAAAGTCAAATCATTTAAATATAAAAAC
