>AILMEGL193114_1.PE4                   405 CDS /gene="ENSAMEG00000006297" /gene_family="HOG000168489" /pro
GTGGGCTCCAGGCTTCTCTGCTGTGTGGCCCTTTGTCTCCTGGGAGCAGGTCACGCAGGA
GCCGGAGTCACTCAGTTCCCCAGGCACAGGGTCACAAGGAAGGGCAAGAATGTAACTCTC
AGCTGTGATCCAATTTCTGGTCATGTTGGCCTTTATTGGTACCAACAGACCGTGGGGCAA
GGCCCGGAGTTCTTGGTTTACTTCCAAAACCGTGACCCACTGGACAAATCAGGGATGACC
AATAATCGGTTCTCTGCCGAGAGGGACGAGGGGACCCGCTCCACTCTGCAGATCCAGCAT
GCAGAGCAGGGGGACTCGGCAGTGTACCTCTGTGCCAGCAGTCTCAGCACAGTGGGGCAC
AGTCACCTCCTTCCTCTTCACAAACCTCAGATTCCTCTCTCCTTG
>AILMEGL193114_1.PE6                   348 CDS /gene="ENSAMEG00000006302" /gene_family="HOG000168489" /pro
ATGGACCTCAGGCTCCTCTGCTGTGTGACCCTCTGTCTCCTGGGGGAAGGTCACGCAGGA
GCCGGAGTCACTCAGTTCCCCAGGCACAGGGTCACAAGGAAGGGCCAGAATGTAACTCTC
AGCTGTGATCCAATTTCTGGTCATGTTGGCCTTTATTGGTACCGACAGACCGTGGGGCAA
GGCCCGGAGTTCTTGGTTTACTTCCAAAACCGTGACCCACTGGACAAATCAGGGATGACC
AATAATCGGTTCTCTGCCGAGAGGCAGGAGGGGACCCGCTCCACTCTGCAGATCCAGCAT
GCAGAGCAGGGGGACTCGGCAGTGTACCTCTGTGCCAGCAGTCTCAGC
>AILMEGL193114_1.PE10                  342 CDS /gene="ENSAMEG00000006311" /gene_family="HOG000168489" /pro
ATGTGCCCCGTATTCATCTGCTCCTTGGTCCTTTGGTTCCTGAGTGCAGGCACCCTCAAT
GCAGAAGTCACCCAGACCCCAGGACACCTAGTCACAGGGAAAGGACAGAAAGCAGAAATG
CACTGTGTCCCAATCAAAGGACACAGTTATGTTTTCTGGTATCAGCAGATCCCAGCAAAA
GAGCTCAAGTTCTTGATTTCTTTCCAGGATGGCGTCATCTTGGATAAAACAGGAATGCCC
GAGAAGAGATTTTCAGCTGTGTGTCCCCAAAACTCACCCTGTAGCCTAGAGATCAAGCCT
ACGGAGATGCAGGATTTAGCTGTGTATTTCTGCGCCAGCAGT
>AILMEGL193114_1.PE13                  372 CDS /gene="ENSAMEG00000006317" /gene_family="HOG000168489" /pro
GCAACACACCCTTCTGGCCCTAACTGTATCATGGCTGTCGGGCTCCTCTGCTATGTGGCC
CTTTACCTTCTGGAGGCAGGCCTCGTGGATGCTGGTGTCTCCCAGATGCCAAGACACTGT
GTTTCAGGGACAGGAAAGAAGATTGTTCTGGAATGTTCTCAAACTCTGGGCCATGACAAC
ATGTACTGGTATCGACAAGACCCAGGAAAGGCACTACAGCTGATCCATTATTCATATGGT
GTTAATACCACTGAGGAAACAGAGCTCTCCTCTGGATCAACTGTCTCCAGAATAAAGAAG
GAGCATTTTCCCCTAACGCTGGAGTCGGCCAGCCCCTCACAGACATCTCTGTACCTCTGT
GCCAGCAGTGAA
>BOVIN4_114.PE23                       342 CDS /gene="ENSBTAG00000039057" /gene_family="HOG000168489" /prot
ATGGACTCCAGGCTCCTCTGCTGTGTGGCCCTCGGGCTCCTAGGAGTAGGTACCTGGGGC
ACAGGGGTTTTCCAGACTCCAAAATATCTCCTCACACAGATGGGAACTAAGACATCCCTA
GAATGTGAGCAAAAGCTGAACCATGATAGTATGTATTGGTATAAGCAGGACTCCAAGAAA
TTGCTGAAGGCTATGTTTAGCTACAATAATAAGCTACTCGTTGGAAATGAAACGGTGCCA
AGTCGTTTCTCACCGGAGTCTCCTGACAAAGCTCATTTAAACCTTCACATCGACTCCCTG
GAGCCAGGCGACTCTGCCATGTATTTCTGTGCCAGCAGCTAA
>BOVIN4_114.PE27                       339 CDS /gene="ENSBTAG00000038385" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTGTGACTCTCTGCCTCCTGGGAGCAGGCCTGGTGGAT
TCTGGAGTCACCCAGACCCCCAAATACCTGATCAAATCAAGAAACCAGCAAGCAACTCTG
AGATGTTCCCCTCACTCTGGACACTTCTCTGTGTACTGGTACCAACAGGCCCTGGGCCAG
GGCCTGCAGTTCCTCGTTCAGTATTACAACCAGAAAGTGAGGGGAGAATCTCACCTCCTG
GATCGATTCTCAGGAAAACAGTTCAGTGACTCTCGCTCTGAGCTGAACTTGAGCTCCTTG
GAGCTGACAGACTCAGCCATGTATCTCTGTGCCAGCAGC
>BOVIN4_115.PE1                        423 CDS /gene="ENSBTAG00000039824" /gene_family="HOG000168489" /prote
ATGGGCTCCAGGCTCCTCTGCTGTGTGACCCTCTGCCACCTGGGAGCAGGGATGGTCCAT
GCTGGTGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACAGAGCGCGACACTG
AAATGTACTCAGGATCTGGGTCATGACTGTATGTACTGGTACCGACAAGACCTGGGACAC
GAGCTGAGGCTGATCCATTACTCAGCTGGTGTGCACACTAGTGAGCCAGGAGACATGCCA
GACGGGTACAGCGTCTCTAGATCAAACACAGAGAACTTCCTTCTCACGCTGGAGTTTGCC
AACCACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACAGCGCTGCAGGGT
CACCTGCTCTCTGTTGAAAAAGACAAAGGGCCCACATGCAGGATCCTAGCACTGGTAACC
TAA
>BOVIN4_115.PE2                        420 CDS /gene="ENSBTAG00000039824" /gene_family="HOG000168489" /prote
ATGGGCTCCAGGCTCCTCTGCTGTGTGACCCTCTGCCACCTGGGAGCAGGGATGGTCCAT
GCTGGTGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACAGAGCGCGACACTG
AAATGTACTCAGGATCTGGGTCATGACTGTATGTACTGGTACCGACAAGACCTGGGACAC
GAGCTGAGGCTGATCCATTACTCAGCTGGTGTGCACACTAGTGAGCCAGGAGACATGCCA
GACGGGTACAGCGTCTCTAGATCAAACACACAGAAATTCCCTCTCACCCTGGAGTCTGCC
AACTGCTCCCAGAGAGTTGTGTACTGTGCCAGCAGTTACTCCACAGCGCTGCAGGGTCAC
CTGCTCTCTGTTGAAAAAGACAAGGGGCCCACATGCAGGATCCTAGCACTGGTAACCTAA
>BOVIN4_115.PE3                        339 CDS /gene="ENSBTAG00000031232" /gene_family="HOG000168489" /prote
ATGGGCTCCAGGCTCCTCTGCTGTGTGACTCTCTGCCTCCTGGGAGCAGGCTTGGTGGAT
TCTGAAGTCACCCAGACCCCCAAATACCTGATCAAATCAAGAAAACAGCAAGTGATACTG
AGATGTTCCCCTGAGTCTGGACACAGATCTGTGTACTGGTACCAACAGGCCCTGGGACAA
GGCCTCCAATTCCTCATTCAGTATTACAATGGGGCAGAGTATGAGAAAGGAAACATATCA
GATCGAGTCTCAGGAAAACAGTTCAGTGACTCTAGCTCTGAGCTGAACTTGACTTCCTTG
GAGCTGACGGACTCAGCCGTGTATCTCTGTGCCAGCAGC
>BOVIN4_115.PE4                        327 CDS /gene="ENSBTAG00000040326" /gene_family="HOG000168489" /prote
ATGGGCTCCAGGCTCCTCTGCTGTCTTCCTTGTCTCTTCCCAAGAGGCCTGGTGGATTCT
GAAATCACCCAGACCCCGTACCTGATCAAATCAAGAAAGCAGCAGGTGACGCTGAGATGT
TCCCCTGACTGTGGACACCGCTCTGTGTCCTGGTACCAACAGGCCCTGGGCCAGGGCCCC
CAGTTCCTTGTTCAGTATTTCAACAGAGTGAGAGAAGAAGCAAACCTATCAGGGCGATTC
TCAGGTCAACAGTTCAGTGACTCTAGCTCTGAACTAAGCTTGTCCTTGGAGCTGAAGGAT
TCAGCTGTGCGTCTCTGTGCCAGCAGC
>BOVIN4_115.PE5                        390 CDS /gene="ENSBTAG00000038354" /gene_family="HOG000168489" /prote
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTTTGTCTCCTGCAGGCAGGGGCGGTCTAT
GCTGGTGTCACTCAGGACCCCAGTTTCCAGGTCGTGAGGAAGGGACTGAACGTGACACTG
ACATGTACTCAGGATCTGGGTCATGACTCTATGTACTGGTACCGACAAGACTTGGGACAC
GGGCTGAGGCTGATCCATTACTCAGATGGCCCTCCCACCACGGTGAAAGGAGATGTGCCC
GAGGGCTACAGCGTCTCCAGACCAAGCAAAAAGGACTTCCCTCTCACGCTGAAGTCTGCC
AACCACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACAGTGCTGCATGGC
CACCTCCTTTCTGTGCAAAAAAGCAGATGA
>BOVIN4_115.PE6                        387 CDS /gene="ENSBTAG00000038354" /gene_family="HOG000168489" /prote
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTTTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCACTCAGGACCCCAGTTTCCAGGTCGTGAGGACGGGACTGAACGTGACACTG
ACATGTACTCAGGATCTGGGTCATAACTCTATGTACTGGTACCGACAAGACCTGGGATGC
GGGCTGAGGATCCATTACTCAGATGGCCCTCCCACCACGGTGAAAGGAGATGTGCCCGAG
GGCTACAGCGTCTCCAGACCAAGCAAAAAGGACTTCCCTCTCACGCTGAAGTCTGCTAAC
CACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACAGTGCTGCATGGCCAC
CTCCTTTCTGTGCAAAAAAGCAGATGA
>BOVIN4_115.PE8                        390 CDS /gene="ENSBTAG00000031223" /gene_family="HOG000168489" /prote
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTACAGGCAGGGCCGGTCCAT
GCTGGTGTCACACAGGACCCCAGATTCCAGGTCGTGAGGACAGGACAGAACACGACACTG
ACATGTACTCAGGATCTGGGTCATGACTGCATGTACTGGTACCGACAAGACTTGGGACAT
GGGCTGAGGCTGATCCATTACTCAGTTGGTGCTCCTGACACGGTTAAAGGAGACATACCC
GAGGGTTACAGCGTCTCCAGACCAAGCACAAAGGACTTCCCTCTCATGCTGGAGTCTGCC
AACCGCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACAGC
CACCTCCTTTCTATGCAAAAAAGCAGATGA
>BOVIN4_115.PE10                       411 CDS /gene="ENSBTAG00000031227" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTGTGACTCTCTGCCTCCTGGGAGCAGGGGCAGTCCAT
GCTGGAGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACAGAGCGCGACACTG
AAATGTACTCAGGATCTGGGTCATGACCGCATGTACTGGTACCGACAAGACCTGGGACAC
GGGCTGAGGCTGATCTATTACTCAGCTGGTGTGCGCTCTAGCGAGCCAGGAGACGTGCCC
GACGGGTACAGTGTCTCCAGATCAAACACAGAGAACTTTCCTCTCACACTGAAGTCTGCC
AACCGCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTCCTTTCTATGCAAAAAAGCAGGGGAGCCCCTTGCAGGCTCCTAGCA
>BOVIN4_115.PE11                       390 CDS /gene="ENSBTAG00000031227" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGACAGGGGCAGTCCAT
GCTGGAGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACAGAGCGCGACACTG
AAATGTACTCAGGATCTGGGTCATGACCGCATGTACTGGTACCGACAAGACCTGGGACAC
GGGCTGAGGCTGATCTATTACTCAGCTGGTGTGCGCTCTAGCGAGCCAGGAGACGTGCCC
GACGGGTACAGTGTCTCCAGATCAAACACAGAGAACTTTCCTCTCACACTGAAGTCTGCC
AACCGCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTCCTTTCTATGCAAAAAAGCAGATGA
>BOVIN4_115.PE12                       390 CDS /gene="ENSBTAG00000031222" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGACAGGACAGAAGGCTACACTG
ACATGTACTCAGGATCTGGATCATAACTGCATGTACTGGTACCGACAAGACTTGGGACAA
GGGCTGAGGCTGATCCATTACTCAGTTGCTGCTCCCAACACGGTTAAAGGAGACATACCC
GAGGGTTACAGCGTCTCCAGACCAAGCACAAAGGCCTTCCCTCTCACGCTGGAGTCTGCC
AACCACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTCCTTTCTATGCAAAAAAACAGATGA
>BOVIN4_115.PE13                       387 CDS /gene="ENSBTAG00000031221" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCTTGAGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCACTCAGGACCCCAGATGCCAGGTCGTGAAGACAGGACAGAAGGCTACACTG
ACATGTACTCAGGATCTGGGTCATGACCGCATGTACTGGTACCGACAAGACCCGGAACGC
GGGCTGAGGCTGATCCATTACTCAGCTGCTGCTCCCACCACAGAGAAAGGAGACATGCCC
GAGGGCTACAGTGTCTCCAGACTAAGCACAGAGAACTTCGCTCTCACGTTGGAGTCCGCC
AACCGCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGAGCTGCATGGC
CACCTGATCTCTGTGCAAAAAGACAGG
>BOVIN4_115.PE15                       390 CDS /gene="ENSBTAG00000031220" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGACAGGGGCAGTCCAT
GCTGGAGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACAGAGCACGACACTG
ACATGTGCTCAGGATCTGGGTCATAACTACATGTACTGGTACCGACAAGACCTGGGACAC
GGGCTGAGGCTGATCCATTACTCAGCTGGTGTGCGCTCTAGCGAGCCAGGAGACGTGCTC
GACAGGTACAGTGTCTCCAGATCAAACACAGAGAACTTTCCTCTCACACTGAAGTCTGCC
AACCGCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTGCTTTCTATGCAAAAAAGCAGATGA
>BOVIN4_115.PE16                       339 CDS /gene="ENSBTAG00000038943" /gene_family="HOG000168489" /prot
ATGGGCTGCAGCCCCGTCTGCTGTGTGGCTCTGTGTCTCCTGGCAGCAGGCCTTGTGGAT
TCTGGAGTCACCCAAACCCCGAGATACCTGATTAAAGCAAGAGGACAGCGAGGGACCCTG
GGATGCTCCCCTGTCTCCGGACACCTCTCCGTGTCCTGGTACCAACAGGCCCTGGGCCAG
AGCCCCGAGTTCCTCATTCAGTATTACAGGCAGGAAGTTAGGGGAGAAGCACAGCTCCCG
GATCGATTCTCAGGAAAACAGTTTAGTGACTTTCACTCTGAGCTGAACTTGAGCTCCTTG
GAGCTGACGGACTCAGCCGTGTATCTCTGTGCCAGCAGC
>BOVIN4_115.PE17                       387 CDS /gene="ENSBTAG00000031219" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCTAT
GCTGGTGTCTCTCAGGACCCCAGATACCAGGTCGTGAGGAGAGGACAGAGCACGACACTA
ACATGTACTCAGGATCTGGATCATAACTCTATGTACTGGTACCGACAAGACCCAGGACAC
GGGCTGAGGCTAATCCATTACTCAGCTGGGCCTCCCAGCACGGAGAAAGGAGACATGCCC
GACGGGTACACGGTGTCCAGATCAAGGAAAGAGAATTTTCCTCTCACACTGGAGTCTGCC
AACCCCTCCCAAACATCTGTGTACTTCTGTGCCAGCAGTTACTCCATGGCGCTGCACGGC
CACCTGCTCTCTGTGCAAAAAGACAGA
>BOVIN4_115.PE18                       384 CDS /gene="ENSBTAG00000031218" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCTCTAAGGACCCCATATTCCATGTCGTGAGGAGAGGACAGAGCGCGACACTG
ACATGTACTCAGGATCTGAACTTTAGCTATATGTACTGGTACCGACAAGACCCAGGGAAC
GGGCTGAGGCTGATCCATTACTCAGTTATCCCTCCCTCCATGGAGAAAGGACCCGTGCCC
GAGGGCTACAGATTCTCCAGACCAAGCACAGAGAACTTCCCTCTCACGCTGGAGTCCGCC
AACTGCTCCCTGACATCTGTGTACTTCTGCACCTGTGGTTATACGGCGCTGCATGGCCAC
CTCCTCTCTGTGCAAAAAGATAAG
>BOVIN4_115.PE19                       327 CDS /gene="ENSBTAG00000037414" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTCTTCCTTGTCTCCTCCCGGCAGGCCTAGTGGATTCT
GAAATCACCAAGCCTGAATACCTGATCAAATCAAGAAAGCAGCAAGCGACGCTGAGATGT
TCCCCTGACTCTGGACACCTCTCTCTGTACTGGTACCAGCCCTTGGGCCAGGGCCCCCAG
TTCCTTGTTCAGTATTTCAACAGAGTGAGAGGAGAAACAAATCTATCAGGACGATGCTCA
GGTCAACAGTTCAGTGACTCTAGCTCTGAACTGAGCTTGAGCTCCTTGGAGCTGAAAGAC
TCAGCCGTGCATCTCTGTGCCAGCAGC
>BOVIN4_115.PE20                       390 CDS /gene="ENSBTAG00000039093" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCTTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCACTCAGGACCCCAGGTTCCAGGTCCTGAGGACAGGACAGAAGGCTACATTG
ACATGTACCCAGGATCTGGGTCATAACTGCATGTACTGGTACCGACAAGACTTGGGACAA
GGGCTGAGGCTGATCCATTACTCAGTTGCTGCTCCCAACACGGTTAAAGGAGACATACCC
GAGGGTTACAGCGTCTCCAGACCAAGCACAAAGGCCTTCCCTCTCACGCTGGAGTCTGCC
AACCACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTCCTTTCTATGCAAAAAAACAGATGA
>BOVIN4_115.PE21                       390 CDS /gene="ENSBTAG00000037761" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGACAGGGGCAGTCCAT
GCTGGAGTCACTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACAGAGCACGACACTG
ACATGTGCTCAGGATCTGGGTCATAACTACATGTACTGGTACCGACAAGACCTGGGACAC
GGGCTGAGGCTGATCCATTACTCAGCTGGTGTGCGCTCTAGCGAGCCAGGAGACGTGCTC
GACAGGTACAGTGTCTCCAGATCAAACACAGAGAACTTTCCTCTCACACTGAAGTCTGCC
AACCGCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTGCTTTCTATGCAAAAAAGCAGATGA
>BOVIN4_115.PE22                       342 CDS /gene="ENSBTAG00000031225" /gene_family="HOG000168489" /prot
ATGGGCTGCAGCCCCGTCTGCTGTGTGGCTCTGTGTCTCCTGGCAGCAGGCCTTGTGGAT
TCTGGAGTCACCCAAACCCCGAGATACCTGATTAAAGCAAGAGGACAGCGAGGGACCCTG
GGATGCTCCCCTGTCTCCGGACACCTCTCCGTGTCCTGGTACCAACAGGCCCTGGGCCAG
AGCCCCGAGTTCCTCATTCAGTATTACAGGCAGGAAGTTAGGGGAGAAGCACAGCTCCCG
GATCGATTCTCAGGAAAACAGTTTAGTGACTTTCACTCTGAGCTGAACTTGAGCTCCTTG
GAGCTGACGGACTCAGCCGTGTATCTCTGTGCCAGCAGCCAA
>BOVIN4_115.PE23                       387 CDS /gene="ENSBTAG00000038654" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCTAT
GCTGGTGTCTCTCAGGACCCCAGATACCAGGTCGTGAGGAGAGGACAGAGCACGACACTA
ACATGTACTCAGGATCTGGATCATAACTCTATGTACTGGTACCGACAAGACCCAGGACAC
GGGCTGAGGCTAATCCATTACTCAGCTGGGCCTCCCAGCACGGAGAAAGGAGACATGCCC
GACGGGTACACGGTGTCCAGATCAAGGAAAGAGAATTTTCCTCTCACACTGGAGTCTGCC
AACCCCTCCCAAACATCTGTGTACTTCTGTGCCAGCAGTTACTCCATGGCGCTGCACGGC
CACCTGCTCTCTGTGCAAAAAGACAGA
>BOVIN4_115.PE24                       384 CDS /gene="ENSBTAG00000038934" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCTCTAAGGACCCCATATTCCATGTCGTGAGGAGAGGACAGAGCGCGACACTG
ACATGTACTCAGGATCTGAACTTTAGCTATATGTACTGGTACCGACAAGACCCAGGGAAC
GGGCTGAGGCTGATCCATTACTCAGTTATCCCTCCCTCCATGGAGAAAGGACCCGTGCCC
GAGGGCTACAGATTCTCCAGACCAAGCACAGAGAACTTCCCTCTCACGCTGGAGTCCGCC
AACTGCTCCCTGACATCTGTGTACTTCTGCACCTGTGGTTATACGGCGCTGCATGGCCAC
CTCCTCTCTGTGCAAAAAGATAAG
>BOVIN4_115.PE25                       333 CDS /gene="ENSBTAG00000038690" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTCTTCCTTGTCTCCTCCCGGCAGGCCTAGTGGATTCT
GAAATCACCAAGCCTGAATACCTGATCAAATCAAGAAAGCAGCAAGCGACGCTGAGATGT
TCCCCTGACTCTGGACACCTCTCTCTGTACTGGTACCAGCCCTTGGGCCAGGGCCCCCAG
TTCCTTGTTCAGTATTTCAACAGAATGAGAGGAGAAACAAATCTATCAGGACGATGCTCA
GGTCAACAGTTCAGTGACTCTAGCTCTGAACTGAGCTTGAGCTCCTTGGAGCTGAAAGAC
TCAGCCGTGCATCTCTGTGCCAGCAGCCAAGAC
>BOVIN4_115.PE26                       390 CDS /gene="ENSBTAG00000039468" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCTTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCACTCAGGACCCCAGGTTCCAGGTCCTGAGGACAGGACAGAAGGCTACATTG
ACATGTACCCAGGATCTGGGTCATAACTGCATGTACTGGTACCGACAAGACTTGGGACAA
GGGCTGAGGCTGATCCATTACTCAGTTGCTGCTCCCAACACGGTTAAAGGAGACATACCC
GAGGGTTACAGCGTCTCCAGACCAAGCACAAAGGCCTTCCCTCTCACGCTGGAGTCTGCC
AACCACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTCCTTTCTATGCAAAAAAACAGATGA
>BOVIN4_115.PE29                       384 CDS /gene="ENSBTAG00000037716" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCTCTCAGGACCCCAGATTCCAGGTCGTGAGGAGAGGACTGAACGCGACACTG
ACATGTACTCAGGATCTGAGCTTCAGCGATATGTACTGGTACCGACAAGACCTGGGACAC
GGGCTGAGGCTGATCCATTACTCAGTTATCCCTCCTGCCACGGAGAAAGGAGCCCTGCCT
GAGGGCTACAGCGTCTCCAGACCAAGCACAGAGGACTTCCCTCTCACGCTGGAGTCTGCC
AACCGCTCCCAGATATCTGTGTACTTCAGCGCCTGCAGTTATACGGCGCTGCACGGCAAC
CTCCTCTCTGTGCAAAAAGATGAG
>BOVIN4_115.PE30                       336 CDS /gene="ENSBTAG00000038307" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTCTTCCTTGTCTCCTCCCAGCAGGCCTGGTGGATTCT
GAAATCACCCAGCCCGAATACCCGATCAAATCAAGAAAGCAGCAAGTGACACTGAGATGT
TCCCCTGAGTCTGGACACCTCTCTGTGTACTGGTACCAACAGGCCCTGGGCCAGGACCCC
CAGTTCCTCGTTCACTATTTCAACAGAATGAGAGGAGAAGCAAACCTATCAGGGCGATTC
TCAGGTCAACAGTTCAGTGACTCTAGCTCTGAACTGAGCTTGAGCTCCTTGGGGCTGAAA
GACTCAGCCGTATATCTCTGTGCCAGCAACCAAGAC
>BOVIN4_115.PE31                       390 CDS /gene="ENSBTAG00000038404" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCGGTCCAT
GCTGGTGTCACTCAGGACCCCAGGTTCCAGGTCGTGAGGACAGGACAGAAGGCTACACTG
ACATGTACTCAGGATCTGGGTCATGACTGCATGTACTGGTACCGACAAGACTTGGGACAC
AGGCTGAGGCTGATCCATTACTCATTTGCTGCTCCCAACACAGTTAAAGGAGACATACCC
GAGGGTTACAGTGTCTCCAGACCAAGCACAGAGGACTTCCCTCTCACGCTGGAGTCTGCC
AACCACTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCACGGTGCTGCACGGC
CACCTCCTTTCTGTGCAAAAAAGCAGATGA
>BOVIN4_115.PE33                       390 CDS /gene="ENSBTAG00000039956" /gene_family="HOG000168489" /prot
ATGAGCCCCTGCCTCCTGGGCTGTGTGGTCTTCTGTCTCCTGCAGGCAGGGGCAGTCCAT
GCTGGAGTCACTCAGGACCCCAGATTCCAGGTCATGAGGACAGGACAGAACGTGACACTG
AGATGTTCTCAGGATCTGGGTCATAACTTCATGTCCTGGTACCGACAAGACCTGGGACAC
GGGCTGAGGCTGATCCATTACTCAGATGGTGCGCACACTAGCGAGCTAGGAGACGTGCCC
AATGGGTACAGTGTCTCTAAATCAAACAAAGAGAACTTTCCTCTCACGCTGGAGTCTGCC
AACCGCTCCCAGACATCTGTGTACTTCTGCGCCAGCAGGTACTCCACAGCGCTGCGTGGC
CACCTCCTCTCTGTGCAAAAAGACTGCTAG
>BOVIN4_115.PE34                       345 CDS /gene="ENSBTAG00000040261" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTGTGACTCTCTGCCTCCTGGGAGCAGGCCTGGTGGAT
TCTGAAGTCACCCAGACCCCCAAATACCTGATCAAATCAAGAAAGCAGCAAGTGACTCTG
AGATGTTCCCCTGAATCTGGACACCGCTATGTATCCTGGTACCAACAGGCCCTGGGCCAG
GGCCCCCAGTTCCTCATTCTGTATTATGATGGGAAAGTGCGTACAAAAGGAAACATGCCT
GATCGATTCTCAGGTGAACAGTTCGGTGACTCTCGCTCTCAGATGAACCTGAGCTCCTTG
GAGCTGACAGACTCAGCCGTGTATCTCTGTGCCGGTAGGCAAGAC
>BOVIN4_115.PE38                       348 CDS /gene="ENSBTAG00000039559" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGGGTGACCCTCTGTGTCCTGGGGGTGGGTCATACAAGA
GCTGGAGTAGTGTCCCAGTCACCTGGGTACAGGGTCGCAGGCAGGGGCCAGACTGTGAAT
TTCAGGTGTGATCCAATTCCTGGTCACCAAGTCCTTTACTGGTACCGACAGATGCTGGGG
CAGGGTCTGGAGTACCTGACTTATTTTCAGGGCAAGGAGGAACCAGACAAATCAGGAATG
CCTAAAAACCGGTTTTCTGCTGAGAGGCCTGAGAGCACGTACTCCTATCTGAAGATCCAG
CCAGTGGAGCCCGAGGACTCGGCCCTGTATCTCTGTGCCAGCAGCCCA
>BOVIN4_115.PE46                       342 CDS /gene="ENSBTAG00000031215" /gene_family="HOG000168489" /prot
ATGTGCCTCAGCCTCCTATGCTGTGTGGCCCTTTTTCTCTGGGGAGCAGGTTCCATGGAC
ACCGAGGTCACTCAGAGTCCAAGTCATCTGATCAAAGGAAAAGACCAGAGAGCAAAGATG
GATTGTGTTCCCAAAGAAGGACACGCTTACGTTTACTGGTATCGCAAGAAGCTGGAAGAA
GCATTTGAGTTTTTGGTTTATTTTCAGAATCAAGACATGATGGAAAATACAGCTCTGTTC
AAACAGCGATTTTCAGCTGAGTGCCCCCAAAACTCACCCTGCAGCCTGGAAATCAACTCC
ACCGAGGCAGCGGACGCGGCTCTGTATTTCTGCGCCAGCAGC
>CALJA8_110.PE17                       339 CDS /gene="ENSCJAG00000013837" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTGCTCTGTTGGATGCTGCTTTGTCTCCTGGTAGCAGGCCTGGTAGAG
GCTGAAGTCACACAAACTCCAAGACACCTGATCAAAATGAGAGGACAGCAAGTGACACTG
AAGTGCTCCCCTGTCTCTGGGCATAACAGTGTGTACTGGTACCAACAGGCCCCAGGACAG
GGCCCTCAGTTCCTCTTTGAATACTACAATGCGATAGAGAGACAAAAAGGAAACTTCCCT
GATCGATTCTCAGGGCACCAGTTCTCTAACTCTACCTCTGAGATGAATGTGAACGCCTTG
GAGCTGGGGGACTCGGCCCTTTATCTTTGTGCCAGCAGC
>CALJA8_110.PE19                       342 CDS /gene="ENSCJAG00000013834" /gene_family="HOG000168489" /prot
ATGGGCTGCAGGCTCCTCTGCTGTGTGGCTCTCTGCCTCCTGAGAACAGGTCCCTCGGAC
TCAGCCATTTCCCAGACTCCAAAATATCTGGTCACACAGATGGGAAAGAAGGAGTCCCTT
AAATGTGAACAGAATCTGGGCCATGATACTATGTATTGGTATAAGCAGGACTCTAAGAAA
CTTCTGAAGATAATGTTTATCTACAATAATAAGGAGCGCATTTTAAATGAAACAGTTCCA
AATCGCTTCTCACCTGAGTCTCCAGACAAAGCTCATTTAAATCTTCACATCGAGTCCCTG
GAGCTTGGTGACTCTGCTCTGTATTTCTGTGCCAGCAGTTAA
>CALJA8_110.PE20                       342 CDS /gene="ENSCJAG00000013833" /gene_family="HOG000168489" /prot
ATGGATACCTGGCTCCTATGCTGGGCAATTTTTAGTCTCTTGAAAGCAGGATACACAGAA
CCTGAAGTCACCCAGACTCCCAGCCATCAGGTCACATGGATGGGACAGGAAGTGATCTTG
TGGTGTGTCCCCATCCCTAACCACTTAAACTTCTTTTGGTACAGACAAATTTTGGGGAAG
AAAGTCGAGTTTCTGGTTTACTTCTATAATGATAACATCTCAGAGAGGTCAGAAATATTT
GATGATCGATTCTCAGTTAAAAGGCCTGATGGATCAAATTTTACTCTGAAGATTCAGTCC
ACAAAGCTGGAGGACTCAGCCACGTACTTCTGTGCCAGCAGC
>CANFA16_10.PE45                       351 CDS /gene="ENSCAFG00000024810" /gene_family="HOG000168489" /prot
ATGGCCACCAGGCTCCTCTGCTGTGTGACCCTTTGCCTCCTGGGAAGAGAGTTCACAGAC
GCTGGAGTCATCCAGATACCCATGCACAAGGTGACAACGATGGGACAAGGAGTAACTCTG
GGATGTGAGCCTATTTCTGGTCATGTGGTCCTCTTCTGGCACAGACAGACTTCAGGGCAG
GGATGGAAGCTGCTGATTTACTTCAACAATCAATCTCCTGTGGATTACTCGGGGATGCCC
AAGGAACGGTTCTCAGCAGAGATGCCTGACAAATTATTCTCCATCCTGAAGATCCAGCCA
ATAGAACCTGGGGACTCAGCCACGTACCTGTGTGCCAGCAGTGTAGACACA
>CANFA16_10.PE47                       408 CDS /gene="ENSCAFG00000003811" /gene_family="HOG000168489" /prot
ATGGGCCCCAGGCTCCTCTGCTGTGTGACCCTCTGTCTCTTGGGGGCAGGTCACGCAGAA
CCCGGAGTCTCCCAATCCCCCAGGCACAGGGTCACGAAGAGGGGCCAGAATGTATCTTTC
ACCTGTGATCCCATTTCTGGGCATGTTGTCCTTTACTGGTACCGACAGACCATGGGGCAG
GGCCCGGAGTTTCTGGTTTACTTCCAAAACGAAGAGGCAATGGACGAGTCAGGGCTGGAC
AAGACTCGGTTCTCTGCCAAGAGGCCCAAGGGGACCAGATCCACTCTGCAGATCCAGCGT
GCAGAGCAGAGGGACTCGGCTGTGTACCTCTGTGCCAGCAGTCTCACCACAGTGGGGCAC
AGTCACCTCCTTCCTCTTTACAAACCTCAGACTCCCCTCTCCTTGCTG
>CANFA16_10.PE54                       408 CDS /gene="ENSCAFG00000024754" /gene_family="HOG000168489" /prot
ATGGGCTGCAGGCTCCTCTACTGGGTGGTCCTTTGTCTCCTGGGGGCAGTCCCCATGGAC
ACTGGAATTACCCAGACCCCCAAACACCTGGTAACAGGGCCTGGGAGGAGAGTGACCCTC
AACTGTGAACAACATCTGGGACATGATGCTGTGTACTGGTATCAGCAGAGGGCTCAGAAG
CCACCGAAGCTCATGTTTGCCTACAGATATAAGGAACTCATTGAGAATGAGCCTGCCTCC
GGTCGCTTCTCACCTGAGTGCCCAGACAGCTCCAGGCTCTACCTTCACGTGGACGCCCTG
GAGCCTGATGACTCTGCCTTGTATCTCTGTGCTAGCAGCAGGGACACAGCCCCACACAGC
CAACCTCTCCCCGTGCACAAACATCCTGGGTCTAGCAGGGGGGCCCTT
>CANFA16_10.PE55                       405 CDS /gene="ENSCAFG00000024754" /gene_family="HOG000168489" /prot
GGACATCTACCCCAAGGGAAGGAATGCATGTCTGAGCTGAGGAGGTGCTGTCAATCAGGT
GCTGTCATGGGCTGCAGGCTCCTCTACTGGGTGGTCCTTTGTCTCCTGGGGGCAGTCCCC
ATGGACACTGGAATTACCCAGACCCCCAAACACCTGGTAACAGGGCCTGGGAGGAGAGTG
ACCCTCAACTGTGAACAACATCTGGGACATGATGCTGTGTACTGGTATCAGCAGAGGGCT
CAGAAGCCACCGAAGCTCATGTTTGCCTACAGATATAAGGAACTCATTGAGAATGAGCCT
GCCTCCGGTCGCTTCTCACCTGAGTGCCCAGACAGCTCCAGGCTCTACCTTCACGTGGAC
GCCCTGGAGCCTGATGACTCTGCCTTGTATCTCTGTGCTAGCAGC
>CAVPO10_7.PE7                         345 CDS /gene="ENSCPOG00000025586" /gene_family="HOG000168489" /protei
ATGGATTACTGGCTCCTATGTTGGGCAATTTTTAGTCTTTTGAAAGCAGGACACATGGCA
GCAGAGGTCAAGCAAACACCCAACCACAGGATTACTCAGATTGGACAGCCTGTGATTCTG
AGATGTGACCCTATTTCTGGTCACCAGTACATCTATTGGTACCGACAGACTGCAGAAAAA
GGAATGGAGTTTATGGTTTATATTTATAACAAGGACCCCATGGAAAAGACAGACCTTTTC
AATGATCGATTCTCAATTGAGAAAACTGAAGGATCCTACTACACTATGAAGATCCATCCC
GTGCAGATCGGAGACTCAGCCATGTATTTCTGTGCCAGCAGTCAG
>CAVPO10_7.PE8                         342 CDS /gene="ENSCPOG00000004442" /gene_family="HOG000168489" /protei
ATGAATTTCAGCTTTCTCTGTTGTGTGGCCTTCTGCCTCCTGCAGGCAGTCCCCATGAAC
ACCACAATTATCCAGACACCAAGATATCTGGTCATGGGAACATCAAACAAGAAGTCTTTA
AAATGTGAACAACATCTGGGACATAATGCCATGTACTGGTATAAACAGAATGCTAAGAAG
CCTCCAGAGCTCATGTTTGCTTACAACCTGACCCCCACGGATAAGGCAGACTTTTTCAGG
GATAGATTCTCAGCAGAGAAACCAGAAGGATCATACTCCAATCTGAAGATTGATCCTGTG
CAGCTGGGAGACTCGGCCATGTACCTCTGTGCCAGCAGTGAA
>CAVPO10_7.PE11                        348 CDS /gene="ENSCPOG00000010598" /gene_family="HOG000168489" /prote
ATGGACAGTATCCTCCCCTGCTGGGTGATCTTTGGTCTCCTGGGGGCAGGACACATGGCA
CCAGGGGTCAAGCAAACGCCTAGCCACAAGATCACTGAGGTGGGACAGCCTGTGACTCTG
TGGTGTGACCCTATTTCTGGTCACCCGTATGTCTATTGGTACCAACAGACTGCAGAAAAA
GGAATGGAGTTCATTGTTTATATTTATGATGAGGACAACACAGAAAAGGCAGACTTTTTC
CAAGATCGATTCTCTGTAGAAAAACCCGAAGGATCATACTCCAATCTGAATATCCAGCCG
GTGCAGCTAGGAGACTCTGCCATCTATCTCTGTGCCAGCAGTTTAGCC
>DASNO82671.PE1                        351 CDS /gene="ENSDNOG00000009264" /gene_family="HOG000168489" /prote
ACCATGTGCCTCAGACTTCTCTGCTGTCTGGCCCTTTTTTTCTTGGGAGCCGGCTCCATG
GACACTGAGGTCGTCCAGAATCCTAGACATCTGGTCAAAGGAAAAGGACAGACAGCAAAG
ATGAATTGTACCCCTATTAAAGGACATAGCTATGTTTTCTGGTATCGTAAGACACTGGAA
GAAGAGTTGAAATTTTTGATTTACTTCCAGAATGAAGATGACATTGATAAAACAGGAATG
CCCCGTGAGCGATATTCAGCTAAATGCTTTAGAAACTCATCCTGCAGCTTTGAGATTCAG
AACACTGAGCATGAGGACTCAGCACTGTATTTCTGTGCAAGCAGTGAATCC
>GORGO7_145.PE20                       351 CDS /gene="ENSGGOG00000006487" /gene_family="HOG000168489" /prot
ATGGGCACCAGGCTCCTCTGCTGGGCAGTCCTGTGCCTCCTGGGGGCAGATCACACAGGT
GCTGGAGTCTCCCAGACCCCCAGTAACAAGGTCACAGAGAAGGGAAAAGATGTAGAGCTC
AGGTGTGATCCGATTTCAGGTCATACTGCCCTTTACTGGTACCGACAAAGCCTGGGGCAG
GGCCCAGAGTTTCTAATTTACTTCCAAGGCACGGGTGCGACAGATGACTCAGGGCTGCCC
AACGATCGGTTCTTTGCAGTGAGGCCTGAGGGATCCGTCTCTACTCTGAAGATCCAGCGC
ACAGAGCAGGGGGACTCAGCCGTGTATCTCTGTGCCAGCAGCTTAACCACA
>GORGO7_145.PE23                       402 CDS /gene="ENSGGOG00000022274" /gene_family="HOG000168489" /prot
TCGGCTCTTCCCCAGGAAGACCAAGCCCTGAATCAAGTGCAGTGCTGCCTGCCTCACTGT
GCAATGGGCCCTGGGCTCCTCTGCTGGGCGCTGCTTTGTCTCCTGGGAGCAGGCTCAGTG
GAGACTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACT
CTGAGATGCTCTCCTCAGTCTGGGCACAACACTGTGTCCTGGTACCAACAGGCCCTGGGT
CAGGGGCCCCAGTTGATCTTTCAGTATTATAGGGAGGAAGAGAATGGCAGAGGAAACTTC
TCTCCTAGATTCTCAGGTCGCCAGTTCCCTAATTATAGCTCTGAGCTGAATGTGAACGCC
TTGGAGCTGGATGACTCGGCCCTGTATCTCTGTGCCAGCAGC
>GORGO7_145.PE28                       372 CDS /gene="ENSGGOG00000025648" /gene_family="HOG000168489" /prot
ATGGGCTCCTGGACCCTCTTCTGTGTGTCCCTTTGTATCTTGGTAGTGAAGCACACAGAT
GCTGGAGTTATCCAGTCACCCCGCCATGAGGTGACAGAGATGGGACAAGAAGTGACTCTG
AGATGTAAACCAATTTCAGGCCACAACTCCCTTTTCTGGTATAGACAGACCATGATGCGG
GGACTGGAGTTGCTCATTTACTTTAACAACAACGTTCCGATAGATGATTCAGGGATGCCC
AAGGATCGATTCTCAGCTAAGATGCCTAATGCATCATTCTCCACTCTGAAGATCCAGCCC
TCAGAACCCAGGGACTCAGCTGTGTACTTCTGTGCCAGCAGTTTAGCCACAGCACTGCAG
AATCACCCCTTT
>GORGO7_145.PE29                       372 CDS /gene="ENSGGOG00000026578" /gene_family="HOG000168489" /prot
ATGGACTCCTGGACCTTCTGCTGTGTGTCCCTTTGCATCCTGGTAGTGAAACACACAGAT
GCTGGAGTTATCCAGTCACCCCGCCATGAGGTGACAGAGATGGGACAAGAAGTGACTCTG
AGATGTAAACCAATTTCAGGCCACAACTCCCTTTTCTGGTACAGACAGACCATGATGCGG
GGACTGGAGTTGCTCATTTACTTTAACAACAACGTTCCGATAGATGATTCAGCGATGCCC
AAGGATCGATTCTCAGCTAAGATGCCTAATGCATCATTCTCCACTCTGAAGATCCAGCCC
TCAGAACCCAGGGACTCAGCTGTGTACTTCTGTGCCAGCAGTTTAGCCACAGCACTGCAG
AATCACCCCTTT
>GORGO7_146.PE1                        387 CDS /gene="ENSGGOG00000023203" /gene_family="HOG000168489" /prote
ATGGCCTCCCTGCTCTTCTTCTGTGGGGCCTTTTGTCTCCTGGGAACAGGGTCCATGGAT
GCTGATGTTACCCAGACCCCAAGGAATAGAATCACAAAGACAGGAAAGAGGATTATGCTG
GAATGTTCTCAGACTAAGGGTCATGATAGAATGTACTGGTATCGACAAGACCCAGGACTG
GGCCTACGGTTGATCTATTACTCCTTTGATGTTAATTCCACAGAGAAGGGAGGTCTTTCC
TCTGAGTCAACAGTCTCCAGAATAAGGACGGAGCATTTTCCCCTGACCCTGGAGTCTGCC
AGGCCCTCACATACCTCTCAGTACCTCTGCGCCAGCAGTGAATACACAGTGCTACATGGA
TACCGACACTCCACACAGAAAGGGTCA
>GORGO9_36.PE4                         387 CDS /gene="ENSGGOG00000000350" /gene_family="HOG000168489" /protei
ATGGCCTCCCTGCTCCTCTTCTGTGTGGCCTTTTGTCTCCTGGGAACAGGGTCCATGGAT
GCTGATGTTATCCAGACCCCAAAGAATAGGATTGCAAAGACAGGAAAGAGGATTATGCTG
GAATGTTCTCAGACTAAGGGTCATGATGGAATGTACTGGCATCGACAAGACCCAGGACTG
GGGCTACGGTTGATCTATTGCTCCTTTGATGTTAATTCCACAGAGAAGGGAGATCTTTCC
TCTGAGTCAACAGTCTCCAGAATAAGGATAGAGCATTTTCCCCTGACCCTGGAGTCTGCC
AGCCCCTCACATACCTCTCAGTACCTCTGTGCAAGCAGTGAATACACAGTGCTACATAGA
TACCGACACTCTGCACAGAAAGGGTCG
>GORGO9_36.PE5                         336 CDS /gene="ENSGGOG00000000350" /gene_family="HOG000168489" /protei
ATGACTATCAGGTTCCTCCGCCAAGTGGCCTTTTATTTTCTGGAGGCAGGCCTTATGGAA
GCTGAAATCTACCAGACCCCAAGATACCATGTTATAGGGACAGGAAAGAAGATCACTCTG
GAATGTTCTCAAACCATGGGCCATGACAAAATGTACTGGTCAAGATCCAGGAATGGAATT
ACACCTCATCCACCATTCCTATGGGTTAATTCCACAGAGAAGGGAGATCTTTCCTCTGAG
TCAACAGTCTCCAGAATAAGGATAGAGCATTTTCCCCTGACCCTGGAGTCTGCCAGCCCC
TCACATACCTCTCAGTACCTCTGTGCAAGCAGTGAA
>HORSE4_100.PE15                       342 CDS /gene="ENSECAG00000006228" /gene_family="HOG000168489" /prot
ATGAGCTCCACGCTCCTGTGCTGTGTGGCCCTTTGTCTCCTGGGAGCAGGCCCAGTGGAT
TCTGGAGTCACCCAAACACCAAGACACCTGGTTAAAACAAGAGGACAGCAGGTGACACTG
AGATGTTCCCCTATGTCTGGGCATGACACTGTATCTTGGTACCGACAGCCCCTGGGTCAG
GGCCTCCAGTTCCTCATTCAGTATTACAGGGGGGAAGAGAATGGAAAAGGAGACTTCCCA
GGTCGATTCAAAGGGCAACAGTTGGATAACTACAGCTCTGAGCTGAACGTGAGTGTCCTG
GAGCTGGTGGACTCCGCCCTGTATTTCTGTGCCAGCAGCTTG
>HORSE4_100.PE22                       342 CDS /gene="ENSECAG00000009397" /gene_family="HOG000168489" /prot
ATGAGCAATGGCCTCCTGTGCTGGGTGGCCTTTTGTCTCCTGCAGGCAGCTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAGATTCCAGATCCTGGGAACAGGACAGAACACAACACTG
AGATGTGCCCAGGATATGAACCACAACTCAATGTACTGGTATCGACAAGACCTGGGACAT
GGGCTGAGGCTGATCCGCTACTCAGCTGGTGCTGGTGTCACTGAAGAAGATGGTCCCGAT
GGTTACAGAGTTTCTAGATCAGATACAAAGAACTTCTCCCTCACGCTGGTGTCCGCTACC
CCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTATTCC
>HORSE4_100.PE23                       342 CDS /gene="ENSECAG00000009404" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTGTGCTGTGTGGCTCTTTGTCTCCTGGGAACAGGCCCAGTAGAT
TCTGGAGTCACCCAAACACCAAGACATCTGATTAAAGCAAGAGGACAGCAAGTGACACTG
AGATGTTCTCCTATCTCTGGGCACAACCGTGTATTTTGGTACCAACAGCCACTGGGCCAG
GGCCCCCAGTTCCTCTTTTACTATTACAATGGGAAAGAGAATGAAAAAGGAGATGTTCCG
GCTCGATTCTCAGGGCAGCAGTTCAGCGACTATCGCTCTGAGCTGAATGTGAGCGTCCTG
GAGCTGAAGGACTCGGCCCTGTATCTCTGTGCCAGCAGCTCA
>HORSE4_100.PE26                       336 CDS /gene="ENSECAG00000009825" /gene_family="HOG000168489" /prot
ATGGGCAATTGGTTGCTCAGTTGGGTGACCCTTTGTCTCCTAGGAGCAGGCACCATGGAT
GGTGGAATCACTCAGAGACCAAAATACCTGATCAGAGAGAGAAATGTGACCCTGGAATGT
GAACAGAATTTTAATTACGATGTCATGTACTGGTACCGACAGGACCCAGGACAAGGGCTG
AGACTGTTCTACTACTCACAGATTATAGATGATGTTCAGAATGGAGACATACCTGAAGGC
TACAGGGCCTCCCGGGAGAAGAAGCCATTCTTTCCTTTCACTGTAACATCAGCTCAAAAG
AACCAGACAGCCCTGTATCTCTGTGCCAGTAGTAGA
>HORSE4_100.PE27                       342 CDS /gene="ENSECAG00000009900" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTGTGGCCCTCTGCCTCCTAGGAGCAGGCCCCTTGGAC
ACAGCAGTTTCCCAGACTCCAAAGTACCTCATCTCACAGGTGGGAAATAAGAAGACCCTA
AATTGTGAGCAAACTCTGGGCCATAATGCCATGTACTGGTATAAGCAGGACTCCAAGAAA
TTGCTGAAGATCATGTTTATCTACTATAATAAGGAGCGCGATCTAAATGAAACAGTTCCA
AGTCGTTTCTCACCTGAAGCTCCTGACAAAGCTCATTTAAACCTTCACGTCAGCTCCCTG
GAGCCAGGCGACTCTGCTGTGTATTTCTGTGCCAGCAGCCAA
>HORSE4_100.PE32                       342 CDS /gene="ENSECAG00000011714" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTCCTCTGCTGTGTGGCTCTTTGTCTCCTGGGAGCAGGTGCAGTGAAT
GCTGGTGTCATTCAGACCCCAAAATTCCAGGTCCTGAAGACAGGACAGAACACGACACTG
AGATGTACCCAGGATATGAACCACGACTCTATGTACTGGTATCGACAAGACCTGGGACAT
GGGCTGAGGCTGATCCACTACTCAGTTGGTGCTGGTGTCACTGCAAACAGAGATGTTCCC
GATGGGTACAGAGTCTCCAGATCAAATACAGAGAACTTCCCCCTCATACTGGTGTCTGCT
ACGCCCTCCCAGACATCTGTGTATTTCTGTGCCAGCAGTTAG
>HORSE4_100.PE34                       342 CDS /gene="ENSECAG00000011714" /gene_family="HOG000168489" /prot
ATGAGTGGTGGCCTCCTGTGCTGGGTGGCCTTTTGTCTCCTGCAGGCAGGTGCAGTGAAT
GCTGGTGTCATTCAGACCCCAAAATTCCAGGTCCTGAAGACAGGACAGAACACGACACTG
AGATGTACCCAGGATATGAACCACGACTCTATGTACTGGTATCGACAAGACCTGGGACAT
GGGCTGAGGCTGATCCACTACTCAGTTGGTGCTGGTGTCACTGCAAACAGAGATGTTCCC
GATGGGTACAGAGTCTCCAGATCAAATACAGAGAACTTCCCCCTCATACTGGTGTCTGCT
ACGCCCTCCCAGACATCTGTGTATTTCTGTGCCAGCAGTTAG
>HORSE4_100.PE35                       348 CDS /gene="ENSECAG00000012942" /gene_family="HOG000168489" /prot
ATGGGCACCAGGTTCCTCTGCTGGGTGACCATCTGTCTCTTGGGAGCAGAACTCACTGAA
GGTGGAGTCACTCAGTCTCCCAGACACATGATCACAGGAAAAGGACAGGCTGTGGCTTTG
TGGTGTGACCCTATTTCTGGCCACCGTGCCCTTTACTGGTACCAGCAGACCCTGGGACAG
GGCCTGGGTCTTCTGATTAGCTTTGAGGATGAGGCTGTAGCAGATGATTCACAGCTGCCT
AAGCATCGGTTTTCTGCAGAGAGGTCCAAAGGAGGAGACTCTCCTCTCCAGATCAAGCCT
GCAGAACTGGGGGACTCAGCCGTGTATTTCTGTGCTAGCAGCTTAGCC
>HORSE4_100.PE38                       339 CDS /gene="ENSECAG00000013780" /gene_family="HOG000168489" /prot
ATGTGCCACAGACTTCTCTGCTGTGTGGCCCTTTTTTTCTGGGGAGCAGGCTCCATGGAC
ACTAAGGTCACCCAGAGGCCTGGACATCTAGTCAAAGGAAAGGAACAGAAAGCAAAGATG
GATTGTTTCCCCATAAAAACACATATTCATGTTTATTGGTATCGCCGGAAGCTGGAAGGA
GAGTTTGAGTTTTTGGTTTACGTAAGGAATGGAGAGATTACGGATAAAATAGAAGGGTTT
GATCAGCAGTTCTCAGTTGAACGGTCCCAAGATGAACGCTACAGCCTGGAAATCAAGTCC
ACTGAGCCAGGAGACTCAGCACTGTATTTCTGTGCCAGC
>HORSE4_100.PE41                       348 CDS /gene="ENSECAG00000014202" /gene_family="HOG000168489" /prot
ATGTGCTGCAGACTTCTCTGCTGTGTGGCCCTTTTTTTCTGGGGAGCAGGCTCCATGGAC
ACTAAGGTCACCCAGAGGCCTGGACATCTGGTCAAAGGAAAGGAACAGAAAGCAAAGATG
GATTGTGTCCCCATAAAAACACATAGTTATGTTTATTGGTATCGCCGGAAGCTGGAAGGA
GAGTTTGAGTTTTTGGTTTACTTACAGAATGGAAAGATTACAGATAAAATAGAAGGGTTT
GATCAGCAATTCTCAGCTCAATGCCCCCAAGATGCATCCTGCAGCCTGGAAATCAAGTCC
ACTGAGCCAGGAGACTCTGCACTGTATTTCTGTGCCAGCAGTGAATCC
>HORSE4_100.PE47                       351 CDS /gene="ENSECAG00000014933" /gene_family="HOG000168489" /prot
ATGGGTGCAAGTCTCCTCTGCAGTGTAGCCCTTTGTCTCCTGGGAGTACAGGTGAGCTCT
GTTGATGCCAACATCACCCAGACTCCAGGACATCTGGTCAAAAGCAAAGGACAGAAAGCA
AGGATGGATTGTATGCCCCAAAAAGGACATACTTCTGTTTACTGGTATCAACAGATTCAG
AAAAAAGAGTTTAAGTTTTTGATTTATTTGGAGGATGGACAAGTTCTTGATCAAATTGAG
TTGGTCAAGGAGCGATTCTCACCTCAATGCCCCAAAAACTTAACCTGCAGCCTGGAAATC
AAGTCCTCCGAACCAGGAGACTTGGCACTGTATTTCTGTGCCAGCAGTCGA
>HORSE4_100.PE48                       381 CDS /gene="ENSECAG00000015016" /gene_family="HOG000168489" /prot
ATGGGTCCCTGGCTCCTGGGCTATATCATGCTTTGTCTTCTGGGAGCAGGCCCTATGGAT
GCCAAAGTAATCCAGACTCCAAGACACCTCATCACAGAGACTGGAAAGAAGTTGACAGTG
AATTGTTCTCAGGATATGAACCATGACGCTATGTACTGGTATCGACAAGACCCAGGGCTG
GGTCTAAAGCTGATCCACTATTCAACTAATGTTGAAGTTCTTTACAATGGAGATGTCCCT
GATGGGTATACTGTCTCTCGAAAAGACAAGGGGAATTTCTCCCTGACCCTGGAGTCAGCC
AGCATCAACCAGACCTCTCTGTACCTCTGTGCCAGCAGTGAATCCACAGCACTGCACAGC
CAGCTGCTGTCTGCACAAAAA
>HORSE4_100.PE50                       339 CDS /gene="ENSECAG00000015158" /gene_family="HOG000168489" /prot
ATGGGGATCAGGCTCCTCTGTGTGGTAGCCTTTTGTTTTCCAGGACTAGGCTTCATGGAT
GCAACAGTAACGCAAACTGAAAGATATCTGGTCAAAAGAAGAGGAGACAAAGTTGTGATG
CACTGTCAACAGAATATGGACCACAACTCAATGTTCTGGTATCGACAAGACCCAGCTCTG
GGGCTACAGCTGCTCCATTTCTCATACCGTATTGACGATGAACAGAAAGGAGATGCCCCT
GAAGGGTACAGTGTCTCTAGAAAGAAGAAGGAGAATTTCACCCTGATCCTGGAGTCTGCC
AGCACCAACCAGACATCTGTGTACCTCTGTGCCAGCAGC
>HORSE4_100.PE51                       336 CDS /gene="ENSECAG00000015847" /gene_family="HOG000168489" /prot
ATGGGATTCACTCTCCTCTGTGCTGTGACCTTTTGTTTTCTGGGAGTAGGGTTCATGGAT
ACAAATGTAACCCAAACCCCACGTTATCTGGTCAAAAGAATAAGAGAGAAAGTTGTGATG
GAATGTTCACAGAATATGGACCATGAAACAATGTTGTGGTATCGACAAGACCCAGCTCTG
GGGCTACAGCTGCTGCATTTCTCAATCGGTATTGACGATAAACAGGAAGGAGATGCCCCT
GAAGGGTACAGTGTCTCTAGAAAGAAGGAGAATTTCACCCTGATTCTAGAGTCTGCCAGC
ACCAACCAGACATCTGTGTACCTCTGTGCCAGCAGC
>HS7.PE4157                            344 CDS /gene="ENSG00000237702" /gene_family="HOG000168489" /protein_id="
ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAGCAGGTCCCTTGGAC
ACAGCTGTTTCCCAGACTCCAAAATACCTGGTCACACAGATGGGAAACGACAAGTCCATT
AAATGTGAACAAAATCTGGGCCATGATACTATGTATTGGTATAAACAGGACTCTAAGAAA
TTTCTGAAGATAATGTTTAGCTACAATAATAAGGAGCTCATTATAAATGAAACAGTTCCA
AATCGCTTCTCACCTAAATCTCCAGACAAAGCTCACTTAAATCTTCACATCAATTCCCTG
GAGCTTGGTGACTCTGCTGTGTATTTCTGTGCCAGCAGCCAAGA
>HS7.PE4160                            344 CDS /gene="ENSG00000211706" /gene_family="HOG000168489" /protein_id="
ATGAGCATCGGGCTCCTGTGCTGTGTGGCCTTTTCTCTCCTGTGGGCAAGTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAAATTCCAGGTCCTGAAGACAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATAACTCCATGTACTGGTATCGACAAGACCCAGGCATG
GGACTGAGGCTGATTTATTACTCAGCTTCTGAGGGTACCACTGACAAAGGAGAAGTCCCC
AATGGCTACAATGTCTCCAGATTAAACAAACGGGAGTTCTCGCTCAGGCTGGAGTCGGCT
GCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTGAAGC
>HS7.PE4161                            347 CDS /gene="ENSG00000211707" /gene_family="HOG000168489" /protein_id="
ATGGGCACAAGGCTCCTCTGCTGGGCAGCCATATGTCTCCTGGGGGCAGATCACACAGGT
GCTGGAGTCTCCCAGTCCCTGAGACACAAGGTAGCAAAGAAGGGAAAGGATGTAGCTCTC
AGATATGATCCAATTTCAGGTCATAATGCCCTTTATTGGTACCGACAGAGCCTGGGGCAG
GGCCTGGAGTTTCCAATTTACTTCCAAGGCAAGGATGCAGCAGACAAATCGGGGCTTCCC
CGTGATCGGTTCTCTGCACAGAGGTCTGAGGGATCCATCTCCACTCTGAAGTTCCAGCGC
ACACAGCAGGGGGACTTGGCTGTGTATCTCTGTGCCAGCAGCTCAGC
>HS7.PE4163                            347 CDS /gene="ENSG00000229200" /gene_family="HOG000168489" /protein_id="
ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGACAGATCACACAGGT
GCTGGAGTCTCCCAGTCCCCTAGGTACAAAGTCGCAAAGAGAGGACAGGATGTAGCTCTC
AGGTGTGATCCAATTTCGGGTCATGTATCCCTTTTTTGGTACCAACAGGCCCTGGGGCAG
GGGCCAGAGTTTCTGACTTATTTCCAGAATGAAGCTCAACTAGACAAATCGGGGCTGCCC
AGTGATCGCTTCTTTGCAGAAAGGCCTGAGGGATCCGTCTCCACTCTGAAGATCCAGCGC
ACACAGCAGGAGGACTCCGCCGTGTATCTCTGTGCCAGCAGCTTAGC
>HS7.PE4164                            344 CDS /gene="ENSG00000211732" /gene_family="HOG000168489" /protein_id="
ATGAGCATCGGGCTCCTGTGCTGTGTGGCCTTTTCTCTCCTGTGGGCAGGTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAAATTCCACATCCTGAAGACAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATGGATACTTGTCCTGGTATCGACAAGACCCAGGCATG
GGGCTGAGGCGCATTCATTACTCAGTTGCTGCTGGTATCACTGACAAAGGAGAAGTCCCC
GATGGCTACAATGTATCCAGATCAAACACAGAGGATTTCCCGCTCAGGCTGGAGTCAGCT
GCTCCCTCCCAGACATCTGTATACTTCTGTGCCAGCAGTTATTC
>HS7.PE4165                            343 CDS /gene="ENSG00000211731" /gene_family="HOG000168489" /protein_id="
ATGGGCCCCGGGCTCCTCTGCTGGGTGCTGCTTTGTCCCCTAGGAGAAGGCCCAGTGGAC
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCACGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACACCAGTGTGTCCTCGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGTTTATCTTTCAGTATTATGAGAAAGAAGAGAGAGGAAGAGGAAACTTCCCT
GATCAATTCTCAGGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAACGCCTTG
TTGCTAGGGGACTCGGCCCTCTATCTCTGTGCCAGCAGCTTGG
>HS7.PE4166                            347 CDS /gene="ENSG00000253291" /gene_family="HOG000168489" /protein_id="
ATGGGTACCAGTCTCCTATGCTGGGTGGTCCTGGGTTTCCTAGGGACAGATCACACAGGT
GCTGGAGTCTCCCAGTCTCCCAGGTACAAAGTCACAAAGAGGGGACAGGATGTAACTCTC
AGGTGTGATCCAATTTCGAGTCATGCAACCCTTTATTGGTATCAACAGGCCCTGGGGCAG
GGCCCAGAGTTTCTGACTTACTTCAATTATGAAGCTCAACCAGACAAATCAGGGCTGCCC
AGTGATCGGTTCTCTGCAGAGAGGCCTGAGGGATCCATCTCCACTCTGACGATTCAGCGC
ACAGAGCAGCGGGACTCAGCCATGTATCGCTGTGCCAGCAGCTTAGC
>HS7.PE4167                            341 CDS /gene="ENSG00000253534" /gene_family="HOG000168489" /protein_id="
ATGAGCCTCGGGCTCCTGTGCTGTGCGGCCTTTTCTCTCCTGTGGGCAGGTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAAATTCCACATCCTGAAGACAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATGGATACATGTCCTGGTATCGACAAGACCCAGGCATG
GGGCTGAGACTGATTTACTACTCAGCTGCTGCTGGTACTACTGACAAAGAAGTCCCCAAT
GGCTACAATGTCTCTAGATTAAACACAGAGGATTTCCCACTCAGGCTGGTGTCGGCTGCT
CCCTCCCGGACATCTGTGTACTTGTGTGCCAGCAGTTACTC
>HS7.PE4168                            343 CDS /gene="ENSG00000211728" /gene_family="HOG000168489" /protein_id="
ATGGGCCCCGGGCTCCTCTGCTGGGCACTGCTTTGTCTCCTGGGAGCAGGCTTAGTGGAC
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTAAGTCTGGGCATGACACTGTGTCCTGGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGTTTATCTTTCAGTATTATGAGGAGGAAGAGAGACAGAGAGGCAACTTCCCT
GATCGATTCTCAGGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAACGCCTTG
TTGCTGGGGGACTCGGCCCTCTATCTCTGTGCCAGCAGCTTGG
>HS7.PE4169                            347 CDS /gene="ENSG00000211727" /gene_family="HOG000168489" /protein_id="
ATGGGCACCAGTCTCCTATGCTGGGTGGTCCTGGGTTTCCTAGGGACAGATCACACAGGT
GCTGGAGTCTCCCAGTCTCCCAGGTACAAAGTCACAAAGAGGGGACAGGATGTAGCTCTC
AGGTGTGATCCAATTTCGGGTCATGTATCCCTTTATTGGTACCGACAGGCCCTGGGGCAG
GGCCCAGAGTTTCTGACTTACTTCAATTATGAAGCCCAACAAGACAAATCAGGGCTGCCC
AATGATCGGTTCTCTGCAGAGAGGCCTGAGGGATCCGTCTCCACTCTGACGATCCAGCGC
ACAGAGCAGCGGGACTCGGCCATGTATCGCTGTGCCAGCAGCTTAGC
>HS7.PE4171                            343 CDS /gene="ENSG00000211725" /gene_family="HOG000168489" /protein_id="
ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGTAGCAGGCCCAGTGGAC
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACAAGAGTGTGTCCTGGTACCAACAGGTCCTGGGTCAG
GGGCCCCAGTTTATCTTTCAGTATTATGAGAAAGAAGAGAGAGGAAGAGGAAACTTCCCT
GATCGATTCTCAGCTCGCCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAACGCCTTG
TTGCTGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGCTTGG
>HS7.PE4172                            344 CDS /gene="ENSG00000211724" /gene_family="HOG000168489" /protein_id="
ATGAGCATCAGCCTCCTGTGCTGTGCAGCCTTTCCTCTCCTGTGGGCAGGTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAAATTCCGCATCCTGAAGATAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATAACTACATGTACTGGTATCGACAAGACCCAGGCATG
GGGCTGAAGCTGATTTATTATTCAGTTGGTGCTGGTATCACTGATAAAGGAGAAGTCCCG
AATGGCTACAACGTCTCCAGATCAACCACAGAGTATTTCCCGCTCAGGCTGGAGTTGGCT
GCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTC
>HS7.PE4173                            343 CDS /gene="ENSG00000230099" /gene_family="HOG000168489" /protein_id="
ATGGGCCCTGGGCTCCTCTGCTGGGCGCTGCTTTGTCTCCTGGGAGCAGGCTCAGTGGAC
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTTCTCAGTCTGGGCACAACACTGTGTCCTGGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGTTTATCTTTCAGTATTATAGGGAGGAAGAGAATGGCAGAGGAAACTTCCCT
CCTAGATTCTCAGGTCTCCAGTTCCCTAATGATAGCTCTGAGCTGAATGTGAATGCCTTG
GAGCTGGACGACTCGGCCCTGTATCTCTGTGCCAGCAGCTTGG
>HS7.PE4175                            344 CDS /gene="ENSG00000211721" /gene_family="HOG000168489" /protein_id="
ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGGCAGGTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAAATTCCAGGTCCTGAAGACAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATGAATACATGTCCTGGTATCGACAAGACCCAGGCATG
GGGCTGAGGCTGATTCATTACTCAGTTGGTGCTGGTATCACTGACCAAGGAGAAGTCCCC
AATGGCTACAATGTCTCCAGATCAACCACAGAGGATTTCCCGCTCAGGCTGCTGTCGGCT
GCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTC
>HS7.PE4179                            343 CDS /gene="ENSG00000211716" /gene_family="HOG000168489" /protein_id="
ATGGGCTTCAGGCTCCTCTGCTGTGTGGCCTTTTGTCTCCTGGGAGCAGGCCCAGTGGAT
TCTGGAGTCACACAAACCCCAAAGCACCTGATCACAGCAACTGGACAGCGAGTGACGCTG
AGATGCTCCCCTAGGTCTGGAGACCTCTCTGTGTACTGGTACCAACAGAGCCTGGACCAG
GGCCTCCAGTTCCTCATTCAGTATTATAATGGAGAAGAGAGAGCAAAAGGAAACATTCTT
GAACGATTCTCCGCACAACAGTTCCCTGACTTGCACTCTGAACTAAACCTGAGCTCTCTG
GAGCTGGGGGACTCAGCTTTGTATTTCTGTGCCAGCAGCGTAG
>HS7.PE4180                            343 CDS /gene="ENSG00000211715" /gene_family="HOG000168489" /protein_id="
ATGGGCCCCGGGCTCCTCTGCTGGGAACTGCTTTATCTCCTGGGAGCAGGCCCAGTGGAG
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACAGCAGTGTGTCCTGGTACCAACAGGCCCCGGGTCAG
GGGCCCCAGTTTATCTTTGAATATGCTAATGAGTTAAGGAGATCAGAAGGAAACTTCCCT
AATCGATTCTCAGGGCGCCAGTTCCATGACTGTTGCTCTGAGATGAATGTGAGTGCCTTG
GAGCTGGGGGACTCGGCCCTGTATCTCTGTGCCAGAAGCTTGG
>HS7.PE4181                            347 CDS /gene="ENSG00000211714" /gene_family="HOG000168489" /protein_id="
ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGGCAGATCACACAGGT
GCTGGAGTCTCCCAGACCCCCAGTAACAAGGTCACAGAGAAGGGAAAATATGTAGAGCTC
AGGTGTGATCCAATTTCAGGTCATACTGCCCTTTACTGGTACCGACAAAGCCTGGGGCAG
GGCCCAGAGTTTCTAATTTACTTCCAAGGCACGGGTGCGGCAGATGACTCAGGGCTGCCC
AACGATCGGTTCTTTGCAGTCAGGCCTGAGGGATCCGTCTCTACTCTGAAGATCCAGCGC
ACAGAGCGGGGGGACTCAGCCATGTATCTCTGTGCCAGCAGCTTAAC
>HS7.PE4182                            344 CDS /gene="ENSG00000211713" /gene_family="HOG000168489" /protein_id="
ATGAGCATCAGGCTCCTGTGCTGTGTGGCCTTTTCTCTCCTGTGGGCAGGTCCAGTGACT
GCTGGGATCACCCAGGCACCAACATCTCAGATCCTGGCAGCAGGACGGAGCATGACACTG
AGATGTACCCAGGATATGAGACATAATGCCATGTACTGGTATAGACAAGATCTAGGACTG
GGGCTAAGGCTCATCCATTATTCAAATACTGCAGGTACCACTGGCAAAGGAGAAGTCCCT
GATGGTTATAGTGTCTCCAGAGCAAACACAGATGATTTCCCCCTCACGTTGGCGTCTGCT
GTACCCTCTCAGACATCTGTGTACTTCTGTGCCAGCAGTGACTC
>HS7.PE4183                            344 CDS /gene="ENSG00000211746" /gene_family="HOG000168489" /protein_id="
ATGAGCAACCAGGTGCTCTGCTGTGTGGTCCTTTGTCTCCTGGGAGCAAACACCGTGGAT
GGTGGAATCACTCAGTCCCCAAAGTACCTGTTCAGAAAGGAAGGACAGAATGTGACCCTG
AGTTGTGAACAGAATTTGAACCACGATGCCATGTACTGGTACCGACAGGACCCAGGGCAA
GGGCTGAGATTGATCTACTACTCACACATAGTAAATGACTTTCAGAAAGGAGATATAGCT
GAAGGGTACAGCGTCTCTCGGGAGAAGAAGGAATCCTTTCCTCTCACTGTGACATCGGCC
CAAAAGAACCCGACAGCTTTCTATCTCTGTGCCAGTAGTATAGA
>HS7.PE4185                            347 CDS /gene="ENSG00000211749" /gene_family="HOG000168489" /protein_id="
ATGGGCACCAGGCTCCTCGGCTGTGCAGCCCTGTGTCTCCTGGCAGCAGACTCTTTTCAT
GCCAAAGTCACACAGACTCCAGGACATTTGGTCAAAGGAAAAGGACAGAAAACAAAGATG
GATTGTACCCCCGAAAAAGGACATACTTTTGTTTATTGGTATCAACAGAATCAGAATAAA
GAGTTTATGCTTTTGATTTCCTTTCAGAATGAACAAGTTCTTCAAGAAACGGAGATGCAC
AAGAAGCGATTCTCATCTCAATGCCCCAAGAACGCACCCTGCAGCCTGGCAATCCTGTCC
TCAGAACCGGGAGACACGGCACTGTATCTCTGCGCCAGCAGTCAATC
>HS7.PE4187                            344 CDS /gene="ENSG00000211751" /gene_family="HOG000168489" /protein_id="
ATGACTATCAGGCTCCTCTGCTACGTGGGCTTTTATTTTCTGGGGGCAGGCCTCATGGAA
GCTGACATCTACCAGACCCCAAGATACCTTGTTATAGGCACAGGAAAGAAGATCACTCTG
GAATGTTCTCAAACCATGGGCCATGACAAAATGTACTGGTATCAACAAGATCCAGGAATG
GAACTACACCTCATCCACTATTCCTATGGAGTTAATTCCACAGAGAAGGGAGATCTTTCC
TCTGAGTCAACAGTCTCCAGAATAAGGACGGAGCATTTTCCCCTGACCCTGGAGTCTGCC
AGGCCCTCACATACCTCTCAGTACCTCTGTGCCAGCAGTGAATA
>HS7.PE4189                            344 CDS /gene="ENSG00000211753" /gene_family="HOG000168489" /protein_id="
ATGGGAATCAGGCTCCTCTGTCGTGTGGCCTTTTGTTTCCTGGCTGTAGGCCTCGTAGAT
GTGAAAGTAACCCAGAGCTCGAGATATCTAGTCAAAAGGACGGGAGAGAAAGTTTTTCTG
GAATGTGTCCAGGATATGGACCATGAAAATATGTTCTGGTATCGACAAGACCCAGGTCTG
GGGCTACGGCTGATCTATTTCTCATATGATGTTAAAATGAAAGAAAAAGGAGATATTCCT
GAGGGGTACAGTGTCTCTAGAGAGAAGAAGGAGCGCTTCTCCCTGATTCTGGAGTCCGCC
AGCACCAACCAGACATCTATGTACCTCTGTGCCAGCAGTTTATG
>HS9.PE482                             387 CDS /gene="ENSG00000240215" /gene_family="HOG000168489" /protein_id="E
ATGGCCTCCCTGCTCCTCTTCTGTGTGGCCTTTTGTCTCCTGGGAACAGGGTCCATGGAT
GCTGATGTTATCCAGACCCCAAGGAATAGGATCACAAAGACAGGAAAGAGGATTATGCTG
GCATGTTCTCAGACTAAGGGTCATGATGGAATGTACTGGTATCGACAAGACCCAGGACTG
GGGCTACGGTTGATCTATTGCTCCTTTGATGTTAATTCCACAGAGAAGGGAGATCTTTGC
TCTGAGTCAACAGTCTCCAGAATAAGGATAGAGCGTTTTCCCCTGACCCTGGAGTCTGCC
AGCCCCTCACATACCTCTCAGTACCTCTGTGCCAGCAGTGAATACACAGTGCTACATAGA
TACCGACACTCTGCACAGAAAGGGTCG
>HS9.PE483                             336 CDS /gene="ENSG00000240215" /gene_family="HOG000168489" /protein_id="E
ATGACTATCAGGTTCCTCCGCCAAGTGGCCTTTTATTTTCTGGAGGCAGGCCTTAAGGAA
GCTGAAATCTACCAGACCCCAAGACACCGTGTTATAGGGGCAGGAAAGAAGATCACTCTG
GAATGTTCTCAAACCATGGGCCATGACAAAATGTACTGGTCAAGATCCAGGAATGGAATT
ACACCTCATCCACCATTCCTATGGGTTAATTCCACAGAGAAGGGAGATCTTTGCTCTGAG
TCAACAGTCTCCAGAATAAGGATAGAGCGTTTTCCCCTGACCCTGGAGTCTGCCAGCCCC
TCACATACCTCTCAGTACCTCTGTGCCAGCAGTGAA
>LOXAF815.PE2                          345 CDS /gene="ENSLAFG00000028589" /gene_family="HOG000168489" /protein
ATGTACTCAGTAGTCATCCGTTTTATGGTCCTTTGCCTACTGGGTACAGGCTCCTTTGAC
ACTAAAGTCACCCAGATGCCAAGATATCTGCTCAAAGGGAAAGGACAGAAAGTGAAAATG
GACTGTGTCCTGACAAAAAGACACAGCTATGTTTACTGGTATCAACAGATTCCAACCAAA
GAGCTCAAGTTCTTGATTTCCTTCCAGAACAAATATGTCCTTAGTGGAAATGAGATGCCC
AAGGAGAGATTTTCAGATAAGTGCCCCCAAGACTCAGCCTGCATCCTTGAGATCCAGCTG
GTGGCGCTACAGGACTCGGCCATGGATCTCTGTGCCAGCGCACTG
>LOXAF83_1.PE8                         348 CDS /gene="ENSLAFG00000027090" /gene_family="HOG000168489" /protei
TTGTCTGTATTTTCTTCATTCTGCTTCCAAATTCTATCTTCTTCTACAGAGCACATGGAT
GCTGGAGTCACTCAGACACCCAGGCACACGGTGGCCGAGATGGGACAGGAGGTGACCCTG
AGATATGAGCCCACTTCAAGCCACAACACCCTTTTCTGGTACAGACAGACCTCAGTGTTG
GGGCTGGAGTTGCTGGCTTTCTTCCAGAACCAGGCTGCTATAGAGCAGGCAGAGATGCTC
AAGGATCGGTTGTCTGCCGAAATGCCTGACGAGTCATTCTCCACCCTGAAGATTCAACGA
GTGGAGCGGGGTGACTCAGCCCTGTACCTCTGTGCCAGCAGCAGAGCC
>LOXAF83_1.PE16                        351 CDS /gene="ENSLAFG00000028455" /gene_family="HOG000168489" /prote
ATGGAGTCCAGGCTCCTTTGCTGGGCAGCCATCTGCCTCCTGGTGGCAAGTCAAACAGGT
GCTGGAGTCTCCCAGGCCCCCAAGCACAGGGTCACAAAGAAGGGCCAGGCTGTAGCTCTC
AGGTGTGATCCAATTTCTGGTCATGTTGGCCTTTTCTGGTACCGACAGACCCTGGGGCAG
GGCCTGGTGCTCCTGACTTATTTCCAGAATAAAGATGAAGCAGACAAATCGGGGATGGCT
GACGATCGGTTCTCTGCGGAGAGGCCTGAGGGGTCGTCTTCCACACTGAGGATACAGCCT
GTGGAGCCGGGGGACTCGGCCGTGTACCTCTGTGCCAGCAGCTTAGAAACA
>LOXAF83_1.PE17                        411 CDS /gene="ENSLAFG00000029143" /gene_family="HOG000168489" /prote
ATGGAGTCCAGGCTCCTTTGCTGGGCAGCCATCTGCCTCCTGGTGGCAGGTCAAACAGGT
CCTGGAGTCTCCCAGGCCCCCAAGCACAGGGTCACAAAGAAGGGCCAGGCTGTAGCTCTC
AGGTGTGATCCAATTTCTGGTCATGTTGGCCTTTTCTGGTACCGACAGACCCTGGGGCAG
GGCCTGGTGCTCCTGACTTATTTTCAGAATGAAAAGGAAGCAGACAAATCGGGGATGGCT
GACGATCGGTTCTCTGCGGAGAGGCCTGAGGGGTCGTCTTCCACGCTGAGGATCCAGCCT
GTGGAGCCGGGGGACTCGGCCGTGTACCTCTGTGCCAGCAGCTTAGACACAGCGTGGCAT
GGCCACCTCCTTCCTGTGCACAAACCACATACTCCTCCTCTCTCCTTGCTT
>MACMU1099214732243.PE1                351 CDS /gene="ENSMMUG00000029339" /gene_family="HOG000168489" /pro
ATGGGAACCAGGCTCCTCTGTTATGTGGCCTTTTGTTTCCTGGCTGTAGGCCTCGTGGAT
GTGAAAGTAACCCAGAGCTCAAGATATCTAATCAAAAGGACAGGAGAGAAAGTTTTTCTG
GAATGTGTCCAGGATATGGACCATGAAAGAATGTTCTGGTATCGACAAGACCCAGGTCTG
GGGCTACGGCTGATCTATTTCTCATATGATGTTAAACTGAACGAAAAAGGAGATATTCCT
GAGGGGTACAGTGTCTCTAGAGAGAAGAAGGAGCGCTTCTCCCTGATTCTGGGGTCCGCC
AGCACCAACCAGACATCTATGTACCTCTGTGCCAGCAGTTTATCCACAGCA
>MACMU1099214735160.PE1                351 CDS /gene="ENSMMUG00000032483" /gene_family="HOG000168489" /pro
ATGGGAACCAGGCTCCTCTGTTATGTGGCCTTTTGTTTCCTGGCTGTAGGCCTCGTGGAT
GTGAAAGTAACCCAGAGCTCAAGATATCTAATCAAAAGGACAGGAGAGAAAGTTTTTCTG
GAATGTGTCCAGGATATGGACCATGAAAGAATGTTCTGGTATCGACAAGACCCAGGTCTG
GGGCTACGGCTGATCTATTTCTCATATGATGTTAAACTGAACGAAAAAGGAGATATTCCT
GAGGGGTACAGTGTCTCTAGAGAGAAGAAGGAGCGCTTCTCCCTGATTCTGGGGTCCGCC
AGCACCAACCAGACATCTATGTACCTCTGTGCCAGCAGTTTATCCACAGCA
>MACMU3_187.PE7                        342 CDS /gene="ENSMMUG00000030080" /gene_family="HOG000168489" /prote
ATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTCTGTCTCCTGGGAGCAGGCTCAGTGGAC
ACTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGGTCTCCTATCTCTGGGCACAACACTGTGTCCTGGTACCAACAGGCCCCTGGTCAG
GGGCCCCAGTTTATCTTCGAATATGCTAATGAGTCAAGGACATCAGAAGGAAACTTCCCT
CATCGATTCTCAGGGCGCCAGTTCCGTGACTATCATCACTCTGAGATGAATGTGAGTGCC
TTGGAGCTGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGC
>MACMU3_187.PE9                        402 CDS /gene="ENSMMUG00000030079" /gene_family="HOG000168489" /prote
TCAGCTCTTCCCCAGGAGGACCAAGCCCTGCATCAGGTGCAGTGCTGCCTGCCCCACTGT
GCCATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTCTGTCTCCTGGGAGCAGGCCCAGTG
CAGGCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACT
CTGAGATGCTCTCCTATCTCTGGGCACACCAATGTGTACTGGTACCAACAGGCCCTGGGT
CAGGGACTCCAGTTCATCCTTTGGTATGACGAGGAAGAAGAGAGAGACAGAGGAACCTTC
CCTCCTAGATTTTCAGGTCATCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAACGCC
TTGGAGGTGGAGGACTCGGCCCTGTATCTCTGTGCCAGCAGC
>MACMU3_187.PE10                       384 CDS /gene="ENSMMUG00000030078" /gene_family="HOG000168489" /prot
GAGGACCAAGCTCTGCATCAGGTGCAGTGCTGCCTGCCCCACTGGGCCATGGGCCCCGGG
CTCCTCTGCTGGGCGCTGCTTTGTCTACTGGGAGCAGGCTCAGTGGACGGTGGAGTCACC
CAAAGTCCCAGGCATTTGATCAAAACAACAGGACAGCAAGTGACACTGAGATGCTCTCCT
ATCTCTGGGCACACCAGTGTGTCCTGGTACCAACAGGCCCTGGGTCACGGGCCCCAGTTT
ATCTTTGAGTATTATGAGGAGAAAGAGAGAGAGAGAGGCAACTTCCCTGATCGATTCTCA
GGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAACGTGAATGCCTTGGAGGCGGGGGAC
TCGCTGTATCTCTGTGCCAGCAGC
>MACMU3_187.PE11                       402 CDS /gene="ENSMMUG00000030077" /gene_family="HOG000168489" /prot
TCAGCTCTTCCCCAGGAGAACCAAGCCCTGCATCAGGTGCAGTGCTGCCTGCCCCACTGT
GCCATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTTTGTCTCCTGGGAGCAGGCTCAGTG
GACACTGGAGTCACCCAAAGTCCCACACACCTGATCAGAAAGAGAGGACAGCAAGTGACA
CTGAGATGCTCTCCTATCTCTGGGCACAACACTGTGTCCTGGTACCAACAGGCCCTGGGT
CAGGGGCCCCAGTTTATCTTTCAGTATTATGAGAAGGAAGAGAGAGAGAGAGGCAACTTT
CCTGGTCGATTCTCAGGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAGCGCC
TTGTTGCTGGGGGACTCAGCCCTGTATCTCTGTGCCAGCAGC
>MACMU3_187.PE12                       339 CDS /gene="ENSMMUG00000030076" /gene_family="HOG000168489" /prot
ATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTTTGTCTCCTGGGAGCAGGCCCAGTGGAC
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTTTG
AGATGCTCTCCTATCTCTGGGCACAGCAGTGTGTCCTGGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGCTTATCTTTGAGTATTATGAGAAGGAAGAGAGAGTCAGAGGCAACTTCCCT
GATCGATTCTCAGGTCGCCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAACGCCTCG
GAGATGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGC
>MACMU3_187.PE13                       339 CDS /gene="ENSMMUG00000030075" /gene_family="HOG000168489" /prot
ATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTTTGTCTCCTGGGAGCAGGCCCAGTGGAC
ACTGGAGTCACCCAAAGTCCCACACACCTGATTAAAACAAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACAGCAGTGTGTCCTGGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGTTTATCTTTGAGTATTATGAGAAGGAAGAGAGAGAGAGAGGCAACTTCCCT
GGTCGATTCTCAGGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAGCGCCTTG
TTGCTGGGGGACTCGGCCTTGTATCTCTGCACCAGCAGC
>MACMU3_187.PE14                       345 CDS /gene="ENSMMUG00000030074" /gene_family="HOG000168489" /prot
ATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTTTGTCTCCTGGGAGCAGGCCCAGTGGAC
ACTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACACTG
AGATGCTCTCCTATCTCTGGGCACAGCAATGTGTACTGGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGTTTATCTTTCAGTATTATGAGAAGGAAGAGAGAGAGAGAGGCAACTTCCCT
GATCGATTCTCAGGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAGCGCCTTG
TTGCTGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGCTTGGCA
>MACMU3_187.PE15                       345 CDS /gene="ENSMMUG00000030073" /gene_family="HOG000168489" /prot
ATGGGCCCCGGGCTCCTCTGCTGGGCGCTGCTCTGTCTCCTGGGAGCAGGCCCAGTGGAC
GCTGGAGTCGTCCAAAGTCCCACGCACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACAACACTGTGTCCTGGTACCAACAGGCACTCGGTCAG
GGGCCCCAGTTGATATTTCAGTATTATCGGGGGGAAGACAGAGGCAGAGGAAACTTCCCT
GATCGATTCTCAGGTCACCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAATGCCTCG
GAGATGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGCTTGGCA
>MACMU3_187.PE18                       330 CDS /gene="ENSMMUG00000030072" /gene_family="HOG000168489" /prot
ACCAGGCTCCTCTGCTATGTCATGCTTTGTCTCCTGGGAGCAGGTTCAGTGGCTGCTGGA
GTCATCCAGTCCCCAAGGCACCTGATCAAAGAAAAGAGGGAAACAGCCACTCTGCAATGC
TATCCTCTCCCTGAACACGACACTGTCTACTGGTACCAGCAGGGTCCAGGTCAGGGCCCC
CAGTTCCTCATTTCGTTTTATCAAAAGATGCAGAGAGAAAAAGGAAGCATCCCTGATCGA
TTCTCAGCTCAACAGTTCAGTGACTATCATTCTGAACTGAACATGAGCTCCTTGGAGCTG
GGGGACTCAGCCGTGTACCTCTGTGCCAGC
>MICMU83824.PE1                        351 CDS /gene="ENSMICG00000005771" /gene_family="HOG000168489" /prote
ACCATGTGCCTCAGACTTGTCTGCTATGTGACCCTTTTCTTCTGGGGAACAGGCTCCATG
GACACTGAGGTCACCCAGAGTCCTAGATATCTGGTCAAAGGAAAGGAGCAGAAAACCAAG
ATGGATTGTGTCCCTAAAAAAGGACATAGTTATGTTTATTGGTACCAAAAGAAGCTGGAA
GAAGGGCTCAAGTTTTTGGTTTATCTTCAGGATGAAGACATTATCGAAAAAGAAGAAATA
ATCAATAATCGATTTTCAGCCCAATGCCCCAAAAACTCACCCTGTATCTTGGAGATCCAG
TCCACTGAGTCAGGGGACTCAGCACTGTATTTCTGTGCCAGCAGCCAGTCC
>MONDO8_213.PE7                        339 CDS /gene="ENSMODG00000025461" /gene_family="HOG000168489" /prote
ATGTATACCAGGGTTTTCTTCTGTATAATGATGTGTTTCTTAATAGCAGGTGTCCAACCA
GATGCTGGAGTGACTCAACGCCCAAGTTACCTGGTCTCAAGGAAAGGACAGTCAGTGGCC
TTGGGATGTGACCCCATCTCTGGACACAATGGGGCTTTCTGGTACAGTCAGATACAGGGT
CAGGGCCCCAAGATGCTCTTTTACTACTATTATAAGCAATTGAATGAGAAAGGAAACATT
TCTGACCGATTCGTTGCCAAGCAGCATGAAAACAACCACTTCACGCTCAACATCAATTAC
TTGGAACTGGGAGATTCTGCTAATTACCTTTGTGCCAGC
>MONDO8_213.PE10                       348 CDS /gene="ENSMODG00000025463" /gene_family="HOG000168489" /prot
AGATTTCTTCATTGGATTTCTATATTCCTCCTGGGAGCAGGACTTACAGATGCGGGTGTC
ACGCAGGTGCCCAAATACCTCATCACAGAAACAGGACAACAAGTGACACTGACATGTGGC
CCCATTTCTGGACATGTTGCTCTCTATTGGTACCAACAGATAACTGGAAAGGGAATAGAA
ATGCTGGTAAATTTCCAGAATAACAAGGCTCTTGATGATACTAGATTGCCTAAAGAAAGA
TTCATAGTTGAATGGCTTAAAGAATCACCATCAACCCTGACGATCAAATCTACAGAATTT
GGAGACTCTGCTGTGTATCTCTGTGCCAGCAGCTCTACCACAGCTCTG
>MONDO8_213.PE11                       342 CDS /gene="ENSMODG00000025463" /gene_family="HOG000168489" /prot
ATGGGCATCATTTTTCTTCACTGGGTTTCCATTTTTCTCCTGGGAGGAGGACTTACAGAT
GCGGGTGTCACGCAGGTGCCCAAATACCTCATCACAGAAACAGGACAACAAGTGACACTG
ACATGTGGCCCCATTTCTGGACATGTTGCTCTCTATTGGTACCAACAGATAACTGGAAAG
GGAATAGAAATGCTGGTAAATTTCCAGAATAACAAGGCTCTTGATGATACTAGATTGCCT
AAAGAAAGATTCATAGTTGAATGGCTTAAAGAATCACCATCAACCCTGACGATCAAATCT
ACAGAATTTGGAGACTCTGCTGTGTATCTCTGTGCCAGCAGC
>MONDO8_213.PE13                       336 CDS /gene="ENSMODG00000025465" /gene_family="HOG000168489" /prot
ATGGGCACCAGAATCCTTCACTGGGTTTCCATGTTTCTGCTGGGAGCAGGGATTACAAAT
GCTGGAGTCACCCAGATCCCCAAACAGCTTATCGCAGAAACAAGACAGCAAGTGAACCTG
ACGTGTCACCCCATTTCTGGACACAATGCACTTTACTGGTACCGACAGGTCCCAGGGAAG
GGAATAGAGATGCTGATTGGTTTCCAGAACAATGAGGATTTTGATAAGACTGGATTACCT
GATCAATTCATAGTCAAATGGCCTAAATCATTACCCTCAACCCTGACAATCCAATCCACA
GAACTCAAGGACTCTGCTGTGTACCTCTGTGCCAGC
>MOUSE6.PE560                          344 CDS /gene="ENSMUSG00000076462" /gene_family="HOG000168489" /protein
ATGGGCTCCATTTTCCTCAGTTGCCTGGCCGTTTGTCTCCTGGTGGCAGGTCCAGTCGAC
CCGAAAATTATCCAGAAACCAAAATATCTGGTGGCAGTCACAGGGAGCGAAAAAATCCTG
ATATGCGAACAGTATCTAGGCCACAATGCTATGTATTGGTATAGACAAAGTGCTAAGAAG
CCTCTAGAGTTCATGTTTTCCTACAGCTATCAAAAACTTATGGACAATCAGACTGCCTCA
AGTCGCTTCCAACCTCAAAGTTCAAAGAAAAACCATTTAGACCTTCAGATCACAGCTCTA
AAGCCTGATGACTCGGCCACATACTTCTGTGCCAGCAGCCAAGA
>MOUSE6.PE570                          347 CDS /gene="ENSMUSG00000076472" /gene_family="HOG000168489" /protein
ATGGGCATCCAGACCCTCTGTTGTGTGATCTTTTATGTTCTGATAGCAAATCACACAGAT
GCTGGAGTTACCCAGACACCCAGACATGAGGTGGCAGAGAAAGGACAAACAATAATCCTG
AAGTGTGAGCCAGTTTCAGGCCACAATGACCTTTTCTGGTACAGACAGACCAAGATACAG
GGACTAGAGTTGCTGAGCTACTTCCGCAGCAAGTCTCTTATGGAAGATGGTGGGGCTTTC
AAGGATCGATTCAAAGCTGAGATGCTAAATTCATCCTTCTCCACTCTGAAGATTCAACCT
ACAGAACCCAAGGACTCAGCTGTGTATCTGTGTGCCAGCAGTTTAGC
>MOUSE6.PE571                          347 CDS /gene="ENSMUSG00000076473" /gene_family="HOG000168489" /protein
ATGGCCCCCAGGCTCCTTTTCTGTCTGGTTCTTTGCTTCTTGAGAGCAGAACCAACAAAT
GCTGGTGTCATCCAAACACCTAGGCACAAGGTGACAGGGAAGGGACAAGAAGCAACTCTG
TGGTGTGAGCCAATTTCAGGACATAGTGCTGTTTTCTGGTACAGACAGACCATTGTGCAG
GGCCTGGAGTTCCTGACTTACTTTCGAAATCAAGCTCCTATAGATGATTCAGGGATGCCC
AAGGAACGATTCTCAGCTCAGATGCCCAATCAGTCGCACTCAACTCTGAAGATCCAGAGC
ACGCAACCCCAGGACTCAGCGGTGTATCTTTGTGCAAGCAGCTTAGA
>MOUSE6.PE576                          347 CDS /gene="ENSMUSG00000076478" /gene_family="HOG000168489" /protein
ATGGGTGCACGGCTCATTTGCTATGTAGCACTTTGCCTCCTGGGGGCAGGCTCTTTTGAT
GCTGCAGTTACACAGAAGCCAAGATATTTGATCAAAATGAAAGGCCAGGAAGCAGAGATG
AAATGTATCCCTGAAAAGGGGCACACTGCTGTTTTCTGGTATCAACAAAAGCAGAGCAAA
GAATTAAAGTTCCTGATTTACTTTCAGAATCAACAGCCTCTTGATCAAATAGACATGGTC
AAGGAGAGATTCTCAGCTGTGTGCCCCTCCAGCTCACTCTGCAGCCTGGGAATCAGAACG
TGCGAAGCAGAAGACTCAGCACTGTACTTGTGCTCCAGCAGTCAATC
>MYOLU115371.PE1                       348 CDS /gene="ENSMLUG00000008634" /gene_family="HOG000168489" /prot
ATGGGCACCAGGATCCTCTGCTGGGTGAGCCTCTGTCTCCTGGGGGCAGGTCACACAGAT
GCTGGAGTGTCCCAGTCCCCCAGGCACATAGTCACAGAGAGGGGACAGGATGTTGCTCTC
AGGTGTGATCCAATTTCTGGACACTCGGTCCTTTACTGGTACCAACAGACACTAGGGCAG
GGCCCGGAGTTTTTGCTTTACTTCCAAGGCAAGAATGGCCCATACACATCAGGGATGCCT
AAAGAGCGGTTCTCTGCTGAGAGGCCTGATGGCTCCTACTCTACTCTGAAGATCCAGCGT
GCAGAGCAGGGGGACTCAGCCGTGTACCTCTGTGCCAGCAGCTTAACC
>PANTR9_36.PE30                        351 CDS /gene="ENSPTRG00000020866" /gene_family="HOG000168489" /prote
ACCATGTGCCTCAGACTTCTCTGCTGTGTGGCCCTTTCTTTCTGGGGAGCAGCCTCCATG
GACACCAAGGTCACCCAGAGACCTAGACTTCTGGTCAAAGCAAATGAACAGAAAGCAAAG
ACGGACTGTGTTCCTATAAAAAGACATAGTTATGTTTACTGGTATCATAAGACGCTGGAA
GAAGAGCTCAAGTTTTTGATTTACTTTCAGAATGAAGAAATTATTCAGAAAGCAGAAATA
ATCAATGAGCGATTTTCAGCCCAATGCCCCCAAAACTCACCCTGTACCTTGGAGATCCAG
TCCACGGAGTCAGGGGACACAGCATGGTATTTCTGTGCCAACAGCAAAGCC
>PANTR9_36.PE31                        360 CDS /gene="ENSPTRG00000020867" /gene_family="HOG000168489" /prote
ACTGGCACCAGGCTTCTCGGCTGTGTAGCTCTTTGTCTCCTGGCAGCAGGCTGTTTTCAT
GCCAAAGTCACACAGACTCCAGGATATTTGGTCAAAGGAAAAGGAAGGAAAACAAAGATG
TATTATACCCCCGAAAACAGACATACTTTCGTTTGTTGGTATCAGCAGAATCAGAATAAA
GAGTTTATGTTTTTGATTTCCTTTCAGAATGAACAAGTTCTTCAAGAAATGGAGATGCAC
AAGAAGCGATTCTCATCTCAATGCCCCAAGAACCCACCCTGCAGCCTGGCAATCCTGTCC
TCGGAACCGGGAGACACCGCACTGTATCTCTGTGCCACCAGTCCGTCCACAGCACTGAAA
>PANTR9_36.PE32                        387 CDS /gene="ENSPTRG00000033770" /gene_family="HOG000168489" /prote
ATGGCCTCCCTGCTCCTCTTCTGTGTGGCCTTTTGTCTCCTGGGAACAGGGTCCATGGAT
GCTGACGTTATCCAGACCCCAAGGAATAGGATCGCAAAGACAGGAAAGAGGATTATGCTG
GAATGTTCTCAGACTAAGGGTCATGATGGAATGTACTGGTATCGACAAGACCCAGGACTG
GGGCTACGGTTGATCTATTGCTCCTTTGATGTTAATTCCACAGAGAAGGGAGATCTTTCC
TCTGAGTCAACAGTCTCCAGAATAAGGATAGAGCGTTTTCCCCTGACCCTGGAGTCTGCC
AGCCCCTCACATACCTCTCAGTACCTCTGTGCCAGCAGTGAATACACAGTGCTACATAGA
TACCGACACTCTGCACAGAAAGGGTCG
>PIG18_7.PE21                          345 CDS /gene="ENSSSCG00000016476" /gene_family="HOG000168489" /protein
ATGTGCTTCAGCCTCCTCTGCTGTGTGGCCCTTTATTTCTGGGGAGCAGGCTCCATGGAC
ACTCAGGTCACCCAGAGTCCTGGCTATCTGGTCAAAGGAAAAGAACAGAAAGCAAAGATG
GAGTGTGTCCCCATAAAAGGACATAGTTATGTTTATTGGTATTGGAAGAAGTTGGAAGAA
GCATTGGAGTTCTTGGTTTACTTACAGAATCAAAAAATCACAGATGAGACAGAAGTGTTC
AAACAGCGATTTACAGCCGAGTGCCTCAAGAACTCCTGCAGCCTGGGAATCAATTCCACT
GAGGCAGGGGACTCAGCAGTGTTTTTCTGTGCCAGCAGCAAAGCC
>PONPY7RD_1.PE6                        348 CDS /gene="ENSPPYG00000018244" /gene_family="HOG000168489" /prote
ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGACAGATCACACAGGT
GCTGGAGTCTCCCAGTCCCCAAGGTACAAAGTCGCAAAGAGGGGACAGGATGTAGCTCTC
AGGTGTGATTCAATTTTTGGTCATGTAACCTTTTATTGGTACCAACAGACCCTGGGGCAG
GGCCCAGAGGTTCTGACTTACTTCCGGAGTGATGCTCAACGAGACAAATCAGGGCTTCCC
AGTGGTCGGTTCTCTGCAGAGAGGCCTGAGGGATCTGTCTCCACTATGAAGATCCAGCAC
ACAGAGCAGGGGGACTCAGCTGTGTATCTCTGTGCCAGCAGCTTAGCC
>PONPY7RD_10.PE3                       345 CDS /gene="ENSPPYG00000018262" /gene_family="HOG000168489" /prot
ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTTTTTCTCCTGTGGGCAGGTCCAGTGAAT
GCCGGTGTCACTCAGACCCCAAAATTCCATGTCCTGAAGACAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATGACTACATGTCCTGGTATCGACAAGACCCAGGCATG
GGGCTGAGGCTGATTCATTACTCAGCTGGTGCTGGTATCACTGACAAAGGAGAAGTCCCC
AATGGCTACAATGTCTCCAGATTAAACACGGAGGATTTCCAGCTCAGACTGGAGTCAGCT
GCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCC
>PONPY7RD_11.PE2                       342 CDS /gene="ENSPPYG00000018264" /gene_family="HOG000168489" /prot
ATGGGACCCGGGCTCCTCTGCTGGGCACTGCTTTGTCTCCTCGGAACAGGCCCAGTGGAG
GCTGGAGTCACACAAAGTCCCACACACTTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACACCAGTGTGTACTGGTATCAACAGGCCCTGGGTCTG
GGCCTCCAGTTCCTCCTTTGGTATGACAAGGGAGAAGAGAGAAACAGAGGAAACTTCCCT
CGTAGATTTTCAGGTCGCCAGTTCCCTAATTATAGCTCTGAGCTGAATGTGAATGCCTTG
GAGCTGGGGGACTCGGCCCTGGATCTCTGTGCCAGCAGCTTG
>PONPY7RD_18.PE3                       342 CDS /gene="ENSPPYG00000018295" /gene_family="HOG000168489" /prot
ATGGGAATCAGGCTCCTCTGTTACGTGGCCTTTTGTTTCCTGGCTGTAGGCCTCGTAGAT
GTGAAAGTAACCCAGAGCTCGAGATATCTAGTCAAAAGGATGGGAGAGAAAGTGTTTCTG
GAATGTGTCCAGGATATGGACCATGAAAGAATGTTCTGGTATCGACAAGACCCAGGTCTG
GGGCTACGGCTGATCTATTTCTCATATGATGTTAAAATGAAAGAACAAGGAGATGTTCCT
GAGGGGTACAGTGTCTCTAGAGAGAAGAAGGGGCACTTCTCCCTGATTCTGGAGTCCGCC
AGCACCAACCAGACATCGATGTACCTCTGTGCCAGCAGTTTA
>PONPY7RD_19.PE1                       342 CDS /gene="ENSPPYG00000018297" /gene_family="HOG000168489" /prot
TCCATGTTCCTCTGCTCAGTTGTGCTTTGTCTCCTGGGAGCAGATCACGCAGATACTGGA
GTCTCCCAGGACCCCAGACACAAGATTACAAAGAGGGGACAGAATGTAACTTTCAGGTGT
GATCCAATTTCTGAACACAACCGCCTTTATTGGTACCGACAGACCCTGGGGCAAGGCCCA
GAGTTTCTGACTTACTTCCAGAATGAAGCTCAACAAGAGAAATCAGGGCTGTTCAGTGAT
CAGTTCTCTGCAGAGAGGCCTAAGGGATCTTTCTCCACCCTGAAGATCCAGCGCACAGAG
CAGGGGGACTCGGCCATGTATCTGTGTGCCAGCAGCTTAGCC
>PONPY7_145.PE17                       348 CDS /gene="ENSPPYG00000018079" /gene_family="HOG000168489" /prot
ATGGATACCTGGCTCCTATGCTGGGCAATTTTTAGTCTCTTGAAAGCAGGACTCACAGAA
CCTGAAGTCACCCAGACTCCCAGCCATCAGGTCACACAGATGGGACAGGAAGTGATCTTG
CAGTGTGTCCCCATCTCTAATCACTTATACTTCTATTGGTACAGACAAATCTTGGGGCAG
AAGATTGAGTTTCTGGTTTACTTTTTTAATGATAAAATCTCAGAGAAGTCTGAAATATTC
GATGATCGATTCTCAGCTGAAAGGCCTGATGGATCAAATTTCACTCTGAAGATCCAGTCC
ACAAAGCTGGAGGACTCAGCCATGTACTTCTGTGCCAGCAGTGAAGCC
>PONPY7_145.PE19                       342 CDS /gene="ENSPPYG00000018081" /gene_family="HOG000168489" /prot
ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAGCAGGCCCAGTGGAG
GCTGGAGTCACTCAAACTCCAAGATGTCTGATCAAAACGAGAGGACGGCAAGTGACACTG
AGCTGCTCCCCTATCTCTGGGCATAGGAGTGTATCCTGGTACCAACAGACCCCAGGACAG
GGCCTTCAGTTCCTCTTCGAATACTTCAGTGGGACACAGAGAGAAAAAGGAAACTTCCCT
GATCGATTCTCAGGGCACCAGTTCTCTAACTCTCGCTCTGAGATGAATGTGAGCGCCTTG
GAGCTGGGGGACTCGGCCCTTTATCTTTGTGCCAGCAGCTTG
>PONPY7_146.PE1                        348 CDS /gene="ENSPPYG00000018082" /gene_family="HOG000168489" /prote
ATGGGCACCAGGCTCCTCTGCTGGGCAGCCATATGTCTCCTTGGGGCAGATCACACAGGA
GCTGGAGTCTCCCAGTCCCCCAGTAACAAGGTCACAGAGAAGGGAAAGGATGTAGAGCTC
AGGTGTGATCCAATTTCAGGTCATACTGCCCTTTACTGGTACCGACAGAGCCTGGGGCAG
GGCCTGGAGTTTTTAATTTACTTCCAAGGCAACAGTGCACCAGACGAATCAGGGCTGCCC
AGTGATCGCTTCTATGCAGAGAGGTCTGGGGGATCCATCTCCACTCTGAAGATCCAGCAT
ACACAGCAGGAGGACTCGGCCATGTATCTCTGTGCCAGCAGCTTAGCC
>PONPY7_146.PE2                        345 CDS /gene="ENSPPYG00000018083" /gene_family="HOG000168489" /prote
ATGAGCCTTGGGCTCCTGTGCTGTGCGGCCTTTTCTCTCCTGTGGGCAGGTCCAGTGAAT
GCTGGTGTCACTCAGACCCCAAAATTCCGCATCCTGAAGACAGGACAGAGCATGACACTG
CAGTGTGCCCAGGATATGAACCATAACTACATGTACTGGTATCGACGAGACCCAGGCATG
GGGCTGAAGCTGATTTATTACTTAGTTGCTGCTGGTACTACTGATAAAGGAGAAGTCCCC
GATGGCTACAGTGTCTCCAGATCAACCACAGAGGATTTCCCGCTCACGCTGGAGTCGGCT
GCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCC
>PONPY7_146.PE3                        342 CDS /gene="ENSPPYG00000018084" /gene_family="HOG000168489" /prote
ATGGGCCCCGGGCTCCTCTGCTGGGCACTGCTTTGCCTCCTGGGAGCAGGCCCAGTACAG
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAATGAGAGGACAGCAAGTAACTCTG
AGATGCTCTCCTTTCTCTGGGCACACCAGCGTGTCCTGGTACCAACAGTCCCTGGGTCAG
GGGCCCCAATTTATCTTCGAATATGCTAATGAGTTAAGGAGATCAAAAGGAAACTTCCCT
GATCGATTCTCAGGTCGCCAGTTCCGTGACTATCACTCTGAGATGAATGTGAGTGCCTTG
GAGCTGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGGTTG
>PONPY7_146.PE4                        342 CDS /gene="ENSPPYG00000018085" /gene_family="HOG000168489" /prote
ATGGGCTTCAGGCTCCTCTGCTGTGTGGTCTTTTGTCTCCTGGGAGCAGGCCCAGTGGAT
TCTGGAGTCACACAAACCCCAAAGCACCTGATCACAGCAACAGGACAGCGAGTGACGCTG
AGATGCTCCCCTAGGTCTGGAGACCTCTCTGTGTACTGGTACCAACAGAGCCTGGACCAG
GGCCTCCAGTTCCTCATTCAGTATTATAATGGAGAAGAGAGAGAAAAAGGAAACATTCTT
GAACGATTCTCCGCACAACAGTTCCCTGACTTGCACTCTGAACTAAACCTGAGCTCTCTG
GAGCTGGGGGACTCGGCTTTGTATTTCTGTGCCAGCAGCGTA
>PONPY7_146.PE7                        342 CDS /gene="ENSPPYG00000018088" /gene_family="HOG000168489" /prote
ATGGGCCCCGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAGCAGGCCCAGTGGAC
GCTGGAGTCACCCAAAGTCCCACACACCTGATCAAAACGAGAGGACAGCAAGTGACTCTG
AGATGCTCTCCTATCTCTGGGCACAAGAGTGTGTCCTGGTACCAACAGGCCCTGGGTCAG
GGGCCCCAGTTTATCTTTGAGTATTATGAGAAAGAAGAGAGAGGAAGAGGAAACTTCCCT
GATCGATTCTCAGCTCGCCAGTTCCCTAACTATAGCTCTGAGCTGAATGTGAACGCCTTG
TTGCTGGGGGACTCGGCCCTGTATCTCTGTGCCAGCAGCTTG
>PONPY7_146.PE15                       342 CDS /gene="ENSPPYG00000018096" /gene_family="HOG000168489" /prot
ATGAGCAACCAGGTGCTCTGCTGTGTGGTCCTTTGTCTCCTCGGAGCAAACACCGTGGAT
GGTGGAATCACTCAGTCCCCAAAGTACCTGTTCAGAAAGGAAGGACAGAATGTGACCCTG
AGTTGTGAACAGAACTTGAATCACGATGCCATGTACTGGTACCGACAGGACCCAGGGCAA
GGGCTGAGATTGATCTACTACTCAGGGATAGTAAATGACTTTCAGAAAGGAGACATAGCT
GAAGGGTACAGCGTCTCTCGGGAGAAGAAGGAATCCTTTCCTCTCACTGTGACATCGGCC
CAAAAGAACCCGACAGCTTTCTATCTCTGTGCCAGTAGTATA
>PONPY7_146.PE17                       348 CDS /gene="ENSPPYG00000018098" /gene_family="HOG000168489" /prot
ATGGGCACCAGGCTCCTCGGCTGTGCAGCCCTGTGTCTCCTGGCCAGAGGCTCTTTTCAT
GCCAGAGTCACACAGACTCCAGGACATTTGGTCAAAGGAAAAGGACAGAAAACAAAGATG
GATTGCACCCCTGAAAAAGGACATACTTTTGTTTATTGGTATCAACAGAATCAGAATAAA
GAGTTTATGCTTTTGATTTCCTTTCAGAATAAACAAGTTCTTCAAGAAACGGAGATGCAC
AAGAAGCGATTCTCATCTCAATGCCCCAAGAACACACCCTGCAGCCTGGCAACCCTGTCC
TCGGAACCAGGAGACACGGCACTGTATCTCTGTGCCAGCAGTCAATCC
>PONPY7_146.PE19                       342 CDS /gene="ENSPPYG00000018100" /gene_family="HOG000168489" /prot
ATGACTATCAGGCTCCTCCGCTACGTGGCCTTTTATTTTCTGGGGGCAGGCCTCATGGAA
GCTGACATCTACCAGACCCCAAGACACCTTGTTATAGGGACAGGAAAGAAGATCACTCTG
GAATGTTCTCAAACCATGGGCCATGACAAAATGTACTGGTATCAACAAGATCCAGGAATG
GAACTACACCTCATCCACTATTCCTATGGGGTTAATTCCACAGAGAAGGGAGATCTTTCC
TCTGAGTCAACGGTCTCCAGAATAAGGATGGAGCATTTTCCCCTGACCCTGGAGTCTGCC
AGGCCCTCACATACCTCTCAGTACCTCTGTGCCAGCAGTGAA
>PONPY9RD_7.PE1                        360 CDS /gene="ENSPPYG00000019864" /gene_family="HOG000168489" /prote
ACGGGCACCAGGCTCCTCGGCTGTGCAGCTCTTTGTCTCCTGGCAGCAGGCTGTTTTCAT
GCCAAAGTCACACAGACTCCAGGATATTTGGTCAAAGGAAAAGGAAGGAAAACAAAGATG
TATTGTACCCCCGCAAAGGGACATACTTTTGTTTGTTGGTATCAACAGAATCAGAATAAA
GAGTTTATGTTTTTGATTTCCTTTCAGAATGAACAAGTTCTTCAAGAAACGGAGATGCAC
AAGAAGCGATTCTCATCTCAATGCCCCAAGAACCCACCCTGCAGCCTGGCAATCCTGTCC
TTGGAACCGGGAGACACCGCACTGTATCTCTGCGCCAGTAGTCCGTACACAGCACTGAAA
>PROCA70825.PE1                        360 CDS /gene="ENSPCAG00000009509" /gene_family="HOG000168489" /prote
ATGGACCCCACACTTCTCTGCCTGGTGATCTTGTGCTTCCTGGCAGCAGGCTCCACGGAC
ACTGAGGTCACCCAGACTCCAAGACAGCTGGTCAGAGCAAGAAACCAGACAGCAAAGATG
GACTGTGTTCCTAAAACTGGGCATAATTATGTCTGCTGGTATCATCAGAAGCTGGGAGAG
GAGCTCAAGTTTTTAATTAATTTCAATTATGATCAAGCTGTTGATGCATCAGGAATGCCT
GATAAAAGATTTGTAGCTCAGTGCCCCCAAAACTCACCCTGCAGCATGGAGATCAAGTCC
ACAGAGCCCAAGGACTCAGCCGTGTACTTCTGTGCCAGCAGTGAAACCACACTGCTTGCA
>RAT15.PE490                           342 CDS /gene="ENSRNOG00000039370" /gene_family="HOG000168489" /protein_
ATGAAGACACTGACTGGATCTTTGTTCCTGTTCTTCTGGCTGCAGCTGAACTGTGTAAGC
AGAGGAGAGCAGGTGGAGCAGCGCCCGTCTCACCTGAGTGTCCGGGAGGGAGACAGTGCC
GCTATCGTCTGCACCTACACAGACCCTAATAATTATTACTTCTACTGGTACAAGCAAGAA
CCTGGAGCAGGTCTTCAGTTGCTTATGGAGGTTTTCTCAAGTACAGAAATAAAAGAAGGA
CAAGGATTCATTGTCCTACTGAACAAGAACGACAAACGTCTCTTGCTGAACATTACAGCT
GCCCATCTTGGGGACTCTGCCAAATACTTCTGTGCAGTCAGA
>RAT4.PE579                            345 CDS /gene="ENSRNOG00000043164" /gene_family="HOG000168489" /protein_i
ATGAGCAAGCAGGTTCTCTGCTTGGTAGCTCTTTGTCTCCTTGCAGTAGGAACCACACAT
GGTGGTGCCATTACTCAGACACCCAAATTCCTGATTGGTCATGAAGGGCAAGAGCTGACC
TTGAAATGTAAACAGAATTTCAATCATGATTCAATGTTCTGGTACCGACAAGATCCAGGG
AAAGGACTGAGACTGATCTACTACTCAATAACTGAAAGCGATCTTCAAAAAGGCGACCTA
TCTGAAGGCTACGATGCCTCTCGAAAGGAGAAGGCATCTTTTTCTCTCACTGTGAAATCT
GCCCAGAAGAGGCAGATGGCTGTTTATCTCTGTGCCAGCAGCATA
>RAT4.PE580                            345 CDS /gene="ENSRNOG00000042764" /gene_family="HOG000168489" /protein_i
ATGAACATGCGGTTTCTCTGCTGTGTAGCCCTTTATCTCCTGCTAGCAGGCTCTTTGGAT
TGCCAAGTTATCCAAACTCCACAGCATCTGCTCAGAGGAAAAGGACAGAAAGCAAAAATG
ACCTGTATTGCTGAAAAGGGACATACTTTTGTTTATTGGTACCAACAGAAGCAGAACAAA
GAGTTAAAATTTTTGATTTATTTTCAACGTCAAGAACCTCGTGACAGTATAGACTTGGTC
AAGGAGCGATTCTTAGCTGAGTGTCCCTTAAACTCTCCCTGCAGCCTGGAAATACAGTCC
TCTGAGGCAGGAGACTCAGCATTATACCTCTGTGCCAGCAGTCTG
