>AILMEGL192338_1_4.PE8                 489 CDS /gene="ENSAMEG00000016928" /gene_family="HOG000024955" /pro
ATGGACGCCCTAGAGGAAGAGAGCTTCGCTCTGTCTTTCTCTTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTATCAGGAGTTTGAAGACACGGAAGAGAACAAACTC
ACCTATACGCCTATTTTTAACGAATACATTTCTTTGGTAGAAAAGTATATTGAAGAACAG
CTGCTGGAGCGGATTCCTGGATTTAACATGGCGGCTTTCACCACAACTTTACAGCACCAT
AAAGATGAAGTGGCTGGTGACATATTTGACATGCTGCTCACGTTTACAGATTTTCTGGCT
TTTAAAGAAATGTTTCTGGACTACAGAGCAGAAAAAGAAGGCCGGGGACTGGACTTAAGC
AGTGGTTTAGTGGTGACTTCATTGTGCAAATCATCTGTGCCAGCTTCCCAGAATGACCTG
CGGCCCTAG
>ANOGA_10.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_11.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_12.PE2903                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_13.PE2901                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_14.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_15.PE2900                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_16.PE2897                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_17.PE2894                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_171.PE466                       438 CDS /gene="AGAP012917" /gene_family="HOG000024955" /protein_id="
GACGCCCGGACAAAGATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAA
TACTTCGACACTGTGATTGGCCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGG
ATGGTCAATCAGTTCATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAATAAA
ATCGTCTACACGGAGATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAG
CATCTGAACCGGAAGATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAAC
AAGAAGACGCAGCTCGACGGGGAGATCTTCGAGCTGCTGTACACGCTGACCGACTTTCTC
GCCTTCCAGGATATGGTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTG
AGCAAGGGCATCAGCGTG
>ANOGA_18.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_19.PE2902                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_20.PE2898                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_21.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_22.PE2897                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_23.PE2904                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_24.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_25.PE2902                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_26.PE2900                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_27.PE2902                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_28.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_29.PE2900                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_30.PE2903                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_31.PE2878                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_32.PE2887                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_33.PE2896                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_34.PE2900                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_35.PE2897                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_36.PE2870                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_37.PE2899                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_38.PE2870                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_39.PE2903                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_40.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_41.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_42.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_43.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_44.PE2894                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_45.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_46.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_47.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_48.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_49.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_50.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_51.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_52.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_53.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_54.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_55.PE2902                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_56.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_57.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_58.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_59.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_60.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_61.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_62.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_63.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_64.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_65.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_66.PE2903                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_67.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_68.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_69.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_70.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_71.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_72.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_73.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_74.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_75.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_76.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_77.PE2903                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_78.PE2905                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_79.PE2904                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>ANOGA_80.PE2904                       441 CDS /gene="AGAP012967" /gene_family="HOG000024955" /protein_id="
ATGAATTTTGAAGAAAACATCATTAAAAGACAAAATTCAAGCGAATACTTCGACACTGTG
ATCGGTCACATCGAGGACATAGTAATCGGCGAAGAGTTTCAGCGGATGGTCAATCAGTTC
ATGGAGTGCTACTACTACGAGTTTGAACCGGGGGAAGAGAACAAAATCGTCTACACGGAG
ATCTACCAGAAGTATACGAACATGATCGAGGCGCACATCGTCGAGCATCTGAACCGGAAG
ATGAGCTGCTTCGATATGGATCTGTTTGCGATGGAGCTGGAGAACAAAAAGACGCAGCTC
GACGGGGAGATCTTTGAGCTGCTGTACACGCTGACCGACTTTCTCGCCTTCAAGGATATG
GTGCTGGATTACAAGGCGTTCAAGGAAGGCGCATACGACGATCTGAGCAAGGGCATCAGC
GTGACGGGTCTGCAGAAATAG
>BOVIN18_25.PE12                       492 CDS /gene="ENSBTAG00000004844" /gene_family="HOG000024955" /prot
ATGGACGCCCTAGAGGAAGAGAGCTTCGCGCTGTCCTTCTCTTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGATGAGTTCCAGTTATTA
CAGAGGAATTTCATGGACAAGTACTACCAGGAGTTTGAAGACACGGAAGAGAATAAGCTC
ACTTACACACCTATTTTTAATGAATATATTTCTTTGGTAGAAAAGTATATAGAAGAACAG
CTGTTGGAGCGGATTCCTGGATTTAACATGGCGGCTTTCACTACAACTTTACAGCACCAT
AAAGATGAAGTGGCTGGTGACATTTTTGACATGCTGCTCACATTTACGGATTTCCTGGCT
TTTAAAGAAATGTTTCTGGACTACCGAGCAGAAAAAGAAGGCCGGGGACTGGACTTGAGC
AGTGGTTTAGTGGTGACTTCACTCTGCAAATCATCTTCTGTGCCAGCCTCCCAGAACAAT
CTGCGGCCCTAG
>BOVIN18_25.PE13                       459 CDS /gene="ENSBTAG00000004844" /gene_family="HOG000024955" /prot
ATGCGCTCTTCCGCCTCTGATGCAGAATTTGATGCTGTGGTTGGATATTTAGAGGACATT
ATCATGGATGATGAGTTCCAGTTATTACAGAGGAATTTCATGGACAAGTACTACCAGGAG
TTTGAAGACACGGAAGAGAATAAGCTCACTTACACACCTATTTTTAATGAATATATTTCT
TTGGTAGAAAAGTATATAGAAGAACAGCTGTTGGAGCGGATTCCTGGATTTAACATGGCG
GCTTTCACTACAACTTTACAGCACCATAAAGATGAAGTGGCTGGTGACATTTTTGACATG
CTGCTCACATTTACGGATTTCCTGGCTTTTAAAGAAATGTTTCTGGACTACCGAGCAGAA
AAAGAAGGCCGGGGACTGGACTTGAGCAGTGGTTTAGTGGTGACTTCACTCTGCAAATCA
TCTTCTGTGCCAGCCTCCCAGAACAATCTGCGGCCCTAG
>CALJA20_12.PE36                       489 CDS /gene="ENSCJAG00000012116" /gene_family="HOG000024955" /prot
ATGGACGCCTTAGAAGAGAGCTTTGCGCTGTCTTTCTCCTCTGCCTCTGATGCAGAATTT
GATGCCGTGGTTGGATATTTAGAGGACATTATCATGGATGACAAGTTCCAGTTACTACAG
AGAAATTTCATGGACAAGTACTACCTGGAGTTTGAAGACACAGAGGAGAATAAACTCACC
TACACTCCTATTTTTAATGAATACATTTCTCTGGTAGAAAAATATGTTGAAGAACAGCTG
CTGGAGCGGATTCCTGGATTCAACATGGCAGCTTTCACCGTAACATTACAGCATCATAGA
GATGAAGTGGCTGGTGACATATTCGACATGCTGCTCACCTTTACAGATTTTCTGGCTTTT
AAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGGCCGAGGACTGGATTTAAGCAGT
GGCTTAGTGGTGACGTCGTTGTGCAAATCATCATCTGTGCCAGCTTCCCCGAACAATCTG
CGGCACTAG
>CALJA6_141.PE2                        486 CDS /gene="ENSCJAG00000012466" /gene_family="HOG000024955" /prote
ATGGACGCCTTAGAAGAGAGCTTAGAAGAGAGCTTTGCGCTGTCTTTCTCCTCTGCCTCT
GATGCAGAATTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTC
CAGTTATTACAGAGAAATTTCATGGATAAGTACTACCTGGAGTTTGAAGACACAGAGGAG
AATAAACTCACCTACACACCTATTTTTAATGAATACATTCTGGTAGGAAAATATGTTGAA
GAACAGCTGCTGGAGCGGATTCCTGGATTCAACTTCACCACAACATTACAGCACCATAAA
GATGAAGGGGCTGGTGACATATTCGACATGCTGCTCACCTTTACAGATTTTCTGGCTTTT
AAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGTCCGAGGACTGGATTTAAGCAGT
TGCTTAGTGGGGACATCGTTGTGCAAATCATCCTCTGTGCCAGCTTCCCCGAACAATCTG
CAGCAC
>CANFA2_63.PE28                        492 CDS /gene="ENSCAFG00000008785" /gene_family="HOG000024955" /prote
ATGGACGCCCTAGAGGAAGAGAGCTTCGCGCTGTCGTTCTCTTCTGCCTCTGATGCAGAA
TTCGACGCTGTGGTTGGATATTTAGAGGACATCATCATGGATGACGAGTTCCAGTTACTA
CAGAGGAATTTCATGGACAAGTACTATCAGGAGTTTGAAGACACAGAAGAGAATAAACTC
ACCTACACGCCTATTTTTAATGAATATATTTCTTTGGTAGAAAAGTATATTGAAGAACAG
CTGCTGGAGCGGATTCCTGGGTTTAACATGGCGGCTTTCACAACAACTTTACAGCACCAT
AAAGATGAAGTGGCAGGCGACATATTTGACATGCTGCTCACGTTTACAGATTTCCTGGCT
TTTAAAGAAATGTTTCTGGACTACAGAGCAGAAAAAGAAGGTCGGGGACTGGACTTAAGC
AGTGGTTTAGTGGTGACTTCATTGTGCAAATCATCTTCTGTGCCAGCTTCCCAGAATGAC
CTGCGGCCCTAG
>CHOHOGS_5247.PE2                      492 CDS /gene="ENSCHOG00000009016" /gene_family="HOG000024955" /pro
ATGGACGCCTTAGAGGAAGAGAGCTTCGCGCTGTCCCTCTCTTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTGGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCAGGAGTTTGAAGACACAGAAGAGAATAAACTC
ACCTACACGCCCATTTTTAATGAATATATTTCCTTGGTAGAAAAGTATATTGAGGAACAG
CTGCTGGAGAGGATTCCTGGATTTAACATGGCGGCTTTCACAACAACATTACAGCACCAT
AAAGATGAAGTGGCTGGTGACATATTTGACATGCTGCTCACATTTACAGATTTTCTGGCT
TTTAAAGAAATGTTTCTGGACTACAGAGCAGAAAAAGAAGGCCGAGGATTGGACTTAAGC
AGTGGTTTAGTGGTGACTTCATTGTGCAAATCATCTTCCACGCCAGCTTCCCAGAACAAT
CTGCGGCACTAG
>FELCAGS_50.PE6                        492 CDS /gene="ENSFCAG00000002937" /gene_family="HOG000024955" /prote
ATGGACGCCGTAGAGGAAGAGAGCTTCGCCCTGTCCTTCTCTTCCGCCTCCGATGCAGAA
TTTGATGCCGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGGAATTTCATGGACAAGTACTACCAGGAGTTTGAAGACACAGAAGAGAATAAACTC
ACCTACACACCTATTTTTAATGAATATATTTCTTTGGTAGAAAAGTATATTGAGGAACAG
CTCCTGGAACGGATTCCTGGATTTAACATGGCAGCTTTCACGACAACTTTGCAGCATCAT
AAAGATGAAGTGGCTGGTGACATATTTGACATGCTGCTCACGTTCACAGATTTTCTGGCT
TTTAAGGAAATGTTTCTGGACTACAGAGCAGAAAAAGAAGGCCGGGGACTGGATTTAAGC
AGTGGTTTAGTGGTGACTTCATTGTGTAAATCATCCCCTGTGCCAGCTTCCCAGAATGAT
CTGCGACACTAG
>GORGO16_49.PE32                       492 CDS /gene="ENSGGOG00000005471" /gene_family="HOG000024955" /prot
ATGGACGCCTTAGAAGGAGAGAGCTTTGCGCTGTCTTTCTCCTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCTGGAGTTTGAAGACACAGAAGAGAATAAACTC
ATCTACACACCTATTTTTAATGAATACATTTCTTTGGTAGAAAAATACATTGAAGAACAG
CTGCTGCAGCGGATTCCTGGGTTCAACATGGCAGCCTTCACCACAACATTACAGCACCAT
AAGGATGAAGTGGCTGGTGACATATTCGACATGCTGCTCACCTTCACAGATTTTCTGGCT
TTTAAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGGCCGAGGACTGGACTTAAGC
AGTGGCTTAGTGGTGACTTCATTGTGCAAATCATCTTCTCTGCCAGCTTCCCAGAACAAT
CTGCGGCACTAG
>HORSE3_11.PE10                        456 CDS /gene="ENSECAG00000016621" /gene_family="HOG000024955" /prote
AGCTCTTCCGCCTCTGATGCAGAATTTGACGCGGTGGTTGGATATTTAGAGGACATTATC
ATGGATGACGAGTTCCAGTTATTACAGAGAAATTTCATGGACAAGTACTACCAGGAGTTT
GAAGACACGGAAGAGAATAAACTCACCTACACACCTATTTTTAATGAATATATTTCTTTG
GTAGAAAAGTATATTGAAGAACAGCTGGTGGAGCGGATTCCCGGGTTTAACATGGCGGCT
TTCACAACAACTCTACAGCACCATAAAGATGAGGTGGCTGGGGACATATTCGACATGCTG
CTCACCTTTACAGATTTCCTGGCATTTAAAGAAATGTTTCTGGACTACAGAGCAGAAAAA
GAAGGCCGGGGGCTGGACTTAAGTAGCGGTTTAGTGGTGACTTCACTGTGCAAGTCCTCG
TCCGTGCCAGCTTCCCAGAACAGTCTGCGGCCCTAG
>HORSE6_73.PE33                        492 CDS /gene="ENSECAG00000011020" /gene_family="HOG000024955" /prote
ATGGATGCAGCGGAAAGACAGAGTTTCGCGCGGTCCATCTCTTCCGCCTCTGAAGTCGAA
TTTGACGCTGTGGTTGGATCTACCGACGATGTCATCATGGATGCCGAGTCCCAGGTCCTG
CAGAGAAATTTCATGGGCAAATACTACCAGGAGTTTGAAGACACAGAAGAGAATAAACTC
GCCTACATACCCATTTTTAAAGAATTCTACCTTTCTTTGGTAGAAAAGTATATTGAAGAA
CAGCTGCTGGAGCAGATTCTGGGATTCAACATGGCGGCTTGCACAACGTTGAAACACGTT
AAAGATGAAGTGGCTGATGACATATTCAACATGCTCCTCACATTTGTAGACTTTGTGCCA
TTCAAAGAGCTGTTTCTGGACGACAGAGGAGAAAAAGAAGGCCGAGGACTGGACTTAAGC
AGTGGTGTAGCGGTGACTTCGTTGTGCAAATCATCTTCTGTGCCAGCTTCCCAGAACAGT
CAGCAGCATTAG
>HS16.PE1495                           492 CDS /gene="ENSG00000102931" /gene_family="HOG000024955" /protein_id=
ATGGACGCCTTAGAAGGAGAGAGCTTTGCGCTGTCTTTCTCCTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCTGGAGTTTGAAGACACAGAAGAGAATAAACTC
ATCTACACACCTATTTTTAATGAATACATTTCTTTGGTAGAAAAATACATTGAAGAACAG
CTGCTGCAGCGGATTCCTGAGTTCAACATGGCAGCCTTCACCACAACATTACAGCACCAT
AAGGATGAAGTGGCTGGTGACATATTCGACATGCTGCTCACCTTCACAGATTTTCTGGCT
TTTAAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGGCCGAGGACTGGACTTAAGC
AGTGGCTTAGTGGTGACTTCATTGTGCAAATCATCTTCTCTGCCAGCTTCCCAGAACAAT
CTGCGGCACTAG
>LAMPAGS_1702.PE5                      492 CDS /gene="ENSVPAG00000005976" /gene_family="HOG000024955" /pro
ATGGACGCCCTAGAGGAAGAGAGCTTCGCGATGACCTTCTCTTCCGCCTCTGATGCAGAA
TTTGATGCCGTGGTTGGATATTTAGAGGACATTATCATGGATGATGAGTTCCAGTTATTA
CAGAGGAATTTCATGGACAAGTACTACCAGGAGTTTGAAGACACAGAAGAGAATAAGCTC
ACCTACACACCTATTTTTAACGAATATATTTCTTTGGTAGAAAAGTATATTGAAGAACAG
CTCTTGGAGCGGATTCCTGGATTTAACATGGCGGCTTTCACTACGACTTTACAGCACCAT
AAAGATGAAGTGGCTGGTGACATTTTCGACATGCTGCTCACGTTTACGGATTTTCTGGCT
TTTAAAGAAATGTTTCTGGACTATCGAGCAGAAAAAGAAGGCCGGGGAGTGGACTTAAGC
AGCGGTTTAGTGGTTACTTCGTTGTGCAAATCATCTTCTATGCCAGCTTCCCAGAACAAT
CTGTGGTCCTAG
>MACMU20_57.PE42                       492 CDS /gene="ENSMMUG00000020352" /gene_family="HOG000024955" /prot
ATGGACGCCTTAGAAGAAGAGAGCTTTGCGCTGTCTTTCTCCTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCTGGAGTTTGAAGACACAGAAGAGAATAAACTC
ACCTACACACCTATTTTTAATGAATACATTTCTTTGGTAGAAAAATATATTGAAGAACAG
CTGCTGCAGCGGATTCCTGGGTTCAACATGGCAGCTTTCACCACAACATTACAGCACCAT
AAGGATGAAGTGGCTGGTGACATATTCGACATGCTGCTCACTTTCACAGATTTTCTGGCT
TTTAAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGGCCGAGGACTGGACTTAAGC
AGTGGCTTAGTGGTGACTTCGTTGTGCAAATCATCTTCTGTGTCAGCTTCCCAGAACAAT
CTGCGGCACTAG
>MICMUGS_2226.PE4                      465 CDS /gene="ENSMICG00000012467" /gene_family="HOG000024955" /pro
GCGCTGTCCTTTTCGTCCGCCTCTGATGCAGAATTTGATGCCGTGGTTGGCTATTTGGAG
GACATTATCATGGATGATGAGTTCCAGATACTACAGAGAAATTTCATGGACAAGTACTAC
CAGGAATTTGAGGACACAGAAGAGAATAAACTCACCTACACCCCTATTTTTAATGAATAT
ATTTCTCTGGTAGAAAAGTATATTGAAGAACAGCTGCTAGAGCGCATTCCCGGATTTAAC
ATGGCGGCTTTCACAACGACGTTACAGCACCATAAGGATGAAGTGGCTGGTGACATATTT
GACATGCTGCTCACATTTACAGATTTTCTGGCTTTTAAAGAAATGTTTCTGGACTACAGA
GCAGAAAAAGAAGGCCGGGGACTGGACTTAAGCAGTGGTTTAGTGGTGACTTCATTGTGC
AAATCATCTTCTATGCCAACTTCCCAGAACAATTTACGGCACTAG
>MOUSE8.PE1466                         459 CDS /gene="ENSMUSG00000031776" /gene_family="HOG000024955" /protei
ATGCGCTCCTCCGCCTCTGATGCAGAATTTGATGCTGTGGTTGGATGTTTAGAGGACATT
ATTATGGATGATGAGTTCCAGTTATTGCAGAGAAACTTCATGGACAAGTACTACCAGGAA
TTTGAAGACACAGAAGAGAATAAACTCACCTATACACCCATTTTTAATGAATATATCTCC
CTGGTAGAGAAGTACATTGAAGAGCAGTTGCTGGAGCGTATCCCAGGCTTCAACATGGCG
GCCTTCACAACCACGCTGCAGCACCACAAAGATGAGGTGGCTGGCGACATCTTTGACATG
CTGCTCACATTCACGGATTTTCTGGCTTTCAAGGAGATGTTCCTGGACTACAGAGCAGAA
AAGGAAGGCCGAGGACTGGACTTAAGCAGCGGCTTGGTTGTGACTTCTCTGTGTAAGTCA
TCTTCTACGCCAGCTTCCCAGAACAACCTGCGGCACTAG
>ORYLA6_24.PE29                        441 CDS /gene="ENSORLG00000015513" /gene_family="HOG000024955" /prote
ATGGCTTGTAAACAATGGAATACGTCTCACTCAGAGGCAGACTCGGCCTTCGACGCTGTC
ATTGGCTGTATAGAAGATATCTTCATGGAGGATCAGTTCCAGCAGCTCCGGGGGGATTTC
ATGGAGAAATACTACCTCGAGTTTGATGGTTTAGATGAGAACAAGCTCAGCTACACGTCC
ATCTTTAATGAATATGTAGGCCTGTTGGAGAAACACCTGGAGCAGAAGCTGATGGAGAGA
ATCCCCAACTTCAACATGAACACCTTCACAGAGCTGCTCATGCAGCATAAAGATGAAGTT
CAGGGCGACATCTTTGACACGCTGTTGACCTTCACAGACTTCCTGGCTTTCAAAGAAATG
TTTCTGGATTACAAAGCAGATAGAGAAGGTGGAGGTCAGGGGTTGGTGGTCACAGCTCTT
CCTGCAGCTTCTTCACACTGA
>ORYLA6_24.PE30                        456 CDS /gene="ENSORLG00000015513" /gene_family="HOG000024955" /prote
GTCATGAATAAAGATAATTTGGACGAAGAAATTATTGCTGTTTCCTGTTCTTCAGAGGCA
GACTCGGCCTTCGACGCTGTCATTGGCTGTATAGAAGATATCTTCATGGAGGATCAGTTC
CAGCAGCTCCGGGGGGATTTCATGGAGAAATACTACCTCGAGTTTGATGGTTTAGATGAG
AACAAGCTCAGCTACACGTCCATCTTTAATGAATATGTAGGCCTGTTGGAGAAACACCTG
GAGCAGAAGCTGATGGAGAGAATCCCCAACTTCAACATGAACACCTTCACAGAGCTGCTC
ATGCAGCATAAAGATGAAGTTCAGGGCGACATCTTTGACACGCTGTTGACCTTCACAGAC
TTCCTGGCTTTCAAAGAAATGTTTCTGGATTACAAAGCAGATAGAGAAGGTGGAGGTCAG
GGGTTGGTGGTCACAGCTCTTCCTGCAGCTTCTTCA
>PANTR16_59.PE27                       492 CDS /gene="ENSPTRG00000008150" /gene_family="HOG000024955" /prot
ATGGACGCCTTAGAAGGAGAGAGCTTTGCGCTGTCTTTCTCCTCCGCCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCTGGAGTTTGAAGACACAGAAGAGAATAAACTC
ATCTACACACCTATTTTTAATGAATACATTTCTTTGGTAGAAAAATACATTGAAGAACAG
CTGCTGCAGCGGATTCCTGAGTTCAACATGGCAGCCTTCACCACAACATTACAGCACCAT
AAGGATGAAGTGGCTGGTGACATATTCGACATGCTGCTCACCTTTACAGATTTTCTGGCT
TTTAAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGGCCGAGGACTGGACTTAAGC
AGTGGCTTAGTGGTGACTTCATTGTGCAAATCATCTTCTCTGCCAGCTTCCCAGAACAAT
CTGCGGCACTAG
>PONPY16_47.PE2                        492 CDS /gene="ENSPPYG00000007384" /gene_family="HOG000024955" /prote
ATGGACGCCTTAGAAGAAGAGAGCTTTGCGCTGTCTTTCTCCTCCACCTCTGATGCAGAA
TTTGATGCTGTGGTTGGATATTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCTGGAGTTTGAAGACACAGAAGAGAATAAACTC
ATCTACACACCTATTTTTAATGAATATATTTCTTTGGTAGAAAAATATATTGAAGAACAG
CTGCTGCAGCGGATTCCTGGGTTCAACATGGCAGCTTTCACCACAACATTACAGCACCAT
AAGGATGAAGTGGCTGGTGACATATTCGACATGCTGCTCACCTTCACAGATTTTCTGGCT
TTTAAAGAAATGTTTTTGGACTACAGAGCAGAAAAAGAAGGCCGAGGACTGGACTTAAGC
AGTGGCTTAGTGGTGACTTCGTTGTGCAAATCATCTTCTCTGCCAGCTTCCCAGAACAAT
CTGCGGCACTAG
>PTEVAGS_1864.PE5                      492 CDS /gene="ENSPVAG00000001391" /gene_family="HOG000024955" /pro
ATGGACGCCTTAGAGGAAGAGAGCTTCGCGCTGTCCTTCTCTTCCGCTTCTGATGCAGAA
TTCGATGCTGTGGTTGGATGTTTAGAGGACATTATCATGGATGACGAGTTCCAGTTATTA
CAGAGAAATTTCATGGACAAGTACTACCAGGAGTTTGAAGACACAGAAGAGAATAAACTC
ACCTACACACCTATTTTTAACGAATACATCTCTCTGGTAGAAAAGTACATCGAAGAACAG
CTGCTGGAGCGCGTTCCTGGATTTAACATGGCAGCTTTCACGACGACTCTACAGCACCAT
AAAGATGAAGTGGCTGGTGACATATTTGACATGCTCCTCACATTTACGGATTTTCTGGCT
TTTAAAGAAATGTTTCTGGACTACAGAGCAGAAAAAGAAGGCCGGGGACTGGACTTGAGC
AGTGGTTTAGTGGTGACTTCATTGTGCAAACCATCCTCTGTGCCAGCCTCGCAGAACAAT
GTGCGGCGCTAG
>RAT19.PE83                            459 CDS /gene="ENSRNOG00000016991" /gene_family="HOG000024955" /protein_i
TTCAGCTCCTCTGCCTCTGATGCAGAATTCGATGCTGTGGTTGGATGTTTAGAGGACATT
ATTATGGATGCTGAGTTCCAGCTACTGCAGAGAAGCTTCATGGACAAGTACTACCAGGAA
TTTGAAGACACTGAAGAGAATAAGCTCACCTATACTCCCATTTTTAATGAATATATTTCC
CTGGTAGAGAAGTACATTGAAGAGCAGTTGCTGGAGCGTATCCCAGGCTTCAATATGGCG
GCCTTCACCACCACACTGCAGCACCATAAAGATGAAGTGGCTGGCGACATCTTTGACATG
CTGCTCACATTCACGGATTTCCTGGCTTTCAAGGAGATGTTCCTGGACTACAGAGCAGAA
AAGGAAGGCCGAGGACTGGACTTAAGCAGCGGCTTGGTGGTGACTTCTCTGTGTAAGTCA
TCTTCTACGCCAGCTTCCCAGAACAACCTACGGCACTAG
>SORARGS_4666.PE2                      453 CDS /gene="ENSSARG00000005442" /gene_family="HOG000024955" /pro
TCTTCAGCCTCTGATGCGGAATTTGATGCCGTAGTTGGGTATTTAGAAGACATTATCATG
GATGATGAGTTCCAATTATTACAGAGAAATTTCATGGATAAGTACTACCAGGAGTTTGAA
GACACAGAAGAGAATAAACTCACCTATACACCTATTTTTAATGAATATATTTCTTTGGTA
GAAAAGTATATTGAAGAGCAGCTGGTGGAGCGGATCCCTGGGTTCAACATGGCAGCGTTC
ACGACGAACTTACAGCACCATAAAGATGAAGTGGCTGGTGACATATTCGACATGCTGCTC
ACATTTACGGATTTCCTGGCTTTTAAAGAAATGTTTCTGGACTACAGAGCCGAGAAAGAA
GGCCGGGCACTGGACCTGAGCAGTGGTCTGGTGGTGACATCCTTGTGCAAGTCACCCACT
GTCCCCGCTCCCCAGAACGACCTCCGGCCGTAG
