>AILMEGL192794_1_1.PE39                261 CDS /gene="ENSAMEG00000000563" /gene_family="HOG000165128" /pro
ATGGCAGAAGACATCAAGACCAAAATCAAGAACTACCAGACCGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACTAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACTGCTAAAGGGGGTGATGTCTCCGTGTGTGAATGGTACCGGCGTGTG
TACAAGTCCCTCTGCCCCATATCCTGGGTGTCAGCCTGGGACGACCGCCGGGCAGAAGGC
ACATTTCCTGGGAAGATCTGA
>ANOGA_1.PE1971                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_2.PE1968                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_3.PE1971                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_4.PE1971                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_5.PE1970                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_6.PE1971                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_7.PE1970                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_8.PE1971                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ANOGA_9.PE1971                        231 CDS /gene="AGAP013092" /gene_family="HOG000165128" /protein_id="A
ATGGCGTACGAACCGAAGACGGCCCCATTCGATCCCCGCTTCCCCAACCAGAACCAGACC
AAGCACTGCTACCAGAGCTATCTGGATTTCCACCGCTGCGAGAAGGTCAAGGGCGAGGGC
GACCAGGTATGCAAGTACTTCAAGAACGTCTTCTCGTCGATGTGCCCCAACTCGTGGGTT
GAGAAGTGGGACAGCCAGCGCGAGGAGGGCACCTTTGCCGGCCACATCTAA
>ASFUM1_2.PE1125                       276 CDS /codon_start=1 /gene_family="HOG000165128" /evidence="4: Pre
ATGGGTGCCATTCCTGAAGCCGATCCCGATGAGCCCATGGAGACCAAGCCCTTCAAGTTC
GTGACAGGCTATGACGCTCGCTTCCCCCAGCAGAACCAGACCAAGCACTGCTGGCAGAAC
TACGTTGACTACCACAAGTGTATCAACGCCAAGGGCGAGGATTTCCGTCCATGCCGCCAG
TTCTACCACGCTTACCGCTCCCTGTGCCCCAAGGCCTGGACTGACAGATGGGATAACCAA
CGCGAGGCTGGAAACTTCCCTGCTCGTCTTGAGTAG
>ASPCL_104.PE381                       276 CDS /gene="CADACLAG00006899" /gene_family="HOG000165128" /protei
ATGGGTGCCATTCCTGAAGCCGATCCCGATGAACCCATGGAGACCAAGCCCTTCAAGTTC
GTGACAGGCTATGACGCCCGCTTTCCCCAGCAGAACCAGACCAAGCACTGCTGGCAGAAC
TACGTCGACTACTACAAGTGTGTCAACGCCAAGGGCGAGGATTTCCGTCCATGCACTCAG
TTCTTCCATGCTTTCCGCTCCCTGTGCCCCAAGGCCTGGACTGACAGATGGGATACCCAA
CGCGAGGCTGGAAACTTCCCTGCTCGTCTGGACTAG
>ASPFC_2.PE1125                        276 CDS /gene="CADAFUBG00002857" /gene_family="HOG000165128" /protein
ATGGGTGCCATTCCTGAAGCCGATCCCGATGAGCCCATGGAGACCAAGCCCTTCAAGTTC
GTGACAGGCTATGACGCTCGCTTCCCCCAGCAGAACCAGACCAAGCACTGCTGGCAGAAC
TACGTTGACTACCACAAGTGTATCAACGCCAAGGGCGAGGATTTCCGTCCATGCCGCCAG
TTCTACCACGCTTACCGCTCCCTGTGCCCCAAGGCCTGGACTGACAGATGGGATAACCAA
CGCGAGGCTGGAAACTTCCCTGCTCGTCTTGAGTAG
>ASPFL_7.PE483                         279 CDS /gene="CADAFLAG00007470" /gene_family="HOG000165128" /protein_
ATGGGTGCTATTCCTGAGGCCGATCCCGATGAGCCCATGGAGACCAAGCCCTTCAAGTTC
GTCACAGGCTATGATGCCCGCTTCCCCCAGATGAACCAGACCAAGCACTGCTGGCAAAAC
TATGTCGACTACCACAAGTGTGTCACCGCCAAGGGCGAGGATTTCCGTCCATGCCGTCAA
TTCTACCACGCTTTCCGCTCCCTGTGCCCCAAGGCGTGGACTGACCGCTGGGACACCCAA
CGCGAGGCTGGCAACTTCCCCGTTCGCCTGGACCACTAG
>BOVIN22_58.PE5                        261 CDS /gene="ENSBTAG00000026650" /gene_family="HOG000165128" /prote
ATGGCAGAATACATCAAGACCAAAATCAAGAACTACCAGTCTGCTCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACCAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACCGCTAAAGGGGGTGACGTCTCCGTGTGCGAATGGTACCGACGTGTG
TACAAGTCCCTCTGCTCCACATCCTGGGTGTCAACTTGGGACAATCGCCAGGCAGAAGGC
ACGTTTCCTGGGAAGATCTGA
>BOVIN5_103.PE6                        261 CDS /gene="ENSBTAG00000023487" /gene_family="HOG000165128" /prote
ATGGCAGAAGACATCAAGACCAAAATCAAGAACTACCAAACTGCTCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGCCCAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACCGCTAAAGGAGGTGACGTCTCCGTGTGTGAATGGTACCGGCGTGTG
TACAAGTCCCTCTGCCCCATATCCTGGGTGTCAACTTGGGACGATCCCCGGGCAGAAGGC
ACGTTTCCTGGGAAGATCTGA
>CALJA22_29.PE50                       261 CDS /gene="ENSCJAG00000010211" /gene_family="HOG000165128" /prot
ATGGCAGAAGAGATGAAGGCCAAACTCAAGAACTACAAGACTGCCCCTTTTGACAGCCGC
TTTCCCAACCAGAACCAGACCAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCCCTGAGTGCTAAAGGAGATGATGTGTCTGTGTGCCAATGGTACCGGCGTGTA
TACAAGTCCCTCTGCCCCATATCCTGGGTCACAGACTGGGACGAGCAGCGGGCTGATGGC
ACTTTTCCCGGGAAGATCTGA
>CALJA22_29.PE51                       309 CDS /gene="ENSCJAG00000010211" /gene_family="HOG000165128" /prot
CACCCTCATCCTCAGATACCGGCTCGAGATATCGCCGGATTCAGCACCATGGCAGAAGAG
ATGAAGGCCAAACTCAAGAACTACAAGACTGCCCCTTTTGACAGCCGCTTTCCCAACCAG
AACCAGACCAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGTGAGAAGGCCCTG
AGTGCTAAAGGAGATGATGTGTCTGTGTGCCAATGGTACCGGCGTGTATACAAGTCCCTC
TGCCCCATATCCTGGGTCACAGACTGGGACGAGCAGCGGGCTGATGGCACTTTTCCCGGG
AAGATCTGA
>CALJA3_198.PE11                       249 CDS /gene="ENSCJAG00000022064" /gene_family="HOG000165128" /prot
ATGGCAGAAGAAATGAAGATCAAAATTAAGAACTACAGAACTGTCCCTTTTGACAACCAC
TTCACCAACCAGAACCAGAACACGAACTGCGGGAACAACTACCTAGACTTCTACCACTCC
ACGAAGGCAATGACTGCTAAAGAGGATGATGTATCTGTGTGCAAATGGTACTGGCATGTG
TACAAGTCCCTCTGCCCCATATCCTCGGTCTTGGCCCGGGACAAAGGCATGTTTCCTGGG
AAGATCTGA
>CANDC_6.PE389                         252 CDS /evidence="4: Predicted" /gene_family="HOG000165128" /gene_id=
ATGCCAGTCGATCCAGCTACTTTTAAATTTGATACTCCACAATTCGACCCAAGATTCCCA
AACCAAAACCAATCCAAACACTGTGCTCAAGCCTACGTTGATTACCATAAATGTGTCAAT
GTGAAAGGTGAAGAATTTGAACCATGCAAAATCTTTTTCAAAACTTTCACTTCATTATGT
CCATTAGATTGGGTTGAAAAATGGGACGACCAAAGAGCTGCTGGTAAATTCCCAGTCAAC
ATGGACGCTTAG
>CANFA1_122.PE41                       261 CDS /gene="ENSCAFG00000006913" /gene_family="HOG000165128" /prot
ATGGCAGAAGACATCAAGTCCAAAATCAAGAACTACCAGACTGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACTAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACTGCTAAAGGGGGTGATGTCTCCGTGTGCGAATGGTACCGGCGAGTG
TACAAGTCCCTCTGCCCCATATCCTGGGTGTCGGCCTGGGATGACCGCCGGGCAGAAGGC
ACATTTCCTGGGAAGATCTGA
>CANFA1_122.PE42                       321 CDS /gene="ENSCAFG00000006913" /gene_family="HOG000165128" /prot
ATGGCAGAAGACATCAAGTCCAAAATCAAGAACTACCAGACTGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACTAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACTGCTAAAGGGGGTGATGTCTCCGTGTGCGAATGGTACCGGCGAGTG
TACAAGTCCCTCTGCCCCATATCCTGGGTGTCGGCCTGGGATGACGGGCAGAAGGCACAT
TTCCTGGGAAGATCTGAACTGGCTCCACCCATCCTCCATCCTTCTCCCAGGGTGGTGAAG
GGGGACCTGGGTACATGGTGA
>DEHAN1_3.PE69                         249 CDS /evidence="4: Predicted" /gene_family="HOG000165128" /gene_id=
ATGGCTCTCGACCCAGAAAACTTTAAGTTTGAAACTCCACAATTTGATCCAAGATTCCCA
AATCAAAATCAAACCAAGCATTGTGCTCAAGCGTACGTTGATTACCACAAGTGTATCAAT
GCCAAAGGAGAAGAATTCGAGCCATGCCAAATTTTCTGGAAAACTTTCACCTCGTTATGT
CCAGTTGATTGGGTTGACAAATGGAATGACCAAAGGGAAGCAGGTAAATTTCCAATTAAC
TTAGATTAA
>FUGRU3_2.PE133                        261 CDS /gene="ENSTRUG00000016356" /gene_family="HOG000165128" /prote
ATGGCTGAAGACATTAAAGACAAACTTGAGAATTATCGCACTGCCCCCTTTGACGCCAGA
TTCCCCAACCAGAACCAGACCAGGAACTGCTGGTCCAATTATCTGGACTATCATCGCTGC
CAGAAGGCTCTGGATGCCAAAGGAGTAGACACAGCTCCGTGTGACTGGTACAAACGGGTC
TACAAATCACTCTGCCCCATGTCCTGGATTCAGAAATGGGATGAGCAGAGAGAAGAGGGG
ACCTTTCCAGGCAAAATCTAA
>HORSE10_7.PE28                        261 CDS /gene="ENSECAG00000012317" /gene_family="HOG000165128" /prote
ATGGCAGAAGACATTAAGAGCAAAATCAAGAACTACCAGACTGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACCAGGAACTGCTGGCAGAACTATCTGGACTTCCACCGCTGT
GAGAAGGCAATGACTGCTAAAGGGGGTGATGTCTCCGTGTGCGAATGGTACCGGCGTGTG
TACAAGTCCCTGTGCCCCCTATCCTGGGTGTCAGCCTGGGACGACCGCCGGGCGGAAGGC
ACATTTCCTGGGAAGATCTGA
>HS19.PE1638                           261 CDS /gene="ENSG00000126267" /gene_family="HOG000165128" /protein_id=
ATGGCGGAAGACATGGAGACCAAAATCAAGAACTACAAGACCGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACTAGAAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
CAGAAGGCAATGACCGCTAAAGGAGGCGATATCTCTGTGTGCGAATGGTACCAGCGTGTG
TACCAGTCCCTCTGCCCCACATCCTGGGTCACAGACTGGGATGAGCAACGGGCTGAAGGC
ACGTTTCCCGGGAAGATCTGA
>HS19.PE1639                           312 CDS /gene="ENSG00000126267" /gene_family="HOG000165128" /protein_id=
ATGCACCCTCATCCTCAGATACCGGGTAGAGATCTCGCCGGATTCAGCACCATGGCGGAA
GACATGGAGACCAAAATCAAGAACTACAAGACCGCCCCTTTTGACAGCCGCTTCCCCAAC
CAGAACCAGACTAGAAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGTCAGAAGGCA
ATGACCGCTAAAGGAGGCGATATCTCTGTGTGCGAATGGTACCAGCGTGTGTACCAGTCC
CTCTGCCCCACATCCTGGGTCACAGACTGGGATGAGCAACGGGCTGAAGGCACGTTTCCC
GGGAAGATCTGA
>KLLAC1_7.PE746                        249 CDS /evidence="4: Predicted" /gene_family="HOG000165128" /gene_id
ATGGCTGAAAATCAAGAATCTCCATTACACACCGTTGGTTTCGACGCTAGATTCCCAAAC
CAAAACCAAACAAAGCACTGCTGGCAATCGTACGTGGATTACCACAAGTGTATCAATGCT
AAGGGTGAAGACTTCGCTCCATGCAAGGTTTTCTGGAAGACCTACTCCTCTCTATGTCCA
GTTGACTGGGTTGAAAAGTGGGATGAACAAAGATCCCAGGGTATCTTTGCTGGTGACATT
AACCCATAA
>LACTH_5.PE387                         249 CDS /locus_tag="KLTH0E09350g" /gene_family="HOG000165128" /old_loc
ATGTCTGAGAAGCAAGAATCCCCACTACACACCGTCGGTTTCGACGCCAGATTCCCAAAC
CAAAACCAAACCATGCACTGCTGGCAATCGTACGTGGACTACTACAAGTGCATCAATGCC
AAGGGTGAAGACTTCGCCCCATGCAAAGTTTTCTTCAGAACCTTCTCTTCTCTGTGTCCT
TTGGACTGGGTTGAGAGATGGGACGAGCAAAGGGAAAAGGGCACTTTCCCCGGTGACATC
AAGCCATAA
>LOXAF4_17.PE41                        267 CDS /gene="ENSLAFG00000026729" /gene_family="HOG000165128" /prote
ATGTTGGGTACTGACATCCAGAAGCCCCCCAAGGGGAAATGGCACACACCGCCCTTCGAC
CCTCGCTTCCCCAACCAAAACCAGACCCGTAACTGCTACCAGAACTTCTTGGACTACCAC
CGCTGCTTGAAGAGGATGAACCGGCGCGGGAAGAGCACGCAGCCCTGCGAGTACTATTTC
CGCGTGTACCACTCGCTGTGCCCCATCAGTTGGGTACAGCGCTGGAATCAACAGATCAAA
GAGGGTACTTTTGCGGGCAAAATCTGA
>MACMU10_87.PE11                       330 CDS /gene="ENSMMUG00000013674" /gene_family="HOG000165128" /prot
ATGGTAGAAGACATCAAGACCAAAATAAAGAACTACAGGACTGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACCAGGAATGGCTGGCAGAAACACCTGGACTTCCACCCCTTC
AAGAAGGCAACGACTGCTACAGGGGGTAATGGTGATGTCTCTGTTTGTGAATGGTACCAG
CATGGGTACAAGTCTCTCTGCCCTATATCCTGGGTCTCAGCCTGGGATGACCATGGGCAG
AAGGTACATTTCTTGGGAAGATCTGAACTGGCTCCATCCCACCTCTGTCCTTCTCCCAGG
ATGGTAAAGAAGAACCTGGGTATATGGTAA
>MACMU19_43.PE55                       264 CDS /gene="ENSMMUG00000016765" /gene_family="HOG000165128" /prot
ATGGCGGAAGAAGACATTGAGACCAAAATCAAGAACTACAAGACTGCCCCTTTTGACAGC
CGCTTCCCCAACCAGAACCAGACCAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGC
TGCCAGAAGGCAATGACCACTAAAGGAGGCAATGTCTCTGTGTGCGAATGGTACCAGCGT
GTGTACCAGTCCCTCTGCCCCACATCCTGGGTCACAGACTGGGACGAGCAACGGGCTGAA
GGCACGTTTCCCGGGAAGATCTGA
>MICMUGS_960.PE5                       261 CDS /gene="ENSMICG00000009902" /gene_family="HOG000165128" /prot
ATGGCAGAAGACATCAAGACCAAAATCAAGAACTACAAGACTGCCCCTTTTGACAGCCGC
TTCCCCAACCAGAACCAGACCAGGAACTGCTGGCAGAACTACCTAGACTTCCACCGCTGC
GAGAAGGCGATGACTGCTAAAGGGGGTGATGTCTCTGTGTGTGAATGGTACCGGCGTGTG
TACAAGTCCCTCTGCCCCGTGTCCTGGGTCTCCACCTGGGACGACCGCCGGGCAGAAGGC
ACGTTTCCTGGGAAGATCTGA
>MONDO4_389.PE70                       261 CDS /gene="ENSMODG00000013962" /gene_family="HOG000165128" /prot
ATGTCTGATGATATCAAGGCCAAGATCCGAAACTACCGCACTGCGCCCTTTGACAGCCGC
TTCCCCAATCAGAACCAGACCCGCAACTGCTGGCAGAACTACCTGGACTTTCACCGTTGT
GAGAAGGCCATGACTGAGAGAGGCGGTGATGTGTCTGTCTGCCAGTGGTACAAACGTGTC
TACAAGTCCCTCTGTCCCTTGTCCTGGGTCAGTAATTGGGATGATCGCAGAGCAGAAGAA
ACCTTCCCTGGAAAGATCTGA
>MOUSE7.PE135                          267 CDS /gene="ENSMUSG00000051811" /gene_family="HOG000165128" /protein
ATGTTGGGTGTTCAAGCCCAGAAGCCCCCTCCGGGCCAATGGACAACGCCGCCCTTTGAT
CCGCGCTTCCCTAACCAGAACCAGACGCGTAACTGCTACCAGAATTTTCTGGACTACCAC
CGGTGTGTGAAGACCATGAATCGCCGCGGAAAGAGCACACAACCCTGCGAGTACTATTTC
CGTGTATTCCATTCACTGTGTCCCATCAGCTGGGTGCAGCGCTGGAATGAGCAGATCAAG
CAGGGAACTTTCCCGGGCAAAATATGA
>MOUSE7.PE1165                         261 CDS /gene="ENSMUSG00000036751" /gene_family="HOG000165128" /protei
ATGGCTGAAGACATCAAGACTAAAATCAAGAACTACAAAACTGCCCCCTTTGACAGCCGC
TTCCCCAACCAGAACCAGACTAAGAACTGTTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACGGCCAAGGGGGGTGATGTCTCCGTGTGTGAGTGGTACCGGCGTGTG
TACAAGTCCCTCTGTCCCGTGTCATGGGTCTCAGCCTGGGATGACCGCATAGCTGAAGGC
ACATTTCCTGGGAAGATCTGA
>MYOLUGS_2099.PE3                      261 CDS /gene="ENSMLUG00000011365" /gene_family="HOG000165128" /pro
ATGGCAGAAGACATCAAGACCAAAATCAAGAACTACCGGACTGCTCCTTTCGACAGCCGC
TTCCCCAACCAGAACCAGACCAGGAACTGTTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACTGCTAAAGGGGGTGATGTCTCTGTGTGTGAATGGTACCGGCGTGTG
TACGAGTCCCTGTGTCCCATATCCTGGGTTTCAGCCTGGGATGACCGCCGGGTAGAAGGC
ACGTTTCCTGGGAAGATCTGA
>NEFIS1_622.PE1568                     276 CDS /gene="CADNFIAG00007897" /gene_family="HOG000165128" /prote
ATGGGTGCCATTCCTGAAGCCGATCCCGATGAGCCCATGGAGACCAAGCCCTTCAAGTTC
GTGACAGGCTATGACGCTCGCTTCCCCCAGCAGAACCAGACCAAGCACTGCTGGCAGAAC
TACGTTGACTACTACAAGTGTGTCAACGCCAAGGGCGAGGATTTCCGCCCATGCCGTCAG
TTCTACCACGCTTTCCGCTCCCTGTGCCCCAAGGCCTGGACTGACAGATGGGATAACCAA
CGCGAGGCTGGAAACTTCCCTGCTCGTCTGGAGTAG
>ORYLA11_15.PE19                       255 CDS /gene="ENSORLG00000006070" /gene_family="HOG000165128" /prot
ATGTTTTATGAGGAGAAGCTGAAGAACTACAGGACGGCTCCGTTTGACGCCCGCTTTCCC
AACACCAACCAAACCCGCAACTGCTACCAGAACTATTTGGACTACCATCGATGTAACAAA
GCTCTGTCGGCCAAAAACCAGGACCCGGCCCCCTGCCAGTGGTACCACAGAGTTTACAAG
AGCCTCTGTCCCATCAGCTGGGTTCAGAAATGGGATGGTCAGCTGGAGGCTGGAACATTT
CCTGGAAAGATCTGA
>ORYLA19_9.PE49                        261 CDS /gene="ENSORLG00000008136" /gene_family="HOG000165128" /prote
ATGGCTGAAGACATCCAAGACAAGCTGGAGAAATACCGCACTGCTCCCTTTGACGCTAGA
TTTCCCAACCAGAACCAGACCAGGAACTGCTGGTCCAACTACGTGGATTACTACCGCTGT
CAGAAAGCCCTGGACGCCAAAGGAATAGACACAGCCCCCTGTGAATGGTACAAGAGGGTC
TACAAATCTCTGTGCCCCATGTCCTGGGTCCAGAAATGGGACGACCAGCGAGAGGAGGGG
ACATTTCCAGGAAAAATCTAA
>PANTR22_41.PE12                       327 CDS /gene="ENSPTRG00000014410" /gene_family="HOG000165128" /prot
ATGGCAAAAGACATCAAGACCAAAATCAAGAACTACAGGACTGCCCCTTTTGAAAGGTGC
TTCCCCAACCAGAACCAGACCAGAAATGGCTGGCAGAAATACCTGGACCTCCACCACTTC
AAGAAGGCAACGACTGCTAAAGGAGGGGGTGATGTCTCTGTTTGTGAATGGTACCAGCAT
GTGTACAAGTCTCTCTGCCCTATACCCTGGGCCTCAGCCTGGGATGACCATGGGCAGAAG
GCACATTTTTTGGGAAGATCTGAACTGGCTCCACCCCACCTCTGTCCTTCTCCCAGGATG
GTAAAGAAGAACCTGGGTATATGGTGA
>PENCW_9.PE744                         279 CDS /evidence="4: Predicted" /gene_family="HOG000165128" /gene_id=
ATGGGTGCTATTCCGGAAGCCGACCCCGATGAGGTCCTCGAGACCAAGCCCTTCAAGTTC
GTGACTGGCTACGATGCCCGTTTCCCCCAGCAGAACCAGACCAAGCACTGCTGGCAAAAC
TATGTCGACTACTACAAGTGCACCACTGCCAAGGGCGAGGACTTCCGCCCCTGCAAGCAG
TTCTACCACGCCTTCCGCTCTCTTTGCCCCAAGGCCTGGACCGATCGTTGGGACGGTCAG
CGCGAGGCTGGCAACTTCCCTGTCCACCTTGACAAGTAG
>PICPG_4.PE439                         243 CDS /locus_tag="PAS_chr4_0422" /gene_family="HOG000165128" /produc
ATGTCTGAAAACATCGAGTTAAAAACCGTGGGCTTTGATGCTCGTTTCCCTCAACAGAAC
CAAACCAAGCACTGTTACCAATCATACCTTGACTACCACAAGTGCATTACAGTTAAGGGT
GAAGACTTTGCGCCATGTAAGGTCTTCTGGAAGACATACAACTCTCTGTGCCCAAGTGCA
TGGGTTGAAGAATGGGATGAGCAAAGAGAAAAAGGAATTTTCCCAGGAAACTTGAAAGTT
TAA
>PIG6_43.PE12                          267 CDS /gene="ENSSSCG00000003296" /gene_family="HOG000165128" /protein
ATGTTGGGTATTGATTTCCAGAAGTCCTCCAAAGGGAAATGGCCAACGCCACCATTCGAC
CCGCGCTTCCCCAACCAGAATCAGACCCGTAACTGCTACCAGAACTTCCTGGACTACCAT
CGCTGCGTCAAGAGCATGAACCTCCGCGGGAAGAGTACACAGCCCTGCGAGTATTATTTC
CGCGTGTTCCACTCGCTGTGCCCCATAAGCTGGGTGCAGCGCTGGAACCAGCAGATCATG
GACGGGACTTTCGCTGGCAAAATCTGA
>PISTI1_2.PE298                        252 CDS /codon_start=1 /gene_family="HOG000165128" /evidence="4: Pred
ATGGCCATCGACAGCGAAAACTTCAAGTTCGACACCGTCCAATTCGACCCAAGATTCCCT
TACCAAAACCAGACCAAGCATTGTGCCCAATCGTACGTCGATTACCACAAGTGCGTTTCC
GTCAAGGGTGAAGAATTCGAGCCATGCAAGATTTTCTTCAAGACCTTCACCTCATTGTGT
CCTGTCGACTGGGTGGAAAGATGGGATGACCAAAGAGCTGCCGGCAAGTTCCCTGTCAAC
ATGGACGTCTAA
>PONPY22_37.PE10                       327 CDS /gene="ENSPPYG00000011853" /gene_family="HOG000165128" /prot
ATGGCAGAAGACATCAAGACCAAAATCAAGAACTATAGGACTGCCCCTTTTGACAGCCGG
TTCCCCAACCAGAACCAGACCAGGAATGGCTGGCAGAAATACCTGGACCTCCACCACTTC
AAGAAGGCAACAACTGCTAAAGGGGCGGGTGATGTCTCTGTTTGTGAATGGTACCAGCGT
GTGTACAAGTCTCCCTGCCCTATACCCTGGGCCTCAGCCTGGGATGACCATGGGCAGAAG
GCACATTTCTTGGGAAGATCTGAACTGGCTCCACCCCACCTCTGTCCTTCTCCCAGGATG
GTAAAGAAGAACCTGGGTATATGGTAA
>PROCAGS_3128.PE2                      267 CDS /gene="ENSPCAG00000012576" /gene_family="HOG000165128" /pro
ATGATGGGTATTGATATCCAGAAGCCCCCCAAGGGGAAATGGCACACACCGCCCTTCGAC
CCTCGCTTCCCCAACCAGAACCAGACCCGTAACTGCTACCAGAACTTCTTGGACTACCAC
CGCTGCTTGAAGATAATGAACCGGCGCGGGAAGAGCACGCAGCCCTGCGAGTACTATTTC
CGCGTGTACCACTCCCTGTGCCCCATCAGTTGGGTACAGCGCTGGAATCAACAAATCAAA
GAGGGCACTTTCGCGGGCAAAATCTGA
>PTEVAGS_513.PE4                       312 CDS /gene="ENSPVAG00000012821" /gene_family="HOG000165128" /prot
ATCTACTCTCACTCCCAGATAGCGGGTCAAGATCTCTCCCGAGTCAGCAACATGGCAGAA
GACATCAAGACCAAAATCAAGAACTACCAGACTGCCCCTTTTGACAGCCGCTTCCCCAAC
CAGAACCAGACCAGGAACTGTTGGCAGAACTACCTGGACTTCCACCGCTGTGAGAAGGCA
ATGACCGCTAAAGGGGGTGATGTCTCCGTATGTGAATGGTACCGGCGTGTGTACAAGTCC
CTCTGCCCCATATCCTGGGTGTCAACCTGGGATGACCGCCGGGCAGAAGGCACATTTCCT
GGGAAGATCTGA
>RAT1.PE759                            267 CDS /gene="ENSRNOG00000038616" /gene_family="HOG000165128" /protein_i
ATGTTGGGTGTTCAAGCCCAGATGCCTGCTCCAGGCCAATGGACAACGCCGCCCTTCGAC
CCGCGCTTCCCTAACCAAAACCAGACGCGTAACTGCTACCAGAATTTTCTGGACTACCAC
CGGTGTGTGAAGACCATGGATCGCCGCGGAAAGAACACACAGGCCTGCGACTACTATTTC
CGTGTATTCCATTCACTGTGTCCCGTCAGCTGGGTGCAGCGCTGGAATGAGCAGATCAAG
CAGGGAACTTTCCCAGGCAAAATCTGA
>RAT1.PE1332                           261 CDS /gene="ENSRNOG00000024309" /gene_family="HOG000165128" /protein_
ATGGCCGAAGACATCAAGACTAAAATCAAGAACTACAAAACCGCCCCCTTTGACAGCCGC
TTCCCAAACCAGAACCAGACTAAGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACGGCAAAGGGCGGTGACGTCTCCGTGTGCGAGTGGTACCGGCGAGTG
TACAAGTCCCTCTGCCCCGTCTCATGGGTCTCAGCCTGGGATGACCGCATAGCAGAAGGC
ACATTTCCTGGGAAGATCTGA
>RAT2.PE1689                           261 CDS /gene="ENSRNOG00000034161" /gene_family="HOG000165128" /protein_
ATGGCCGAAGACATCAAGACTAAAATCAAGAACTACAAAACCGCCCCCTTTGACAGCCGC
TTCCCAAACCAGAACCAGACTAAGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGT
GAGAAGGCAATGACGGCAAAGGGCGGTGACGTCTCCGTGTGTGAGTGGTACCGGCGTGTG
TACAAGTCCCTCTGCCCCGTCTCATGGGTCTCAGCCTGGGATGACCGCATAGCAGAAGGC
ACATTTCCTGGGAAGATCTGA
>SCHPO_3.PE651                         261 CDS /gene="SPCC1442.08c" /gene_family="HOG000165128" /protein_id="
ATGTCTGAACAAGAAGATCAAGAAGCACCTAAGCAGTTTACTTTTGGTACAGTTGGGTTT
GATGCAAGATTCCCAAACACTAATCAAACAAAACATTGCTTCCAAAGTTACATTGATTAT
TTCCGCTGTATTAAGGCTAAGGGTGAAGACTTTGTCCCCTGTAAACAGTTTTGGCACGCT
TATCAATCTTTGTGCCCAATGGAATGGGTAGAACGCTGGGACGAACAAAGGGAAAACGGA
ACCTTCCCGGCCCCTATCTAG
>SORARGS_2678.PE3                      261 CDS /gene="ENSSARG00000010771" /gene_family="HOG000165128" /pro
ATGGCAGAAGATATCAAGAGGAAGATCAAGAACTATCAGACTGCCCCTTTTGATAGCCGA
TTCCCCAACCAGAACCAAACCCGGAACTGCTGGCAGAACTATCTGGACTTCCACCGCTGC
GAGAAGGCAATGAGTGCCAAAGGGGGTGACGTCTCCGTGTGCGAATGGTACCGGCGTGTG
TACAAGTCCCTCTGCCCCTTGTCCTGGGTGTCGACTTGGGATGACCGCCGGGCAGAAGGC
ACGTTTCCTGGAAAGATCTGA
>TURTRGS_1168.PE3                      309 CDS /gene="ENSTTRG00000002241" /gene_family="HOG000165128" /pro
GTCCACCCTCCCTCCAAAGCGGGTGGAGATCGCTTCCGAGTCAGCACTATGGCAGAGGAC
ATCAAGACCAAAATCAAGAACTACCAGACTGCTCCTTTTGACAGCCGCTTCCCCAACCAG
AACCAGACGAGGAACTGCTGGCAGAACTACCTGGACTTCCACCGCTGTGAGAAGGCAATG
ACTGCTAAAGGGGGTGACGTCTCCGTGTGTGAATGGTACCGGCGTGTGTACAAGTCCCTC
TGCCCCATATCCTGGGTGTCAGCCTGGGACGACCGCCGGGCAGAAGGCACGTTTCCTGGG
AAGATCTGA
>YALIP1_6.PE683                        255 CDS /evidence="4: Predicted" /gene_family="HOG000165128" /gene_id
ATGTCTGATACCGAAGAGCAGAAGGTTGTCTTTAAGACTGTCGGATTCGACCCCCGATTC
CCCAACCAGAACCAGACCAAGCACTGCTGGCAAAACTACGTCGACTACTTCAAGTGCATC
AACGCCAAGGGTGAGGAGTTTGAGCCTTGCAAGGTCTTCTGGCGATCATACAACTCTCTG
TGCCCCCAGGACTGGATTGAGAAGTGGGACGGCCAGCGAGAGAAGGGCAACTTTGCCGGT
GATCTTAACCCTTAA
>YEASTXII.PE110                        252 CDS /gene="YLR038C" /gene_family="HOG000165128" /protein_id="YLR0
ATGGCTGATCAAGAAAACTCTCCACTACATACAGTTGGTTTCGATGCTAGATTTCCCCAA
CAAAACCAAACAAAGCATTGTTGGCAATCTTATGTGGATTATCACAAGTGTGTTAATATG
AAGGGCGAAGATTTTGCTCCGTGCAAGGTCTTTTGGAAGACCTATAACGCCTTATGTCCC
CTAGACTGGATCGAAAAATGGGATGATCAAAGAGAAAAAGGTATTTTCGCAGGTGATATC
AACTCAGACTAA
