>AILMEGL192908_1_1.PE10                384 CDS /gene="ENSAMEG00000010057" /gene_family="HOG000004830" /pro
ATGAACTTCTCCGGCAAGTACCAGCTGCAGAGCCAGGAAAACTTTGAGGCCTTCATGAAG
GCAGTCGGTCTGCCTGACGAACTCATCCAGAAGGGGAAGGACATCAAGGGGGTGTCGGAA
ATTGTGCAGAATGGGAAGCACTTCAAACTCACCATCACCACTGGGTCCAAAGTGATTCAA
AATGAGTTCACCTTGGGGGAAGAGTGTGAGCTGGAGACCATGACTGGGGAGAAGGTCAAG
GCTGTGGTCCAGATGGAAGGTGACAATAAACTGGTGACAACTTTCAAAGGCATCAAGTCT
GTGACCGAACTCAATGGCGATGTGATCACCAATACCATGACATTGGGTGACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAA
>BOVIN11_52.PE8                        384 CDS /gene="ENSBTAG00000018054" /gene_family="HOG000004830" /prote
ATGAACTTCTCCGGCAAGTACCAAGTCCAGACCCAGGAGAACTATGAGGCCTTCATGAAG
GCAGTTGGGATGCCCGATGACATCATCCAGAAGGGGAAGGATATCAAGGGGGTGTCGGAA
ATCGTGCAGAATGGGAAGCACTTCAAGTTCATCATCACCGCTGGCTCCAAAGTGATCCAG
AATGAGTTCACCTTGGGGGAGGAGTGTGAGATGGAGTTCATGACTGGGGAGAAGATCAAG
GCAGTGGTTCAGCAGGAAGGTGATAATAAACTTGTGACAACTTTCAAGGGCATCAAGTCT
GTGACTGAATTCAATGGTGACACTGTTACCAGTACCATGACGAAGGGCGACGTTGTCTTC
AAGAGAGTCAGCAAGAGAATTTAG
>BOVIN7_74.PE4                         390 CDS /gene="ENSBTAG00000010632" /gene_family="HOG000004830" /protei
AGCATGGCCTTCACTGGCAAGTACGAGACTGAGAGTGAGAAGAACTATGATGAGTTCATG
AAGCGCCTGGGGCTCTCCAGCGACAGGATTGAAAAGGGCCGCAACTTCAAGGTCATCTCG
GAGATACAGCAGGATGGGCAGAACTTCACCTGGTCCCAGCACTACCCTGGGGGCCACTCC
ATTTCCAACAATTTCACCATTGGCAAGGAGACTGAGATGGAGACCGTGGGAAACAAGAAG
TTCAAGGTCACTGTGAAGATGGAGGGTGGGAAAGTGGTCGTGGACTCTGCCAACTACCAC
CACACCGTAGAGATTGTGGATGGCAAGCTGGTGGAGGTCTCCACCTTTGGAGGCGTGATC
TACGAGCGCGTGAGCAAGAAGGTGGCCTGA
>CALJA14_21.PE5                        384 CDS /gene="ENSCJAG00000019353" /gene_family="HOG000004830" /prote
ATGAACTTCACCGGCAAGTACCAACTGCAAAGCCAGGAAAACTTTGAACCCTTCATGAAG
GCAATCGGTCTGCCGGACGAGCTCATCCAGAAGGGGAAGGATATCAAGGGGGTGACGGAA
ATCGTGCAGAACGGGAAGCACTTCAAGCTCACCATCACCGCTGGGTCCAAAGTGATCAAC
AACGAGTTCACCCTGGGAGAGGAATGTGAGCTGGAGACAATGACAGGGGAGAAGGTCAAG
GCAGTGGTTCAGATGGAAGGTGGCAATAAACTGGTGACAACTTTCAAAAACATCAAGTCT
GTGACCGAACTCAACGGCGACATAATCACCAGTACCTTGACATTGGGCGACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAA
>CALJA2_23.PE1                         537 CDS /gene="ENSCJAG00000019114" /gene_family="HOG000004830" /protei
AGGAAGACAGTGCTGATGATGGTGGTGGTGGTGGCGCTGCAGGTGCTGACCCAGGTTCTG
AAAGCTATGTTGTCTGCGTGCACATGGGTGAGCCGGAAAGGAGACCCGCAGACAATGAGA
CAGACACAGAAAGGAAAGCCTCCTAACAGCATGGCTTTCAATGGCAAGTTCGAGATAGAG
AGTGAGAAGAATTATGATGAGTTCATGAAGCTGCTGGGAATCTCCAGCAATGCAATCGAA
AAGGCCCGCAACTTCAAGATCGTCACGGAGGTGCAGCAGGATGGGCAGGACTTCACTTGG
TCCCAGCACTACGCCGGGGGCCACACCATGACCAACAAGTTCACTGTTGGCAAGGAAAGT
GAGATACAGACAATGGGGGGCAAGAAGTTCAAGGCCACTGTGCAGATGGAGGGTGGGAAA
CTGGTGGTGAATTTCCCCAACTATCACCAGACCTCAGAGATTGTGGGTGACAAGCTGGTG
GAGTTCTCCACCATCGGAAGCGTGACCTATGAGCGTGTGAGCAAGAGGCTGGCCTAA
>CANFA17_42.PE11                       384 CDS /gene="ENSCAFG00000007413" /gene_family="HOG000004830" /prot
ATGAACTTCTCCGGCAAGTACCAACTGCAGAGCCAAGAAAACTTTGAGGCCTTCATGAAG
GCAGTCGGTCTGCCTGATGAACTCATCCAGAAGGGGAAGGACCTCAAGGGGGTGTCAGAA
ATCGTGCAGAATGGGAAGCACTTCAAGCTCATCATCACCACTGGTTCCAAAGTGATCCAG
AATGAGTTCACCTTGGGGGAAGAGTGTGAGCTGGAGACCATGACTGGAGAGAAGGTCAAG
GCAGTGGTTCAGATGGAAGGTGACAATAAGCTGGTGACAACTTTCAAAGGCATCAAGTCT
GTGACCGAACTCAATGGCGATGTGATCACCAATACCATGACATTGGGTGACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAG
>CANFA4_54.PE7                         396 CDS /gene="ENSCAFG00000017275" /gene_family="HOG000004830" /protei
ATGGCCTTCAACGGCAAGTACGAGTTCGAGAGTGACAAGAATTATGACGAGTTCATGAAG
CGCCTCGGTGAGCCAGGGCTCCCCAGCGACGCTATCGAAAGGGGCCGAAACTTCAAGATT
GTCACGGAGGTGCAGCAGGATGGACAGAACTTCACCTGGTCCCAGCACTACCCGGGGGGC
CACTCCATGACCAACAGGTTCACCATCGGCACGGAGTGTGACATGGAGACCATGGGGGGC
AAGAAGTTCAAGGCCACCGTGCACATGGACGGGGGGAAGATCGTGGTGGACTTCCCCAAC
TATCACCAGACCTCGGAGGTTGTGGGTGACAAACTGGTGGAGATCTCCACCATCGGAAAC
GTGACCTATGAGCGTGTGAGCAAGAGGCTGGCCTGA
>CAVPO17_8.PE5                         399 CDS /gene="ENSCPOG00000025902" /gene_family="HOG000004830" /protei
CCCTCCTGCAGCATGGCCTTCACCGGAAAGTTCGAGGCAGAGAGCGAGAAGAACTTTGAG
GCTTTCATGAAGCGCATTGGTCTTCCCAGCGACGTGATCGAAAAGGGTCACAACTCCAAA
GTCATCACAGAGGTGCAGCAGAACGGGCAGGAATTCACCTGGTCGCAGTCCCACGCCTTG
GGCCACATCCTCACCAACAAGTTCACCATCGGCAAAGAGAGTGACTTGGTGTCCTTGGGG
GGCAAGAAGTTCAAGGCCACCGTGAAAATGGAGGGCGGGAAGATAGTGTTCGAGTTTCCC
AACTATCGCCAGACCTCGGAGATCGTGGGTGACAAGCTGGTGGAGATCTCCACCGTTGGG
GACGTGACCTACGAGCGCGTGAGCAAGAGGCTGGCCTGA
>CAVPO37_4.PE8                         384 CDS /gene="ENSCPOG00000005632" /gene_family="HOG000004830" /protei
ATGAACTTCACCGGCAAGTACCAACTGCAGAGCCAGGAAAACTTCGAGGCCTTTGTGAAG
GCAGTGGGGTTGCCTGATGACGTCATCCAGAAGGGGAAGGATGTCAAGGGGGTGATAACA
GAAATCGTGCAGAATGGCAAGCACTTCAAGTTCATCATCAGCACAGGGCCAAAAGTGACC
AAGAATGAATTCACCTTGGGACAGGAGTGTGAGATAGAGACCATGACTGGGGATAAGGCC
AAGGCCGTGGTTACCATGGAAGGTGACAAGCTGGTGACAACTTTCAAAAATATCAGATCT
GTGACTGAACTCAATGGGGACATCCTGACCAGCACCATGACCCTGGGTGACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAG
>CAVPO37_4.PE9                         384 CDS /gene="ENSCPOG00000007173" /gene_family="HOG000004830" /protei
ATGAGCTTCACCGGCAAGTACCAACTGCAGAGCCAGGAAAACTTCGAGGCCTTCATGAAG
GCAGTGGGGATGGCTGAGGACCTCATCCAGAAGGGGAAGGACCTCAAGGGGACATCAGAA
ATCGTGCAGAACGGGAAGCACTTCAAGCTCAAAAGCAGCATGGGGACAAATGTGATCATG
AATGAGTTCACCGTGGGGGAGGAGTGTGAGATGGAGACCATGACTGGGGAGAAGGTCAAG
GCAGTGGTTACCATGGAAGGAGCCAACAAGCTGGTGACAACTTTGAAAAACATCAAGACC
GTGATTGAAATCAATGGGGACACCCTGACCAGCATCATGACACTGGGTGACACTGTCTTC
AAGAGAATCAGTAAGAGAATTTAG
>CAVPO37_5.PE1                         384 CDS /gene="ENSCPOG00000009188" /gene_family="HOG000004830" /protei
ATGAGTTTCTCCGGCAAATACCAACTGCAGAGCCAGGAAAACTTCGAGGCCTTCATGAAG
GCAGTGGGGGTGCCTGACGACCTCATCCAGAAGGGGAAGGACGCCAAGGGGTTGACGGAA
ATTGTGCAGAACGGCAAGCACTTCAAGATCACCATCACTACAGGGTCCAAAGTGATGCAC
AATGAGTTCACCGTGGGCGAGGAGACTGAGATGGACAGCATTACCGGGGAGAAGATCAAG
TCATTGGTTAACTTGGAAGGTGACAACAAGCTGGTGACAATGTACAAAAACATCAAGTCT
GTGACTGAAATCAATGGGGACATCCTGACCAGCACTCTGACACTGGGTGACATTGTCTTC
AAGAGAGTCAGCAAGAGAGTTTAG
>CHICK13.PE131                         390 CDS /gene="ENSGALG00000001445" /gene_family="HOG000004830" /protei
AACATGGCATTCACAGGCAAATATGAATTCGAAAGCGATGAGAACTATGATGACTTTGTG
AAGAAGATCGGTCTCCCTGCTGACAAGATCGAAATGGGAAGGAATTGCAAAATAGTCACC
GAGGTGGTGCAGAATGGAAATGATTTCACCTGGACTCAGCATTTCCCAGGAGGACGCACC
ACGACTAATTCATTCACTATAGACAAGGAAGCAGACATGGAGACAATGGGTGGTAGAAAG
TTCAAGGCAACAGTCAAAATGGAAGGTGGGAAAATAGTAGCTGATTTTCCCAACTATCAT
CATACTGCAGAGATTTCTGGAGGAAAGCTTGTAGAGATCTCTACTTCTTCTGGAGTAGTC
TACAAGAGAACCAGCAAAAAGATTGCTTAA
>CHICK4.PE1454                         384 CDS /gene="ENSGALG00000015937" /gene_family="HOG000004830" /protei
ATGAGCTTCACTGGAAAGTACGAGCTCCAGTCCCATGAAAACTTTGAGCCTTTCATGAAA
GCCCTCGGGCTTCCTGATGATCAGATCCAGAAGGGTAAGGACATCAAGAGTATCTCAGAA
ATTGTGCAGAATGGGAATAAGTTCAAGATTACTGTGACTACTGGCTCCAAAGTAATGACC
AATGAGTTCACCATTGGGGAAGAGTGTGAGATGGAGCTGCTGACAGGAGAGAAGGCCAAG
TGTATTGTTAACATGGAAGGTAACAACAAACTGGTTGCTAACTTGAAGGGGCTGAAATCC
GTGACCGAACTCAACGGAGACACCATCACCCATACAATGACGAAGGGAGACCTCACCTAC
AAGAGAATTAGCAAGAGAATCTAG
>DANRE8_1.PE32                         390 CDS /gene="ENSDARG00000059227" /gene_family="HOG000004830" /protei
ATGTCGTTCACTGGGAAATATCAGCTGGAGAGTCAAGAGGGCTTCGTGGAGTTCATGAAG
GCCGTCGGTCTTCCTGACGACATGATTGAGAAAGGCAAAGACATCAAGAGTGTGTCTGAG
ATCGAGGAGAACGGAAACCAGTTTAAAGTGACCGTCACGACCGGATCAAAAGTGCTGACC
AACAGCTTCACCATCGGGCAGGAGGCCGACATTGAGACGCTGACCGGAGAGAAAGTCAAG
ACTGTGGTGCACAAAGACGGACAGAAGCTGAAGGCAGCGCTGGGCAACATCACTTTAACC
TGGGAGCTGCTGGATGAAAACACACTGCTCATCACTCTGAGCACCGCTGACAACATCGCC
TACAAGCGCTTCAGCAAACGTGTGGTGTAA
>DASNOGS_2082.PE2                      315 CDS /gene="ENSDNOG00000004133" /gene_family="HOG000004830" /pro
CTGCCCGACGACCTCATCGAGAAGGGCAAGGACATCAAGGGCATCTCGGAGGTCGTGCAG
GAAGGGAAGCACTTCAAGATCACCATCACCACTGGCCCCAGAGTGATCCACAACGAGTTC
ACCCTGGGGGAGGAGTGCGAGCTGGAGACCATAACCGGGGAGAAGGTCAAGGCGGTGGTT
CGGATGGAAGGTGACAATAAGCTGGTGACAACTTTCAAAGGCGTCTCCTCTGTGATGGAA
TTCAACGGTGACACCATCAGCAGCACTCTGACGCTGGGGGACATTGTCTTCAAGAGAATC
AGCAAGAAAATTTAG
>ECHTEGS_2486.PE2                      384 CDS /gene="ENSETEG00000011358" /gene_family="HOG000004830" /pro
ATGAACTTCTCTGGCAAGTACCAAGTGCAGACCCAGGAGAACTTTGAGGCCTTCATGAAG
GCTGCTGGTCTGCCGGACGACCTCATCCAGAAGGGCAAGGACATCAAGGGGGTGTCGGAA
ATCGTGCAGAATGGGAAGCACTTCAAGCTCACCATCACCACCGGCTCCAAAGTCATCCAG
AACGAGTTCACCCTGGGGGAGGAGTGTGAGCTGGAGACCTTAACCGGGGAGAGGGTCAAG
GCGGTGGTTCACTTGGAAGGTGACAATAAACTGGTGACAACGTTCAAAGGCATTAAGTCC
GTGGTGGAGTTCAACGGAGACACTGTAATCAGCACCATGACATTGGGTGACATTGTCTTC
AAGAGAATCAGCAAGAAAATTTAG
>ERIEU343000.PE1                       384 CDS /gene="ENSEEUG00000007295" /gene_family="HOG000004830" /prot
ATGAACTTCTCCGGGAAATACCAGCTGCAGAACCAGGAAAACTTTGAGCCTTTCATGAAG
GCTATTGGTCTGCCTGATGACCTCATCCAGAAAGGAAAGGACATCAAGGGGGTGTCGGAG
ATTGTGCAGAATGGCAATCACTTCAAGCTCACCATCACCACTGGCTCCAAAGTGATCCAC
AATGAGTTCACCTTGGGAGAGGAGTGTGAGCTGGAAACCATGACTGGGGAGAAGGTCAAG
GCAGTAGTCCAGAAGGAAGGTGAGAACAAACTGGTGACAACATTCAAAGGCATCAAGTCT
GTGACTGAACTCAATGGTGACACCATCACCAATACCATGACGCTGGGCAACATTGTCTTT
AAGAGAATCAGCAAGAGAATCTAG
>ERIEUGS_6879.PE1                      387 CDS /gene="ENSEEUG00000003076" /gene_family="HOG000004830" /pro
ATGGCCTTCAATGGCAAATATGAGATGGAGAGCGAGAAGAACTATGACGAGTTCATGAAG
TGCCTGGGGCTCCCCAGAGAGGCCATTGAAAAGGGCCGCAACTTCAAGATCGTCACGGAG
GTACAGCAGGACGGGCAGAACTTCACCTGGTCCCAGCACTACCCCTCTGGCCATTCCATG
GTCAACAAGTTCACCATTGGCAAGGAGTGCGACATGGAGACCGTGGGGGGCAAGAAGTTC
AAGGCCACTGTGAAGATGGAGGGAGGGAAGGTGGTGGTGGACTTCCCCAACTACCATCAG
ACCTCAGAGATTGTGGACGGCAAGCTGGTGGAGATTTCTACCATCGGGGGTGTGACCTAT
GAGCGCGTGAGCAAGAGACTGGCCTGA
>FUGRU11_3.PE46                        384 CDS /gene="ENSTRUG00000015614" /gene_family="HOG000004830" /prote
ATGTCTTTCTCTGGAAAATACCAGCAGGTTTCTCAGGAGAACTTCGAGCCTTTTATGAAG
GCCATCGGTCTCCCTGATGAAGTCATCCAACAGGTTAAAGAGCTCAAGAGCACCTCTGAG
ATTGAGCAGAATGGCAATGATTTCAAAATCACTATCACTACTGGACCGAAGGTAACGGTC
AACAAATTTACCATTGGGAAGGAGACAGAGATGGACACCATTACTGGAGAAAAGATCAAG
ACGGTGTTTCATCTTGATGGCAACAAGCTGAAGGTCTCCCTTAAAGGAATAGAGTCGGTG
ACAGAACTGGCGGATCCCAACACCATCGTGAGCACGATGACTCTGGGCGACGTCGTGTAC
AAGACAACGAGCAAGCGCATCGCA
>FUGRU126.PE50                         399 CDS /gene="ENSTRUG00000001091" /gene_family="HOG000004830" /protei
ACCACCATGACGTTCACTGGGAAATACGAGCTGGAGACTCAGGAAAATTACGAGGAGTTT
TTGGAAGCAATCGGTACACAAATAACAGGACTCCTCGGTGCCAAGACGGACCACAAAGTG
ATAACAGAGGTGGTCCAGAATGGGAACGACTTCACCTGGACACAAACCATTCCCAACTGG
ACGTGGTCGAACACGTTCAGCGTCGGTCAGGAATGTGAGCTGGTGACCATGAAGGGCATC
CAGTTCAAGGCTCCAGTTCGTATGGAAAACGGAAAGATCTCAGTCCAGTTTCCTCAGTAC
CATTTCACAGCAGAGGTCAACGGGGACAAGTTGATAATGAATTGCACAACTCCAGGAGAG
AAGGGAGTGACCTTCAAAAGAATAAGCAGGAGACTTTAA
>GORGO5_151.PE1                        534 CDS /gene="ENSGGOG00000004642" /gene_family="HOG000004830" /prote
ATGAAGACAGTGACGATGATGATGGTGGTGGAGATGCAGGTGCTGACTCAGGTTCTGAGA
GCTGTGTTGTCTGCGTGCACATGGGTGAGCCGGAAAGGAGACCTGCAGAGAATGAAACAG
ACACAGAAAGGAAAGCCTCCCAGCAGCATGGCTTTCACCGGCAAGTTCGAGATGGAGAGT
GAGAAGAATTATGATGAGTTCATGAAGCTCCTTGGGATCTCCAGCGATGTAATCGAAAAG
GCCCGCAACTTCAAGATCGTCACGGAGGTGCAGCAGGATGGGCAGGACTTCACTTGGTCC
CAGCACTACTCCGGGGGCCACACCATGACCAACAAGTTCACTGTTGGCAAGGAAAGCAAC
ATACAGACAATGGGGGGCAAGACGTTCAAGGCCACCGTGCAGATGGAGGGCGGGAAGCTG
GTGGTGAATTTCCCCAACTATCACCAGACCTCAGAGATCGTGGGTGACAAGCTGGTGGAG
GTCTCCACCATTGGAGGCGTGACCTATGAGCGCGTGAGCAAGAGACTGGCCTAA
>HORSE14_20.PE8                        396 CDS /gene="ENSECAG00000022261" /gene_family="HOG000004830" /prote
CCCGGCAGCATGGCCTTCACCGGCAAGTACGAGATCGAGAGTGAGAAGAACTACGATGAG
TTCATGAAGCACATTGGGATCCCCAGCGAGACTATCGAAAAGGGCCGAAACTTCAAGATC
ATCTCGGAGGTGCAGCAGGACGGGCAGAACTTCACCTGGTCCCAGCACTACCCCGGGGGC
CACTCCATCACCAACAAGTTCACCATCGGCAAGGAGTGTGACATGGAGACTGTGGGGGGC
AAGAAGTTCAAGGCCACCGTGCAGATGGAGGGTGGGAAGCTGACGGTGGACTCCCCCAAC
TTTCACTTTTCCTCGGAGATTGTGGGGGACAAGCTGGTGGAGACATCCACGGTCAGGGGC
GTGACCTACGAGCGCGTGAGCAAGAGGCTGGCCTGA
>HORSE15_18.PE15                       381 CDS /gene="ENSECAG00000015990" /gene_family="HOG000004830" /prot
ATGAACTTCTCCGGCAAGTACCAACTGCAGAGCCAGGAAAACTTTGAGCCCTTCATGAAG
GCAGTCGGTATGTCCGATGACCTCATCCAGAAGGGGAAGGACCTCAAGGAGACTTCGGAA
ATCGTGCACAATGGGAATCACTTCAAGATCACCATCACCACAGGGCCCAAAGTGGTCCAC
CACGAGTTCACTTTGGGGGAGGAGTTTGAGCTGGAGTCCTTTACTGGGGAGAAGGTCAAG
GCAATAACTCACATGGAAGGTGATAAACTGGTGTCAACCATCAAAGGCATCAAGTCTGTG
ACAGAACTCAAGGGTGATATAATCACCAATACCATGACACTGGGCGACATCGTCTTCAAG
AGAGTCAGCAAGAGAATTTAG
>HS2.PE2399                            384 CDS /gene="ENSG00000163586" /gene_family="HOG000004830" /protein_id="
ATGAGTTTCTCCGGCAAGTACCAACTGCAGAGCCAGGAAAACTTTGAAGCCTTCATGAAG
GCAATCGGTCTGCCGGAAGAGCTCATCCAGAAGGGGAAGGATATCAAGGGGGTGTCGGAA
ATCGTGCAGAATGGGAAGCACTTCAAGTTCACCATCACCGCTGGGTCCAAAGTGATCCAA
AACGAATTCACGGTGGGGGAGGAATGTGAGCTGGAGACAATGACAGGGGAGAAAGTCAAG
ACAGTGGTTCAGTTGGAAGGTGACAATAAACTGGTGACAACTTTCAAAAACATCAAGTCT
GTGACCGAACTCAACGGCGACATAATCACCAATACCATGACATTGGGTGACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAA
>HS2.PE2400                            375 CDS /gene="ENSG00000163586" /gene_family="HOG000004830" /protein_id="
ATGAGTTTCTCCGGCAAGTACCAACTGCAGAGCCAGGAAAACTTTGAAGCCTTCATGAAG
GCAATCGGTCTGCCGGAAGAGCTCATCCAGAAGGGGAAGGATATCAAGGGGGTGTCGGAA
ATCGTGCAGAATGGGAAGCACTTCAAGTTCACCATCACCGCTGGGTCCAAAGTGATCCAA
AACGAATTCACGGTGGGGGAGGAATGTGAGCTGGAGACAATGACAGGGGAGAAAGTCAAG
ACAGTGGTTCAGTTGGAAGGTGACAATAAACTGGTGACAACTTTCAAAAACATCAAGTCT
GTGACCGAACTCAACGGCGACATAATCACCAATGTAAGTTGGTGGTGCTCTGAGCGTGTG
GCTCCCAGTGCTTGA
>HS5.PE3531                            534 CDS /gene="ENSG00000170231" /gene_family="HOG000004830" /protein_id="
ATGAAGACAGTGACGATGATGATGGTGGTGGAGATGCAGGCGCTGACTCAGGTTCTGAGA
GCTGTGTTGTCTGCGTGCACATGGGTGAGCCGGAAAGGAGACCTGCAGAGAATGAAACAG
ACACATAAAGGAAAGCCTCCCAGCAGCATGGCTTTCACCGGCAAGTTCGAGATGGAGAGT
GAGAAGAATTATGATGAGTTCATGAAGCTCCTTGGGATCTCCAGCGATGTAATCGAAAAG
GCCCGCAACTTCAAGATCGTCACGGAGGTGCAGCAGGATGGGCAGGACTTCACTTGGTCC
CAGCACTACTCCGGGGGCCACACCATGACCAACAAGTTCACTGTTGGCAAGGAAAGCAAC
ATACAGACAATGGGGGGCAAGACGTTCAAGGCCACTGTGCAGATGGAGGGCGGGAAGCTG
GTGGTGAATTTCCCCAACTATCACCAGACCTCAGAGATCGTGGGTGACAAGCTGGTGGAG
GTCTCCACCATCGGAGGCGTGACCTATGAGCGCGTGAGCAAGAGACTGGCCTAA
>HS5.PE3533                            387 CDS /gene="ENSG00000170231" /gene_family="HOG000004830" /protein_id="
ATGGCTTTCACCGGCAAGTTCGAGATGGAGAGTGAGAAGAATTATGATGAGTTCATGAAG
CTCCTTGGGATCTCCAGCGATGTAATCGAAAAGGCCCGCAACTTCAAGATCGTCACGGAG
GTGCAGCAGGATGGGCAGGACTTCACTTGGTCCCAGCACTACTCCGGGGGCCACACCATG
ACCAACAAGTTCACTGTTGGCAAGGAAAGCAACATACAGACAATGGGGGGCAAGACGTTC
AAGGCCACTGTGCAGATGGAGGGCGGGAAGCTGGTGGTGAATTTCCCCAACTATCACCAG
ACCTCAGAGATCGTGGGTGACAAGCTGGTGGAGGTCTCCACCATCGGAGGCGTGACCTAT
GAGCGCGTGAGCAAGAGACTGGCCTAA
>HS5.PE3534                            534 CDS /gene="ENSG00000170231" /gene_family="HOG000004830" /protein_id="
ATGAAGACAGTGACGATGATGATGGTGGTGGAGATGCAGGCGCTGACTCAGGTTCTGAGA
GCTGTGTTGTCTGCGTGCACATGGGTGAGCCGGAAAGGAGACCTGCAGAGAATGAAACAG
ACACATAAAGGAAAGCCTCCCAGCAGCATGGCTTTCACCGGCAAGTTCGAGATGGAGAGT
GAGAAGAATTATGATGAGTTCATGAAGCTCCTTGGGATCTCCAGCGATGTAATCGAAAAG
GCCCGCAACTTCAAGATCGTCACGGAGGTGCAGCAGGATGGGCAGGACTTCACTTGGTCC
CAGCACTACTCCGGGGGCCACACCATGACCAACAAGTTCACTGTTGGCAAGGAAAGCAAC
ATACAGACAATGGGGGGCAAGACGTTCAAGGCCACTGTGCAGATGGAGGGCGGGAAGCTG
GTGGTGAATTTCCCCAACTATCACCAGACCTCAGAGATCGTGGGTGACAAGCTGGTGGAG
GTCTCCACCATCGGAGGCGTGACCTATGAGCGCGTGAGCAAGAGACTGGCCTAA
>HS5.PE3535                            387 CDS /gene="ENSG00000170231" /gene_family="HOG000004830" /protein_id="
ATGGCTTTCACCGGCAAGTTCGAGATGGAGAGTGAGAAGAATTATGATGAGTTCATGAAG
CTCCTTGGGATCTCCAGCGATGTAATCGAAAAGGCCCGCAACTTCAAGATCGTCACGGAG
GTGCAGCAGGATGGGCAGGACTTCACTTGGTCCCAGCACTACTCCGGGGGCCACACCATG
ACCAACAAGTTCACTGTTGGCAAGGAAAGCAACATACAGACAATGGGGGGCAAGACGTTC
AAGGCCACTGTGCAGATGGAGGGCGGGAAGCTGGTGGTGAATTTCCCCAACTATCACCAG
ACCTCAGAGATCGTGGGTGACAAGCTGGTGGAGGTCTCCACCATCGGAGGCGTGACCTAT
GAGCGCGTGAGCAAGAGACTGGCCTAA
>LAMPAGS_2381.PE1                      315 CDS /gene="ENSVPAG00000009798" /gene_family="HOG000004830" /pro
CTGCCCGACGACCTCGTCCAGAAGAGTAAGGGCACTAAGGAGGTGACAGAAGTCGTGCAG
AACGGGAAGCATTTCAAGTTTACTGTCACTGCTGGGCCCAAAGTGTTCCAGAACGAGTTC
ACTGTGGGTGAGGAGAGTGAGATGGAGACCATAACCGGGGAGAAGGTCAAGGCAGTGGTT
CAGCTGGAAGGTGAGAATAAACTGGTGACAACTTTCAAAGACATCAAGTCTGTGACTGAG
TTGAATGGTGACACAATCATCAGTACCATGACTTTGGGCGACATTGTCTTGAAGAGAATC
AGCAAAAGAGTTTAG
>LOXAF1_84.PE6                         384 CDS /gene="ENSLAFG00000025554" /gene_family="HOG000004830" /protei
ATGGCCTTCAGCGGCAAGTATGAGGTGGAGAGTGAGAAGAATTACGAGGAGTTTGTGAAG
CAAGTGGGGCTCCCCAGGACCGAAATTGATAAAGGCCACAACTTCAAGATCACAGAGGTG
CAGCAGGATGGGCAGAACTTCACCTGGATCCAGCACTACCCCGGGGGCCAGTCCATAACC
AACAAGTTCACCATCGGCAAGGAGTGCGAAATGGAAGCCATAGGGGGCAAGAAGTTCAAG
GTCACTGTGCAGATGGAGGGTGGAAAAGTCTTGGTGAACGTCCCCAATTATCACCAGACC
TCAGAGATCGTGGGTGACAAGCTGGTAGAGATCTCCACCATCAGAGGTGTGTCCTATGAG
CGTGTGAGCAAGAGGCTGGCCTGA
>LOXAF86_2.PE4                         384 CDS /gene="ENSLAFG00000014043" /gene_family="HOG000004830" /protei
ATGAGTTTCTCCGGCAAGTACCAATTGCAGAGCCAGGAAAACTTTGAGTCCTTCGTGAAG
GCAATCGGTCTGCCTGATGACCTCATCCAGAAGGGGAAGGACATCAAGGGGGTGACAGAA
ATCGTGCAGAATGGAAAGCACTTCAAGTTCACCATCACCACCGGGTCCAAAGTGATCCAA
AATGAGTTCACCCTGGGGGAGGAGAGTGAACTGGATTCCATTACCGGGGAGAAGGTCAAG
ACGGTGGTTAATCTGGAAGGCAACAATAAACTGGTGACAACTTTCAAAGGCATAAAGTCG
GTGACCGAACTCAACGGAGACACACTGACCAGTATCCTGACAGTGGGTGACATTGTCTTC
AAGAGAATCAGCAAGAGAATCTAG
>MACEUGS_4439.PE1                      396 CDS /gene="ENSMEUG00000002745" /gene_family="HOG000004830" /pro
ACTTCCATCATCATGAGCTTCACTGGCAAATACGAAGTTGAGAGTGAAAAGAATTATGAA
GCGTTCCTGAAAATTTTGGGACTCTCCAGTGATACTATTGAAAAATATAGGAACTTCAAG
ACAACCACTGAAGTGGTTCAGGATGGGAACAACTTTACCTGGCAGCACTACCCAGGTGGT
CATACTGTGACAAACAAATTCACTATTGGCAAGGAGAGTGAAATGGAGACCATGGGAGGC
AAGAAGTTCAAGGCCACAGTGCAGATGGAGGGGAACAAGATTGTGGCTACCTTCCCCAAC
TATCAACAAACCTCAGAGATTGTAGGGGGAAAACTGGTGGAGATTTCCACTAGTGGGGGT
GTGACCTACGAACGAGTCAGCAAGAAACTGTCTTAG
>MACMU1099214182296.PE1                324 CDS /gene="ENSMMUG00000030612" /gene_family="HOG000004830" /pro
GGTTTGCCGGAAGAGCTCATCCAGAAGGGGAAGGATATCAAGAGTGTGACGGAAATCGTG
CAGAACGGGAAGCACTTCAAGTTCACCATCACCGCCGGGTCCAAAGTGATCCAAAACGAG
TTCACGGTGGGGGAGGAAAGTGAGCTGGAGACAATGACAGGGGAGAAAGTCAAGAGAGCC
TGGGGCCTCATTCCTCAAGGCTCTAACCTCACAATTCCAACCATAGATACCATTTCTGAA
CCCACCTCCACTGTGGGAGAAGCAGAGAGACAAAGGCAGCTCTTAGGGAAGAATCTTATA
GGGAAGCTGCTCTCATCTTCCCAG
>MACMU6_160.PE11                       387 CDS /gene="ENSMMUG00000023072" /gene_family="HOG000004830" /prot
ATGGCTTTCACCGGCAAGTTCGAGATGGAGAGTGAGAAGAATTATGATGAGTTCATGAAG
CTCCTCGGGCTCTCCAGCGATGTAATCGAAAAGGCCCGCAACTTCAAGATCGTCACGGAG
GTGCAGCAGGATGGGCAGGACTTCACTTGGTCCCAGCACTACTCCGGAGGACACACCATG
ACCAACAAGTTCACTGTTGGCAAGGAAAGCGACATACAGACAATGGGGGGCAAGAAGTTC
AAGGCCACCGTGCAGATGGAGGGCGGGAAGCTGGTGGTGAATTTCCCCAACTATCACCAG
ACCTCAGAGATCGTGGGTGACAAGCTGGTGGAGGTCTCCACCATCGGAGGCGTGACCTAT
GAGCGCGTGAGCAAGAGACTGGCCTAG
>MICMUGS_1222.PE3                      387 CDS /gene="ENSMICG00000003251" /gene_family="HOG000004830" /pro
ATGGCCTTCAACGGCAAGTTTGAGATGGAGAGCGAGAAGAATTATGACGAGTTCATGAAG
CGCCTGGGTCTCTCCAGCGACGTGATCGAAAAGGCCCGCAACTTCAAGACCATCACGGAG
GTGCAGCAGGACGGGCAGAACTTCACCTGGTCCCAGCACTACTCCGGGGGCCACATCATG
ACCAACAAGTTCACCATCGGCAAGGAATGTGACTTACAGACCATAGGTGGCAAGAAGGTC
AAGGTCACCGTGGAGATGGAGGGCTCGAAGGTGGTGGCGAACTTCCCCAACTATCGCCAG
ACCTCAGAGATTGTGGGTGACAAGCTGGTGGAGACCTCCACCGTCGGAGACGTGACCTAC
GAGCGCGTGAGCAAGAGGCTGGCCTAG
>MICMUGS_3586.PE4                      381 CDS /gene="ENSMICG00000011431" /gene_family="HOG000004830" /pro
ATGAACTTCTCCGGCAAGTACCAACTGCAGAGCCAGGAAAACTTTGAACCCTTCATGAAG
GCAATGGGTCTGCCTGACGACCTCATCCAGAAGGGGAAGGACATCAAGGGGGTGTCAGAA
ATCGTGCAAAACGGGAAGCACTTCAAGCTCACCATCACCACCGGTTCCAAAGTGATGCAC
AACGAGTTCACCCTGGGGGAGGAGTGTGAGCTGGAGACCATGACAGGGGAGAAGGTCAAG
GCAGTGGTTCAGCTGGAAGGCAATAAGTTGGTGACAACTTTCAAGAACATCAAGTCCGTG
ACCGAGCTCAATGGCGACACAATCACCAATACCATGACATTGGGTGACATTGTCTTCAAG
AGAATCAGCAAGAGAATTTAG
>MONDO1_366.PE1                        387 CDS /gene="ENSMODG00000008000" /gene_family="HOG000004830" /prote
ATGAGCTTCAGTGGCAAATATGAAGTTGAAAGTGAAAAGAACTACGAGGCATTCCTGAAT
CAGTTGGGAATCTCCAAGGATACCATTGAAAAATACAGGAACTTCAAGACCCTCACTGAG
GTGGTTCAGGATGGGAACAACTTTACCTGGATCAATACTTATCCAGGGGGTCAAATCATG
ACTAACAAATTCACCATTGGCAAGGAGTGTGAAATGGAGACCATGGGAGGCAAGAAGTTT
AAGGCCACAGTGCAGATGGAGGGAAACAAGATAGTGGCGACCTTCCCCAACTATCAACAA
ACCTCTGAGATCGTTGGAGGAAAACTGGTGGAGATCTCCACTAGCGGAGGTGTGACCTAC
GAAAGAGTCAGCAAGAAATTGTCCTAG
>MOUSE11.PE677                         387 CDS /gene="ENSMUSG00000020405" /gene_family="HOG000004830" /protei
ATGGCCTTCAGTGGCAAATATGAATTTGAGAGTGAGAAGAATTACGATGAGTTCATGAAG
CGCCTGGGTCTTCCAGGAGACGTGATTGAAAGGGGACGTAACTTCAAGATCATCACAGAG
GTCCAGCAGGACGGACAGGACTTCACCTGGTCCCAGTCTTACTCTGGGGGCAACATTATG
AGCAACAAGTTCACCATTGGCAAAGAATGTGAAATGCAGACCATGGGGGGCAAGAAGTTC
AAGGCTACCGTGAAGATGGAGGGTGGCAAGGTGGTGGCAGAGTTCCCCAACTATCACCAG
ACTTCGGAGGTCGTGGGTGACAAGTTGGTGGAGATCTCCACCATCGGGGATGTGACCTAT
GAGCGCGTAAGCAAGAGGCTGGCTTGA
>MOUSE6.PE1107                         384 CDS /gene="ENSMUSG00000054422" /gene_family="HOG000004830" /protei
ATGAACTTCTCCGGCAAGTACCAATTGCAGAGCCAGGAGAACTTTGAGCCATTCATGAAG
GCAATAGGTCTGCCCGAGGACCTCATCCAGAAAGGGAAGGACATCAAGGGGGTGTCAGAA
ATCGTGCATGAAGGGAAGAAAATCAAACTCACCATCACCTATGGACCCAAAGTGGTCCGC
AATGAGTTCACCCTGGGGGAGGAGTGCGAACTGGAGACCATGACTGGGGAAAAAGTCAAG
GCAGTCGTCAAGCTGGAAGGTGACAATAAAATGGTGACAACTTTCAAAGGCATAAAGTCC
GTGACTGAACTCAATGGAGACACAATCACCAATACCATGACATTGGGCGACATTGTCTAC
AAGAGAGTCAGCAAGAGAATTTAG
>MYOLUGS_1527.PE3                      312 CDS /gene="ENSMLUG00000003069" /gene_family="HOG000004830" /pro
CTCCCCAGCGATGCAATTGAAAAGGGCCGTAATTTCAAGATCGTCACGGAGGTCCAGCAG
GATGGGCAGAACTTCACCTGGTCCCAGCACTACCCCGGGGGCCACTCCATGACCAACAAG
TTCACCATTGGCAAGGAGTGCGACATGGAGACCATGGGAGGCAAGAAGTTCAAGGCCACT
GTGCAGATGGAAGGCGGGAAGGTGGTGGTGGATTTCCCCAACTATCACCAGACCTCGGAG
ATCGTGGGTGGCAAGCTGGTGGAGATACACACGATGAGAGGATTGACCAGCATGGGTCAT
AGGCTGACCCGG
>MYOLUGS_4694.PE2                      315 CDS /gene="ENSMLUG00000012480" /gene_family="HOG000004830" /pro
CTGCCTGACGACCTCATCCAGAAGGGGAAGGACATCAAGGGAGTGTCGGAGGTCGTGCAG
AATGGGAAGCACTTCAAGCTCACCGTCACCACCGGGTCCAAAGTGATCCAGAACGAGTTC
ACCCTGGGCGAGGAGTGCGAGCTGGAGACCATGACTGGGGAGAAGGTCAAGGCAGTGGTG
CAGCTGGAAGGTGAGAATAAACTGGTGACATCTTTCAAAGGCATCAAGTCCGTGACGGAA
CTCAATGGAGACACAGTCATCCACACCATGACATTGGGTGACATTGTCTTCAAGAGAATC
AGCAAGAGAATTTAG
>OCHPR1657.PE2                         381 CDS /gene="ENSOPRG00000012820" /gene_family="HOG000004830" /protei
ATGAACTTCACCGGCAAGTACCAACAGCAGAGCCAGGAAAACTATGAGCCCTTCATGAAG
GCAGCCGGTGTGCCAGCTGATGTCATCCAGAAGACAAAGGATGTCAAGATGATGTTGGAA
ATTGTGCAGAATGGGAAGCACTTCAAGCTCATCATGTCCGTCGGCCCCAAAGTGACCCAG
AACGAGTTCACCTTGGGGGAGGAGTGTGAGCTGGACACTGTGATGGGCAAGTTCAAGACG
GTGGTGAAGTTGGAAGGTGAGAATAAACTGGTGACAAGTTTCAAAAACATAAAATCTGTG
ACTGAACTCAACGGGGATACCATCATCAACAGCATGACATTGGGTGACATTGTCTTCAAG
AGAATCAGCAAGCGAGTTTAA
>ORYLA11_17.PE31                       381 CDS /gene="ENSORLG00000007702" /gene_family="HOG000004830" /prot
ATGGACTTTAGCGGAACTTGGAAAGTTTATTCTGAGGAGAACCTAGAAGCGTTCCTCAAA
GTCATAGGGGCACCTGAGATGATCGTGAAAATGCGAAAGGACGTCAAACCTGTAGTAGTG
ATAGAGCAGAATGGTAAAGATTTTGTCTACACCATCAAGACTCCAATGTTTACCAGGGTG
TACTCATTCACCCTTGGACAGGAGACAGAAATTCCTTCTGTGGATGGCAGAAAGGTTAAG
TGCATCATCAGGGAGGAAAACGGGAAGCTAATTGGTGAGGCTGACAAGTTCACTTCTGTT
CGAGAGATCCGGGGGGATGAAATGACAGAGACCATCACTTCTGGTTCAGTAACGTTCATC
AGCAAAAGCAAACGGGCCTAA
>ORYLA16_22.PE25                       381 CDS /gene="ENSORLG00000014794" /gene_family="HOG000004830" /prot
ATGGACTTCAATGGAACTTGGCAGGTGTACTCCCAGGAAAACTACGAGGAGTTCCTCAGG
GCTTTGGAGTTGTCAGAAGATATCATCAAGCTGGCCAAGGATGTTAAGCCAGTTACTGAG
ATCAAACAGACGGGCAACGACTTCGTCATCACCTCCAAGACACCTGGAAGAACAGTGACC
AACTCCTTCACCATCGGCAAGGAGGCTGAAATCTCCACCATGGATGGCAAGAAGCTGAAG
TGTGTTGTCAACATGGAGGGTGGCAAACTGGTCTGCAAAACTGGCAAATTTTGCCACGTG
CAAGAGATCAAAGGAGGAGAAATGGTTGAGACTATGACCGTTGGCTCAACAACACTCATC
AGGAAAAGCAAGAAGATGTGA
>PANTR5_168.PE1                        534 CDS /gene="ENSPTRG00000017487" /gene_family="HOG000004830" /prote
ATGAAGACAGTGACGATGATGATGGTGGTGGAGATGCAGGTGCTGACTCAGGTTCTGAGA
GCTGTGTTGTCTGCGTGCACGTGGGTGAGCCGGAAAGGAGACCTGCAGAGAATGAAACAG
ACACAGAAAGGAAAGCCTCCCAGCAGCATGGCTTTCACCGGCAAGTTCGAGATGGAGAGT
GAGAAGAATTATGATGAGTTCATGAAGCTCCTTGGGATCTCCAGCGATGTAATCGAAAAG
GCCCGCAACTTCAAGATCGTCACGGAGGTGCAGCAGGATGGGCAGGACTTCACTTGGTCC
CAGCACTACTCCGGGGGCCACACCATGACCAACAAGTTCACTGTTGGCAAGGAAAGCAAC
ATACAGACAATGGGGGGCAAGACGTTCAAGGCCACCGTGCAGATGGAGGGCGGGAAGCTG
GTGGTGAATTTCCCCAACTATCACCAGACCTCAGAGATCGTGGGTGACAAGCTGGTGGAG
GTCTCCACCATCGGAGGCGTGACCTATAAGCGCGTGAGCAAGAGACTGGCCTAA
>PIG3_54.PE7                           318 CDS /gene="ENSSSCG00000008214" /gene_family="HOG000004830" /protein_
GGTCTGCCCGACGAACTCATCCAGAAGGGGAAGGACATCAAGGGGACATCGGAAATCGTG
CAGAATGGGAAGCACTTCAAGTTGACCATCACTACCGGGTCCAAGGTCGTCCAGAATGAG
TTCACCTTGGGAGAGGAGTGTGAGATGGAGACCCTGACTGGGGAGAAGGTCAAGACAGTG
GTTCAGTTGGAAGGTGACAATAAACTGGTGACAACTTTCAAAGGCATCAAGTCTGTGACT
GAACTCAACGGTGACATAATCACCAGTACCATGACACTGGGTGACATTGTCTTCAAGAGA
ATCAGCAAGAGAATTTAG
>POEGU13_2.PE12                        399 CDS /gene="ENSTGUG00000000197" /gene_family="HOG000004830" /prote
CCCAAGGGAGCAATGGCATTCTCAGGCAAATACGAGTTCGAGGGCGATGAGAACTACGAC
GCCTTTGTGCAGAAGATTGGCCTCCCCAGTGACAAGGTTGAAATGGGAAGGAACTGCAAG
ATTGTGACAGAGGTGGTGCAGAATGGGAATGACTTCACATGGACACAGCACTTCCCAGGA
GGCCGCACCACCACCAACACCTTCACCGTGGGCAAGGAGGCAGACATGGAGACCATGGGA
GGGAAGAAGTTCAAGGCAACTGTCAAAATGGAAGATGGGAAACTTGTAGCTGATTTCCCC
AACTACCGCCACACTGCAGAGATCTGTGGGGGGAAGCTGGTAGAGATTTCTACGTCTTCT
GGTGTAGTCTACAAGAGGACCAGCAAAAAGATTGCCTAA
>POEGU4_68.PE18                        384 CDS /gene="ENSTGUG00000010860" /gene_family="HOG000004830" /prote
ATGAGCTTCACTGGAAAATACCAGCTCCAGTACCAGGAAAACTTTGAGCCCTTTATGAGA
GCCCTCGGGCTCCCTGAGGACCAGATCCAGAGGGGCAAGGACCTCAAGAGCATCTCAGAA
ATTGTGCAGGATGGGAAAAAGTTCACTATTACTGTGACCACTGGCTCCAAAGTGGTGAAA
AACCAGTTCACCATTGGGGAGGAGAGTGACATAGAGATGCTGAATGGAGAGAAAGTGAAG
GCTGTTGTGCAGATGGAGGGTAACAACAAACTGGTCACGCAGGTGAAAGGGATGAAATCC
GTCACGGAGCTCAACGGAGACACCATCACCTACACAATGACCATGGGTGACCTCACCTTG
AAGAGAGTCAGCAAGAGAATCTAG
>PONPY5_167.PE4                        387 CDS /gene="ENSPPYG00000016004" /gene_family="HOG000004830" /prote
ATGGCTTTCACCGGCAAGTTCGAGATAGAGAGTGAGAAGAATTATGATGAGTTCATGAAG
CTCCTCGGGATCTCCAGCGATGTAATCGAAAAGGCCCGCAACTTCAAGATCGTCACGGAG
GTGCAGCAGGATGGGCAGGACTTCACTTGGTCCCAGCACTACTCCGGGGGCCACACCATG
ACCAACAATTTCACTGTTGGCAAGGAAAGCAACATACAGACAATGGGGGGCAAGACGTTC
AAGGCCACCGTGCAGATGGAGGGCGGGAAGCTGGTGGTGAATTTCCCCAACTATCACCAG
ACCTCAGAGATCGTGGGTGACAAGCTGGTGGAGGTCTCCACCATCGGAGGCGTGACCTAT
GAGCGCGTGAGCAAGAGACTGGCCTAA
>RABIT2_101.PE8                        381 CDS /gene="ENSOCUG00000016960" /gene_family="HOG000004830" /prote
ATGAACTTCACCGGCAAGTACCGACTGCAGAGCCAGGAAAACTTTGAGACCTTCATGAAG
GCAGCCGGCGTGCCTGAGGACATCATCCAGAAGATGAAGGATGCGGAAGGGTCGTCGGAA
ATCGTGCAGAACGGGAAGCACTTCAAGCTCATCATCTCCATCGGCTCCAAAGTGATCCAG
AACGAGTTCACCTTGGGGGAGGAGTGTGAGCTGGACACCGTGATGGGGAAGGTCAAGACA
GTGGTGAAGCTGGAAGGTGAGAACAAGCTGGTGACGACGTTCAAAAACATCAAATCCGTG
ACCGAACTCAACGGCGACACCATCACTAACACGATGACAATTGGTGACGTTGTCTTCAAG
CGAATCAGCAAGCGGATTTAG
>RABIT3_43.PE5                         402 CDS /gene="ENSOCUG00000005435" /gene_family="HOG000004830" /protei
CCCAGCACCATGGCCTTCACCGGCAAGTTCGAGATGGAGAGTGAGAAGAACTATGACGAG
TTCATGAAGCTCCTGGGCCCAGGGCTTCCCAGCGACGTGGTGGAAAAGAGCCGCAACATT
AAGATCGTCACGGAGATAAAGCAGGACGGACAGGACTTCACCTGGTCCCATCACTACTCC
GGGGGACAAATCATGACCAACAAGTTCACCATCGGCAAGGAGAGTGAAATACAGACCTTT
GGGGGCAAGAAGTTCAAGGCCGTCGTGAACATGGAAGGCGGCAAGGTGGTGGCGAACTTT
CCCAACTATCAGCACACCTCGGAGATCAAGGGTGACAAGCTGGTGGAGGTCTCCAGCATT
GGAGGAGTGACCTACGAGCGCGTGAGCAAGAGGCTGGCCTGA
>RAT10.PE490                           387 CDS /gene="ENSRNOG00000003902" /gene_family="HOG000004830" /protein_
ATGGCCTTCACCGGCAAATACGAATTTGAAAGTGAGAAGAATTACGACGAGTTCATGAAG
CGCCTGGGTCTTCCAGGAGATGTGATTGAAAGGGGACGTAACTTCAAGATCATCACAGAG
GTCCAGCAGGATGGAGAGAACTTCACCTGGTCCCAGTCTTACTCTGGGGGCAACATCATG
AGCAACAAGTTCACCATTGGCAAAGAATGTGAAATGCAGACCATGGGGGGCAAGAAGTTC
AAGGCAACCGTGAAGATGGAGGGTGGCAAGGTGGTGGCAGACTTCCCCAACTATCACCAG
ACTTCGGAGGTCGTGGGTGACAAGTTGGTGGAGATCTCCACCATCGGGGATGTGACCTAC
GAGCGTGTAAGCAAGAGGGTGGCTTGA
>RAT4.PE1025                           384 CDS /gene="ENSRNOG00000006675" /gene_family="HOG000004830" /protein_
ATGAACTTCTCCGGCAAGTACCAAGTGCAGAGCCAAGAGAACTTTGAGCCCTTCATGAAG
GCGATGGGTCTGCCTGAGGACCTCATCCAGAAAGGGAAGGACATCAAGGGGGTGTCAGAA
ATCGTGCATGAAGGGAAGAAAGTCAAACTCACCATCACCTATGGGTCCAAGGTGATCCAC
AATGAGTTCACCTTGGGGGAGGAGTGCGAACTGGAGACCATGACTGGGGAAAAGGTCAAG
GCAGTGGTTAAGATGGAGGGTGACAATAAAATGGTGACAACTTTCAAAGGCATAAAGTCC
GTGACTGAATTCAATGGAGACACAATCACCAATACCATGACACTGGGTGACATCGTCTAC
AAGAGAGTCAGCAAGAGAATTTAG
>SORARGS_4922.PE1                      384 CDS /gene="ENSSARG00000005622" /gene_family="HOG000004830" /pro
ATGAACTTCTCCGGCAAATACCAACTGCAGAGCCAGGAAAACTTTGAGGCCTTCATGAAG
GCCATTGGCATGCCAGATGACCTCATTCAGAAAGGGAAGGACATCAAGGGGGTGACAGAA
GTCGTGCAGACCGGCGACCACTTCAAAGTCATCATCACCACCGGCACCAAAGTGATCACG
AATGAGTTCACCTTGGGAGTGGAGTCTGAGATAGAGACCATGACGGGAGAGAAGGTCAAG
GCTGTGGTTAAGAAGGAAGGTGACAATAAGCTGGTGACATCTTTCAAAGGCATCACGTCT
GTGACTGAGATCAATGGTGACACTGCCACCCATACCATGACCCTGGGCGATATTGTCTTC
AAGAGAGTGAGCAAGAAGATCTAG
>TARSYGS_5771.PE1                      384 CDS /gene="ENSTSYG00000003357" /gene_family="HOG000004830" /pro
ATGAACTTCTCTGGCAGGTACCAGCTGCAGAGCCAGGAAAACTTTGAGCCCTTCATGAAG
GCAGTGGGTCTGCCCGATGACCTCATCCAGAAGGGGAAGGACATCAAGGGGGTGTCGGAA
ATCGTCCAGAACGGGAAGCACTTCAAGCTCACCATCACCACCGGTTCCAAGGTGATCCAG
AACGAGTTCACGCTGGGTGAGGAGTGCGAGCTGGAGACCATGACGGGGGAGAAGGTCAAG
GCAGTAGTCCAGATGGAAAATGACAACAAGCTGGTGACAACTTTCAAAAACATCAAGTCG
GTGACAGAACTCAACGGCGACACAATCACCAATACCATGACATTGGGCAACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAG
>TETNG1.PE81                           396 CDS /gene="ENSTNIG00000004652" /gene_family="HOG000004830" /protein_
TCCACCATGACTTTTACTGGGAAATACGAGCTGGAGACTCAGGAAAACTACGAGGAGTTT
CTGGATGCCATCGGTACTGCGGCAGGACTTCTCAGCGCCAAGACGGACCACAAAGTGATA
ACGGAGGTGAGCCAGGACGGGAACGACTTCACCTGGACTCAAAGCATTCCCCACTGGACG
TGGACAAACACCTTCAGCGTCGGTCGGGAATGTGAGCTGGTGACCATGAAGGGCACCAAG
TTCAAGGCGCCTGTCGTGATGGACGATGGGAGGATCTCAGTCCAGTTTCCCCAGTACCAT
TTCACAGCCGAGGTCAGCGGGGACAAGCTGATCATGAATTGCACAATTCCAGGAGAGAAG
GGTGTGACCTTCAGGAGAACCAGCAGGAGGGTCTGA
>TETNG12.PE575                         387 CDS /gene="ENSTNIG00000016680" /gene_family="HOG000004830" /protei
CTCCATTCAGCTGTGCACCATTCCATAAAAGGTAAGGAGAACTTTGAGCCTTTTATGAAG
GCCATTGGTGTTCCTGATGAAATCATCCAGCAGATCAAAGACATCATGAGCTTCACTGAG
ATTGTGCAGAATGGCAATGATTTCAAAATCACCACCACTACTGGCCCAAAGGTAACGGTC
AACCAATTTACCATTGGGAAGGAGACAGAGATGGACGCCATCAGCGGAGAAAAGATAAAG
AAGACGGTGTTTCGTCTGGAGGACAACAAACTGAAAGTCTCCCTGAAAAATATAGAGTCG
GTCACAGAACTGGTGGATCCAAACACGCTCGTTGCCGTGATGACTTTGGGCGACATCGTG
TACAAGTCAACAAGTAAACGCGTGTAA
>TETNG12.PE576                         375 CDS /gene="ENSTNIG00000016680" /gene_family="HOG000004830" /protei
CTCTCATCTGGAAAATACCAGCAGGTGTCATTCCAGAACTTTGAGCCTTTTATGAAGGCC
ATTGGTGTTCCTGATGAAATCATCCAGCAGATCAAAGACATCATGAGCTTCACTGAGATT
GTGCAGAATGGCAATGATTTCAAAATCACCACCACTACTGGCCCAAAGGTAACGGTCAAC
CAATTTACCATTGGGAAGGAGACAGAGATGGACGCCATCAGCGGAGAAAAGATAAAGACG
GTGTTTCGTCTGGAGGACAACAAACTGAAAGTCTCCCTGAAAAATATAGAGTCGGTCACA
GAACTGGTGGATCCAAACACGCTCGTGATGACTTTGGGCGACATCGTGTACAAGTCAACA
AGTAAACGCGTGTAA
>TUPGB123696.PE2                       384 CDS /gene="ENSTBEG00000005284" /gene_family="HOG000004830" /prot
ATGAACTTCTCCGGCAAGTACCAAGTGCAGAGCCAGGAAAACTTCGAAGCCTTCATGAAG
GCAGTCGGTCTGCCTGATGAGCTCATCCAGAAAGGGAAGGACATCAAGGGAGTGTCGGAA
ATCGTGCAGAATGGGAAGCACTTCAAGCTCACCATCACCACTGGGTCCAAAGTGATCCAA
AACGAGTTCACCTTGGGGGAAGAATGTGAGCTGGAGACCATGACTGGGGAGAAGGTCAAG
ACGGTGGTCCAGCTGGAAGGTGAGAATAAACTGGTGACAACATTCAAAAACATCAAATCC
GTGACTGAACTCAATGGTGACACACTCACCAGTACCATGACTCTGGGCAACATTGTCTTC
AAGAGAATCAGCAAGAGAATTTAG
>TURTR106877.PE2                       516 CDS /gene="ENSTTRG00000012640" /gene_family="HOG000004830" /prot
GTGGTGGGGCAGCAGGCGCAAAGGGTTTTGAAGGCCCTGTTGTCTGCGAGCACATGGACA
GCAGAGAAAGGGCGTCTGTGCAGAATCAAGTTGAAAAAGAGAGAAGATGAAGATGAACTC
TCCGGCAGCATGTCCTTCACCGGCAAGTATGAGATGGAGAGTGAGAACAACTATGACGAG
TTCATGAAGCGCCTGGGGCTCCCCAGCAACAGGATTGAAAAGGGTCGCGACCTCAAGACT
ATCTCAGAGGTGCAGCAGGACGGGCAGAACTTCACCTGGTCCCAGAACTACCCCGGGGGC
CCCTCCATTACCAACAATTTCACCATCGGCAAAGAGTGCGACATGGAGACCGTGATGGGC
AAGAAGTTCAAGGCCACTGTGCAGATGGAGGGTGGGAAGGTGGTGGTGAACTTCCCCCAC
TACAACTATACTGCGGAGATTGTGGATGGCAAGCTGGTGGAGATCTCCACCGTTGCAGGT
GTGTCCTACGAGCGCGTGAGCAAGAGGCTGGCCTGA
>TURTRGS_2024.PE6                      384 CDS /gene="ENSTTRG00000014532" /gene_family="HOG000004830" /pro
ATGAACTTCTCCGGCAAGTACCAAGTGCAGAGCCAGGAAAACTTTGAGACCTTCATGAAG
GCAGTCGGTATGCCTGATGAACTCATCCAGAAGGGGAAGGACATCAAGGGGGTGTCAGAA
GTCGTGCATAACGGAAACCACTTCAAGTTCACCATCATCACTGGCTCCAAAGTGATCCAG
AACGAGTTCACCTTGGGGGAGGAGTGTGAGATGGAATTCCTGACTGGGGAGAAGGTCAAG
GCGGTGGTTCAGCTGGAAGGTGAGAATAAACTGGTGACAACTCTCAAAGGCATCAAGTCC
GTGACTGAATTCAACGGTGACACAGCCATCAGCACCATGACACTGGGGGACATCGTCTTC
AAGAGAATCAGCAAGAAAATTTAG
