>AILMEGL192492_1_1.PE33                516 CDS /gene="ENSAMEG00000017348" /gene_family="HOG000230780" /pro
ATGGAAAGTAGCGACGAGAAGGCGGTAGAGAAGTGCCGCGTCCACTTGCGCCCCGGCACG
CTGCGCGACGCCGCCCTCGCCACGCTGCACCTTCTGCCCTGCGAGGTTCTGGTTAATGGG
CCCGCCCCGGTGGAGCGCTTCTTCACCCCAGCCATGCGCCAGGGTCCCGATGGACTCGAA
GTGTCGTTTCGGGGCCGTAGACTACGGGGCGAGGAGGTGGTGGTGCCGCCGGGCCTCGTG
GGATACGTGATGGTGATGGAAGAAAAGGGAGAGGTGCTGGTGGGGAAGGACTTCTCGGAG
GATTCATGGAATGACGAGCGAGAGGAGCAGGAGCTGGCGGAACCCCCTGAGGCGCTGGAG
CGAGACTTTGACCAATTTATCGGAGCCACCGCCAGTTTCAGCCGCTTCATGCTGTGGGGC
CTGGAGACAATCCCCGGTCCGGACGCCAAAGTGCGCGGGGCCCTAACCTGGCCCAGCCTG
GCTGCAGCGATTCACGCACAGGTGCCTGAAGACTGA
>ANOGA_100.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_101.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_102.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_103.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_104.PE904                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_105.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_106.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_107.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_108.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_109.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_110.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_111.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_112.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_113.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_114.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_115.PE904                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_116.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_117.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_118.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_119.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_120.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_121.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_122.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_123.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_124.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_125.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_126.PE904                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_127.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_128.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_129.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_130.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_131.PE905                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_132.PE904                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_133.PE902                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_134.PE899                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_135.PE902                       447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_81.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_82.PE904                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_83.PE900                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_84.PE887                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_85.PE904                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_86.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_87.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_88.PE895                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_89.PE904                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_90.PE901                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_91.PE903                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_92.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_93.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_94.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_95.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_96.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_97.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_98.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>ANOGA_99.PE905                        447 CDS /gene="AGAP011243" /gene_family="HOG000230780" /protein_id="A
ATGGCAAAAATCAATTTGAAGCTAAGCTCGAAGGACGTGGAAACCAGCCTCCAGGACGGC
TCCATCAAGCTGCAGTACATTCCCGCCACGATCAAGGGCGACGGGCCGGCGAATCTGGAG
CAGTTTTTCACACCGTACACGGAAACGCAACGGGACGGAACTCTGTGCAATGCGCTTCGG
GGATATCCGCTGCGCGGCAAAGCAACGTCCCTGCCGGCCGGCTACACGGGCGTGATGCTG
CAGGAAACGAAAAAACCACTCTCGGACGAGGACGATCGAACGCTAACGTTTGCCGGTGCT
TTCCGCGACTTTACCTACTGGAACTACGATCGCCAGCCGTCCCGGAACGATCCGATGGCG
AAGGCACTGGGCTGGCTGCAGCTGGCGGAGGTGCTGCATGGCGACGAGCCCGATACTGAC
ACCGAGCAGGCTGTGAAGCAGGAACGG
>BOVIN29_47.PE34                       498 CDS /gene="ENSBTAG00000005577" /gene_family="HOG000230780" /prot
ATGGAGAATAGCTACGAGGAAACCATCGACAAACGCCGCGTCCACCTGCGCCCTGATACG
CTGCGCGATCCCGCCCCCGCCTCGCTGCACCTTCTTCCCTGCGAGGTCCCGGTTAACCGG
CCCACGCCGGTGGGGCGCTTCTTCACCCCAGCCATCCGTATGGGTCGTGACGGACTAGAA
GCGTCGTTTCGGGGCCGTAGTCTACGTGGCGAGGAGGTGGTGGTGCCGCCCGGCTTCGTG
GGATATGTGGTGACAGAAGAGAAGGCAGAGGTGTTGATGGGGAAGCAGGATGACCACGAG
CGACAGGAGCAGGAACTGCTGGAACCCCCAGAGGCGCTGGAGCGGGACTGCGACCGCTTT
ATGGGAGCCACAGCCAGTTTCAGCAGCTTCACCGTGTGGGGCCTGGAATCTATCCCTGGT
CCGGATGCCAAACTGCGTGGGGCCCTAAGCTGGCCCAGCCTCGCTGCAGCGATTCACGCA
CAGGTACCCGAAGACTGA
>CULQU_2973.PE10                       465 CDS /gene="CPIJ005009" /gene_family="HOG000230780" /protein_id="
ATGGCCATCAACCTCAAACTAAAACAATCGGACGTCCAGCAATGCTTGGAGACCCCGCCT
AAGGTCCACTACATTCCGGCCACGATCCGGGGCGACGGACCGGCCAATGTGGCGCAATTT
TTCGAATCCTACACCGACGAATCGGAGGGCAAAATTTTTCTTTCAGCTCTAACGAACGCC
TTGCGAGGCTTTCCGCTGCGCGGCAAGGAGTTTAACCTACCGGCCGGTTACACCGCCGTC
ATGTTCCAGGAAACGAAGCGGCCACTGTCCGCGGACGAGGATCGCAACTTTAGCTTCGCG
GGAGCGTTCAAGCAGTTTACCTACTGGAACTACGACAAGATTCCGACGAAGAATGACCCG
CTGGAGAAGGCGCTCGATTGGATGGAGCTGTCCCGGGCGCTGCACGATCCGTTGGGGGAG
GAGGATGATGATGAGGAGAAGGTGGTGAAGAAGGAGAAGAAATAA
>FELCA135309.PE2                       492 CDS /gene="ENSFCAG00000000042" /gene_family="HOG000230780" /prot
ATGGAGAGCAGCGATGAAGCGGCCGTCGAGAAATGCCGAATCCACTTGCGCCCCGGCACG
CTGCGCGACGCACCTCCCGCCACGTTGCACCTTCTGCCCTGCGAGGTTCTGGTTAGCCGG
CCTGCCCCCGTGGGGCGCTTCTTCACCCCAGCCATCCGCCAGGGTCCCGACGGACTGGAA
GTGTCGTTTCGGGGCCGCAAACTACGCGGCGAGGAGGTGGTGGTGCCGCCCGGGCTCGTG
GGCTACGTGATGGAAGAAAAGGGAGAGGGGTTGGTGGGGAAGGGCTTCTCGGAGGGTTCG
TCGAATGACAACGAGCAAGAGCAGGAGGCGCTGGAGCGGGACTTTGACCGGTTCATTGGA
GCCACCGCTAGTTTCAGTGGCTTCACGCTGTGGGGCCTGGAGACCATCCCCGGTCCGGAT
GCCAAAGTGCGCGGGGCCCTAACCTGGCCCAGTCTCGCTGCCGCGATTCACGCACAGGTG
CCTGAGGACTGA
>MOUSE19.PE197                         501 CDS /gene="ENSMUSG00000024925" /gene_family="HOG000230780" /protei
ATGAAGAACCCGGAGGAAGCGGCAGACGGGAAACAGCGTATTCACCTGCGCCCTGGCTCG
CTGCGTGGTGCCGCACCGGCTAAGCTGCACCTCCTGCCCTGCGACGTTCTAGTCAGCCGG
CCGGCCCCGGTAGATCGCTTCTTCACGCCCGCCGTCCGCCACGATGCAGACGGGCTACAG
GCGTCGTTTCGCGGTCGCGGCCTGCGGGGCGAGGAGGTAGCTGTGCCGCCAGGGTTTGCG
GGATTCGTGATGGTGACGGAGGAGAAGGGAGAGGGGTTGATAGGGAAACTGAACTTCTCC
GGGGACGCGGAGGACAAAGCGGACGAGGCGCAGGAGCCGCTGGAGCGGGACTTCGACCGC
CTTATCGGGGCCACCGGCAGCTTCAGCCATTTCACCTTGTGGGGTCTGGAAACGGTCCCG
GGTCCAGATGCCAAAGTGCATAGGGCCCTAGGTTGGCCCAGCCTCGCAGCAGCGATTCAC
GCCCAGGTCCCTGAGGACTGA
>RAT1.PE3311                           501 CDS /gene="ENSRNOG00000020700" /gene_family="HOG000230780" /protein_
ATGAAGAACCCGGAGGAAGCTGGGGACGATAAACAGCGTATTCACCTGCGCCCTGGCTCA
CTGCGTGGCGCCGCACCAGCTAAGCTGCACCTCCTGCCATGTGACGTTCTGGTCAGCCGG
CCCGCCCCGGTTGAACGCTTCTTCACGCCCGCCGTCCGCCACGGTGCAGACGGACTGCAG
GTGTCGTTTCGCGGTCGTGGCCTGCGGGGCGAAGATGTAGCTGTCCCGCCAGGGTTTGCG
GGATTCGTGATGGTGACAGAAGAGATGGGAGAGGGGCTGATAGGGAAGCTGAACTTCTCA
GGGGACGCGGAGGACAAAGCGGACGAGGCACAGGAGCCGCTGGAGCGGGACTTTGACCGC
TTTATCGGAGCCACCGGCAGCTTCAGTCACTTCACCTTGTGGGGTCTGGAAACGGTCCCT
GGTCCAGATGCCAAAGTGCATAGGGCCCTAGGTTGGCCCAGCCTTGCTGCAGCGATTCAC
GCACAGGTGCCAGAGGACTGA
