>AILMEGL194206_1.PE2                   309 CDS /gene="ENSAMEG00000010339" /gene_family="HOG000115781" /pro
CCCCTAAACGTAAAAGTGTTCCAGCAAGAGCATAAGATTCCTGCAATGGAGGCCCCCCAA
GACTCGTTTCCTGTGACGACCACCGTGGTCACCATCCACACTGAGACGGCCGTGCCCGAC
CACATCGTCGTCCCTGTTCAACACCATCTTCATGAATGCTGCCTGGGCTTCGTGGCCTTC
GCCTACTCCGTGAAGTCTAGGGACCGGAAGATGGTGGGTGACATGACTGGGGCCCGGACT
CTCCACCGCCAAGTGCCTGAACATCTGGGCCCTGGTCCTGGGCCTCCTTCTGACCATCAC
GTTCATCAT
>AILMEGL194848_1.PE10                  405 CDS /gene="ENSAMEG00000003396" /gene_family="HOG000115781" /pro
ATGGACACGTCGTACCCCCGCGAGGACCCCCGGGCCCCGACGCCCCGCAAGGCAGACGGC
GCAGCCCACACGGCCCTCACTCTGGGGGCGCCGAGACCCCCGCCTCGAGACCACTTGATC
TGGTCGGTGTTCAGCACCCTGTACTTGAACCTGTGCTGCCTCGGCTTCCTGGCGCTGGCC
TACTCCATCAAGGCCCGAGACCAGAAGGTGGCTGGAGACCTGGAGGCAGCCCGGCGTTTG
GGCTCCAAAGCCAAGTGCTACAACATCCTGGCCACGATGTGGGCGTTGGTACCGCCTCTG
CTGCTCCTGGCGCTGGTGGTGACCGGCGCGCTGCACCTGTCCCGGTTGGCCAAGGACTCT
GCTGCCTTCTTCAGCACCAAGTTCGACGACTCGGACTATGACTGA
>ANOCA9_7.PE6                          354 CDS /gene="ENSACAG00000017472" /gene_family="HOG000115781" /protein
ATGGACACATCTTACCCGCGTGAAGACTACTTGCCGATGACATCCCACAAGCAGGAACCA
TCCCCCACAGTCATCAAGGTTAGGCCTCCGGTGGTGCCACGAGACTACATGGTCTGGTCT
ATCTTCAACACGATCTACATGAACCTCTGCTGCCTCGGCTTTGTAGCCCTTACCTATTCT
GTCAAGGCAAGGGATCAGAAGGTGGCTGGTGACCTGGAAGCTGCTCGTCGCTATGGCTCC
AAAGCCAAATGCTACAATGTCCTTGCAACCTTGTGGAATGTGGTGGTGCCATTAGTGCTC
ATTGCTCTGGTAGTCACTGGTGTGCTCCACCTGTCCAAGCTGGCTCAAGAGTCC
>BOVIN23_30.PE1                        438 CDS /gene="ENSBTAG00000031905" /gene_family="HOG000115781" /prote
ATGAACTGCACATCCCAGCCCTTATTCACTGGGGCACACGGTGTGGTGCCCCCAGCCTAT
GAGGTGCTCAAGGAGGAGCATGAGGTGGCCGTGCTGGGGGTTCCCCAGAGCCAGGCCCCC
GTGACGACCACGGTGATCAACATCTGCAGCGAGACCTCTGTGCCCAACCACATTGTCTGG
TTCCTGTTCAACACCATCTTCATGAACTGGTGCTGCCTGGGCTTCGTGGCATTCGCCTAC
TCTGTGGAGTCTAGGGACCGGAAGATGGTTGGTGACATCACTGGGGCCCAGAGGTACACC
TCCACCGCCAAGTGCCTGAACATCTGTGCCCTGGTCCTGGGCCTCCTTCTGATTATCGTC
CTCATCATCATGTCCATCGGCTCCCTGATGATTGTTCAAGCAGTTTTGGAGCTCATACAG
AACTATGGAGGCCACTAG
>CALJA10_50.PE11                       396 CDS /gene="ENSCJAG00000023220" /gene_family="HOG000115781" /prot
ATGAACCACACTGTCCAAACCTTCACTCCCACCAGCACCGACCGTCCCCCAAACTATGAG
ATATTGAAGGAGGAACATGAGGTGGATATGCTGGGGGCGCTCCACAACACTGCACCCTCG
ACATCCACCGTTATCCACATCCAGAGTGAGACCTCCGTGCCCGACCATGTAATCTGGTCG
CTGTTCAACACCCTCTTCATGAACTGCTGCCCGGGGTTCATAGCATTCGCCTACTCAGTG
AAGTCTAGGGACATGAAGATGGTTGGCGACCTGACTGGGGCCCATGTCTATGCCTTCACC
GCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGTATCATCATGACCATTCTGCTGATC
ATCATCCCAATACCGATTCTGCAAGCCTATCAGTAG
>CALJA12_47.PE3                        399 CDS /gene="ENSCJAG00000023382" /gene_family="HOG000115781" /prote
ATGAACCACATTGTCCAAACATTCTTCACTTCCATCCACACCGACTGTCCCCCCAGCTAT
GAGATACTGAAGGAGGAGCCTGAGATGGCTGTGCTGGGGGCTCCCCACAACCCTGCTCCC
CCAACATCCACTGTAATCCACATCTGCAGTGAGACCTCCATGCCCGACCATGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCTGCCTGGGTTTCATAGCATTTGCCTAC
TCCCTAAAGTCTAGGGACAGGAAGATGGTTGGTGACCTGACCAGGACCCAGGCCTATGCT
ACCACCAAGTGCCTGAACGTCTGGGCCCTGATTTTGGGCATCATGATGACCATTCTGCTG
ATCATCATCCCAGTACTCATCTTGCAAGTCTATCGATAG
>CALJA12_75.PE3                        399 CDS /gene="ENSCJAG00000013423" /gene_family="HOG000115781" /prote
ATGAACCACACTGTCCAAACCTTCTTCACTCCTGCCAATACCGTCCATCCCCCCAACTAT
GAGATACTGAAGGAGGATGATGAGGTGGCTGTTCTGGGGGTACCCCACAACCCTGCCACC
TTGACATCCACCATGATCCACATGTGCAGCAAGACCTCCATGCCCAACCGTGTTGTCTGG
CCCCTGTTCAACACCCTCTTCATGAACTCTTGCTGCCTGGGCTTCATAGTGTTAGCCTAC
TCCATGAAGTCTAGGCTGCATATGAACATGGCCCTTGACCGGGGCCCAGGCCCATGCCTC
CCTGCCAAGTGCCTGAACATCTGGGTCTTGATTTTGGGCATCATTATGACCCTTCTGCTT
ATCATCATCCCAGTACTGATCTTGCAAGTCTATCGATAG
>CALJA13_110.PE1                       402 CDS /gene="ENSCJAG00000022863" /gene_family="HOG000115781" /prot
ATGAACCACACCGTCCAAACCTTCTTCACTCCCGCCAGCACCAACCATCCCCCGAACTAT
GAGATGCTGAAGGAGGACCATGAGCTGGCTGCACTGGGGGCGCACCACAACCCTGCGCCC
CCGACATCCACCGTGATCCACATCCGAAGCGAGGCCTCCATGCCCGACCACGTCGTCTGG
TCCCTGTTCAACACCGTCTTCATGAACTCCTGCTGCCTGGGCTTCACAGCGTTCGCCCAC
TCTGTGAAGTCTAGGGACAGGAAGATGGTTGGCTACCTGACCGGGGCCCAGGCCTACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGTATCATCATGACCATTCTG
TTGATCATCATCCCAATACTGATTCTGCAAGCCTATCATTAG
>CALJA15_55.PE1                        402 CDS /gene="ENSCJAG00000023077" /gene_family="HOG000115781" /prote
ATGAACCACACGGTTCAAACCTTCTTCACTCCTGCCAGCACCAGCCGTCCCCCGAACTAT
GAGATGCTGAAGGAGGAACATGAGGTGGCTGTGCTGGGGGCACCCCACAACCCTGCACCC
CCGACATCCATCGTGATCCACATCCGAAGCGAGACCTCCATGCCCGACCACGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCTGCCTGGGCTTCATAGCGTTAGCCTAC
TCCATAAAGTCTAGGGACAGGAAGATGGTTGGCGACCTGACCGGTGCCCAGGCCTACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGTATCATCACGACCATTCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA15_99.PE7                        402 CDS /gene="ENSCJAG00000000492" /gene_family="HOG000115781" /prote
ATGAACCACACCGTCCAAAGCTTCTTCACTCCCGCCAGCACCAGCCGTCCCCCGAACTAT
GAGATGCTGAAGGAGGAACATGAGGTGGCTGCGCTGGGGGCGCCCCACAACCCTGTGCCC
CCGACATCCACCGTGATCCACATCCGAAGCGAGACCTCCGTGCCCGACCACGTCGTCTGG
TCCCTGTTCAACACCCTCTTCGTGAACTCCTGCTGCCTGGGCTTCATAGCGTTCGCCTAC
TCCGTGAAGTCTAGGGACAAGAAGATGGTTGGCGACCTGACCGGGGCCCAGGCCTACGCT
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGCATCATCACGACCAATCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA16_54.PE25                       402 CDS /gene="ENSCJAG00000021728" /gene_family="HOG000115781" /prot
ATGAACCACACGGTCCAAACCTTCTTCACTCCCGCCAGCACCAGTCGTCCCCCGAACTAT
GAGATGCTGAAGGAGGAACATGAGGTGGCTGCGCTGGGGGCGCCCCACAACCCTGCGCCC
CCGACATCCACCGTGATCCACATCCGAAGTGAGACCTCCGTGCCCGACCACGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCTGCCTGGGCTTCATAGCGTTCGCCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACATGACCGGGGCCCAGGCGTACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGTATCATCACGACCATTCTG
CTAATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA18_12.PE7                        402 CDS /gene="ENSCJAG00000023236" /gene_family="HOG000115781" /prote
ATGAGCCACACTGTCCAATCCTTCTTCACTCCCGCCAGCACCAGCCGTCCACCCAACTAT
GAGATGCTGAGGGAAGAGCATGAGGTGGCTGCGCTGGGGGTGCCCCACAACCCAGCTCCC
CTGACATCCACTGTGATCCACATCCACAGCGAGACCGCTGTGCCCGACCATGTCGTCTGG
TCCCTGTTCCACACCCTCTTCATGAACTCCTGCTGCCTGGGCTTCATAGCGTTCGCCTAC
TCTGTGAAGTCTAGGGACAGGAAGATGGTTGGTGTCCTGACCAGGGCCCAGGCCGATGCC
TCCACCGCCAAATGCCTGAAAATCTGGGCCCTGATCATGGGCATCATCATGACCATTCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAATAG
>CALJA19_31.PE20                       306 CDS /gene="ENSCJAG00000021881" /gene_family="HOG000115781" /prot
ATGAACCACACTGTCCAAACCTTCTTCACTCCCGCCAACACCGGCCTTCCCCCCAGCTAT
GAGATGCTGAAGGAGGAGCATGAGGTGGATGTGCTGGGGGCGCCCCACAACCCTGCTCTC
CCAACATCCACTGTGTTTGCCTGCTCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGTA
CTGACCGGGGCCCAGGCTGATGCCTCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATT
TCAGGCATCATTATGACCATTCTGCTGATCATCATCCCAATATTGATCTTGCAAGTCTAT
CAATAG
>CALJA1_157.PE1                        402 CDS /gene="ENSCJAG00000022537" /gene_family="HOG000115781" /prote
ATGAACCACACTGTCCAAACCTTCTTCACTCCCGCCAACACCCACCATCCCCTTAACTAT
GAGATGCCGAAGGAGGAGCAAGAGGTGGCTGCACCAGGGGTGCCCCACAACCCTGCACCC
CCAACATCCACGGTGATCTGCATCCACAGCAAGACCTCTGTGCCAGACCACGTCATCTGG
TCCCTGTTCAACACCGTCTTCATGAACTCCCTCTGCCTAGGCTTCACAGAGTTTGCCTAC
TCCATGAAGTCTAGGGACAGGAAGATGGTTGGCAACCTGACTGGGGCCCAGGCCTACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGCATCATCATGACGATTCTA
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA20_23.PE57                       393 CDS /gene="ENSCJAG00000015621" /gene_family="HOG000115781" /prot
ACAGTCCAAACCTACTTCACTCCTGCCAACACTGACTGTCCCCCCAACTATGAGATGCTG
AAGGAGGAGCATGAAGTAGATGTGCAGTGGGCACCCCCCCATAACCTGGCTCCCCCAACA
TCTACCATGATCCACATCTGCAGTGAGACCTCCATGCCCGACCATGTCGTCTGGTCCCAA
TTCAATGCCCTCTTCATGAACTTCTGCTGCCTGGGCTTCATAGCATTCACCTACTCCATC
AAATCTAGGGACAGGAAGATGGTTGGTGACCTGACCGGGGCCCAGGCCTATGCCTCTACC
GACAAGTGCCTGAACATCTGGGCCCTGATTTTGGGCATCTTCATGACCATTCTGCTTATC
ATCATCCCAGTATTGACCTTAGAAAGCTCATTG
>CALJA2_132.PE2                        402 CDS /gene="ENSCJAG00000022290" /gene_family="HOG000115781" /prote
ATGAACCACACGGTCCAAACCTTCTTCACTCCCGCCAGTACCAGCCGTCCCCCGAACTAT
GAGATGCTGAAGGAGGAACATGAGGTGGCTGCGCTGGGGGCGCCCCACAACCCTGCCCCC
CTGACATCCACTGTGATCCACATCCGAAGCGAGACCTCCGTGCCCAATCACGTGGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCTGCCTGGGCTTCATAGTGTTCGCCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGTGACCTGACCGGGGCCCAGGCCGACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGTATCATCATGACCATTCTG
CTGATCATCATCCCAATACTGATTGTGCAAGTCTATCAGTAG
>CALJA4_167.PE12                       402 CDS /gene="ENSCJAG00000022893" /gene_family="HOG000115781" /prot
ATGAACCACACTGTCCAAACCTTCTTCACTCCCGCCAGCACCAACCGTCCCCTGAACTAT
GAGATGCTGAAGGAAGAACATGAGGTGGCTGCGCTGGGAGTGCCCCACAACCCTGCACCC
CCGACATCCACGGTGATCCACATCCAAAGCGAGACCTCCGTGCCCAACCATGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCAGCCTGGGCTTCATAGCATTCACCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACCTGACCGGGGCCCAGGCCTATGCC
TCGACCGCCAAGTGCCTGAACATCTGGACCCTGATTTTGGGTATCATCATGACCGTTCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA4_46.PE6                         402 CDS /gene="ENSCJAG00000023338" /gene_family="HOG000115781" /protei
ATGAACCACACTGTCCAAACCTTCTTCACTCCCGTCAGCACCCACCGTCCCCCGAACTAT
GAGATGCTGAAGGCGGAACATGAAGTGGATGTGCTAGGGGTACCCCACAACCCTGCACCC
CCGACATCCACCATGATCCACATCCGAAGCAAGACCTCTGTGCCCAACCACGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCTGCTTGGGCTTCATAGCGTTCACCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCAACCTGACCGGGGCCCAGGCCTACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTCGGGTGTCATCATGACCATTCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA5_9.PE38                         396 CDS /gene="ENSCJAG00000023289" /gene_family="HOG000115781" /protei
ATGAACCACACGGTCCAAACCTTCTTCACTCCCGGCAGCACCAGCCGTCCCCCGAACTAT
GAGATGCTGAAGGAGGAACATGAGGTGGCTGCGCTGGGGGCGCCCCACAACCCTGCGACA
TCCACCGTGATCCACATCCGAAGCGAGACCTCCGTGCCCGACCACGTCGTCTGGTCCCTG
TTCAACACCCTCTTCATGAACTCCCGCTGCCTGGGTTTCATAGCGTTCGCCTACTCCCTG
AAGTCTAGGGACAGGAAGATGGTTGGCGACCTGACCGGGGCCCAGGCCTACGCCTCCACC
GCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGCATCATCACGACCATTCTGCTGATC
ATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJA8_101.PE11                       402 CDS /gene="ENSCJAG00000021790" /gene_family="HOG000115781" /prot
ATGAACCACGTGGTCCAAACCTTCTTCACTCCCGCCAGCACCAGCCGTCCCCTGAACTAT
GAGATGCTGAAGGAGGAACATGAGGTGGCTGCGCTGGGGGCACCCCACAACCCTGCGCCC
CCGACATCCACCGTGATCCATATCCGAAGCAAGACCTCCGTGCCCGACCACGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACTCCTGCTGCCTGGGCTTCATAGCGTTCGCCTAC
TCCGTGAAGTCTAGGGACAGGAAAATGGTTGGCGACGTGACTGGGGACCAGGCCTATGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGTATCATCACGACCATTCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CALJAACFV01202310_1.PE1               399 CDS /gene="ENSCJAG00000023323" /gene_family="HOG000115781" /pro
CGTGAACCACACTGCCAAACCTTCACTCCCGATAACACTGACCATCCCCCCAACTATGAG
ATGCTGAAGGAGGAGCAAGAGGTGGCTGCGTTGGGGGTGCCCCACAACCCTACTCCCCTG
ACATCCACCGTGATCCATATCCGTGGTGAGACCTCCGTGCCCGACCACGTCGTCTGGTTC
ATGTTCAACACCCTCTTCATGAACTCCTGCTGCCTGGGCTTCAAAGCGGTCGCCTACTCC
GTGAAGTCTAGGGACAGGAAGATGGTTGGTGACCTGACTGGGACCCAGGCCTACGCCTCC
AGCGCCAAGTGGCTGAACGTCTGGGCCCTGGTTTTGGGCATCATCATGACCATTCTGCTG
ATCATCATCCCAGTACTGATTCTGCAAGCCTATCAGTAG
>CALJAGL285293_1.PE1                   402 CDS /gene="ENSCJAG00000033369" /gene_family="HOG000115781" /pro
ATGCACCACACCGTCCAAATCTTCTTCACTCCCGCCAGCAACGACCGTCCCCCGAACTAT
GAGATGCTGAAGGAGGAGCATGAGGTGGCTGCGCTGGGGGCGCCCCACAACCCTGCGCCC
CTGACATCCACTGTGATTCACATCCGAAGCGAGGCCTCTGGGCCCAACCACGTTGTCTGG
TCCCGGTTCAACACCCTCTTCATGAACTCCTGCGGCCTGGGCTTCATAGCGTTCGCCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACCTGACCGGGGCCCAGGCCTACGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTTTGGGCATCATCATGACCATTCTG
CTGATCATCATCCCAATACTGATTCTGCAAGCCTATCAGTAG
>CAVPO218.PE34                         351 CDS /gene="ENSCPOG00000011175" /gene_family="HOG000115781" /protei
ATGCCCAAGGAGGAGCATGAGGTGGCTACGCTGGGGGGACCCCATCGCTCAGCTCCTGAG
ACTACCACTGTGATCAACATCCACAGCGACACTGCTGTGCCTGACCATGTGGTCTGGTCC
CTCTTCAACACAATCTTCATGAACATATGCTGCCTGGGCTTCATAGCCTTTGCCTTCTCC
ATAAAGTCTAGGGACAGGAAGATGGTGCATGACATGATCGGGGCCCAGAGCTACGCCTCC
ACTGCCAAGTGCCTGAACATCAGCACCCTGGTCTTGAGCATCGCCACGATCATTATCTTC
ATCATATTGTATGCTACCACCGCCATAGCAATCACCCGAAACTTGTATTAG
>CAVPO218.PE35                         405 CDS /gene="ENSCPOG00000024893" /gene_family="HOG000115781" /protei
ATGAACAACACGACCCAGACCTTCTTCTCCCAGGCCAATGTCAGCCTCTCCCCAAACTAC
GAGAGACTGCAGGAAGAACACGAGGTTTCTGTGCTTGGGGTCACCCATGGTCCGGTTCCC
CCAACATCCACTGTGATCAACATCCGCAGCGACACTGCTGTGCCTGACCATGTGGTCTGG
TCCCTCTTCAACACGATCTTCATGAACACGTGCTGCCTGGGCTTCATAGCTTTTGCCTAC
TCCATAAAGTCTAGGGACAGGAAGATGGTGGGCGATGTGATCGGGGCCCAGAGCTACGCC
TCCACTGCCAAGTGCCTGAACATCAGCGCCCTGGTCTTGAGCATCATTCTGGTCATCAGC
CTCATCTTTGTGTTTGTCTTCACCTCTGTGCAGTTGTTCACATGA
>GORGO11_1.PE16                        405 CDS /gene="ENSGGOG00000003377" /gene_family="HOG000115781" /prote
ACCATGAATCACACTGTCCAAACCTTCTTCTCTCCTGTCAACAGCGGCCAGCCCCCCAAC
TATGAGATGCTCAAGGAGGAGCACGAGGTGGCTGTGCTGGGGGCGCCCCACAACCCTGCT
CCTCCGACGTCCACCGTGATCCACATCCGCAGCGAGACCTCCGTGCCCGACCATGTCGTC
TGGTCCCTGTTCAACACCCTCTTCATGAACCCCTGCTGCCTGGGCTTCATAGCATTCGCG
TACTCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACGTGACCGGGGCCCAGGCCTAT
GCCTCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTCTGGGCATCCTCATGACCATT
CTGCTCATCGTCATCCCAGTGTTGATCTTCCAGGCCTACGGATAG
>HORSE12_34.PE10                       381 CDS /gene="ENSECAG00000000910" /gene_family="HOG000115781" /prot
ATGATCAAGGAGGAGCATGAGGTGTCCGTGCTGGGGGCACCCCAGAGCTCAGCTCCCATG
ACGACCACCGTGATCAACATCCACAGTGACACCTCCGTGCCCGACCACATCGTCTGGTCC
CTGTTCAACACGCTCTTCATGAACTGGTGCTGCCTGGGCTTCGTGGCCTTCGCCTACTCC
GTGAAGTCTAGGGACCGGAAGATGGTGGGCGACGTGACTGGGGCCCAGAGCTATGCGTCC
ACTGCCAAGTGCCTGAACATCTGGGCCCTGGTCTTGGGCCTCTTTCTGAGCACTGGATTC
ATCGTTCTTATGGGATTTACCTGCCTGACACTCTACCAGATAATTGTAAAGGCCATGCAG
GACGGCAGAGGCTACTTCTAG
>HORSE12_34.PE11                       444 CDS /gene="ENSECAG00000000968" /gene_family="HOG000115781" /prot
ATGAACCGCAGTTTCCAGACCTTTGTCAGTGGCGCCCACACTGGTGTCCCCCCGACCTAT
GAGATGCTCAAGGAGGAGCATGAGGTGTCCGTGCTGGGGGCACTCCGGAGCTCAGCTCCC
GTGACGACCACCGTGATCAACATCCACAGTGACACCTCCGTGCCCGACCACATCGTCTGG
TCCCTGTTCAACACGCTTTTCACATACTGGTGCTGCTGCCTGGGCTTCGTGGCCTTCGCC
TACTCCGTGAAGTCTAGGGACCGGAAGATGGAGGGCGACGTGACTGGGGCCCAGAGCTAT
GCGTCCACTGCCAAGTGCCTGAACATCGCTGCCCTGGTCATGGGCCTCCTCGTGATCATT
ACATTCTTCATTATTTCTTGCCTCTGGCTGACTGATCTTTTTCCACACATTTTAGCGATC
ATAATGAGTTCCAGAGACTACTAG
>HORSE12_34.PE12                       444 CDS /gene="ENSECAG00000001514" /gene_family="HOG000115781" /prot
ATGAACCGCACTTTCCAGACCTTTGTCAGTGGCGCCCACACTGGTGTCCCCCCGACCTAT
GAGATGCTCAAGGAGGAGCATGAGGTGTCCGTGCTGGGGGCACCGCAGAGCTCAGCTCCC
GTGACGACCACCGTGATCAACATCCACAGCGAGACGTCTGTGCCCGACCACATCGTCTGG
TCCCTGTTCAACACGCTCTTCATGAACTGGTGCTGCCTGGGCTTCGTGGCCTTCGCCTAC
TCCGTGAAGTCTAGGGACCGGAAGATGGTGGGCGACGTGACTGGGGCCCAGAGCTATGCG
TCCACTGCCAAGTGCCTGAACATCTGGGCCCTGGTCTTGGGCCTCTTTCTGAGCACTGGA
TTCATCGTTCTTATGGGATTTACCTGCCTGACACTCTACCAGATAATTGTAAAGGCCATG
CAGGACGGCAGAGGCTACTTCTAG
>HORSE12_34.PE13                       399 CDS /gene="ENSECAG00000001962" /gene_family="HOG000115781" /prot
ATGGACACGTCGTACCCCCGCGAGGACCCCCGGGCCCCCCGTAAGGCGGACGGCGCCGCG
CACACGGCCCTTGCGCTGGGGGCGCCGCGCTCCCCGCCTCGGGACCACCTGATCTGGTCG
GTGTTCAGCACCCTCTACCTGAACCTGTGCTGCCTCGGCTTCCTGGCGCTGGCCTACTCC
ATCAAGGCCCGAGACCAGAAAGTGGCTGGAGACTTGGAGGCAGCCCGGCGTTTCGGCTCC
AAGGCCAAGTGCTACAACATCCTGGCCGCGATGTGGGCGCTGGTGCCGCCGCTGCTGCTC
CTGGCACTGGTGGTGACTGGCGCCTTGCACCTGTCCCGGCTGGCCAAGGACTCTGCTGCC
TTCTTCAGCACCAAGTTCGACGACTCAGACTATGACTGA
>HS11.PE33                             402 CDS /gene="ENSG00000142089" /gene_family="HOG000115781" /protein_id="E
ATGAATCACACTGTCCAAACCTTCTTCTCTCCTGTCAACAGTGGCCAGCCCCCCAACTAT
GAGATGCTCAAGGAGGAGCACGAGGTGGCTGTGCTGGGGGCGCCCCACAACCCTGCTCCC
CCGACGTCCACCGTGATCCACATCCGCAGCGAGACCTCCGTGCCCGACCATGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACCCCTGCTGCCTGGGCTTCATAGCATTCGCCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACGTGACCGGGGCCCAGGCCTATGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTCTGGGCATCCTCATGACCATTCTG
CTCATCGTCATCCCAGTGCTGATCTTCCAGGCCTATGGATAG
>LOXAF198.PE8                          438 CDS /gene="ENSLAFG00000011110" /gene_family="HOG000115781" /protein
AAGAAGTGCACTTCCCAGCCCTCCTTCGGCTCACAGCACTGCTTCCCCCCAACCCAGGAG
ATGGTCAAGGAGGAGCATGAAGTGGCTGTGCTGGGGGTGCCCCACGATTCTCCACCCATG
ACGTCCACCGTGATCAACATCCGCAGCGACACCGCCGTGCCAGACCACGTCGTCTGGTCC
CTCTTCAACACGCTCTTCATGAACTGCTGCTGCCTGGGCTTCGTGGCCTTCGCCTACTCC
GTGAAGTCTAGGGACCGGAAGATGGTGGGCGACGTGACCGGGGCCCAGAGCTATGCGTCC
ACTGCCAAGTGCCTGAATGTCATTGCCCTGGTCGTCAGCCTCCTACTGACCATCGGGTTC
ATCATTCTTTTAGCCACTGGTGCGGTGGTGAGCCTCCAAGCCATTTCACAGATGTTGCAG
AACCATGGGGGCTACTAG
>LOXAF198.PE9                          408 CDS /gene="ENSLAFG00000025606" /gene_family="HOG000115781" /protein
ATGGACACGGCATACCCCCGCGAAGACCCCCGGGCCCTGGCGCCCCGCAAGGCCGAGGGC
GCCACCCACACAGCCCTCACGCTGGAGGCGCCGCGCCCCCAGCTGCCACGCGACCACATG
ATCTGGTCGGTCTTCAGCACCCTCTACCTGAACTTGTGCTGCTTCGGCTTCCTGGCGCTG
GCTCACTCCATCAAGGCCCGAGACCAGAAGGTGGCAGGGGACCTGGAGGCAGCCCGACGT
CTTGGCTCCAGAGCCAAGTGTTACAACATCCTGGCTGCTATGTGGACGCTGGTGCCGCCA
CTCCTGCTGCTGGCCCTGGTGGTGACTGGTGCCCTGCACCTGTCGCGGCTGGCCAAGGGC
TCCGCTGCCTTCTTCAGCACCAAGTTTGATGACGCAGACTATGACTGA
>LOXAF198.PE13                         372 CDS /gene="ENSLAFG00000031586" /gene_family="HOG000115781" /protei
ATGATCAAGGAGGGGCAAGAAGTGACTGTGGTGGGGGCACCCCACAATTCGGCACCCGTG
ATGTCCACTGTGATCAACATCCAGAGGGAGATCCCTGTGCCTGACCATGTCATCTGGTCC
CTCTTCAACACACTTTTCCTGAACTGGTGCTGCCTGGGCTTCTTAGCCTTCGCCTTCTCA
GTGAAGTCTAGGGACCGGAAGATGGTGGGTGATTTGACGGGGGCCCAGAGCTACGCGTCC
ACCGCCAAGCGACTGAACATCTCTGCCGTGGTCATTGGTCTCGTACTGACCATCATCACT
GTCATTCTTTTTGCAGCTCGATTAGTGATATTTTTCCACTTCCTTTTACACTCAATAAAG
AACCGTCAACAT
>MOUSE16.PE224                         426 CDS /gene="ENSMUSG00000065968" /gene_family="HOG000115781" /protei
ATGGGCCCGGCGTTGCTGAGGAAGCTGCTCCATCTCTTCAATCTCCAGCACCTGAAAGCT
CCCAACTGCCTCAAAAACCAAGAGATGCCTAAGGATCAGCATGAGGTGGTTGTAATGGGG
ACACCCCACACCTCAACTTCTTCGACAACCACCATAATCACCATGCCTGAGATCTCCAAG
CCTGATTATGTGGTCTGGTCTCTGTTCAATACACTCTTCATGAACTTCTGCTGCCTGGGT
TTCATAGCCTATGCCTACTCTGTGAAGTCTAGGGACAGGAAGATGGTGGGTGATATGACT
GGGGCCCAGGCCTTCGCCTCCACTGCCAGGTGCCTGAACATCAGCTGCCTGATCCTCTCC
GTCGTCATGGTCATCCTCTTCATCACTTTCTTTGCCACTAGAAGCTTCTACCCCCGGCTT
CCTTGA
>MOUSE7.PE3922                         435 CDS /gene="ENSMUSG00000060591" /gene_family="HOG000115781" /protei
ATGAGCCACAATTCTCAAGCCTTCTTGTCCACCAATGCCGGGCTTCCTCCAAGCTATGAG
ACAATCAAAGAGGAGTACGGGGTGACTGAGCTGGGGGAACCCAGCAACTCAGCTGTTGTG
AGGACCACCGTGATCAACATGCCCAGAGAGGTGTCGGTGCCTGACCATGTGGTCTGGTCC
CTGTTCAATACACTCTTCTTCAACGCCTGCTGCCTGGGCTTCGTTGCCTATGCCTACTCT
GTGAAGTCTAGGGACAGGAAGATGGTGGGCGATGTGGTTGGAGCCCAGGCCTACGCCTCC
ACTGCCAAGTGCCTGAATATCAGCTCCCTGATCTTCAGCATCCTTATGGTCATTATCTGC
ATCATTATTTTCTCTACCACCTCTGTGGTAGTCTTTCAGTCTTTTGCACAAAGAACACCC
CATTCTGGATTCTAG
>MOUSE7.PE3923                         321 CDS /gene="ENSMUSG00000025491" /gene_family="HOG000115781" /protei
ATGCCTAAGGAGCAGCAAGAGGTGGTTGTACTGGGGTCACCCCACATCTCAACTTCTGCG
ACAGCCACCACAATCAACATGCCTGAGATCTCCACGCCTGACCATGTGGTCTGGTCCCTG
TTCAATACACTCTTCATGAACTTCTGCTGCCTGGGCTTCGTAGCCTATGCCTACTCCGTG
AAGTCTAGGGACAGGAAGATGGTGGGTGATACGACTGGGGCCCAGGCCTTCGCCTCCACC
GCCAAGTGCCTGAACATCAGCTCCCTGTTCTTCACCATCCTCACGGCCATCGTCGTCATC
GTTGTCTGTGCCATTAGATGA
>MOUSE7.PE3924                         321 CDS /gene="ENSMUSG00000025491" /gene_family="HOG000115781" /protei
ATGCCTAAGGAGCAGCAAGAGGTGGTTGTACTGGGGTCACCCCACATCTCAACTTCTGCG
ACAGCCACCACAATCAACATGCCTGAGATCTCCACGCCTGACCATGTGGTCTGGTCCCTG
TTCAATACACTCTTCATGAACTTCTGCTGCCTGGGCTTCGTAGCCTATGCCTACTCCGTG
AAGTCTAGGGACAGGAAGATGGTGGGTGATACGACTGGGGCCCAGGCCTTCGCCTCCACC
GCCAAGTGCCTGAACATCAGCTCCCTGTTCTTCACCATCCTCACGGCCATCGTCGTCATC
GTTGTCTGTGCCATTAGATGA
>MOUSE7.PE3925                         321 CDS /gene="ENSMUSG00000025491" /gene_family="HOG000115781" /protei
ATGCCTAAGGAGCAGCAAGAGGTGGTTGTACTGGGGTCACCCCACATCTCAACTTCTGCG
ACAGCCACCACAATCAACATGCCTGAGATCTCCACGCCTGACCATGTGGTCTGGTCCCTG
TTCAATACACTCTTCATGAACTTCTGCTGCCTGGGCTTCGTAGCCTATGCCTACTCCGTG
AAGTCTAGGGACAGGAAGATGGTGGGTGATACGACTGGGGCCCAGGCCTTCGCCTCCACC
GCCAAGTGCCTGAACATCAGCTCCCTGTTCTTCACCATCCTCACGGCCATCGTCGTCATC
GTTGTCTGTGCCATTAGATGA
>MOUSE7.PE3926                         414 CDS /gene="ENSMUSG00000025492" /gene_family="HOG000115781" /protei
ATGAACCACACTTCTCAAGCCTTCATCACCGCTGCCAGTGGAGGACAGCCCCCAAACTAC
GAAAGAATCAAGGAAGAATATGAGGTGGCTGAGATGGGGGCACCGCACGGATCGGCTTCT
GTCAGAACTACTGTGATCAACATGCCCAGAGAGGTGTCGGTGCCTGACCATGTGGTCTGG
TCCCTGTTCAATACACTCTTCATGAACTTCTGCTGCCTGGGCTTCATAGCCTATGCCTAC
TCCGTGAAGTCTAGGGATCGGAAGATGGTGGGTGATGTGACTGGAGCCCAGGCCTACGCC
TCCACTGCTAAGTGCCTGAACATCAGCACCTTGGTCCTCAGCATCCTGATGGTTGTTATC
ACCATTGTTAGTGTCATCATCATTGTTCTTAACGCTCAAAACCTTCACACTTAA
>MOUSE7.PE4040                         393 CDS /gene="ENSMUSG00000045777" /gene_family="HOG000115781" /protei
ATGGCACCCACTCTGTTTCCTATGGAGTCTAAAAGCAGCAAGACTGACAGCGTTCGGGCA
TCGGGTGTCCCGCAAGCCTGCAAGCACTTAGCTGAGAAGAAGACGATGACGAACCCCACC
ACAGTCATCGAGGTCTACCCGGACACTACGGAGGTGAACGACTACTATCTGTGGTCCATC
TTCAACTTCGTCTACCTCAACTTCTGTTGCCTGGGCTTCATTGCTCTGGCCTACTCCCTC
AAAGTTCGGGACAAGAAGCTCTTGAATGACCTGAATGGAGCTGTGGAGGATGCCAAGACA
GCACGGCTGTTTAACATCACCAGTTCTGCTCTGGCAGCCTCCTGCATCATCCTTATCTTC
ATTTTCCTGCGGTACCCACTCACTGACTACTGA
>MOUSE8.PE203                          321 CDS /gene="ENSMUSG00000068631" /gene_family="HOG000115781" /protein
ATGCCTAAGGAGCAGCAAGAGGTGGTTTTACTGGGGTCACCCCACATCTCAACTTCTGCG
ACAGCCACCACAATCAACATGCCTGAGATCTCCACGCCTGACCATGTGATCTGGTCCCTG
TTCAATACACTCTTCATGAACTTCTGCTGCCTGGGCTTCATAGCCTATGCCTACTCCGTG
AAGTCTAAGGACAGGAAGATGGTGGGTGATACGACTGGGGCCCAGGCCTTCGCCTCCACC
GCCAGGTGCCTGAACATCAGCTCCCTGTTCTTCACCATCCTCATGGCCATCGTCGTCATC
GTTGTCTATGCCACTAGATGA
>ORYLA6_4.PE27                         381 CDS /gene="ENSORLG00000001737" /gene_family="HOG000115781" /protei
ATGAATTCTTACCCAAATGCACCTCTCTCTGCCCAGGATATTCCAATGAAGGGAACTCCA
CAGCATGTGTACCCGGGACAGCTTCATACCACCACAGCTGCAGGGGGTCACAACACCATT
GTCCTCCAAACTGAGCCCCCGAGGGACCACATCATCTGGTCCCTCTGCAGCTTTTTTTAC
TTCAACCCACTGTGCCTGGGACTGGCAGCTCTCATCTTCTCCATCAAGTCCAGAGACCGG
AAGGTAGTCGGAGACCTGGAAGGCGCCCGTCACTACGGCGCCACTGCTCGCTGTCTCAAC
ATTGCAGCAACCATCATAGCAAGCATCACAGTTATCATTGTCATTATTGTCTATGCTGTT
ATTGCAAGTCGACTGTCATCA
>PANTR11_1.PE19                        402 CDS /gene="ENSPTRG00000003112" /gene_family="HOG000115781" /prote
ATGAATCACACTGTCCAAACCTTCTTCTCTCCTGTCAACAGCGGCCAGCCCCCCAACTAT
GAGATGCTCAAGGAGGAGCACGAGGTGGCTGTGCTGGGGGCGCCCCACAACCCTGCTCCC
CCGATGTCCACCGTGATCCACATCCGCAGTGAGACCTCCGTGCCCGACCATGTCGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACCCCTGCTGCCTGGGCTTCATAGCATTCGCCTAC
TCCGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACGTGACCGGGGCCCAGGCCTATGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTCTGGGCATCCTCATGACCATTCTG
CTCATTGTCATCCCAGTGTTGATCTTCCAGGCCTATGGATAG
>PIG2_145.PE3                          402 CDS /gene="ENSSSCG00000014563" /gene_family="HOG000115781" /protein
ATGGACACGTCGTATCCCCGCGAGGACCCCCGGGCCCCGACGCCCCGCAAGGCCGACGGT
GCCCACACGGCCCTCACGCTGGGGGCGCCGCGACCCCCACCTCGAGACCACCTGATCTGG
TCGGTGTTCAGCACCCTCTACCTGAACCTGTGCTGCCTTGGCTTCCTGGCGCTGGCTTAC
TCCATCAAGGCCCGAGATCAGAAGGTGGCTGGAGACCTGGAGGCAGCCCGGCGTCTCGGC
TCCAAAGCCAAGTGCTACAACATCCTGGCCACCATGTGGGCATTAGTGCCACCTCTGCTG
CTCCTGGCGCTGGTGGTGACCGGCGCCCTGCACCTGTCCCGGCTGGCAAAGGGCTCCGCC
GCCTTCTTCAGCACCAAGTTCGACGACTCAGACTATGACTGA
>PIG2_145.PE4                          432 CDS /gene="ENSSSCG00000014564" /gene_family="HOG000115781" /protein
CCGTCTCTGCATCAAGAAACACTTCTCAAAGCATCTCCTCTGCCACTGACCCTGGAGATG
ATCAAGAGCCAGCACGAGATGGACGGGCTGGGGGCTCCCCAGACCTCAGCCCCCGTGGCC
ACCACGGTGATCACCATCCCCAGGGAGACCTCCGTGCCCGACCACATCGTCTGGTCCCTG
TTCAACACCCTCTTCCTGAACTGGTGCTGCCTGGGCTTCGTGGCTTTCGCCTACTCCGTG
AAGGCGAGGGACCGGAAGATGGTGGGAGACATCATTGGGGCCCAGAGCTATGCCTCCACC
GCCAAGTGCCTGAACATCTGGGCTCTGATCCTGGGCCTCATTCTGACCATCGGAGCCACT
GTTCTTCTGGTGTTTGTATACATAACAGCCTACCATATGTTAGAGCGCGCAAAGAGTAAC
AGAGGCTACTAG
>PIG2_145.PE5                          375 CDS /gene="ENSSSCG00000014565" /gene_family="HOG000115781" /protein
ATGCTCAGGGAGGAGCACGAGGTGGCCGTGCTGGGGGCTCCCCAGACCTCAGCCCCCGTG
GCCACCACGGTGATCAACATCCGAAGCGAGACCTCCGTGCCCGACCACGTCGTCTGGTCC
CTGTTCAACGCCCTCTTCATGAACTGGTGCTGCCTGGGCTTCGTGGCTTTCGCCTACTCC
GTGAAGGCGAGGGACCGGAAGATGGTGGGAGACATCATTGGGGCCCAGAGCTATGCCTCC
ACCGCCAAGTGCCTGAACATCTGGGCTCTGGTCCTGGGCATTTTTCTGACCATCGGAGCC
GTCGCTCTTCTGGTGTTTGCATACATAACAGCCTACCATATGTTAGAGCGCGCAAAGAGT
AACAGAGGCTACTAG
>PIG2_145.PE6                          381 CDS /gene="ENSSSCG00000014566" /gene_family="HOG000115781" /protein
GAGATGCTCAGGGAGGAGCACGAGGTGGCCGTGCTGGGGGCTCCCCAGACCTCAGCCCCC
GTGGCCACCACGGTGATCAACATCCGAAGCGAGACCTCCGTGCCCGACCACGTCGTCTGG
TCCCTGTTCAACGCCCTCTTCATGAACTGGTGCTGCCTGGGCTTCGTGGCTTTCGCCTAC
TCCGTGAAGGCGAGGGACCGGAAGATGGTGGGAGACATCATTGGGGCCCAGAGCTATGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCTCTGGTCCTGGGCATTTTTCTGACCATCGGA
GCCGTCGCTCTTCTGGTGTTTGCATGCATAGCAGTCTACGAGATGGCTTTACAACATGCA
AAGAGTAACAGAGGCTACTAG
>PONPY11_1.PE5                         402 CDS /gene="ENSPPYG00000002858" /gene_family="HOG000115781" /protei
ATGAACCACACTGTCCAAACCTTCTTCTCTCCTGTCAACAGCGGCCAGCTCCCCAACTAT
GAGATGCTCAAGGAGGAGCACGAGGTGGCTGTGCTGGGGGCGCCCCACAACCCTGCTCCC
CCGACATCCACCGTGATCCACATCCGCAGCGAGACCTCCGTGCCGGACCATGTTGTCTGG
TCCCTGTTCAACACCCTCTTCATGAACCCCTGCTGCCTGGGCTTCATAGCATTCGCCTAC
TCTGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACATGACCGGGGCCCAGGCGTATGCC
TCCACCGCCAAGTGCCTGAACATCTGGGCCCTGATTCTGGGCATCCTCATGACCATTCTG
CTCATCGTCATCCCAGTGTTGATCTTCCAGGCCTATCAATAG
>PROCA29874.PE1                        357 CDS /gene="ENSPCAG00000006682" /gene_family="HOG000115781" /prote
TCCCCAGCCCAGGAGATGGTCAAGGTGGAGCCCGAAGTAGCCGAGCTGGGGGTGCCCCAC
AGTTCTGCGCCCATGACATCTGTGGTGATCAACATGCCGAGTGACTATCCCGTGCATGAC
CACATCATCTGGTCACTCTTCAACACGCTTTTCATGAACTGGTTCTGCCTGGGCTTTGTG
GCCTTCTCCTATTCTGTGAAGTGTAGGGACCGGAAGATGGTGGGCGACTTGATCGGGGCC
CAGAGCCACAGCTCCATCGCCAAGTCCCTGAACATCTGCGCCCTGATCTTGGGCCTCATC
CTGACCGTCATTTTCTTGTTGCCAATATTTTGTCATATGTCACAGATCCATTTCAAT
>PROCA29874.PE2                        342 CDS /gene="ENSPCAG00000006682" /gene_family="HOG000115781" /prote
ATGGTCAAGGTGGAGCCCGAAGTAGCCGAGCTGGGGGTGCCCCACAGTTCTGCGCCCATG
ACATCTGTGGTGATCAACATGCCGAGTGACTATCCCGTGCATGACCACATCATCTGGTCA
CTCTTCAACACGCTTTTCATGAACTGGTTCTGCCTGGGCTTTGTGGCCTTCTCCTATTCT
GTGAAGTGTAGGGACCGGAAGATGGTGGGCGACTTGATCGGGGCCCAGAGCCACAGCTCC
ATCGCCAAGTCCCTGAACATCTGCGCCCTGATCTTGGGCCTCATCCTGACCGTCATTTTC
TTGTTGCCAATATTTTGTCATATGTCACAGATCCATTTCAAT
>PTEVAGS_3386.PE1                      378 CDS /gene="ENSPVAG00000014042" /gene_family="HOG000115781" /pro
CCCCAAAGCTGGATGATCACCGAGGAGCACGAAGTGGCCGTGCTGGGGGCGCCCCAGACC
TCGGGGGCCGTGACGTCCACCGTGGTCAACATCCGCAGCGAGACCGTCGTGCCCGACCAC
GTCGTCTGGTCCCTGTTCAACACCCTCTTCTTTAACCCCTGCTGCCTGGGCTTCGTGGCG
TTCGCCTACTCCGTGAAGTCTAGGGACCGGAAGATGGTGGGCGACGTGATCGGGGCCCAG
AGCTACGCTTCCACCGCCAAGTGCCTGAACGTCTGGGCCCTGGTCTTGGGCATCGTCGTC
ACCATCACTCTCATCATTTTACTGCTACCCGGCTCACTGATTGTTTTCTCAGGAATTTTA
CGATTTATAAAGTTCTGG
>PTEVAGS_3386.PE2                      366 CDS /gene="ENSPVAG00000014042" /gene_family="HOG000115781" /pro
ATGATCACCGAGGAGCACGAAGTGGCCGTGCTGGGGGCGCCCCAGACCTCGGGGGCCGTG
ACGTCCACCGTGGTCAACATCCGCAGCGAGACCGTCGTGCCCGACCACGTCGTCTGGTCC
CTGTTCAACACCCTCTTCTTTAACCCCTGCTGCCTGGGCTTCGTGGCGTTCGCCTACTCC
GTGAAGTCTAGGGACCGGAAGATGGTGGGCGACGTGATCGGGGCCCAGAGCTACGCTTCC
ACCGCCAAGTGCCTGAACGTCTGGGCCCTGGTCTTGGGCATCGTCGTCACCATCACTCTC
ATCATTTTACTGCTACCCGGCTCACTGATTGTTTTCTCAGGAATTTTACGATTTATAAAG
TTCTGG
>RAT1.PE3016                           435 CDS /gene="ENSRNOG00000014936" /gene_family="HOG000115781" /protein_
ATGAGCCACAATTCCCAAGCCTTCTTGCCCGCCAATGCCGGGCTTCCTCCAAGCTATGAG
ACAATCAAAGAGGAGTACGGGGTGACTGAGCTGGGGGAACCCAACAACTCAGCTGTCGTG
AGGACCACCGTGATCAACATGCCCAGAGAGGTCTCTGTGCCTGACCATGTGGTCTGGTCC
CTGTTCAATACGCTCTTCTTCAATGCCTGCTGCCTGGGCTTCATTGCCTATGCCTACTCT
GTGAAGTCCAGGGACAGGAAGATGGTGGGCGATGTGATTGGAGCCCAGGCCTACGCCTCC
ACTGCCAAGTGCCTGAACATCAGCTCCCTGATCTTCAGTGTCCTCATGGTCATTATCTGC
ATCATCATTTTCTCTACCACCTCTGCGGTAGTCTTTCAGTCGCTTTCACAAAGAACGCCA
CATTCTGGATTCTAG
>RAT1.PE3018                           414 CDS /gene="ENSRNOG00000015078" /gene_family="HOG000115781" /protein_
ATGAACCACACTTCTCAAGCCTTCGTGAACGCTGCCACTGGGGGACAACCCCCAAACTAC
GAAAGAATCAAGGAAGAATATGAGGTGTCTGAACTGGGGGCACCCCACGGATCGGCTTCT
GTCAGAACTACCGTGATCAACATGCCCAGAGAGGTCTCTGTGCCTGACCATGTGGTCTGG
TCCCTGTTCAATACGCTCTTCATGAACTTCTGCTGCCTGGGCTTCATTGCCTATGCCTAC
TCTGTGAAGTCTAGGGATCGGAAGATGGTGGGTGATATGACTGGAGCCCAGGCCTACGCA
TCCACTGCCAAATGCCTGAACATCAGCTCCCTGGTCCTCAGCATCCTCATGGTCATTATC
ACTATTGTTACTGTCGTCATCATTGCTCTTAATGCTCCTCGTCTCCAGACTTGA
>RAT1.PE3095                           393 CDS /gene="ENSRNOG00000020164" /gene_family="HOG000115781" /protein_
ATGGCACCCACCCTGTTTCCTATGGAGTCTAAAAGCAGCAAGACAGACAGCGTTCGGGCA
TCGGGTGTCCCGCAAGCCTGCAAGCACTTAGCTGAGAAGAAGACCATGACGAACCCCACA
ACAGTCATCGAGGTCTACCCCGACACCACAGAGGTGAACGACTACTATCTGTGGTCCATC
TTCAACTTCGTCTACCTCAACTTCTGTTGCCTGGGCTTCATTGCTCTGGCCTACTCCCTC
AAAGTTCGGGACAAGAAGCTCCTAAATGACCTGAATGGAGCCGTGGAGGATGCCAAGACA
GCACGGCTGTTTAACATCACCAGTTCTGCATTGGCAGCCTCCTGCATCATCCTCATCTTC
ATTTTCCTGCGGTACCCGCTCACTGACTACTGA
>RAT11.PE166                           411 CDS /gene="ENSRNOG00000021674" /gene_family="HOG000115781" /protein_
ATGAACCACACTTCTCAAGCCTTCATTACCGCTGCCACTGGGGGACTACCCCCAAACTAT
GAAAGAATCGAAGAAGAATATGAGGTGGCCGAACTGGGGGCACCCCACAGATCAGCTTCT
GTCAGAACTACCGTGTTCAACGTGCCCAGAGAGGTCTCTGTGCCTGACCATGTGGTCTGG
TCCCTGTTCAATACGCTCTTCATGAACTTCTGCTGCTTGGGCTTCACTGCTTATGCCTAC
TCTGTGAAGTGTAGGGATCGGCAGATGGCGGGTGATGTGACTGGAGCCCAGGCCTACGCA
TCCACTGCCAAATGCCTGAACATCAGCTCCCTGGTCCTCAGCATCCTCATGGTCGTTACC
ACTATGGTTGCTGTTGCCATCATTGCTCTTAACACTCATTGTCTTCAGACT
>RAT13.PE450                           414 CDS /gene="ENSRNOG00000042995" /gene_family="HOG000115781" /protein_
ATGAGCCACAATTCCCAAGCCTTCTTGCCCACAAATGCTGGGCTTTCTCCAAGCTATGAG
ACAAGCAAAGCTATGAGACAAGCAAAGAGGAGTACGGGGTTGACTGAGCTGGGGGAACCC
CACAACTCAGCTGTTGTGAGGACCACCGTGATCAACATGCCCAGAGAGGTGTCTGTGCCT
GACCCTGTGGTCTGGTCCCTGTTCAACACATTCTTCTTCAACTCCTGCTGCTTGGGCTTC
ATTGCCTCCGCGTACTCTGCAAAGTCCAGGGACAGGAAGATGGTGGACGACTTGATTGGA
GCCCAGGCCTACACCTCCACTGCCACGTGCCTGGACATCAGCTCCCTGATCTTCAGCATC
CTTGTGGTCGTTCTCAGCATCACTATGTCCCCTATCACCTCTTCCAGTCCTTTT
>RAT14.PE607                           405 CDS /gene="ENSRNOG00000026292" /gene_family="HOG000115781" /protein_
ATGAACCACCCTTCTCAAGTCTTTATTATTATTACCAGTGGGGGACAACCCCCAAACTAT
GAAAGAATCAAGGAAGAATATGAGGTGGCTGAGCTAGGGGCACCCCATGGATTGTCTTCT
GTCAGAACTACTGTGATCTACAAGCCCAGAGAGGTCTCTGTGCCTGACCATGTGGTGTGG
TCTGGTCCCCGTCAATACACTCTTCATGAACTTCTGCTGCCCAGAGGCTTCACTGCCTAT
GACTACTCCGTGAAGTCTATGGACCGGAAGATGGTGAGTAATGTGACTGGAGCCCAAGCC
TACGCCCCCACTACCAAGTGCCTGATCATCAGCACCCTGGTCCTCAGACTCATTATGGTC
GTTATCACTATTGTTGCTGTCATCGTCATTGCTCTCATTGCTCAT
>RAT4.PE453                            369 CDS /gene="ENSRNOG00000042681" /gene_family="HOG000115781" /protein_i
ATCAAAGAGGAGTACGGGGTGACTGGGCTGGGGGAACCCAACAGCTCAGCTGTTGTGAGG
ACCACCGCGATCAACATGTCCAGAGAGGTCTCTGTGCCTGACCATGTGATCTGGTCCCTG
TTCACTGCACTCTTCTTCAATGCCTGCTGCCTGGGCTTGATTGCTTCCGCCTACTCTGTG
AAATCCAGGGACAGGAAGATGGTGGGCGATGTGATTGGAGCCCAGGTCTGCACCTCCACT
GCCCAGTGCCCGGACATCAGCTCCCTGATCTTCAGCATCCTCATGGTGGTTCTCTGCATC
ATTATGTCTTCTACTACCTCTTTCAATCGTTTTCACAAAGAATGCCACATTCAGTATTCC
ACGGTCCAC
>SORAR139607.PE1                       321 CDS /gene="ENSSARG00000014536" /gene_family="HOG000115781" /prot
CCCACCAACTATACCATGAACAAGGAGGAGTATGAGATAGGAGAAGTTGGAGCACCCCAG
CCTTCAGCGCCTGTGACCTCCACCGTGGTCAGCATCCAGCCTGAGATCTCGGAGCCTGAC
CACATTGTCGTCCCTGTTCAATACTCTCTACTTGAATGCTGTCTGGGCTTCTTGGCTTTC
GTATATTCTGTGAAGTCTAGGGACAGGAAGATGGTTGGCGACATGATTGGGGCCCGGAGC
GTCCACTGCCAAGTGCCTGAACATCAGCACCGTGATCCTGGGCATCCTCTTCAACATTGG
AATCATCGTCTCTGTAGTGTT
>TURTRGS_3228.PE10                     405 CDS /gene="ENSTTRG00000013541" /gene_family="HOG000115781" /pro
ATGGACACGTCGTACCCCCGCGAGGACCCCCGGGCCCCGACGCCCAACAAGGCCGACGGC
ACCGCCCACACGGCCCTCACGCTGGGGGCGCCGCTACCCCCACCTCGAGACCACTTGATC
TGGTCGGTGTTCAGCACCCTCTACCTGAACCTGTGCTGCCTCGGCTTCCTGGCGCTGGCC
TACTCCATCAAGGCCCGAGACCAGAAGGTGACTGGAGATCTGGAAGCAGCCCGGCGGCTC
GGCTCCAAAGCCAAGCGCTACAACATCCTGGCCACGGTGTGGGCGCTGGTGCCGCCTCTG
CTGCTGCTGGTGCTGGTGGTGACCGGCGCCCTGCACCTGTCCCGGCTGGCCCAGGGCTCC
GCCGCCTTCTTCAGCACCAAGTTCGACGACTCAGACTATGACTGA
