>AILMEGL192575_1_2.PE6                 399 CDS /gene="ENSAMEG00000019662" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTGCAAGAG
GTGCTGAAAACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAGCACCAAATCAACCTAATCAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTGGTGGTTAAGGACTATGGCAAAGAGTCTCAGGCG
AAGGATGTCATCGAGGAATACTTTAAATGCAAGAAATGA
>AILMEGL192626_1_2.PE2                 396 CDS /gene="ENSAMEG00000019300" /gene_family="HOG000210688" /pro
CCCGAGGAAGGCCCTGCTGCCGGAGGTGTCCTGGACGTTAATACTGCTTTACAAGAGGTG
CGGAAGCCCGCCCTCACGCAGGATGGCCCACTACCGGGAATTCGCAAAAGCTGCCAGAGC
CTTCGACAAGGCCAAGCCCATCTTTGTGTGTTTGCATCCAACTGTGACGAGCCTGTGTAT
GTCCAGTTGGTGGAGGCCCTTTGTGCCGAACACCAAATCAACCTAATTAAGGTTGATGAC
AACAAGAAACGAGGGGAGAGAGGAGTGCTCTGCAGAACGGACACAGGGGGAGAGCCCCCC
GGCAAAGTGCTGGCTTGCAGCTGTGCTATAGTGAAGGACGACGGCAAAGAGTCTCAGGCC
AAGGATGTCATGGAGGAGTACTTCAAATGCGAGAAA
>AILMEGL195209_1.PE1                   399 CDS /gene="ENSAMEG00000008015" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTGCAAGAG
GTGCTGAAAACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAGCACCAAATCAACCTAATCAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTGGTGGTTAAGGACTATGGCAAAGAGTCTCAGGCG
AAGGATGTCATCGAGGAATACTTTAAATGCAAGAAATGA
>ANOCA35_6.PE1                         399 CDS /gene="ENSACAG00000010479" /gene_family="HOG000210688" /protei
ATGGCCGAGTCCAACATTGCTGCTGGAGGTATAATGGATGTCAACACCGCCCTTCAAGAA
GTGCTGAAGACCGCACTCATCCACGATGGATTGGGCCGTGGAATTCGTGAAGCTGCCAAA
GCCTTAGACAAACGCCAAGCCCATCTTTGTGTTCTTGCATCCAATTGCAACGAGCCTATG
TATGTCAAACTGGTTGAAGCCCTTTGTGCTGAACATCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAGCTGGGAGAGTGGGTAGGCCTCTGCAAGATCGACAGAGAAGGAAAACCC
CGCAAAGTTGTGGGCTGCAGTTGTGTGGTTGTGAAAGACTATGGCAAAGAATCTCAGGCT
AAAGATGTCATCGAAGAGTACTTCAAGTGCAAGAAATGA
>ANOGA_100.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_101.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_102.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_103.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_104.PE739                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_105.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_106.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_107.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_108.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_109.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_110.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_111.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_112.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_113.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_114.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_115.PE739                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_116.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_117.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_118.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_119.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_120.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_121.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_122.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_123.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_124.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_125.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_126.PE739                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_127.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_128.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_129.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_130.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_131.PE740                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_132.PE739                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_133.PE737                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_134.PE734                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_135.PE737                       414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_81.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_82.PE739                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_83.PE735                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_84.PE722                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_85.PE739                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_86.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_87.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_88.PE730                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_89.PE739                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_90.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_91.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_92.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_93.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_94.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_95.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_96.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_97.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_98.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ANOGA_99.PE740                        414 CDS /gene="AGAP011077" /gene_family="HOG000210688" /protein_id="A
ATGTCCGACGTCGAAGTTGAAGCCCCGAGTGCGCCCGTCGATGGCTCGATGGATGTCAAC
ACCGCCCTCCAGGAGGTGCTCAAGAAGTCGCTGATCGCCGACGGACTGGTGCACGGTATT
CACGAAGCGTGCAAGGCGCTCGACAAACGCCAGGCCGTGCTGTGCATTCTGGCCGAGAGC
TGCGACGAGCCGCAGTACAAGAAGCTGATCACGGCCCTGTGCAACGAGCACCAGATTCCA
CTGATCCGTGTCGATTCCAACAAGAAGCTCGGCGAATGGTCCGGCCTGTGCAAGATTGAC
AAGGAAGGCAAGCCCCGAAAGATTTGCGGCGCCTCCTGCGTCGTGCTGAAGGATTTCGGA
GAGGAGACTCCAGCCCTCGACGTCATCAAGGAGCACCTTCGGCAGACAGCCTAA
>ARALY_2.PE55                          423 CDS /gene="Al_scaffold_0002_50" /gene_family="HOG000210688" /protei
ATGTCTGGTGATGCGGCTGTTGTTGCTCCGGTTGTTGAGGCAGCAGTGATCCCAGAGGAC
ATGGATTTAATGACTGCAGCGGAGTTGACAATTAGGAAATCTTGTGCTTATGGTGGTGTT
GTTCGTGGTCTCCATGAAAGCACTAAGCTTATTGAGAAGCGTGTTGCTCAGCTCTGTGTC
TTGGCTGAAGATTGCAACCAACCTGATTATGTCAAGCTGGTTACAGCTCTTTGCACTGAC
CACAACATCAATTTGCTTACGGTTCCCAGTGCCAAAACACTCGGTGAATGGGCTGGTCTT
TGCAAGCTTGATTCAGAGGGCAATGCGAGGAAGGTTGTTGGATGCTCATGTCTTGTGGTC
AAGGATTACGGTGAGGAGACTACTGCACTAAACATTGTCAAGAAGCATCTTGAATCTAAC
TAA
>ARATH_2.PE3240                        435 CDS /gene="AT2G32060" /gene_family="HOG000210688" /protein_id="AT
ATGTCAGGTGATGAGGCTGTTGCTGCTCCTGTGGTTCCTCCTGTTGCTGAGGCAGCAGTG
ATCCCAGAGGACATGGATGTGAGTACTGCATTGGAGTTGACTGTAAGGAAATCTCGTGCT
TATGGTGGTGTTGTTCGTGGTCTCCATGAAAGCGCTAAGCTTATTGAGAAGCGTAATGCT
CAGCTCTGTGTCCTGGCTGAAGATTGCAACCAACCTGATTATGTCAAGCTTGTTAAAGCT
CTTTGCGCTGACCACAGCATCAAATTGCTTACTGTTCCAAGTGCCAAAACACTCGGCGAA
TGGGCTGGTCTTTGCAAGATTGATTCTGAGGGCAATGCAAGGAAGGTTGTTGGATGCTCA
TGTCTCGTGATCAAGGATTTCGGTGAGGAGACAACTGCACTAAACATTGTCAAGAAGCAT
CTTGATTCTAACTAA
>ARATH_2.PE3241                        435 CDS /gene="AT2G32060" /gene_family="HOG000210688" /protein_id="AT
ATGTCAGGTGATGAGGCTGTTGCTGCTCCTGTGGTTCCTCCTGTTGCTGAGGCAGCAGTG
ATCCCAGAGGACATGGATGTGAGTACTGCATTGGAGTTGACTGTAAGGAAATCTCGTGCT
TATGGTGGTGTTGTTCGTGGTCTCCATGAAAGCGCTAAGCTTATTGAGAAGCGTAATGCT
CAGCTCTGTGTCCTGGCTGAAGATTGCAACCAACCTGATTATGTCAAGCTTGTTAAAGCT
CTTTGCGCTGACCACAGCATCAAATTGCTTACTGTTCCAAGTGCCAAAACACTCGGCGAA
TGGGCTGGTCTTTGCAAGATTGATTCTGAGGGCAATGCAAGGAAGGTTGTTGGATGCTCA
TGTCTCGTGATCAAGGATTTCGGTGAGGAGACAACTGCACTAAACATTGTCAAGAAGCAT
CTTGATTCTAACTAA
>ARATH_2.PE3242                        435 CDS /gene="AT2G32060" /gene_family="HOG000210688" /protein_id="AT
ATGTCAGGTGATGAGGCTGTTGCTGCTCCTGTGGTTCCTCCTGTTGCTGAGGCAGCAGTG
ATCCCAGAGGACATGGATGTGAGTACTGCATTGGAGTTGACTGTAAGGAAATCTCGTGCT
TATGGTGGTGTTGTTCGTGGTCTCCATGAAAGCGCTAAGCTTATTGAGAAGCGTAATGCT
CAGCTCTGTGTCCTGGCTGAAGATTGCAACCAACCTGATTATGTCAAGCTTGTTAAAGCT
CTTTGCGCTGACCACAGCATCAAATTGCTTACTGTTCCAAGTGCCAAAACACTCGGCGAA
TGGGCTGGTCTTTGCAAGATTGATTCTGAGGGCAATGCAAGGAAGGTTGTTGGATGCTCA
TGTCTCGTGATCAAGGATTTCGGTGAGGAGACAACTGCACTAAACATTGTCAAGAAGCAT
CTTGATTCTAACTAA
>ASFUM1_1.PE495                        435 CDS /codon_start=1 /gene_family="HOG000210688" /evidence="3: Infe
ATGTCCAACCCCCCCGTTGCCGCTGCCGATGAGGTCGAGGTTTCCGCTGATGCCGGCGCC
GGCGGTCAGATGTCCGTCCTCGATGCTCTGAAGGGTGTCCTCCGCATTGCTCTGATCCAC
GACGGTCTTGCCCGTGGTCTCCGCGAGGCCGCCAAGGCCCTCGACCGCCGCCAGGCTCAC
ATGTGTGTCCTCAACGAGGGCTGCGAGGAGGAGGCCTACAAGAAGCTCGTCATTGCTCTG
TGCTCTGAGCACAAGATCCCCCTCATCAAGGTCCCCGATGGAAAGATGCTGGGCGAGTGG
GTCGGTCTCTGCCAGCTTGACCGTGAGGGTAACGCCCGCAAGGTCGTCAACTGCTCGTGC
GTTGTCGTCAAGGACTGGGGTGAGGAGTCCCAGGAGCGCTCCGTCCTCCTCAACTACTTC
CAGACTGAGCAATAA
>ASPCL_38.PE1109                       435 CDS /gene="CADACLAG00002887" /gene_family="HOG000210688" /protei
ATGTCCAACCCCCCCGTTGCCGCTGCCGATGAGGTCGAGGTTAGCGCCGATGCCGGTGCT
GGCGGCCAGATGTCCGTCCTCGACGCTCTCAAGGGTGTCCTCCGCATCTCGCTGATCCAC
GATGGTCTTGCCCGTGGTCTGCGCGAGGCCGCCAAGGCCCTCGACCGCCGCCAGGCCCAC
ATGTGTGTCCTCAACGAGGGCTGCGAGGAGGAGGCTTACAAGAAGCTGGTCATTGCCCTG
TGCTCCGAGCACAAGATCCCCCTCATCAAGGTTCCCGATGGAAAGATGCTGGGCGAGTGG
GTTGGTCTTTGCCAGCTCGACCGTGAGGGTAACGCTCGCAAGGTCGTCAACTGCTCTTGC
GTCGTTGTCAAGGATTGGGGAGAAGAGTCCCAGGAGCGCTCCGTCCTCCTCAACTACTTC
CAGACCGAGCAGTAA
>ASPFC_1.PE574                         435 CDS /gene="CADAFUBG00000586" /gene_family="HOG000210688" /protein_
ATGTCCAACCCCCCCGTTGCCGCTGCCGATGAGGTCGAGGTTTCCGCTGATGCCGGCGCC
GGCGGTCAGATGTCCGTCCTCGATGCTCTGAAGGGTGTCCTCCGCATTGCTCTGATCCAC
GACGGTCTTGCCCGTGGTCTCCGCGAGGCCGCCAAGGCCCTCGACCGCCGCCAGGCTCAC
ATGTGTGTCCTCAACGAGGGCTGCGAGGAGGAGGCCTACAAGAAGCTCGTCATTGCTCTG
TGCTCTGAGCACAAGATCCCCCTCATCAAGGTCCCCGATGGAAAGATGCTGGGCGAGTGG
GTCGGTCTCTGCCAGCTTGACCGTGAGGGTAACGCCCGCAAGGTCGTCAACTGCTCGTGC
GTTGTCGTCAAGGACTGGGGTGAGGAGTCCCAGGAGCGCTCCGTCCTCCTCAACTACTTC
CAGACTGAGCAATAA
>BOVIN11_40.PE6                        399 CDS /gene="ENSBTAG00000024019" /gene_family="HOG000210688" /prote
ATGGCTGAAGAAGGCATTGTTGCTGGAGGTGTAATAGACATTAATCCTGCTTTACAAGAG
GTGCTGAAGACCATCGTCATCCATGATGGCCTGGCACGTGGAACTCACAAAGCTGCCAAA
CCCTTAGACAAGTGCCAAGTCCATCTTTGCATGCTTCCATCCAACTGTGATGAGCCTCTA
TGCACACGAACTGGTGGAGGCCTCTGTGCTATACACCAAATCAATGCAATTAGGGCTGAT
GACAACAAGAAACTACGGGAATGGGTTGTTGTTGTTGTTGTTGAGGAATGGGGAAAACCC
AGTAAAGTGGTTGGTTGCATCTATGTGGTAGGTAAGGACTATGGCAAAGAGTCTCAGGCA
CATGATGCCATCAAGGAGTACTTCAGATGCAAGAAATGA
>BOVIN6_65.PE6                         405 CDS /gene="ENSBTAG00000002550" /gene_family="HOG000210688" /protei
ACTGCCGTGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATAGACGTCAATACTGCTCTG
CAAGAGGTGCTGAAGACTGCGCTCATCCACGATGGCTTAGCACGTGGAATTGGCGAAGCT
GTGAAAGCTTTAGACAAGCGCCAAGCCCATCTACGTGTGCTTGCATCCAACCGTGATGAG
CCCATGTATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAGCATCAAATCAACCTGATTAAG
GTAGATGACAACAAGAAACTAGGGGAATGGGTAGGCCTCAAATTGACAGAGAGGGAAAAC
CCCGTAAAGTGGTTTGGTTGCAGTTGTTTGGTGGTTAAGGACTATGGCAAAGAATCTCAG
GCCAAGGATGTCATCGAGGAGTACTTCAAATGTTCATACAATGTC
>BOVIN9_75.PE23                        399 CDS /gene="ENSBTAG00000001360" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTCTGCAAGAG
GTACTGAAGACCGCCCTCATCCACGATGGCTTAGCACGTGGAATTCGCGAAGCTGCGAAA
GCTTTAGACAAGCGCCAAGCCCATCTGTGTGTGCTCGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAGCATCAAATCAACCTGATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCT
CGTAAAGTGGTTGGTTGCAGTTGTGTGGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>CAGLA1_10.PE305                       429 CDS /evidence="3: Inferred from homology " /gene_family="HOG0002
ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAGTTGTTGAACAAACCGCTGAA
GTTTCTATTGAAGATGCTTTGAAGGTTGTCTTGAGAACCGCTTTGGTCCACGATGGTTTG
GCCAGAGGTTTGAGAGAATCCACCAAGGCTTTGACCAGACACGAAGCTCAATTGGTTGTC
TTGGTCTCCTCTGTCACCGAAGACAACATCATCAAGTTAGTCGAAGGTTTGGCTAACGAC
CCAAACAACAAGGTTCCATTGATCAAGGTTGCTGACGCTAAGCAATTGGGTGAATGGGCT
GGTCTAGGTAAGATCGACCGTGACGGTAACGCCAGAAAGGTTGTCGGTGCCTCCGTTGTT
GTTGTCAAGAAGTGGGGTGCTGAAACTGATGAACGTAACATGATCTTGGAACACTTCTCC
CAACAATAA
>CALJA14_46.PE4                        396 CDS /gene="ENSCJAG00000031287" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGCTGCTAGAGGTGTAATGGATGTTAATACTGATTTACAAGAG
ATGAAGACTGCCCTCATCCTTGATGGCCTAGCATGTGGAATTCGCAAAGCTGCCAAAGCC
TTTGACAAGCACCAAACCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATGTAT
GTCAGGTTGGTGGAGACCCTTTGTGCCGAACACCAAATCAACCTAATTAAGGTTGATGAC
AACGAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAACTGACAGAGAGGGGAAGCCCGGT
AAAGTGATTGGTTGCAGTTGTATAGTAGTTAAGGACTATGGCAAGGAGTCTCAGGCCAAG
GATGTCATCAAAGAGTACTTCAAATGCAAGAAATAA
>CALJA4_140.PE11                       399 CDS /gene="ENSCJAG00000002865" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAGATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAGCCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAGGAGTCTCAGGCC
AAGGATGTCATCGAAGAGTACTTCAAATGCAAGAAATGA
>CANFA1_30.PE2                         399 CDS /gene="ENSCAFG00000000190" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAATAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGAAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTGGTGGTTAAGGACTATGGCAAAGAATCTCAGGCG
AAAGATGTTATCGAGGAATACTTCAAATGCAAGAAATGA
>CAVPO20_22.PE13                       393 CDS /gene="ENSCPOG00000001609" /gene_family="HOG000210688" /prot
ACGGACGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACATCAATACTGCTTTACAAGAG
GTGCTGAAGACCACGTTCATCCACGATGGCCTAGCATGTGGCATTCAGGAAGCTGCCAAA
GCCTTAGACAAACGCCAAGCTCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCCATG
TATGTAAAGCTAGTGGAGGCCCTTTGTGCTGAACACCAGATCAACCTCATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTGGTCCTCTGTAAAACTGACCGAGAGGGGAAACCC
CGCAAAGTGGTGGGTTGCAGTTACGTGGTGGTTAAGGACTACGGCAAAGAATCTCAGGCC
AAGGATGTCATTGAAGAATATTTTAAACGCAAG
>CAVPO68_1.PE5                         402 CDS /gene="ENSCPOG00000000429" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTCAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGCGGCATCCGCGAAGCTGCCAAA
GCCTTAGACAAACGCCAAGCTCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCCATG
TATGTAAAGTTAGTGGAGGCCCTTTGTGCTGAACACCAGATCAACCTCATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACCGAGAGGGGAAACCC
CGCAAAGTGGTTGGTTGCAGTTGTGTGGTGGTTAAGAAGGACTACGGCAAAGAATCTCAG
GCCAAGGATGTAATTGAAGAATACTTTAAATGCAAGAAATGA
>CHICK3.PE929                          399 CDS /gene="ENSGALG00000013990" /gene_family="HOG000210688" /protein
ATGGCCGAGGAAGGCATTACTGCTGGAGGTGTAATGGATGTTAACACCGCCCTCCAAGAA
GTGCTGAAGACCGCACTTATCCATGATGGCCTCGCTCGTGGTATTCGTGAAGCAGCCAAA
GCCTTGGACAAGCGCCAAGCCCATCTCTGTGTCCTGGCTTCAAATTGTGATGAGCCCATG
TATGTAAAGCTAGTTGAAGCACTTTGTGCAGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAAAAGCTGGGTGAATGGGTAGGACTCTGCAAGATCGACAGAGAAGGGAAACCT
CGCAAAGTTGTGGGCTGCAGTTGTGTGGTTGTCAAAGATTATGGCAAGGAATCTCAGGCC
AAAGATGTCATCGAAGAGTACTTCAAGTGCAAGAAATGA
>DANRE23_33.PE20                       399 CDS /gene="ENSDARG00000036875" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATCGCTGCCGGAGGTGTGATGGATGTCAACACCGCTCTGCCTGAA
GTGCTGAAGACCGCACTCATCCACGACGGTCTGGCCCGCGGTATCCGTGAGGCCGCCAAG
GCCCTCGACAAGCGCCAGGCTCATCTTTGCGTCCTCGCTGCAAACTGTGACGAGCCCATG
TACGTCAAGCTGGTGGAGGCTCTCTGTGCCGAGCATCAGATCAACCTCATCAAGGTTGAT
GACAATAAGAAGCTCGGGGAATGGGTTGGTCTGTGTAAGATCGACAGAGAGGGCAAACCC
CGCAAGGTGGTGGGCTGCAGCTGTGTAGTCATCAAGGACTACGGCAAAGAGTCCCAGGCT
AAGGACGTCATTGAAGAGTACTTCAAATCCAAGAAATAA
>DASNOGS_1887.PE1                      399 CDS /gene="ENSDNOG00000006214" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGTTGCTGGAGGTGTAATGGACGTCAACACTGCATTACAAGAG
GTGCTAAAAACTGCCCTCATCCACGATGGCCTAGCACGTGGGATCCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCCTCCAACTGTGATGAACCCATG
TATGTCAAGCTGGTGGAGGCCCTTTGTGCTGAGCACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGCGAATGGGTAGGCCTCTGTAAAATCGACAGAGAGGGCAAACCC
CGAAAAGTAGTTGGCTGCAGTTGTGTGGTTGTTAAGGATTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAAGAATATTTTAAATGCAAGAAATGA
>ECHTE164599.PE1                       399 CDS /gene="ENSETEG00000011025" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAACAGTGCTTTACAAGAG
GTTCTGAAGACCGCCCTCATCCACGATGGCCTAGCGCGTGGAATTCGCAAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCTCATCTTTGTGTGCTTGCATCCAACTGTGATAAGCCTATG
GATGTCAAGTTAGTGGAGGCCCTGTGTGCTGAACACCAAACCAACCTCAGTAAGGTTGAT
GACAACAAGAAACTAGGAGAGTGGGTAGGCCTCTGCAAAACTGATAGAGAAGGAAAACCC
CGGAAAGTGGTTGGTTGCAGTTGTGTGGTTGTTAAGGACTATGGCAAAGAATCTCAAGCC
AAGGATGCTATTGAAGAATACTTTAAATGCAAAAAATGA
>ECHTE318212.PE1                       399 CDS /gene="ENSETEG00000006854" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAACACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCTCATCTTTGTGTGCTCGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTAGTGGAGGCCCTGTGTGCTGAACACCAAATCAACCTCATTAAGGTTGAT
GACAACAAGAAACTAGGAGAGTGGGTGGGCCTTTGCAAAATTGACCGAGAAGGAAAACCC
CGGAAAGTGGTTGGTTGCAGTTGTGTGGTTGTTAAGGACTATGGCAAAGAATCTCAAGCC
AAGGATGTTATTGAAGAATACTTTAAATGCAAAAAATGA
>ERIEU262478.PE1                       399 CDS /gene="ENSEEUG00000008421" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTGAATACCGCTCTCCAAGAG
GTGCTGAAGACCGCCCTCATTCACGATGGCCTAGCACGCGGCATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTAATGAGCCTGTG
TATGTCAAGTTGGTAGAGGCCCTCTGTGCTGAACACCATGTCAACCTAATTAAGGTTGAT
GACAACAAGAAGCTTGGAGAATGGGTAGGCCTCTGTAAAACTGACAGAGAGGGCAAACCT
CGTAAGGTCGTGGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAAAATGTCATCGAGGAATACTTCAAATGCAAGAAATAA
>ERIEUGS_9000.PE2                      393 CDS /gene="ENSEEUG00000011083" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGCCATTGCTGCTGGTGGTGTGATGGACGTGAATACCGCTCTCCAAGAG
GTGAGGAAGACCGCCCTCATTCAGGAGGGCCTAGCACGCCGCATTAGCGAAGCTACCAAA
GCCTTAGACCGCCAAGCCCACCTTTGTGTGCTTGCATCCAACTATAATGAGCCTATGTAT
GTCAAGTTGATAGAGGCCATCTGTGCTGAACACCAGGTCAACCTAATTAAGGTTGATGAC
AAGAAACTTGGAGAAAGGGTAGGCCTCTGTAAAACTGACAGAGAGGGCAAACCTCCTAAG
GTCATTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAAGAATCTCAGACCAAAGAT
GTCATCAAGGAATACTTCAAATGCAAGGAATGA
>FUGRU72_1.PE13                        399 CDS /gene="ENSTRUG00000004877" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCGTTGCTGCTGGAGGTGTCATGGATGTCAACACTGCTCTCCCAGAA
GTGCTGAAGACTGCCCTCATCCACGATGGCCTTGCCCGCGGTATCCGCGAAGCTGCCAAG
GCTCTAGACAAGCGTCAGGCCCATCTGTGCGCCCTTGCTGCCAATTGTGACGAGCCCATG
TACGTCAAGCTGGTGGAGGCCCTCTGCGCTGAGCATCAGATCAACCTGATAAAGGTCGAT
GACAACAAGAAGCTTGGCGAGTGGGTCGGGCTGTGCAAGATCGACCGTGAGGGCAAACCC
CGCAAGGTGGTGGGCTGCAGCTGCGTCGTAGTCAAGGATTATGGCAAGGAGTCACAGGCC
AAGGACGTGATTGAGGAGTACTTCAAGAGCAAGAAATAA
>GORGO4_73.PE2                         402 CDS /gene="ENSGGOG00000025776" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGTATTGCTGCTGGAAGTGTAATGGACGTTAATACTGCTTTACAGGAG
GTGCTGAAGACTGCCCTCATCCACGATTGCCTAGCACGTGGAATTCACGAAGCTACCAAA
GGCTTAGACAAGCACCAAGCCCACCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTGTG
ATGTATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTT
GATGACAACAAGAAACTAGGGGAAAGGGTAGGCCTCTGTAAAACTGACAGAGAGGGGAAG
CCTCATAAAGTGGTTGGTTGCAGTTGTGCAGTAGTTAAGGACTATGGCAAGGAGTCTCAG
GCCAAGGATGTCATCGAAGAGTACTTCAAATGCAAGAAATGA
>GORGO6_139.PE3                        399 CDS /gene="ENSGGOG00000012234" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGTTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTTCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTTTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAGGAGTCTCAGGCC
AAGGATGTCATCGAAGAGTATTTCAAATGCAAGAAATGA
>HORSE23_40.PE6                        396 CDS /gene="ENSECAG00000006417" /gene_family="HOG000210688" /prote
GCCCTGGAAGGCATCGCTGCTGGAGGTGTAATGGACGTCAACGGCACCTTCCAAGAGGAG
CTGAAGACCGCCCTCATCCACGACGGCCTGCCACACCGGATCCGCGAAGCTGCCAAGGCC
CTAGACAAGCGCCAAGCTCATCTTTGTGTGCTTGCATCCAACTGCGACGAGCCTGTGTAT
GTGAAGTCGGTGGAGGTCCTTTGTGCCCAACACCAGATCAGCCTGATTAAGGTTGATGAC
AACAAAAAACTAGGGGAATGGGCAGGCCTCTGCAAAACTGACCGAGGGGGAATGCCCCAG
AAAGTGGCTGGTTGCAGTTGTGTAGTGGCGAAGGACTATGGCAAAGAGTCTCAGGCCAAG
GATGTCATCGAGGAGTACTTCAAATGTAAGAAATGA
>HS6.PE3671                            399 CDS /gene="ENSG00000112306" /gene_family="HOG000210688" /protein_id="
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTTCTGAAGACTGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTTTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAGGAGTCTCAGGCC
AAGGATGTCATTGAAGAGTATTTCAAATGCAAGAAATGA
>KLLAC1_7.PE10                         405 CDS /evidence="3: Inferred from homology " /gene_family="HOG000210
ATGTCTGACGTTGAAGAAGTCCAACAAGTCCCAGTCGCTGAATTGACCATCGAAGATGCC
CTAAAGGTCGTCTTGAGAACCTCTTTGGTTCACGATGGTTTGGCCAGAGGTTTGAGAGAA
TCTGCCAAGGCTTTGACCAGAGGTGAAGGTCAACTAGCTGTTTTGGTTGAATCGGTTACT
GAAGAAGCCATCAGCAAGTTGGTCCAAGGTTTGGCCACTGAAAACAACGTTCCATTAATC
AAGGTTGCTGATGCCAAGCAATTAGGTGAATGGGCCGGTTTGGGTAAGATCGACCGTGAC
GGTAACGCCAGAAAGGTCGTCGGTGCTTCCGTTGTTGTTGTTAAGAACTGGGGTGCTGAC
ACCCAAGAAAGAGAAATTCTTTTGGAACATTTCAGCCAACAATAA
>LACTH_4.PE26                          438 CDS /locus_tag="KLTH0D00792g" /gene_family="HOG000210688" /old_locu
ATGTCTGACGTTGAAGAAGTCCAAGAGGTCCAAGAGATCCAAGAAGTTGCTGTTGAGCAA
CCAACCGAGTCCATCACCATCGAAGATGCCTTGAAGGTCGTCTTGAGAACCTCTTTGGTT
CACGATGGTTTGGCCAGAGGTTTGAGAGAATCTGCCAAGGCTTTGACCAGAGGTGAGGCC
CAATTGGTCGTCTTGGTTGACTCTGTCACCGAGGACAACATCATCAAGCTGGTGGAGGGT
TTGGCCAACGACCCAGAGAACAAGGTTCCTTTGATTAAGGTCGCCGACGCCAAGCAATTG
GGTGAGTGGGCCGGTTTGGGTAAGATCGACCGTGAAGGTAACGCCAGAAAGGTTGTTGGT
GCTTCCGTTGTTGTTGTCAAGAACTGGGGTGCTGACACCGAAGAGCGTCAAATGATCTTG
GAACACTTCTCTCAATAA
>LEDON1_13.PE45                        426 CDS /transl_table=1 /gene_family="HOG000210688" /locus_tag="LDBPK
ATGGCTGAGGAAACCGTCCGTGTTGAAGTCCCTGCGGTAGAGGAGAACGTCGTGGTTGAT
GTCGCGCCGGAAAGCCTGGAGGATGCCGTCCGTATTGTGATCCAGAAGGCGCTCGAGGCC
AATGGCCTCGTCCGCGGCCTCTCTGAGGTGGCCCGCACCCTGGACTGCAAGACGGCGCAC
ATGTGCATTCTCGCTGATGACTGCGAGGATGAGGAGTACAAGAAGCTTGTCACCGCGCTC
GCCAAGCAGGGCAACATCGATCTGATCAACGTCGAGGAGCGCGAGAAGCTCGCCCAGTGG
GCCGGCCTCGTGCGCCGCGATGTGGCCGGTGAGGTGACCAAGACTCTCAAGTGCTCCTCT
GTCGCCATTCGCGACTTCGGTGAGCGCACTAAGGCTCTGGACTACTTGCTGTCTCAGCTG
CACTAA
>LEINF1_13.PE50                        426 CDS /locus_tag="LinJ13.0500" /gene_family="HOG000210688" /codon_s
ATGGCTGAGGAAACCGTCCGTGTTGAAGTCCCTGCGGTAGAGGAGAACGTCGTGGTTGAT
GTCGCGCCGGAAAGCCTGGAGGATGCCGTCCGTATTGTGATCCAGAAGGCGCTCGAGGCC
AATGGCCTCGTCCGCGGCCTCTCTGAGGTGGCCCGCACCCTGGACTGCAAGACGGCGCAC
ATGTGCATTCTCGCTGATGACTGCGAGGATGAGGAGTACAAGAAGCTTGTCACCGCGCTC
GCCAAGCAGGGCAACATCGATCTGATCAACGTCGAGGAGCGCGAGAAGCTCGCCCAGTGG
GCCGGCCTCGTGCGCCGCGATGTGGCCGGTGAGGTGACCAAGACTCTCAAGTGCTCCTCT
GTCGCCATTCGCGACTTCGGTGAGCGCACTAAGGCTCTGGACTACTTGCTGTCTCAGCTG
CACTAA
>LEMAJ1_13.PE57                        426 CDS /transl_table=1 /gene_family="HOG000210688" /locus_tag="LMJF_
ATGGCTGAGGAAACCGTCCGTGTTGAAGTCCCTGCGGTAGAGGAGAACGTCGTGGTTGAT
GTCGCCCCGGAAAGCTTGGAGGATGCCGTCCGTATTGTGATCCAGAAGTCGCTCGAGGCC
AATGGCCTCGTCCGCGGCCTCTCTGAGGTGGCCCGCACCCTGGACTGCAAGACGGCGCAC
ATGTGCATTCTGGCTGATGACTGCGAGGATGAGGAGTACAAGAAGCTTGTCACCGCGCTC
GCCAAGCAGGGCAACATCGATCTGATCAACGTTGAGGAGCGCGAGAAGCTCGCCCAATGG
GCCGGCCTCGTGCGCCGCGATGTGGCCGGTGAGGTGACCAAGACTCTCAAGTGCTCCTCG
GTCGCCATTCGCGACTTCGGTGAGCGCACCAAGGCTCTGGACTACCTGCTGTCTCAGCTG
CACTAA
>LEMEX1_13.PE47                        426 CDS /transl_table=1 /gene_family="HOG000210688" /locus_tag="LMXM_
ATGGCTGAGGAAACCGTCCGTGTTGAAGTCCCTGCGGTAGAGGAGAACGTCGTGGTTGAT
GTCGCCCCGGAAAGCCTGGAGGATGCCGTCCGCATTGTGATCCAGAAGGCGCTTGAGGCC
AACGGCCTCGTCCGCGGCCTCTCTGAGGTGGCCCGCACGCTGGACTGCAAGACGGCGCAC
ATGTGCATTCTGGCTGATGACTGCGAGGATGAGGAGTACAAGAAGCTCGTCACCGCGCTC
GCCAAGCAGGGCAACATTGATCTGATCAACGTTGAGGAGCGCGAGAAGCTCGCCCAGTGG
GCCGGCCTCGTGCGCCGCGATGTGGCCGGTGAGGTGACGAAGACTCTCAAGTGCTCCTCT
GTCGCCATTCGTGACTTCGGTGAGCGCACTAAGGCTCTGGACTACCTGCTGTCTCAGTTG
CACTAA
>LOXAF0_28.PE1                         399 CDS /gene="ENSLAFG00000007933" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAACACCGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATCCGCGAAGCTGCCAAA
GCCTTAGACAAGCGTCAAGCCCATCTTTGTGTGCTTGCGTCCAACTGTGATGAGCCTATG
TATGTCAAGTTAGTAGAGGCCCTTTGTGCTGAACACCAAATCAACCTGATCAAGGTTGAT
GACAACAAGAAACTAGGGGAGTGGGTAGGCCTCTGCAAAATTGACAGAGAGGGAAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTGGTTGTTAAGGACTATGGCAAAGAATCACAGGCC
AAGGATGTCATCGAAGAATATTTCAAATGCAAGAAATAA
>MACEUGS_2678.PE1                      399 CDS /gene="ENSMEUG00000004285" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTGAACACCGCTCTCCAAGAA
GTGCTGAAGACCGCGCTCATCCACGACGGCCTAGCTCGTGGAATTCGAGAAGCTGCCAAA
GCCTTGGACAAACGCCAAGCCCATCTTTGTGTTCTTGCTTCCAACTGTGATGAACCTATG
TATGTAAAATTGGTTGAGGCCCTGTGTGCTGAACACCAAATCAACTTGATCAAGGTTGAT
GACAACAAGAAACTGGGAGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGAAAGCCC
CGTAAAGTGGTTGGCTGCAGTTGCGTTGTTGTTAAGGACTATGGCAAGGAATCTCAGGCC
AAAGATGTCATCGAAGAATATTTTAAATGCAAGAAATAA
>MACMU10_14.PE6                        399 CDS /gene="ENSMMUG00000031376" /gene_family="HOG000210688" /prote
CATGGCCGAGGAGGGATTGCCGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGTACGTGGAATTCGCGGAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAGTCAACCTAATTAAGGTTGAC
CACAACAAGAAACTAGGAGAATGGGTAGGCCTCTGTAAAATTGACAGAGACGGGAAACCC
CATAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAAGAGTCTCAGGCC
AAGGATGTTATCGAAGAGTACTTCAAATGCAAGAAGTGA
>MACMU10_33.PE6                        399 CDS /gene="ENSMMUG00000010204" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATAGACATTAATACTGCCTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCAACCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAGATCAACCTAATTAAGGTTGAT
GACAATAAGAAACTAGGAGAATGGGTAGGCCTCTGTAAAACTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGAAAGGAGTCTCAGGCC
AAGGATGTTATCGAAGAGTACTTCAAATGCAAGGAATGA
>MACMU13_43.PE3                        399 CDS /gene="ENSMMUG00000030854" /gene_family="HOG000210688" /prote
ACGGCCGAGAAAGGCATTTCTGTTGGAGGTGTAATGGATGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCGTCCACCATGGCCTAGCATGCGGAATTTGCAAAGCTGCCAAA
ACCTTGAACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGGGCCTATG
TATGTCAAGTTGGTGGGGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGGTGAT
GACAACAAGAAACTAGGGGAATGGGCAGGCCTCTGTAAAACTGACAGAGGGGGGAAACCC
CATAAAGTGGTTAGTAGCAGTTGTGTAGTAGTTAAGGACTATGGCAAAGAGTCTCAGGCC
AAGGATGTCATTGAAGAGTACTTCAAATACAAGAAATGA
>MACMU4_136.PE8                        399 CDS /gene="ENSMMUG00000013237" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAGGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACATCAGATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGAAAGGAGTCTCAGGCC
AAGGATGTTATCGAAGAGTACTTCAAATGCAAGAAATGA
>MACMU7_86.PE44                        399 CDS /gene="ENSMMUG00000006463" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACATCAGATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGAAAGGAGTCTCAGGCC
AAGGATGTTATCGAAGAGTACTTCAAATGCAAGAAATGA
>MACMU8_40.PE2                         390 CDS /gene="ENSMMUG00000029006" /gene_family="HOG000210688" /protei
ATGGCCGAGGACGGCATTGCTACTGGAGGTGTAATGGACGTTAATAAAGAGGTGCTGAAA
ACCGCCCACATCCACGATGGCCTAGCACGTGGAATTCCCGAAGCTGCCAAAGCCTTAGAC
AAGCACCAAGCTCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATGTATATCAAG
TTGGTGGAGGCCCTTTATGCTGAACACCAAATCAACCTAATTAAGGTTGATGACAACAAG
AAACCAGGAGAATGGGTAGGCCTCTGTAAAACTGACAGAGAGGGGAAACCCTGTAAAGTG
GTTGGTTGCAATTGTGTAGTAGTTAAGGACTATGGAAAGGAGTCTCAGGCCAAGGGTGTT
ATCGAAGGGTACTTCAAATGCAAGAAATGA
>MACMU9_31.PE1                         399 CDS /gene="ENSMMUG00000030633" /gene_family="HOG000210688" /protei
ATGGCCGAGGAGGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACTGCCCTCATCCATGATGGCCTAGCACGTGGAATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGACGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGGAGGCCTCTGTAAAACTGACAGAGAGGGGAAACCC
TGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGAAAGGAGTCTCAGGCC
AAGGATGTTATCAAAGAGTACTTCAAATGCAAGAAATGA
>MICMUGS_1190.PE4                      369 CDS /gene="ENSMICG00000005252" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCGCTGCTGTAATGGTTACTGCTTACAGAGTGCTGAAGGCCCTCATC
GATGCTGCACGTATTCGCGAAGCTGCCAAAGCCTTAGACAAGCGCCAAGCCCATCTTTGT
GTGCTTGCATCCAACTGTGATGAGCCCATGTATGTCAAGTTGGTGGAGGCCCTTTGTGCT
GAACATCAAATCAATCTAATTAAGGTTGATGACAACAAGAAACTAGGGGAATGGGTAGGC
CTTTGTAAAATTGACAGAGAAGGGAAACCCCGTAAGGTGGTTGGTTGCAGTTGTGTAGTA
GTTAAGGACTATGGCAAAGAATCTCAGGCCAAGGATGTCATCGAAGAGTACTTCAAATGC
AAGAAGTGA
>MICMUGS_4834.PE4                      390 CDS /gene="ENSMICG00000001949" /gene_family="HOG000210688" /pro
ATGGCTGAGGAAGGCACTGCTGCTGGAGGTGTAATGGATGTTAATACTGCTTTACAAGAG
GTGCCGAAGAACACCTTCATCCACAATGGCCTTGCACGTGGAATTCCGAAAGCTGCCAAA
GCCTTAGACAAGTCCCAAGCTCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTAGTTGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTTTGTAAAATTAACAGAGAGGATAAACCC
AATAAAGTGGTTGGTTGCAGTTGTGCAGTAGTTAAGAATTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGTACTTCTGCAAATGA
>MONDO2_419.PE20                       399 CDS /gene="ENSMODG00000017520" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAACACCGCTCTACAAGAA
GTGCTGAAGACCGCACTTATCCACGATGGCCTAGCTCGTGGAATTCGTGAAGCTGCCAAA
GCCTTGGACAAACGCCAAGCCCATCTTTGTGTTCTTGCTTCCAACTGTGATGAACCTATG
TATGTTAAATTGGTTGAGGCCTTGTGTGCTGAGCACCAAATCAACTTGATCAAGGTTGAT
GACAACAAGAAGCTGGGTGAATGGGTAGGCCTCTGTAAAATTGACAGAGAAGGAAAGCCT
CGTAAGGTGGTTGGCTGCAGTTGCGTTGTTGTTAAGGACTATGGCAAGGAATCTCAGGCC
AAAGATGTCATCGAAGAATATTTTAAATGCAAGAAATGA
>MOUSE10.PE277                         399 CDS /gene="ENSMUSG00000061983" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTGTGTGTGCTCGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCACTTTGTGCTGAGCACCAAATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGCAAACCA
CGGAAGGTGGTTGGTTGCAGTTGCGTAGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAATACTTCAAGTGCAAGAAATAA
>MOUSE10.PE1623                        399 CDS /gene="ENSMUSG00000069540" /gene_family="HOG000210688" /prote
ATGGCTAAGGAAGGCACTGCTGCTGGAGTTGTCATGGACGTCAATACGGCTTTGCAAGAG
GTGCTGAAGACCGCCCTGGTCCACGATGGCCTAGCGCGAGGAATTCACGAAGCTGCCAAA
GCCTTAGGCAAGCGCCAAGCCCATCTCTGTGTGCTTGCATCCAATTGTGATAAACCTATG
TACATCAAGTTGGTGGAAACCCTCTGTGCTGAGCACCAGATCAACCTAATTAAGGTTGAT
GACAACAAGAAGCTGGGGGAATGGGTAGGCCTCTGCAAAATTGATCGAAAGGGGAAACCT
CGGAAAGTGATAGGTTGCAGCTGTGTGGTGGTTAAGGACTTTGGCCAAGAATCTCAGGCG
AAAGATGTCATTGAAGAGTACTTCAAATGCAGAAAATGA
>MOUSE14.PE1230                        399 CDS /gene="ENSMUSG00000058518" /gene_family="HOG000210688" /prote
ATGGCTGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTCCAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGACCTAGCACGTGGCATATGCGAAGCTGCCAAA
GCCTTAGACAAGCACCAAGCCCATCTGTGTGTGCTCGCATCCAACTGTGATGAGCCCGTG
TATGTCAAGCTAGTGGAGGCACTTTGTGCTGAGCACCAAATCAACCTGATAAAGGCTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAAGCA
CGGAAGGTGGTTGGTTGCAGTTGCGTAGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAATACTTCAAGTGCAAGAAATAA
>MOUSE19.PE1388                        399 CDS /gene="ENSMUSG00000067038" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTGTGTGTGCTCGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCACTTTGTGCTGAGCACCAAATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGCAAACCA
CGGAAGGTGGTTGGTTGCAGTTGCGTAGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAATACTTCAAGTGCAAGAAATAA
>MOUSE7.PE1869                         399 CDS /gene="ENSMUSG00000078087" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTGTGTGTGCTCGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCACTTTGTGCTGAGCACCAAATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGCAAACCA
CGGAAGGTGGTTGGTTGCAGTTGCGTAGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAATACTTCAAGTGCAAGAAATAA
>MOUSE8.PE527                          384 CDS /gene="ENSMUSG00000059333" /gene_family="HOG000210688" /protein
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGTGTGCTCGCATCCAACTGTGATGAGCCCATG
TATGCCAAGCTGGTGGAGCACCAAATCAACCTGATAAAGGTTGATGACAACAAGAAACTA
GGTGAATGGGTAGGCCTCTGTAAAATTGATCGAGAGGAGAAACCATGGAAGGTGGTTGGT
TGCAGTTGCGTAGTGGTTAAGGACTATGGCAAAGAATCTCAGGCCAAGGATGTCATCGAG
GAATACTTCAAGTGCAAGAAATAA
>MYOLU140853.PE1                       399 CDS /gene="ENSMLUG00000001137" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTGCAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTCGCGCGCGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCACCTTTGCGTACTTGCATCCAACTGTGATGAGCCTATG
TACGTCAAGTTGGTGGAGGCTCTTTGTGCCGAACACCAAATCAACCTAATTAAGGTTGAC
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGCGTGGTGGTTAAGGACTATGGCAAAGAGTCTCAGGCA
AAGGATGTCATCGAGGAATACTTCAAATGCAAGAAATGA
>NEFIS1_162.PE1162                     435 CDS /gene="CADNFIAG00001087" /gene_family="HOG000210688" /prote
ATGTCCAACCCCCCCGTTGCCGCCGCCGATGAGGTCGAGGTTTCCGCTGATGCCGGCGCC
GGCGGTCAGATGTCCGTCCTCGATGCTCTGAAGGGTGTCCTCCGCATTGCTCTCATCCAC
GACGGTCTTGCCCGTGGTCTCCGCGAGGCCGCCAAGGCCCTCGACCGCCGCCAGGCCCAC
ATGTGTGTCCTCAACGAGGGCTGCGAGGAGGAGGCCTACAAGAAGCTCGTCATTGCTCTG
TGCTCTGAGCACAAGATCCCCCTCATCAAGGTTCCCGATGGAAAGATGCTGGGCGAGTGG
GTCGGTCTCTGCCAGCTTGACCGTGAAGGTAACGCCCGCAAGGTTGTCAACTGCTCTTGC
GTTGTCGTCAAGGACTGGGGTGAGGAGTCCCAGGAGCGCTCCGTCCTCCTCAACTACTTC
CAGACTGAGCAGTAA
>ORYLA24_15.PE11                       399 CDS /gene="ENSORLG00000016460" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCCGGAGGTGGGATGGATGTGAACACTGCTCTCCCAGAG
GTGCTGAAGACCGCACTCATCCATGACGGCCTTGCCCGTGGAATCCGCGAGGCTGCCAAG
GCCCTGGACAAGCGTCAGGCCCATCTCTGCGTCCTGGCCGCCAACTGCGATGAGCCGATG
TACGTGAAGCTGGTGGAAGCCCTCTGCGCTGAGCATCAAATTAACCTGATAAAAGTTGAC
GACAACAAGAAGCTCGGTGAGTGGGTCGGTTTGTGCAAGATCGACCGGGAGGGCAAACCC
CGCAAGGTGGTCGGCTGTAGTTGTGTTGTTGTCAAGGATTACGGCAAGGAGTCTCAAGCC
AAGGACGTGATTGAGGAATACTTCAAAGCCAAGAAATGA
>OTOGAGS_534.PE8                       384 CDS /gene="ENSOGAG00000003276" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGAAGGTGTAATAGATGTGAACACCGCTTTACTAGAG
GTGCTGAAGACCGCCCTCATCCATGATGGCCTTGCACGTGGAATCCGCGAAGCTGCCAAA
GCCTTAGACAAGACCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATGTATGTC
AAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGATGACAAG
AAGAAAAGGGAATGGGTAGGCCTTTGTAAAGTTGACGAGGGGAAACCCCATAAAGTGCTT
GGTCACAGTTGTGTAGCAGTTGACTATGACAAAGAATCTCAGGCCAATGATGTCATTGAA
GAGTACTTCAAATGCAAGAAATGA
>PANTR6_140.PE15                       399 CDS /gene="ENSPTRG00000018618" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTTCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTTTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAGGAGTCTCAGGCC
AAGGATGTCATCGAAGAGTATTTCAAATGCAAGAAATGA
>PENCW_15.PE233                        447 CDS /evidence="3: Inferred from homology " /gene_family="HOG00021
ATGTCGGACGGAGAAGAGCCCACATCCCCTGTCGCCCCCGCCGAGGAGGTCGAGGTTTCT
GCCGATGCCGGCAGCGGCCAGATGTCCGTCCTGGACGCCCTCAAGGGTGTTCTGCGCGTC
TCCCTGATCCACGACGGTCTTGCCCGTGGTCTCCGTGAGGCCGCCAAGGCCCTCGACCGC
CGTGAGGCCCACATGTGTGTCCTGAACGAGGGCTGCGAGGAGGAGGCTTACAAGAAGCTC
GTTGTCGCTCTCTGCTCCGAGCACAAGATCCCTCTCATCAAGGTTCCCGACGGAAAGATG
CTCGGCGAGTGGGTCGGTCTCTGCACTCTCGACCGTGAGGGTAACGCCCGCAAGGTTGTC
AACTGCTCTTGCGTCGTTGTCAAGGACTGGGGTGAGGAGTCCCAGGAGCGCTCCGTTCTC
CTCAACTACTTCCAGACCGAGCAGTAG
>PHPAT1_583.PE56                       420 CDS /gene="E_GW1.194.130.1" /gene_family="HOG000210688" /protein
ATGGCCGACGCCCCAGCTGAGGCGACGGCCGCCGCAGAGCCCGCGCTCGGGGAGCCCATG
GACATCCTCACAGGGTTGCAGATCGTTTTGAAGAAGGCGCTCGCTCACGACGGCCTCGCC
AAGGGTCTTCACGAAAGCGCCAAGGCCATCGAGAAGCACGCCGCTCAGCTGTGCGTGCTC
GCCGAGGACTGCAACCAGCCTGACTACACCAAGCTTGTGCAGGCTTTGTGCCAGGAGCAC
AACGTGAACCTTATCTCTGTCCCCAGCGCCAAGAAGCTCGGTGAATGGGCTGGTCTCTGC
AAGATCGACTCCGAGGGAAAGGCTCGCAAGGTTGTTGGATGCTCCTGCGTAGTGGTGAAG
GATTACGGTGAAGAAACCGAGGGACTTAATATCGTGAGGGAGTACGTCAAGAGTCAGTAG
>PHPAT1_726.PE152                      396 CDS /gene="GW1.26.230.1" /gene_family="HOG000210688" /protein_i
GAGGCCCCAGTTGCGGAGCAGACTGCGCCTGGAGAGCCCATGGACATCCTCACTGGTCTA
CAGATGGTGTTGAAGAAGGCCTTGGCGCACGATGGGCTTGCGAAGGGGCTTCACGAGAGC
GCTAAGGCGATCGAGAAGCACGCCGCTCAGTTGTGTGTGCTAGCAGAGGATTGCAATCAG
CCTGACTACACCAAGCTCGTGCAGGCTCTGTGTCAAGAGCACAACGTCAACCTGATTTCC
GTTCCCTCTGCTAAGAAGCTCGGAGAGTGGGCTGGTCTCTGCAAAATTGACTCCGAGGGG
AAGGCCAGAAAGGTAGTAGGATGCTCGTGTGTGGTTGTGAAGGACTACGGTGAGGAGACT
GAGGGGCTTAACGTTGTGAGGGAATATATTAAGAAT
>PIG1_34.PE1                           399 CDS /gene="ENSSSCG00000004177" /gene_family="HOG000210688" /protein_
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCATGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCAATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAGCACCAGATCAACCTAATTAAGGTCGAC
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGAAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTGGTGGTGAAGGACTATGGCAAAGAGTCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATAA
>PISTI1_6.PE329                        435 CDS /codon_start=1 /gene_family="HOG000210688" /evidence="3: Infe
ATGTCTGACGTTGAACAAGAACAAATTGTCGAAGAAGTTGCCGTTGAACAAACCGAAGCC
GGCTCCATCTCCATCGAAGATGCCTTGAAGGTCGTCTTGAGAACCTCTTTGGTCCACGAC
GGTTTGGCCAGAGGTTTGAGAGAAGCTTCCAAGGCTCTTTCTAGAAGAGAAGCTCAATTG
TGTGTTCTCTGTGACTCTGTCACCGAAGAATCCATCATCAAGTTGGTTGAAGCTTTGTGT
AACGAGCCAGAAGAAAAGATCCCATTGATCAAGGTCTCTGACGCCAAGTTGTTGGGTGAA
TGGGCTGGTCTCTGTCAATTGGACAGAGAAGGTAACGCCAGAAAGGTCGTTGGTGCCTCT
TGTGTTGTCGTCAAGAACTGGGGTGCTGACTCTGATGAAAGAAACATCTTGTTGGAACAC
TTCTCTCAACAATAA
>POEGU3_61.PE1                         399 CDS /gene="ENSTGUG00000011574" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCATTACTGCTGGAGGTGTAATGGATGTTAACACCGCTCTGCAAGAA
GTGCTGAAGACCGCACTTATCCACGATGGCCTTGCTCGCGGTATCCGTGAAGCAGCCAAA
GCCTTGGACAAACGCCAAGCCCATCTCTGTGTTCTGGCCTCAAACTGTGATGAGCCCACA
TATGTAAAATTAGTTGAAGCACTCTGTGCAGAACATCAGATCAACTTAATAAAGGTTGAT
GACAACAAGAAGCTGGGCGAATGGGTGGGTCTCTGCAAGATCGACAGAGAAGGAAAACCT
CGCAAAGTGGTGGGCTGCAGTTGTGTGGTTGTCAAAGACTATGGCAAGGAATCTCAGGCC
AAAGATGTCATCGAAGAGTACTTCAAGTGCAAGAAATGA
>PONPY6_140.PE8                        396 CDS /gene="ENSPPYG00000017020" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTTCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAAGCGCTTTGTGCTGAACACCAAATCAACCTGATTAAGGTGGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAGGAGTCTCAGGCC
AAGGATGTCATCGAAGAGTATTTCAAATGCAAGAAA
>POPTR_12.PE612                        438 CDS /gene="POPTR_0002s05710" /gene_family="HOG000210688" /protein
ATGTCTGGTGAAGAAGGTGCTGTTGCTCAGACTGAGACTCCAGCTGTTGCTGATGTACCA
CCACTTGGTGAGCCAATGGACTTGATGACAGCATTGCAGCTTGTGCTGAGAAAATCTCTG
GCTCATGGTGGGCTTTCTCGAGGTCTTCATGAAGGTGCCAAAGTGATTGAGAAGCATGCT
GCTCAACTTTGTGTCTTGGCAGAGGATTGCAACCAGCCTGACTATGTTAAACTTGTTAAG
GCACTTTGTGCTGATCACAACGTGAACTTGCTAACTGTTCCAAGTGCAAAAACCCTCGGA
GAGTGGGCTGGTTTGTGTAAGATTGACTCAGAGGGGAAGGCTAGGAAAGTGGTCGGTTGC
TCGTGTGTTGTTGTGAAGGATTTTGGGGAGGACACTGAAGCTCTTAATGTCATTCAACAG
CATGTCAAGGCCAACTAA
>POPTR_15.PE2388                       441 CDS /gene="POPTR_0005s22790" /gene_family="HOG000210688" /protei
ATGTCAGGTGAAGAAGGTGCTGTTCCTCAGAATGAGACTCCAGCTGTTGCTGATGCACCC
GCACCCCTCGGTGAGCCAATGGACTTGATGACAGCATTGCAGCTTGTTCTGAGAAAATCA
CTTGCTCATGGTGGGCTTTCTCGAGGGCTTCATGAAGGGGCCAAAATGATTGAGAAGCAT
ACTGCTCAACTTTGTGTCTTGGCCGAGGATTGTAACCAACCTGACTATGTCAAACTTGTT
AAGGCACTTTGTGCTGACCACAAAGTGAACTTGCTATCTGTTCCAAGCGCAAAGACCCTA
GGAGAGTGGGCTGGTTTGTGCAAGATTGATTCAGAGGGGAAGGCCAGGAAAGTAGTTGGT
TGCTCTTGCGTTGTTGTGAAGGATTTTGGAGAGGACAGTGAAGCTCTTAATGTTGTCCAA
CAGCATATCAAAGCTAACTAA
>PTEVAGS_547.PE4                       399 CDS /gene="ENSPVAG00000017201" /gene_family="HOG000210688" /prot
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTGCAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATCCGTGAAGCTGCCAAA
GCCTTAGACAAGCGCCAGGCCCATCTGTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGTTGGTGGAGGCCCTTTGTGCTGAACACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGAAAACCC
CGGAAAGTGGTTGGTTGCAGTTGCGTGGTGGTTAAGGACTATGGCAAAGAGTCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>RABIT12_127.PE15                      399 CDS /gene="ENSOCUG00000001606" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCATGATGGCCTAGCCCGTGGAATCCGTGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTTTGTGTGCTTGCATCTAACTGCGATGAGCCTATG
TATGTCAAGCTGGTGGAGGCCCTGTGTGCTGAGCACCAAATCAACCTCATTAAGGTTGAT
GACAACAAGAAACTTGGGGAATGGGTAGGCCTCTGTAAAATTGACCGAGAAGGGAAACCC
CGCAAAGTGGTTGGTTGCAGTTGCGTAGTGGTTAAGGACTACGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAAGAATACTTCAAATGCAAGAAATGA
>RAT1.PE217                            399 CDS /gene="ENSRNOG00000016411" /gene_family="HOG000210688" /protein_i
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGCGTGCTTGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCGCTCTGTGCCGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAGCCA
CGGAAAGTGGTTGGTTGCAGTTGCGTTGTAGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>RAT1.PE3706                           399 CDS /gene="ENSRNOG00000032173" /gene_family="HOG000210688" /protein_
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACATCAACACTGCTCTACAAGAG
GTGCCGAAGACTGCCCTCATCCACGATGGTCTAGCACGTGGCATATGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGGCCATCTCTGTGTGCTTGCATCCAACTATGATGAGCCCATG
TATGTCAAGCTGGTGGCGGCACTCTGTGCTGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAACCA
CGGAAAGTGGTTGGTTGCAGTTGCGTTGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCGAATGCAAGAAATGA
>RAT1.PE3858                           399 CDS /gene="ENSRNOG00000029067" /gene_family="HOG000210688" /protein_
GTGGCTGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACTGTCCTTCTTCTCGATGGCCTAGCACTTGGCATACGCAAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGGCCATCTCTGTGTGCTTGCATCCAACTGTGATGAGGCCGTG
TATGTCAAGCTGGTGGCGGCACTCTGTGCTGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAACCAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAACCA
CGGAAAGTGGTTGGTTTCAGTTGCACAGTGGTTAAGGACTGTGGCAAAGACTCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>RAT1.PE4102                           399 CDS /gene="ENSRNOG00000032045" /gene_family="HOG000210688" /protein_
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGTGCCAAGCCCATCTCTGCGTGCTTGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCGCTCTGTGCCGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAGCCA
CAGAAAGTGGTTGGTTGCAGTTGCGTTGTAGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>RAT14.PE1006                          399 CDS /gene="ENSRNOG00000042277" /gene_family="HOG000210688" /protein
ATGGCCGAGGAAAGCATAGCTGTTGGAGGTGTAATGGACATCAACACTGCTCTACAAGGG
ATGCTGAAGACCGCCCTCATCCATGACAGCCTAGCACGTGACATACGCGAAGCTGCCAAA
GCCTTTGACAAGCGCCAAGCCCATGTCTATGTGCTTGCCTCCGACTGTGATGAACCCATG
TGTGTCAAGCTGGTGTACGCACTCTGTGCTGAGCACCAGATCAACCTGATAAAGGCTGAT
GACAACAAGAAACTTGGGGAATGGGGAGGCCTCTGTAAAATCGATCGAGAGGGGAAACCA
CAGAAAGTGGTTGTTTGCAGTTGTGTAGTGGTTCAAGATTATGGCAAAGAATCTCAGGCC
AAGGATATCATCAAGGAGTACTTCAAATGCAAGAAATGA
>RAT19.PE472                           414 CDS /gene="ENSRNOG00000020093" /gene_family="HOG000210688" /protein_
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACAATGGCCTAGCACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGAAACATAGGAAAAGGCGCCAAGCCCATCTCTGCGTGCTTGCATCCAAC
TGTGATGAGCCCATGTATGTCAAGCTGGTGGAGGCGCTCTGTGCCGAGCACCAGATCAAC
CTGATAAAGGTTGATGACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGAT
CGAGAGGGGAAGCCACGGAAAGTGGTTGGTTGCAGTTGCGTTGTAGTTAAGGACTATGGC
AAAGAATCTCAGGCCAAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>RAT3.PE1854                           399 CDS /gene="ENSRNOG00000033913" /gene_family="HOG000210688" /protein_
ATGGCCGAGGAAGGCATAGCTGCTGGAGGTGTAATGGACGTCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGTACGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGCGTGCTTGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCACTCTGTGCTGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAACCC
CGGAAAGTGGTTGGTTGCAGTTGCGTTGTAGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>RAT4.PE1579                           399 CDS /gene="ENSRNOG00000029083" /gene_family="HOG000210688" /protein_
GTGGCTGAGGAAGGCATAGCTGCTAGAGGTGTAATGGACTCCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCATCATCCACGATGGCTTAGCACGTGGCATACGCAAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGTGTGCTTGCATCCGACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCACTCTGTGCTGAGCACCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATCCATCGAGAGGAGAAACCA
CGGAAAGTGGTTGGTTGCAGTTGCGTAGTGGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAAAAATGA
>RAT5.PE238                            399 CDS /gene="ENSRNOG00000032454" /gene_family="HOG000210688" /protein_i
ATGGCTGAGGGAGACATAGCTGCTGGAGGTGTAATAGACATCAACACTGCTCTACAAGAG
GTGCTGAAGACCGCCTTCATCCACGATGCCTTAGCATGTGGCATACGCGAAGCTGCCAAA
GCCTTAGACAAGTGCCAAGCCCATCTCTGTGTGCTTGCATCCAACTGTGATGAGCCCATG
TATGTCAAGCTGGTGGAGGCACTCTGTGCTGAGCACCAGATCAACCTGATGAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCCCTGTAAAATCGATCTAGAGGGGAAACCA
CTGAAAGTGGTTGGTTGCAGTTGCATAGTGGTTAAGGACTATGGCAAAGAATCTCAGGAC
AAGGATGTCATCAAGGAGTACTTCAAATGCAAGAAATGA
>RAT5.PE1179                           402 CDS /gene="ENSRNOG00000031300" /gene_family="HOG000210688" /protein_
ATGGCTGAGGAAGGCATAGCGCCTGGAGCTGTAATGGACGTCAACACTGCTCTACTAGAA
GTGTTGAAGACCGCCCTCATCCATGATGGCCTAGCACATGGCGTACACGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCTTCTCTGTGTGCTTGCATCCGACTGTGACAAGGCCGTG
TATGTCAAGTGCGTGGAGGCGCTTTGTGCTGAGCACGAAATCAACCTGATAAAGGTTGGT
GACAACAAGGAACCAGGGGAATGGGTAGGCCTCTGTAAAATCGATCGAGAGGGGAAGCCA
CGGAAAGCGGGTGGTTGTAGTTGCCTAGTGACTAAGGACGATGGCAAAGAATCTCAGGCC
AATGACGTCATCGAGGAGTACTCAGATGCAAGCAATGAATAA
>RAT7.PE605                            399 CDS /gene="ENSRNOG00000043412" /gene_family="HOG000210688" /protein_i
ATGGCCAAGGAAGACACTGCTGCTGGAGTTATCATGGATGTTAATACTGCTTTGCAAGAG
GTGCTGAAGACCGCCCTGGTCCACGATGGCCTAGCCAGAGGAATTCACGAAGCTGCCAAA
GCCTTAGGCAAGCGCCAAGCCCATCTCTGTGTGCTTGCAGCCAACTGTGATAAACCTATG
TACATCAAGTTGGTGGAAACCCTTTGTGCTGAGCACCAAATCAACCTAATTAAGGTTGAT
GACAACAAGAAACTAGGAGAATGGGTAGGCCTCTGCAAAATTGATCGAAAGGGGAAACCT
CGTAAAGTGATAGGTTGCAGCTGTGTGGTGGTTAAAGATTATGGCCAAGAATCTCAAGCT
AAAGATGTCATCGAAGAGTACTTCAAATGCAAGAAATGA
>SCHMA_171.PE9                         396 CDS /gene="Smp_060090" /gene_family="HOG000210688" /protein_id="Sm
ATGTTGGCCACAGAAATGGATTTGGATAGTGCTGTGCAGCAAGTCCTTAAAAATGCTGCT
AAGTGCCGTGGAATATGTCGTGGATTAAACGAGTGCACGAAATTGATTGAACAACGGGGT
GTTGTCCTTTGTTTTCTGGCAGAAAATTGTAACGAAAAAGCCTATACAACTCTGATTGAA
GCACTATGCCACGAACATGGTATCCCTCTTGTGAAGGTTCCCGATAATAAAAAGCTTGGT
GAGTGGTCTGGATTGTGTAAGTATGACAAAGAAGGAAAGGCTAGAAAAGTCGTGTCAGCC
TCATGTATTGTAGTAACCGATATCGGAGAAGAATCCTATGGACTAAAGTACTTGGTTGAA
AAATTCAGATTACCCATCCAAACAAGAGAGGCCTAA
>SCHMA_171.PE10                        396 CDS /gene="Smp_060090" /gene_family="HOG000210688" /protein_id="S
ATGTTGGCCACAGAAATGGATTTGGATAGTGCTGTGCAGCAAGTCCTTAAAAATGCTGCT
AAGTGCCGTGGAATATGTCGTGGATTAAACGAGTGCACGAAATTGATTGAACAACGGGGT
GTTGTCCTTTGTTTTCTGGCAGAAAATTGTAACGAAAAAGCCTATACAACTCTGATTGAA
GCACTATGCCACGAACATGGTATCCCTCTTGTGAAGGTTCCCGATAATAAAAAGCTTGGT
GAGTGGTCTGGATTGTGTAAGTATGACAAAGAAGGAAAGGCTAGAAAAGTCGTGTCAGCC
TCATGTATTGTAGTAACCGATATCGGAGAAGAATCCTATGGACTAAAGTACTTGGTTGAA
AAATTCAGATTACCCATCCAAACAAGAGAGGCCTAA
>SORAR181734.PE1                       396 CDS /gene="ENSSARG00000010303" /gene_family="HOG000210688" /prot
ATGGCTGAGGGCATTGCTGCAGGAGGTGTAATGGACATGGATACTGCGCTGCAAGAGGTG
CTGAAGACCGCCCTCATCCACGATGGTCTTGCACGTGGCATCCCTGAAGGCGCCAAAGCC
CTAGACAAGCGCCAAGCCCAACTTTGTGTGCTTGCATCCGACTGTGATGAGCCTATGTAT
GTCAAGTTGGTGGAGGCACTTTGTGTTGAACACCAGATCAACCTAATTAAGATTGATGAC
AAAAAGAAGCTAGGGAAATGTGTCAGCCTCTGTAAAATTGATAGAGAAGGGAAACCCCGA
AAAGCGGTTGGCTGCAGTTGTGTTGTAGTTAAGGACTATGGCGAAGAATCACAGGCCAAG
GATGTCATCAAAGAATACTTCAAATGCAAGAAATAA
>TARSY29478.PE1                        399 CDS /gene="ENSTSYG00000010097" /gene_family="HOG000210688" /prote
ATGGCCGAGGAAGGCATCGCTGCTGGAGGTGTAATGGACGTGAACACAGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGACGGCCTAGCGCGTGGAATTCGCGAAGCCGCCAAA
GCCTTAGACAAGCGCCAGGCCCATCTCTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TACGTCAAGTTGGTGGAAGCCCTTTGTGCTGAACACCAAATCAATCTAATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTGTGTAAAATCGACAGAGAGGGGAAACCC
CGGAAAGTGGTTGGTTGCAGTTGTGTAGTAGTTAAGGACTATGGCAAAGAATCTCAGGCC
AAGGATGTCATCGAAGAGTACTTCAAATGCAAGAAATGA
>TETNG14.PE405                         399 CDS /gene="ENSTNIG00000016328" /gene_family="HOG000210688" /protei
ATGGCCGAGGAAGGCGTTGCTGCTGGAGGTGTCATGGATGTCAACACTGCTCTCCCAGAA
GTGCTGAAGACTGCCCTCATTCACGACGGCCTTGCCCGTGGCATCCGGGAGGCTGCCAAG
GCTCTGGACAAGCGTCAGGCCCACCTGTGCGCCCTTGCTGCCAACTGTGACGAGCCCATG
TATGTGAAGCTGGTGGAGGCCCTCTGCGCTGAGCATCAGATCAACCTGATAAAGGTTGAT
GACAACAAGAAGCTTGGTGAGTGGGTCGGACTGTGCAAGATCGACCGTGAGGGGAAACCC
CGCAAGGTGGTGGGCTGCAGCTGCGTCGTAGTCAAGGATTATGGCAAGGAGTCCCAGGCC
AAGGATGTGATTGAGGAGTACTTCAAGAGCAAGAAATAA
>TUPGBGS_2142.PE1                      366 CDS /gene="ENSTBEG00000016776" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTTTACAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCCGCCAAA
GCCTTAGACCAAGCCCATCTGTGTGTTCTTGCGTCCGCCTGTGATGAACCTATGTATGTT
AAGTTGATGGAGACCCTTTGCGCTGAACAGCAAATCAACTTAGTGAATGACAACAATAAA
CTAGTGGAAGTAGGACTCTGTAAAACTGACAGAAAATTCCATAAAGTGGTTAGTTGCAGC
CATGTAGTAGTTAAGGAATCTCAGTCCAAGGATGTCATCAAAGAGTACTTTGAATGCAAG
AAATGA
>TURTRGS_1817.PE5                      399 CDS /gene="ENSTTRG00000000609" /gene_family="HOG000210688" /pro
ATGGCCGAGGAAGGCATTGCTGCTGGAGGTGTAATGGACGTTAATACTGCTCTGCAAGAG
GTGCTGAAGACCGCCCTCATCCACGATGGCCTAGCACGTGGAATTCGCGAAGCTGCCAAA
GCCTTAGACAAGCGCCAAGCCCATCTCTGTGTGCTTGCATCCAACTGTGATGAGCCTATG
TATGTCAAGCTGGTGGAGGCCCTTTGTGCTGAGCACCAGATCAACCTGATTAAGGTTGAT
GACAACAAGAAACTAGGGGAATGGGTAGGCCTCTGTAAAATTGACAGAGAGGGGAAACCC
CGTAAAGTGGTTGGCTGCAGCTGTGTGGTGGTTAAGGACTATGGCAAAGAGTCTCAGGCC
AAGGATGTCATCGAGGAGTACTTCAAATGCAAGAAATGA
>USMAY1_1.PE522                        438 CDS /codon_start=1 /gene_family="HOG000210688" /evidence="3" /loc
ATGTCCGACGTTGAGGAGGTCCCCCAGCAGGTCGAGGAGGTCGAGGTCGCCGAGGCTGCT
CCCGCCAAGGGCGCCATGTCCATTGAGGACGCCCTTCAGGAGGTGCTCAAGAAGGCTCTC
ATCCACGACGGTCTCGCCCGTGGTCTGCGTGAGTGTGCCAAGGCGCTCGACCGTCGTCAG
GCCCACCTTTGCGTTCTCGTCGAGACCTGCAACGAGCCCGAGTACCTCAAGCTTATCGAG
GCACTCTGCAACGAGCACAAGATCGATCTGCTCAAGGTCTCTGACCCCAAGACTCTCGGC
ACCTGGGCCGGTCTCTGCAAGATCGACCGCGAGGGTAACCCCCGTAAGGTGGTCGGCTGC
TCTTGCGTCGTCGTCAAGGACTACGGTGAGGAGTCTGAGGGTCTCAACGTCCTCCTCGAG
TACTTCAAGAGCCGTTAA
>YEASTXV.PE576                         432 CDS /gene="YOR369C" /gene_family="HOG000210688" /protein_id="YOR36
ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTGTTGAACAAACTGCC
GAAGTTACTATCGAAGATGCTTTGAAGGTTGTTTTGAGAACCGCTTTGGTTCACGATGGT
CTAGCTAGAGGTTTGAGAGAATCTACCAAGGCTTTAACCAGAGGTGAAGCTTTATTGGTT
GTTTTGGTCAGCTCTGTTACTGAAGCTAACATTATCAAGTTGGTTGAAGGTTTGGCTAAC
GACCCAGAAAACAAGGTTCCATTGATCAAGGTTGCTGATGCTAAGCAATTAGGTGAATGG
GCTGGTTTGGGTAAGATCGACCGTGAAGGTAACGCCAGAAAGGTTGTCGGTGCCTCCGTT
GTTGTTGTCAAGAACTGGGGTGCTGAAACTGATGAATTGTCCATGATCATGGAACACTTC
TCCCAACAATAA
>ZYGRO_3.PE19                          438 CDS /locus_tag="ZYRO0C00594g" /gene_family="HOG000210688" /old_locu
ATGTCTGATACTCAAGAAGTCCAAGAAGTTCAAGAAGTTCCAGAAGTTCAAGAAGAACAA
ACCGCTGAAGTCACCATCGAAGATGCTTTGAAGGTTGTCTTGAGAACTGCCTTGATCAAT
GACGGTTTGGCTAGAGGTTTGAGAGAATCTGCCAAGGCTTTGACCAAGGGTCAAGCTCAA
TTGGTTGTCCTTGTCAGCTCTGTCACTGAAGACAACATCATCAAGTTGGTTGAAGGTTTG
GCTAACGATCCTGAGAACAAGGTTCCATTGATCAAGGTCGCTGACGCTAAGCAACTAGGT
GAATGGGCCGGTTTGGGTAAGGCTGACCGTGAAGGTAACGTCAGAAAGGTTGTCGGTGCT
TCCGTTGTTGTTGTTACCAACTGGGGTGCTGAAACTGATGAACGTACCATGATCTTGGAA
CACTTCTCCCAACAATAA
