>AEDAE_113.PE33                        459 CDS /gene="AAEL000593" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACGGAGAAAGATCTGTATCGGGAAACACCCGTGCGATATCTCGGTTACGCA
AACGAAATCGGAGAAGCATTCCGGCCGGTGATCCGGAAGGTATTTGTCCATGCCAGTTAC
GTCGTTGCCGTTGGGTATGTTCTGGCCGATACGGCGGACAAGTCCCGCAAACAGTATGCG
AAACCGGAAATTCTAGGAGGGGGCGCCCGTGGAGCAGCGATAGCCTCTGGGGACACTCTG
CTGTGGCAGATGTTTGCCTCGGTCATCATTCCGGGCTTCACGATTAACAGAATTTGCTGG
CTCTCGAAGAAGGTCCTCGCGATGAACAAAGTAAAAGGACCGCTGGGAAAATGGGCTCCG
ACGGCGCTGGGCCTGCTGGCGATTCCATTCATCATCCATCCCATCGATCACGGAGTGGAT
CTGGTGATGGATCAAACCTACCGGAAGTATGTTAAATAA
>AILMEGL192437_1_2.PE11                501 CDS /gene="ENSAMEG00000007581" /gene_family="HOG000007398" /pro
ATGTCTGAGCCACCCCCGCGGGGTGCCGAGCGCGATCTTTTCCGGGACACGTGGGTACGG
TACCTAGGCTATGCCAATGAGGTGGGAGAGGCGTTCCGCTCCCTGGTACCAGCAACTGTG
GTGTGGCTGAGCTATGGTGTGTCCAGCTCGTACGTGCTGGCCGATGCCATTGACAAGGGC
AAGAAGGCAGGAGCTGTACCGAGCTCTGAAGCAGGCCGCAGCTCCAGGGTGACCGTGGCT
GTGGTGGACACTTTCGTGTGGCAGGCCCTGGCTTCTGTGGCTATCCCAGGCTTCACTATC
AACCGTGTGTGTGCTGCCTCTCTCTACATCCTGGGCACTGCCACCCGCTGGCCTCTGTCT
GTCCGCAAGTGGACCACCACTGCACTGGGGCTTCTGGTCATCCCTGTCATCATCCACCCC
ATTGACAGGTCAGTGGACTTCCTCCTGGACTCCAGCCTGCGTAAGCTCTACCCGTCAGTG
GAGAAGCCCAGCTCCTCCTGA
>ANOGA_10.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_11.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_12.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_13.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_14.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_15.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_16.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_17.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_18.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_19.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_20.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_21.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_22.PE604                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_23.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_24.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_25.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_26.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_27.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_28.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_29.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_30.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_31.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_32.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_33.PE603                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_34.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_35.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_36.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_37.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_38.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_39.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_40.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_41.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_42.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_43.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_44.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_45.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_46.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_47.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_48.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_49.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_50.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_51.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_52.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_53.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_54.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_55.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_56.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_57.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_58.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_59.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_60.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_61.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_62.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_63.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_64.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_65.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_66.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_67.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_68.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_69.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_70.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_71.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_72.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_73.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_74.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_75.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_76.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_77.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_78.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_79.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>ANOGA_80.PE612                        459 CDS /gene="AGAP001603" /gene_family="HOG000007398" /protein_id="A
ATGTCAATTACCGAGAAGGATCTGTACCGGGACACTCCGGTGCGTTATCTAGGATACGCG
AACGAGATTGGAGAAGCCTTCCGACCGGTCATCAAGAAGATCTTTGTGCATGCGAGCTAC
GCGGTGGCGATCAGCTACGTGCTAGCGGATACGGCCGACAAGTCCAAGAAGCAGTACGAT
AAACCGGAAATACTGGGTGGAGGATTCCGTGGAGCGGCCGTTGCATCCGGCGACACGCTG
TTGTGGCAAATGTTTGCCTCCGTCATCATACCCGGATTTACCATCAATCGGATCTGCTGG
CTGTCGAAAGCGGCCTTGAAAGCGAACAAGGTCAAGGGACCGGTCGGCAAGTGGGGACCG
ACGCTGCTCGGGCTGCTGGCCATTCCGTTCATCATCCATCCGATCGATAGTGCGGTTGAT
TATGCGATGGATAACACCTACCGAAAGTATGTTAAATAA
>CABRI1_6.PE1974                       489 CDS /codon_start=1 /gene_family="HOG000007398" /evidence="3: Inf
ATGTCTCCAGTAGAAAGTAGCAATGTAGAGAAGGACATCTTCCGCGATACACCAGTCAGA
TTTCTAGGCAAGCGATATGCCAACGAGGTTGGAGAAGCGTTTCGATCTCTGGTCAAACCG
GTAGTCGTCAAATTCTCGTACGTCGTCGCCTTCGGCTACGTGGCTGCTGATTCTGTCGAC
AAAGGTTTCAAGGAGTCGAAGAAACCCCACGCCAACGACACCGAAAAGGCCAAGAGAGTT
GCGATCATCGCTGTGGACACGGTTTTGTGGCAAACTTTTGCATCCGTTTTAATCCCCGGA
TTCACGATCAACAGATTCTGCTTCTTCACGAACATGCTCCTTGAGAAGTCGACCAAGTTG
CCAACAAATCTCCGAAAATGGACGGTCACCGCCTTGGGGCTCGCCACAATTCCATTCATC
GTCCATCCTATTGACGCTTTTGTGGAGGATGCGATGAATAAGACTGCACGCAAGGTGTAT
AATTATTAG
>CAEELX.PE1373                         501 CDS /gene="T13C5.8" /gene_family="HOG000007398" /protein_id="T13C5
ATGACCCCAGTCGAAGAAATTATTAAAAAAGACATTTTCCGGGAGACACCTCTCAGATAT
TTAGGATATGCCAACGAGGTTGGAGAAGCCTTCCGATCGCTTGTAAAACCAGTCGTCGTC
AAATTTTCGTATGTCGTCGCCTTCGGATATGTTGCAGCCGATTCGATAGATAAGGGACTG
CAGGAATATATTAAGACCCATTCGACTAGCACCGAAAAGACCAAAAAGGTTGCGATAGCC
GCTGTGGACACCGTGTTATGGCAGACATTTGCATCAGTCCTGATCCCAGGATTCACTATA
AACCGCTTTTGTTTCTTCTCCAACTTGCTCCTACAGAAGTCTACAAAACTGCCAACAAAC
ATGAGAAAGTGGACAGTGACGTGCTTGGGTCTTGCAACAATACCGTTTATTGTGCACCCC
ATCGACTCATTTGTAGAGGAGGCTATGGATAAGACTGCTCGAAAGATTTACAATGAACCA
ACAATTTCCAACAAAGAGTAG
>CAEELX.PE1374                         501 CDS /gene="T13C5.8" /gene_family="HOG000007398" /protein_id="T13C5
ATGACCCCAGTCGAAGAAATTATTAAAAAAGACATTTTCCGGGAGACACCTCTCAGATAT
TTAGGATATGCCAACGAGGTTGGAGAAGCCTTCCGATCGCTTGTAAAACCAGTCGTCGTC
AAATTTTCGTATGTCGTCGCCTTCGGATATGTTGCAGCCGATTCGATAGATAAGGGACTG
CAGGAATATATTAAGACCCATTCGACTAGCACCGAAAAGACCAAAAAGGTTGCGATAGCC
GCTGTGGACACCGTGTTATGGCAGACATTTGCATCAGTCCTGATCCCAGGATTCACTATA
AACCGCTTTTGTTTCTTCTCCAACTTGCTCCTACAGAAGTCTACAAAACTGCCAACAAAC
ATGAGAAAGTGGACAGTGACGTGCTTGGGTCTTGCAACAATACCGTTTATTGTGCACCCC
ATCGACTCATTTGTAGAGGAGGCTATGGATAAGACTGCTCGAAAGATTTACAATGAACCA
ACAATTTCCAACAAAGAGTAG
>CANFA26_28.PE9                        501 CDS /gene="ENSCAFG00000012742" /gene_family="HOG000007398" /prote
ATGGCCGAGCCGCCCCCGCGGGGTGCCGAGCGCGACCTTTTCCGGGACACTTGGGTGCGG
TACCTAGGCTATGCCAATGAGGTGGGAGAGGCATTCCGTTCCCTGGTGCCAGCAGCTGTG
GTGTGGCTGAGCTATGGTGTGTCCAGCTCCTACGTGCTGGCCGATGCCATTGACAAGGGC
AAGAAGGCAGGAGACGTACCAAGCCCGGAGGCAGGTCGCAGCACCAGGGTGACCGTGGCT
GTGGTGGACACTTTTGTGTGGCAGGCTCTGGCTTCTGTGGCTATCCCAGGCTTCACTATC
AACCGTGTGTGTGCTGCTTCTCTCTACATCCTGGGCACTGCCACCCGTTGGCCTTTGTCT
GTCCGCAAGTGGACCACCACTGCACTGGGGCTTCTGGTCATCCCTGTCATCATCCATCCC
ATTGACAGGTCAGTGGACTTCCTCCTGGACTCCAGCCTACGCAAGCTCTACCCCTCAGTG
GAGAAGCCCAGCTCTTCCTGA
>CAVPO4_14.PE8                         498 CDS /gene="ENSCPOG00000025757" /gene_family="HOG000007398" /protei
ATGTCAGAGCCACAGCCGGGTGGCGCAGAGCGCGATCTCTACCGGGACACGTGGGTGCGA
TACCTGGGCTATGCCAATGAGGTGGGGGAGGCTTTCCGCTCCCTGGTCCCAGTGTCTGTG
GTGTGGCTGAGCTACGGTGTGTCCAGCTCTTACGTGTTGGCCGATGCCATTGACAAAGGC
AAGAAAGCAGGAAAGATGCCAAGCCCCGAAGCCAGCCGCAGCTCAAGAGTGACCATAGCC
GTGGTGGATACCTTCGTGTGGCAGGCTCTGGCCTCTGTGGCCATTCCAGGCTTCACTATC
AACCGTATATGTGCCACTTCTCTCTACGTCCTGCGCACTGCCACCCGCTGGCCCCTGGCT
GCCCGCAAGTGGACCACCACTGCAGTTGGGCTTCTGGCCATTCCTGTCATCATCCACCCC
ATTGACAGGTCAGTGGACTTCCTCCTGGACTCCAGCTTGCGCAAGCTCTACCCATCGGTG
GGGAAGCCCAGCTCCTCC
>CULQU_469.PE16                        459 CDS /gene="CPIJ007314" /gene_family="HOG000007398" /protein_id="C
ATGTCCGTCACGGAAAAGGACCTGTACCGGGACACTCCCGTGCGCTATTTGGGTTACGCA
AACGAAGTCGGCGAGGCGTTCCGGCCGATCATCAAGAAGATTTTCGTACACGCCTCGTAC
GCGGTTTCGATCGGTTACGTGCTGGCCGATACGGCGGACAAATCGCGGAAACAGTATGCG
AAACCGGAAGCCCTCGGTGGTGGGCCACGTGGGGCCGCAATCGCAACCGGTGACACCCTG
CTCTGGCAAATGTTTGCCTCGGTGATTATTCCAGGGTTCACCATCAATCGAATTTGTTGG
ATCTCGAAAAAGGCTCTCTCGGCGGGAAAACTGAAGGGTCCGCTTCGCAAGTGGGGACCC
ACGGCGATCGGACTGCTGGCCATTCCGTTCATCATTCACCCGATCGACCACGGAGTGGAC
TACGTGATGGATGAAACATACCGAAAGTATGTAAAGTAG
>ECHTEGS_1251.PE2                      501 CDS /gene="ENSETEG00000008191" /gene_family="HOG000007398" /pro
ATGCCTGAGCCGCCGCCGCGGGCCGCTGAGCGTGACCTCTACCGGGACACCTGGGTGCGG
TACCTGGGCTATGCCAATGAAGTGGGCGAGGCTTTTCGCTCTCTGGTGCCTGCAGCTGTG
GTGTGGCTGAGCTACGGGGTGGCCAGCTCTTATGTGCTGGCTGATGCTGTGGACAAGGGC
AAGAAGGCAGGAGAGGTGCCAAGCCCTGAAGCAGGCCGCAGCACCAGGATGACCGTGGCT
GTGGTGGACACCTTTGTGTGGCAGGCTCTGGCTTCTGTGGCCATCCCCGGCTTCACTGTC
AACCGTGTGTGTGCAGCCTCCCTCTATGTCCTGAGCGCCACGACCCGCTGGCCTCTGGCC
ATTCGCAAGTGGACCACCACCGCACTGGGGCTGCTGATCATCCCAGCCATCGTCCACCCC
ATCGACAGGTCTGTGGATTTCCTCCTGGACTCCAGCCTGCGCAAGCTGTACCCCTCACTG
GAGAAGCCCAGCTCTTCTTGA
>LOXAF68_5.PE13                        501 CDS /gene="ENSLAFG00000005694" /gene_family="HOG000007398" /prote
AACGCCATGCCTGAGCCGCGGGCCGCTGAGCGTGACCTCTACCGAGACACGTGGGTGCGG
TACCTGGGTTATGCAAACGAGGTTGGGGAGGCCTTCCGCTCTCTGGTGCCGGCAGCTGTG
GTGTGGCTGAGCTACGGTGTGTCCAGCTCCTATGTGCTGGCTGATGCCATCGACAAGGGC
AAGAAGGCAGGAGATGTGTCAAGCCCTGAAGCTGGCCGCAGGACTAGGGTGACTGTGGCT
GTGGTGGACACCTTTGTGTGGCAGGCTCTGGCCTCTGTGGCCATCCCAGGCTTCACTGTC
AACCGCGTGTGTGCAGCCTCCCTCTACGTCCTGGGCACCGCCACCCGCTGGCCTCTGGCT
GTCCGCAAGTGGACCACCACTGCAGTGGGGCTGCTGATTATCCCTGTCATTGTCCACCCC
ATTGACAGGTCTGTGGACTTCCTCCTGGACTCCAGCCTGCGCAAGCTGTACCCATCAGTG
GAGAAGCCCAGCTCTTCCTGA
>MACEUGS_1512.PE2                      495 CDS /gene="ENSMEUG00000003325" /gene_family="HOG000007398" /pro
ATGCCGGACCAGCCAAGATGCCCACCCGACCTCTACCGCGACACGTGGGTGCGCTACCTG
GGTTATGCCAATGAAGTGGGAGAGGCCTTCAGAGCTATCGTGCCTACATCCGTGGTGTGG
CTGAGTTACGGAGTGGCCAGCTCCTACGTGGTGGCCGATGCTGTGGACAAGGGCAAGAAG
GCCGGAGCTGCCCTGAGCCCAGAGTCAGGCAGGACCACCAAGATGGCGGTGGCTGTGGTG
GACACATTTGTCTGGCAGGCGCTAGCTTCTGTGGCCATCCCAGGCTTCACCATCAACCGT
CTGTGTGCCGCTTCTCTCTACGTGCTTAGCAGAGCCACCAGCTGGCCCCTGGCTGCCCGC
AAGTGGACAACCACAGCCCTAGGGCTGATGGCCATCCCTGTCATCATTCACCCCATTGAC
AGGTCCGTTGATTTCCTGATGGACTCCAGCTTACGTAAAATCTACCCTTCTCAGAAGAAG
CCCAGCTCGGCCTGA
>MOUSE11.PE90                          501 CDS /gene="ENSMUSG00000004748" /gene_family="HOG000007398" /protein
ATGTCGGAGCAGCAGCGGCAGGGCGCCGAGCGCGACCTCTACCGGGACACGTGGGTGCGC
TACCTGGGCTACGCCAATGAGGTGGGGGAGGCTTTCCGCTCGCTGGTTCCTGCAGCTGTG
GTGTGGTTGAGCTATGGTGTGTCCAGCTCCTATGTCCTGGCCGATGCCATAGACAAAGGC
AAGAAGGCAGGAGAGGTGCCAAGCCCTGAAGCAGGCCGCAACACCAGAATGGCCCTGGCT
GTGGTCGACACCTTTGTGTGGCAGTCTCTGGCCTCTGTGGCTATCCCAGGCTTCACCATC
AACCGTCTGTGTGCTGCCTCTCTCTATGTCTTGGGTACTATGACCCACTGGCCCCCGACT
GTCCGCAAATGGACCACCACCACACTTGGACTGCTGGCCATCCCCGTCATAATCCACCCC
ATCGACAGGTCAGTGGACTTCCTCCTGGACTCTAGCCTGCGCAAGCTGTACCCGTCAGTG
GAGAAGCCCAGCACCCCCTGA
>ORYLA12_13.PE9                        501 CDS /gene="ENSORLG00000007264" /gene_family="HOG000007398" /prote
ATGGATTCCAGTGGAGACACAGCTAAAGCTGTCGATATTTACCGTGACACGTGGGTTCGT
TTCCTTGGATATGCCAATGAAGTTGGGGAAGCCTTCCGTGCTCTGGTGCCAGTGAGTTTT
GTATGGGGCAGCTATGCTGTGGCCACTGCGTACGTCACTGCTGATGCTGTGGATAAAGGG
AAGAAAGCAGCTATTGCACATGGGGACAACCCAGGGAAGACGACCCGAGTAGCTGTTGCA
GTTGTGGACACTTTTGTGTGGCAGGCGCTGGCCTCTGTGATCATCCCCGGCTTCACCATT
AACCGCGTCTGTGCGGCTTCTCTGTACCTGTTGGGAAAAAGCACAAGATGGCCCTTACCA
GCTCGGAAGTGGACCACAACGGCCATAGGACTCTCCACAATCCCTTTCATTATTACCCCA
ATCGACAGGTCAGTGGATTTCCTGCTGGACTCCAGCCTAAGGAAGGTCTACAATGAGGTC
TGTAAACCTGCAACACCATAG
>PIG14_50.PE13                         501 CDS /gene="ENSSSCG00000010007" /gene_family="HOG000007398" /protei
ATGTCTGAGCCGCCCCCGCGGGGGGCCGAGCGCGACCTTTTCCGGGACACGTGGGTGCGG
TACTTGGGCTATGCCAATGAGGTAGGGGAGGCCTTCCGCTCCTTGGTGCCAACAGCTGTT
GTGTGGCTGAGCTATGGTGTGTCCAGCTCCTATGTGCTGGCTGATGCCATTGACAAAGGC
AAGAAGGCAAGAGATGTGCCAAGCCCTGAGGCAGGCCGCAGCACCAGGGTGACCGTGGCC
GTGGTAGACACCTTTGTGTGGCAGGCTCTGGCCTCTGTGGCCATCCCAGGCTTCACTATC
AACCGTGTGTGTGCTGCCTCTCTCTACATCCTGGGCACTGCCACCCGCTGGCCTCTGGCT
GTCCGCAAGTGGACCACTACTGCACTGGGGCTACTGGCCATCCCCATCATCATCCACCCC
ATCGACAGGTCAGTGGACTTCCTCCTGGACTCCAGCCTCCGCAAGCTCTACCCCTCAGTG
GAGAAGCCCAGCTCCTCCTGA
>RAT14.PE832                           501 CDS /gene="ENSRNOG00000004640" /gene_family="HOG000007398" /protein_
ATGTCGGAGCAGCAGCGGCAGAGCACCGAGCGCGACCTCTACCGGGACACGTGGGTGCGC
TACCTGGGCTACGCCAATGAAGTGGGGGAGGCTTTCCGCTCCCTGGTTCCTAAAGCTGTG
GTGTGGTTGAGCTATGGCGTGTCCAGCTCCTATGTCTTGGCCGATGCCATAGACAAAGGC
AAGAAGGCAGGAGAGGTGCCAAGCCCTGAAGCAGGCCGCAGTACCAGAATGGCCCTGGCT
GTGGTAGATACCTTCGTGTGGCAGTCTCTGGCCTCTGTGGCCATTCCGGGCTTCACCATC
AACCGTCTGTGTGCTGCCTCTCTCTATGTCTTGGGTACTATGACCCGCTGGCCCCTGAAT
GTCCGCAAATGGACCACCACCACACTTGGGCTGCTGGCCATCCCTGTCATTGTCCACCCC
ATTGACAGGTCGGTAGACTTCCTCCTGGACTCCAGCCTGCGCAAGCTGTACCCGTCAGTG
GGGAAGCCCAGCACCCCCTGA
>TURTRGS_496.PE11                      501 CDS /gene="ENSTTRG00000001539" /gene_family="HOG000007398" /pro
ATGTCCGAGCCGCCCCCGCGGGGGGCCGAGCGCGACCTTTTCCGGGACACGTGGGTGCGG
TACCTGGGCTACGCCAATGAGGTGGGGGAGGCCTTCCGCTCCCTGGTGCCTGTATCTGTC
GTGTGGCTGAGCTACGGTGTGTCCAGCTCCTACGTGCTGGCTGATGCCATTGACAAGGGC
AAGAAAGCGAGAGACGTGCCAAGCCCTGAGGCAGGCCGCAGCACCAGGGTGACCGTGGCC
ATGGTGGACACCTTCGTGTGGCAGGCTTTGGCCTCTGTGGCCATCCCAGGCTTCACTATC
AACCGTGTGTGTGCTGCCTCTCTCTATATCCTGGGCACTGCTACCCGCTGGCCTCTGGCT
GTCCGCAGGTGGACCACCACCGCACTGGGACTACTGGCCATCCCCATCATCATCCACCCC
ATCGACAGGTCAGTGGACTTCCTCCTGGACTCCAGCCTGCGCAAGCTCTACCCCTCTGTG
GAGAAGCCCAGTTCCTCCTGA
>XENTR91_2.PE6                         480 CDS /gene="ENSXETG00000016147" /gene_family="HOG000007398" /protei
CAGCAGCCGGGCAAGCCCTCCGAGAAAGACTTGTACAGGGACACATGGGTGCGATACCTG
GGTTACGCTAATGAGGTTGGGGAGGCTTTTCGAGCACTAGTTCCCAAAGCATTGGTTTGG
GCCAGCTATGGAGTAGCCACTGCCTATGTCACAGCTGATGCAGCAGATAAGGGCAAAAAA
GCAGCAAATTCTTCTAGAGAAAGCCCAGATCGGACAAAACAAATCACCGTGGCTGTAGTG
GACACTTTTATATGGCAAGCTTTGGCTTCAGTGGCTATTCCAGGCTTTACCATCAATCGT
ATTTGTGCAGCATCTCTCTACCTTATGGGACAAGTAACCCGCTGGCCCCTCCCAGCTCGG
AAGTGGGCAACCACCGCAGTAGGACTGTCTGCAATTCCCATTATTATAACACCAATCGAC
AGGTCAGTAGATTGGATGCTGGACTCCAGTCTTCGGAAACTATATAACAAATCCCATTAG
