>AEDAE_57.PE2                          429 CDS /gene="AAEL014251" /gene_family="HOG000008032" /protein_id="AAE
ATGGTCCAAACGGAGAACATTGAAAAAGTCTACCTGTTCGAGAAGGATCGCGTCAACAGT
TTCAAAAAGTGGCCCTATTCCGGTTCCAGCCCGTGCAACATCCAGAAGATGGCCGAAGCC
GGTTTCTACTGGCAGGGTGACGACAAGGAGGACGAAGACACCTCCGTCTGTTTCGTGTGC
GGCAAGGTCCTGGACGGCTGGGAGGAATCTGATGACCCCTGGGAGGAACACAAGAAGCAC
GCTCCCCAGTGCCTTTTCGTGAAGTACGGTCGACCAGAGGCGGAAATGACGTGTGAGGAA
ATGCTTAACCTGCTGGAGGTCATTCTGAAGGGACGGATTCAGAGCAGCTATACCGCCCTG
AAGGACTGCCTTAAGGCCCACATCGAGAAGAAACGCAAAGAGATGACGAAACAGTTGTCG
AAGAATTAG
>AILMEGL192595_1_2.PE8                 429 CDS /gene="ENSAMEG00000013864" /gene_family="HOG000008032" /pro
ATGGGCGCTTCGTCGTTGCCCCCCGCCTGGCAGTTCTACCTCAAGGACCACCGCGTCTCT
ACGTTCAAGAACTGGCCGTTCTTGGAGGGCTGCGCTTGCACCCCGGAACGGATGGCAGAG
GCCGGCTTCATCCACTGTCCCACTGAGAACGAGCCCGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGATGACCCTATAGAGGAGCATAAAAAGCAT
TCATCTGGTTGTGCTTTTCTTTCTGTCAAGAAGCAGTTTGAAGAGTTAACCCTCAGTGAA
TTTTTGAAACTGGACAAAGAAAGAGCCAAGAACAAAATCGCAAAGGAAACCAACAGTAAG
CAGAAAGAATTTGAAGAGACCGCAAAGAGAGTGCGCGGTGCCATCGAGCAGCTGGCCGCC
GTGGAGTAA
>ANOGA_136.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_137.PE663                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_138.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_139.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_140.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_141.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_142.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_143.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_144.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_145.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_146.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_147.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_148.PE678                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_149.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_150.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_151.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_152.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_153.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_154.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_155.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_156.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_157.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_158.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_159.PE677                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_160.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_161.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_162.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_163.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_164.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_165.PE677                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_166.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_167.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_168.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_169.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>ANOGA_170.PE679                       402 CDS /gene="AGAP008420" /gene_family="HOG000008032" /protein_id="
ATGGAATCCACCCACAACAGTGCTAAAATATACTTACTTCAAGAGGATCGCGAGAAAAGC
TTTAAACATTGGCCATTTTCCGATGATAAACAATGCAGCATACAGAAGATGGCTGAGGCC
GGCTTCTATTGGCACGGGACGGAGACAGAGATAGACATAGCGGCTTGCTTCGTGTGTGGC
AAAGAGCTGGACGGTTGGGAAGAGTCGGACGATCCGTGGAGCGAACACCGGAAGCATGCA
CCACAGTGTCCGTTTGTGAAATTTGGCCGCCCAGAGACGCATCTAACGGTAATGGACGGA
AAGTGCTATTGGTTGAATGATGAAGAGAAGATAAAACTAACGGATATTACTTTTGCCCTC
AACTTGCAGTGCGATGAATTTGTCACTATTATGATGGCCACG
>BOVIN19_56.PE15                       429 CDS /gene="ENSBTAG00000013573" /gene_family="HOG000008032" /prot
ATGGGTGCCCAGTCTTTGCCTCCGGCCTGGCAGCTCTACCTCAAGGACCACCGCGTCTCC
ACGTTTAAGAACTGGCCTTTTTTAGAGGGCTGCGCCTGCACCCCGGAGCGGATGGCCGCG
GCAGGCTTCATCCACTGTCCCACTGAGAACGAGCCCGACTTGGCTCAGTGTTTCTTCTGC
TTCAAGGAGTTGGAAGGCTGGGAACCAGATGACGACCCTATAGAAGAACATAAAAAGCAT
TCATCTGGTTGTGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTCAGTGAA
TTTTTGAAACTGGATAAAGAAAGAACCAAGAACAAAATCGCAAAAGAAACCAACAATAAG
CAGAAAGAATTTGAAGAAACTGCAAAGAAAGTCCGCTGTGCCATTGAGCAGCTGGCTGCC
TTGGAGTGA
>CALJA5_133.PE10                       429 CDS /gene="ENSCJAG00000019490" /gene_family="HOG000008032" /prot
ATGGGTGCCCCGATGTTGCCCCCTGCCTGGCAGCCCTTTCTCAAGGACCACCGCATCTCT
ACATTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGCACCCCGGAGCGGATGGCCGAG
GCGGGCTTCATCCACTGCCCGACTGAGAACGAGCCGGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCATCTGGTTGCGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTTGGTGAA
TTTCTGAAACTGGACAGAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAATAAG
AAGAAAGAATTTGAAGAAACTGCAAAGAAAGTGCGCCGTGCCATCGAGCAGCTGGCTGCC
ATGGAGTGA
>CANFA9_6.PE19                         429 CDS /gene="ENSCAFG00000005302" /gene_family="HOG000008032" /protei
ATGGGCGCTTCGTCGCTGCCCCCCGCCTGGCAGCTCTACCTCAAGGACCACCGCGTCTCT
ACGTTCAAGAACTGGCCGTTCCTGGAGGGCTGCGCCTGCACCCCGGACCGGATGGCAGAG
GCCGGCTTCATCCACTGTCCCACTGAGAACGAGCCAGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGATGACCCTATAGAGGAGCATAAAAAACAT
TCATCTGGTTGTGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTCAGTGAA
TTTTTGAAACTGGACAAAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAACAAG
CAGAAAGAATTCGAAGAGACCGCAAAGAAAGTGCGCTGTGCCATTGAGCAGCTGGCCGCC
GCAGAATAG
>CAVPO76_4.PE8                         429 CDS /gene="ENSCPOG00000027390" /gene_family="HOG000008032" /protei
ATGGGGGCCCCGTCATTGCCCCGGGCGTGGCAGCTCTATCTGAAGGAACACCGTGTCTCT
ACATTCAAGAACTGGCCCTTCGTGAACGGCTGCTCCTGCACTCCGGAACGGATGGCCGAG
GCCGGCTTCATCCACTGCCCCACTGAGAACGAACCTGATTTGGCGCAGTGTTTCTTCTGC
TTCAAGGAGTTGGAAGGCTGGGAGCCAGATGATAACCCCATAGAAGAGCATAAAAAGCAT
TCATCTGGCTGTGCATTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACTCTCAGCGAA
TTTTTAAAACTGGACAAAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAGCAAG
CAGAAGGAATTTGAAGAGACGGCAGCGAAAGTCCGCCAGGCCATGGAGCAGCTGGCCGCC
TTGGAGTGA
>FELCA152633.PE1                       408 CDS /gene="ENSFCAG00000006949" /gene_family="HOG000008032" /prot
CCGGCCTGGCAGCTCTACGTCAATGACCACCGCATCTGGACGTTCAAGAGTTGGCCGTTC
TTGGAGGGCTGCGCATGCACCCAGGAGAGTATGGCCGAGGCCGGCTTCATCCACTGTCCC
ACTGAGAACGAGCCCGATTTGGCTCAGTGTTTCTTCTGCTTCAAGGAGCTGGAAGGCTGG
GAGCCAGACGATGACCCCATAGAGGAACATAAGAAGCATTCATCTGGTTGTGCCTTTCTT
TCTGTCAAGAAGCAGTTTGAAGAATTAACCCTCAGTGAATTTTTGAAACTGGACAAAGAG
AGAGCCAAGAACAAAATTGCAAAGGAAACCAACCATAAACAGAAAGAATTTGAAGAGACT
GCAAAGAGAGTGCGCTGTGCCATTGAGCAGCTGGCGGCCCTGGAGTGA
>HORSE11_5.PE12                        429 CDS /gene="ENSECAG00000008466" /gene_family="HOG000008032" /prote
ATGGGCGCCCCGTCGTTGCCCCCAGCCTGGCAGCTGTATCTCAAGGACCACCGCGTCTCT
ACCTTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGCACTCCGGAGCGGATGGCGGCG
GCCGGCTTCATCCACTGTCCCACTGAGAACGAGCCCGACTTGGCGCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCATCCGGCTGTGCTTTCCTGTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTCAGTGAA
TTTTTGAAACTGGACAAAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAATAAG
CAGAAAGAATTTGAAGAAACTGCAAAGAAAGTTCGCTATGCCATTGAGCAGCTGGCTGCC
TTGGAGTGA
>HORSE11_53.PE7                        429 CDS /gene="ENSECAG00000002695" /gene_family="HOG000008032" /prote
ATGGGTGCCCCGTTGTTGCCCCCGGCCTGGCAGCTCTCCCTCAAGGACCACCGCGTCTCT
ACCTTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGTACCCCGGAGTGGATGGCGGTG
GCCGGCTCCATCCACTGTCCCACTGAGAATGAGCCCAACTTCGCGCAGGGTTTCTTCTGC
TTTAAGGAGCTGCAAGGCTGGGAGCCAGACGAGGACCCCGTAGAGGAGCATGAAAAGCAT
TCATCCGGCTGTGCTTTCCTGTCTGTCAAGAAGCGGTTTGAAGAATTAACCCTCAGTGAA
TTTTTGAAACTGGACAAAGAAAGAGCCAAGAACAAAGTTGCAAAGGAAACCAACAGTAAC
CAGAAAGAATTTGAAGAAACTGCAAAGAAGGTTCATTATGCCATTGAGCAGCTGGCTGCC
TTGGAGTGA
>HS17.PE3143                           429 CDS /gene="ENSG00000089685" /gene_family="HOG000008032" /protein_id=
ATGGGTGCCCCGACGTTGCCCCCTGCCTGGCAGCCCTTTCTCAAGGACCACCGCATCTCT
ACATTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGCACCCCGGAGCGGATGGCCGAG
GCTGGCTTCATCCACTGCCCCACTGAGAACGAGCCAGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCGTCCGGTTGCGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTTGGTGAA
TTTTTGAAACTGGACAGAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAATAAG
AAGAAAGAATTTGAGGAAACTGCGGAGAAAGTGCGCCGTGCCATCGAGCAGCTGGCTGCC
ATGGATTGA
>LOXAF49_5.PE12                        420 CDS /gene="ENSLAFG00000006585" /gene_family="HOG000008032" /prote
ATGGGCGCCCAGCTGTTGCCCCCCGCCTGGCAGCTGTATCTCAAGGATCACCGCATCTCT
ACGTTCAAGAACTGGCCCTTCTTGGAGGGCTGCTCCTGCACTCCGGAGCGGATGGCCGAG
GCTGGCTTCATCCACTGTCCCACTGAGAACGAGCCTGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCATCTGGCTGTGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACTCTCAGTGAA
TTTTTGAAACTGGACAAAGAGCGAGCCAAGAACAAAATTGCAAAGGAAACCAACAGTAAA
CAGAAAGAGTTTGAAGAAACTGCCAAGAAAGTGCGTTCTGCCATTGAGCAGCTGGCCGCC
>MACMU16_77.PE17                       429 CDS /gene="ENSMMUG00000013767" /gene_family="HOG000008032" /prot
ATGGGTGCCCCGACATTGCCCCCTGCCTGGCAGCCCTTTCTCAAGGACCACCGCATCTCT
ACATTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGCACCCCGGAGCGGATGGCCGAG
GCTGGCTTCATCCACTGCCCCACTGAGAACGAGCCAGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCGGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCATCCGGTTGCGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTCGGTGAA
TTTTTGAAACTGGACAGAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAATAAG
AAGAAAGAATTTGAGGAAACTGCAAAGAAAGTGCGCTGTGCCATCGAGCAGCTGGCTGCC
ACGGACTGA
>MOUSE11.PE4168                        423 CDS /gene="ENSMUSG00000017716" /gene_family="HOG000008032" /prote
ATGGGAGCTCCGGCGCTGCCCCAGATCTGGCAGCTGTACCTCAAGAACTACCGCATCGCC
ACCTTCAAGAACTGGCCCTTCCTGGAGGACTGCGCCTGCACCCCAGAGCGAATGGCGGAG
GCTGGCTTCATCCACTGCCCTACCGAGAACGAGCCTGATTTGGCCCAGTGTTTTTTCTGC
TTTAAGGAATTGGAAGGCTGGGAACCCGATGACAACCCGATAGAGGAGCATAGAAAGCAC
TCCCCTGGCTGCGCCTTCCTCACTGTCAAGAAGCAGATGGAAGAACTAACCGTCAGTGAA
TTCTTGAAACTGGACAGACAGAGAGCCAAGAACAAAATTGCAAAGGAGACCAACAACAAG
CAAAAAGAGTTTGAAGAGACTGCAAAGACTACCCGTCAGTCAATTGAGCAGCTGGCTGCC
TAA
>PANTR17_82.PE15                       429 CDS /gene="ENSPTRG00000009707" /gene_family="HOG000008032" /prot
ATGGGTGCCCCGACGTTGCCCCCTGCCTGGCAGCCCTTTCTCAAGGACCACCGCATCTCT
ACATTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGCACCCCGGAGCGGATGGCCGAG
GCTGGCTTCATCCACTGCCCCACTGAGAACGAGCCAGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCGTCCGGTTGCGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTTGGTGAA
TTTTTGAAACTGGACAGAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAATAAG
AAGAAAGAATTTGAGGAAACTGCGAAGAAAGTGCGCTGTGCCATCGAGCAGCTGGCTGCC
ATGGATTGA
>PONPY17_71.PE13                       429 CDS /gene="ENSPPYG00000008687" /gene_family="HOG000008032" /prot
ATGGGTGCCCCGACGTTGCCCCCTGCCTGGCAGCCCTTTCTCAAGGACCACCGCATCTCT
ACATTCAAGAACTGGCCCTTCTTGGAGGGCTGCGCCTGCACCCCGGAGCGGATGGCCGAG
GCTGGCTTCATCCACTGCCCCACTGAGAACGAGCCAGACTTGGCCCAGTGTTTCTTCTGC
TTCAAGGAGCTGGAAGGCTGGGAGCCAGATGACGACCCCATAGAGGAACATAAAAAGCAT
TCGTCCGGTTGCGCTTTCCTTTCTGTCAAGAAGCAGTTTGAAGAATTAACCCTTGGTGAA
TTTTTGAAACTGGACAGAGAAAGAGCCAAGAACAAAATTGCAAAGGAAACCAACAATAAG
AAGAAAGAATTTGAGGAAACTGCGAAGAAAGTGCGCTGTGCCATCGAGCAGCTGGCTGCC
ATGGATTGA
