>AEDAE_14.PE16                         315 CDS /gene="AAEL003942" /gene_family="HOG000224989" /protein_id="AA
ATGGTCAACGTACCCAAGCAGCGTCGTACCTACTGCAAGAAGTGCAAGGTGCACCGCGTC
CACAAGGTCACGCAGTACAAGAAGTCCAAGGAACGTCAAGCTTCGCAGGGTCGTCGCCGT
TACGATCGTAAACAGAAGGGTTTCGGAGGGCAAACCAAGCCCATCTTCAGAAAGAAGGCC
AAGACCACGAAGAAAATCGTGCTGCGTATGGAATGCGTCGACTGCAAGTACCGCAAGCAG
ACCCCGCTGAAGCGCTGTAAGCACTTCGAACTGGGAGGCGACAAGAAGCGAAAGGGACAG
ATGATTCAGTTCTAA
>AILMEGL192881_1_1.PE3                 321 CDS /gene="ENSAMEG00000019379" /gene_family="HOG000224989" /pro
ATGGTCAACGTTCCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGAAAACATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTCTACGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATATTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGTGTGGAACCCAACTGCAGGTCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGTCAAGTGATCCAGTTCTAA
>AILMEGL193876_1.PE11                  318 CDS /gene="ENSAMEG00000009384" /gene_family="HOG000224989" /pro
GTGAACGTTCCTAAAACCCGCCGTACTTTCTGCAAGAAGTGTGGCAAGCACCAGCCCCAC
AAAGTGACACAGTACAAGAAAGGCAAAGATTCTCTTTATGCCCAGGGAAAGCGGCGTTAT
GACAGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCGATTTTCCGGAAAAAGGCTAAA
ACTACAAAGAAGATTGTGCTGAGGCTTGAATGTGTCGAGCCCAACTGCAGATCTAAGAGA
ATGCTGGCTATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAGGGC
CAAGTGATCCAGTTCTAA
>ANOGA_10.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_11.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_12.PE3005                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_13.PE3003                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_14.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_15.PE3002                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_16.PE2999                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_17.PE2996                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_18.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_19.PE3004                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_20.PE3000                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_21.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_22.PE2999                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_23.PE3006                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_24.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_25.PE3004                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_26.PE3002                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_27.PE3004                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_28.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_29.PE3002                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_30.PE3005                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_31.PE2980                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_32.PE2989                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_33.PE2998                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_34.PE3002                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_35.PE2999                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_36.PE2972                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_37.PE3001                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_38.PE2972                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_39.PE3005                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_40.PE3005                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_41.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_42.PE3001                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_43.PE3006                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_44.PE2996                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_45.PE3000                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_46.PE2996                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_47.PE2999                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_48.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_49.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_50.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_51.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_52.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_53.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_54.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_55.PE3004                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_56.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_57.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_58.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_59.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_60.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_61.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_62.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_63.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_64.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_65.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_66.PE3005                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_67.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_68.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_69.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_70.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_71.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_72.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_73.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_74.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_75.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_76.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_77.PE3005                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_78.PE3007                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_79.PE3006                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ANOGA_80.PE3006                       315 CDS /gene="AGAP003538" /gene_family="HOG000224989" /protein_id="
ATGGTAAACGTACCGAAGCAGCGCCGTACGTACTGCAAAAAGTGCAAGGTTCACCGCGTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAACGACAGGCTGCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGTATGGAATGTGTCGAGTGCAAGTACCGCAAACAG
ACCCCACTGAAGCGCTGCAAACACTTCGAGCTCGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAA
>ARALY_3.PE2604                        318 CDS /gene="fgenesh2_kg.3__2555__AT3G23390.1" /gene_family="HOG000
ATGGTGAACATTCCAAAGACAAAGAACACTTACTGTAAGAACAAGGAATGCAAGAAACAT
ACTTTGCACAAGGTTACCCAGTACAAGAAGGGTAAAGACAGTCTTGCTGCTCAAGGAAAG
CGTCGTTATGACCGTAAACAATCTGGTTATGGTGGTCAGACTAAGCCCGTCTTCCACAAG
AAGGCTAAGACCACGAAGAAGATTGTTCTGAGGCTTCAGTGCCAAAGCTGCAAGCACTTT
TCGCAGCGCCCGATCAAGAGGTGCAAGCATTTTGAGATTGGTGGAGACAAGAAGGGAAAG
GGAACATCTCTCTTCTAA
>ARALY_7.PE3004                        318 CDS /gene="scaffold_703188.1" /gene_family="HOG000224989" /protei
ATGGTGAACATTCCTAAAACCAAGAACACTTACTGCAAGAACAAGGAATGCAAGAAGCAT
ACCTTGCACAAGGTTACTCAGTACAAAAAGGGTAAAGACAGTCTCGCTGCCCAAGGAAAG
CGTCGTTATGACCGTAAACAATCTGGTTATGGAGGTCAGACCAAGCCCGTCTTCCACAAG
AAGGCTAAGACAACCAAGAAGATTGTCCTGAGGCTTCAGTGCCAAAGCTGCAAACATTTC
TCTCAACGCCCGATTAAAAGGTGCAAGCACTTTGAGATCGGTGGAGACAAGAAAGGAAAG
GGAACATCTCTCTTTTAA
>ARATH_3.PE3167                        318 CDS /gene="AT3G23390" /gene_family="HOG000224989" /protein_id="AT
ATGGTGAACATTCCAAAGACAAAGAACACTTACTGTAAGAACAAGGAATGCAAAAAGCAT
ACTTTGCACAAGGTTACCCAATACAAGAAGGGTAAAGACAGTCTTGCTGCTCAAGGAAAG
CGTCGTTATGACCGTAAACAATCTGGTTATGGTGGTCAGACTAAGCCTGTCTTCCACAAA
AAGGCTAAGACCACGAAGAAGATTGTTTTGAGGCTTCAGTGTCAAAGCTGCAAGCACTTT
TCGCAGCGTCCTATCAAGAGGTGCAAGCATTTCGAGATCGGTGGTGACAAGAAGGGAAAG
GGAACATCTCTGTTTTAA
>BOVIN10_44.PE3                        321 CDS /gene="ENSBTAG00000025564" /gene_family="HOG000224989" /prote
ATGGTCAACGTACCTAAAACCCGCAGGACTTTCTGTAAGAAGTGTGGAAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAAGATTCCCTGTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAAAGTGGCTACGGTGGGCAAACCAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACCAAGAAGATCGTGCTGAGACTTGAATGCGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGGTGCAAGCATTTTGAACTTGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>BRADI_1.PE2980                        318 CDS /gene="BRADI1G26010" /gene_family="HOG000224989" /protein_id=
ATGGTGAACGTTCCGAAGACCAAGAAGACCTATTGCAAGAACAAGGAGTGCAAGAAGCAC
ACCCTTCACAAGGTCACACAGTACAAGAAGGGGAAAGACAGCCTGTCTGCCCAGGGAAAG
CGCCGTTATGACAGGAAGCAGTCAGGATATGGTGGTCAGACTAAGCCTGTTTTCCACAAG
AAGGCGAAAACCACCAAGAAGATTGTGCTAAAGCTGCAGTGCCAGAGCTGCAAGCACTAC
TCCCAGCGTGCCATCAAGAGGTGCAAGCACTTTGAGATCGGTGGAGACAAGAAGGGCAAG
GGAACATCCCTCTTCTAA
>CAGLA1_8.PE249                        321 CDS /evidence="3: Inferred from homology " /gene_family="HOG00022
ATGGTTAACGTTCCAAAGACTAGAAAGACCTACTGCAAGGGTAAGGCCTGCCGTAAGCAC
ACTCAACACAAGGTTACCCAATACAAGGCTGGTAAGGCTTCCTTGTTCGCTCAAGGTAAG
AGACGTTATGACCGTAAGCAATCTGGTTTCGGTGGTCAAACTAAGCCTGTTTTCCACAAG
AAAGCTAAGACTACCAAGAAGGTTGTCTTGAGATTGGAATGTGTTAACTGTAAGACCAAG
GCTCAATTGACCTTGAAGAGATGTAAGCACTTCGAATTGGGTGGTGAAAAGAAGCAAAAG
GGTCAAGCTTTGCAATTCTGA
>CALJA10_77.PE7                        321 CDS /gene="ENSCJAG00000017409" /gene_family="HOG000224989" /prote
ATGGTCAACGTACCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTACAAGAAGGGCAAGGATTCCTTGTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTCCGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>CALJA5_135.PE15                       321 CDS /gene="ENSCJAG00000022873" /gene_family="HOG000224989" /prot
ATGGTCAATGTACCTAAAACCCGAAGAAGCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGAACAAGAAGGGCAAGGATTCCTCGTGTGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCGAATTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTCCGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AAGATGCTGGCTATTAAGAGATGCAAGCATTTTCAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>CALJAX_92.PE37                        321 CDS /gene="ENSCJAG00000004864" /gene_family="HOG000224989" /prote
ATGGTCAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAAGATTCTCTGTATGCCCAGGGAAAGCGGCGT
TATGACAGAAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAGACTACAAAGAAGATTGTGCTGAGGCTCGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAACATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>CANFA8_30.PE5                         321 CDS /gene="ENSCAFG00000011410" /gene_family="HOG000224989" /protei
ATGGTCAATGTTCCCAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGAAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTTTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGCGTTGAACCTAACTGCAGGTCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTCGAACTGGGAGGAGATAAGAAGAGAAAA
GGCCAAGTGATCCAGTTCTAA
>CANFA8_30.PE6                         321 CDS /gene="ENSCAFG00000011410" /gene_family="HOG000224989" /protei
ATGGTCAATGTTCCCAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGAAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTTTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGCGTTGAACCTAACTGCAGGTCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTCGAACTGGGAGGAGATAAGAAGAGAAAA
GGCCAAGTGATCCAGTTCTAA
>CANFAX_80.PE10                        321 CDS /gene="ENSCAFG00000017688" /gene_family="HOG000224989" /prote
ATGGTGAATGTTCCTAAAACCCGCCGGACTTTCTGCAAGAAGTGTGGTAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAAGGCAAAGATTCTCTTTACGCTCAGGGAAAGCGGCGT
TATGACCGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCGATCTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAATGTGTTGAGCCCAACTGCAGATCGAAG
AGAATGCTGGCTATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>CANFAX_80.PE11                        318 CDS /gene="ENSCAFG00000017688" /gene_family="HOG000224989" /prote
GTGAATGTTCCTAAAACCCGCCGGACTTTCTGCAAGAAGTGTGGTAAGCACCAACCCCAC
AAAGTGACACAGTACAAGAAAGGCAAAGATTCTCTTTACGCTCAGGGAAAGCGGCGTTAT
GACCGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCGATCTTCCGGAAAAAGGCTAAA
ACTACAAAGAAGATTGTGCTGAGGCTTGAATGTGTTGAGCCCAACTGCAGATCGAAGAGA
ATGCTGGCTATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAGGGC
CAAGTGATCCAGTTCTAA
>CHOHO21881.PE1                        321 CDS /gene="ENSCHOG00000009574" /gene_family="HOG000224989" /prote
ATGGTCAATGTACCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGAGGGCAGACGAAACCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGTGTGGAGCCTAACTGCAGATCAAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAATTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>CULQU_1613.PE6                        315 CDS /gene="CPIJ009651" /gene_family="HOG000224989" /protein_id="C
ATGGTGAACGTGCCCAAGCAGCGCCGTACCTACTGCAAGAAGTGCAAGGTGCACCGCGTC
CACAAGGTGACACAGTACAAGAAGTCCAAGGAGCGACAGGCGTCCCAGGGTCGTCGTCGT
TACGATCGTAAACAGAAGGGTTTCGGTGGTCAAACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAAATCGTGCTGCGCATGGAGTGCGTCGACTGCAAGTACCGCAAGCAG
ACCCCGCTGAAGCGCTGCAAGCACTTCGAGCTGGGAGGCGACAAGAAGCGCAAGGGCCAG
ATGATTCAGTTCTAA
>DASNOGS_2694.PE3                      321 CDS /gene="ENSDNOG00000015954" /gene_family="HOG000224989" /pro
ATGGTGAATGTTCCTAAAACCCGCCGAACTTTCTGTAAGAAGTGCGGCAAGCATCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTATATGCCCAGGGAAAGCGGCGT
TATGACAGGGAACAGAGTGGTTACGGTGGGCAGACTAGGCCAATTTTCCGGGAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTCGAATGTGTTGAGCCCAATTGCAGATCTAAG
AGGATGTTGGCTATTAAGAGATGCAAACACTTTGAACTAGGAGGCGACAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>DROME2L_9.PE58                        315 CDS /gene="FBgn0031980" /gene_family="HOG000224989" /protein_id="
ATGGTGAACGTACCGAAACAACGCCGCACCTTCTGCAAGAAGTGCAAGGTCCACAAGCTG
CACAAGGTGACGCAGTACAAGAAGTCCAAGGAGCGCAAGGGAGCTCAGGGCAGGCGTCGT
TACGACAGGAAACAGCAGGGTTTCGGAGGTCAGACCAAGCCCATCTTCAGGAAGAAGGCC
AAGACCACCAAGAAGATTGTGCTGCGTATGGAGTGCACCGAGTGCAAATACCGCAAGCAG
ACTCCCCTGAAGCGTTGCAAGCACTTCGAGCTGGGCGGTGACAAGAAGCGCAAGGGACAG
ATGATCCAGTTCTAG
>FELCAGS_3498.PE2                      321 CDS /gene="ENSFCAG00000009120" /gene_family="HOG000224989" /pro
ATGGTCAATGTTCCGAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGAAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAGGGAAAGAGGCGC
TACGATCGGAAGCAGAGTGGCTATGGTGGGCAGACGAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGTGTCGAACCTAACTGCAGGTCCAAG
AGGATGCTGGCCATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>GORGO14_32.PE3                        321 CDS /gene="ENSGGOG00000011105" /gene_family="HOG000224989" /prote
ATGGTCAACGTACCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTCTTTGTATGCCCAGGGAAGGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>GORGO14_48.PE12                       315 CDS /gene="ENSGGOG00000011986" /gene_family="HOG000224989" /prot
ATGGTCAATGTGCCTAAAACCAGAAGAGCTTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
TACAAAGTGCCCCAGTATAAGGGCAAGGATTCCTCCTATGCCCAGGGGAAGATGCGCTGT
GATCAGAAGCAGCGTGGCTACGGTGGGCAGACAAAACTGATTTTCTGGAAGAAGGCTGAA
ACTACCCAGATGATTGTGCTAAGGCTGGAATGTAGGGAGCCTAACTGCAGATCCAAGGGG
ATGCTAGCCATTCAGAAATGCAAAGCAGGAAGGCAGGGAGGGGACAGCAAAAGAGAAGGT
TTCCAAGAAAGGTTA
>GORGO15_58.PE24                       318 CDS /gene="ENSGGOG00000022491" /gene_family="HOG000224989" /prot
ATGGTCAATGTACCTAAAACCCGAAGAGCCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGAGCAAGGATTCCTTGTATGCCCAGGGAAAAAGGTGC
TATGATCGGAAGCAGAGTAGCCATGGTGGGCAGACAAAGCCAATTTTCTGGAAGAAGGCT
AAGACCACAAAGAAGGTTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGAAGGAGATAAGAGAAAGGGC
CAAGTGATCCAGTTCTAA
>GORGO7_16.PE4                         321 CDS /gene="ENSGGOG00000025024" /gene_family="HOG000224989" /protei
CTGGTTAACCTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CATAAAGTGACACAGTACAAGAAGGGCAAGGATTATCTGTATGCCCATGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACCAAGCTGATTTTCCGGAAAAAGGCT
AAAGCTACAAAGAAGATTGTCCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCCGCCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAATAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>GORGOX_101.PE24                       321 CDS /gene="ENSGGOG00000009460" /gene_family="HOG000224989" /prot
ATGGTTAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CATAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTACGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>HORSEX_82.PE2                         321 CDS /gene="ENSECAG00000015464" /gene_family="HOG000224989" /protei
ATGGTGAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTAACACAATACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAATGTGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATCAAGAGATGCAAGCATTTTGAACTTGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>HS14.PE572                            321 CDS /gene="ENSG00000165502" /gene_family="HOG000224989" /protein_id="
ATGGTCAACGTACCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTCTTTGTATGCCCAGGGAAGGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>HSX.PE1704                            321 CDS /gene="ENSG00000241343" /gene_family="HOG000224989" /protein_id="
ATGGTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CATAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTACGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>KLLAC1_5.PE320                        321 CDS /evidence="3: Inferred from homology " /gene_family="HOG00022
ATGGTTAACGTTCCAAAGACCAGAAAGACTTACTGTAAGGGTAAGGAGTGCCGTAAGCAC
GCCCAACACAAGGTTACCCAATACAAGGCTGGTAAGGCTTCCTTGTACGCTCAAGGTAAG
AGAAGATATGACCGTAAACAATCTGGTTTCGGTGGTCAAACCAAGCAAATTTTCCACAAG
AAAGCTAAGACTACCAAGAAGGTCGTTTTGAGATTGGAATGTATGTCCTGTAAGACCAAG
ACCCAATTGGCTTTGAAGAGATGTAAGCACTTCGAATTGGGTGGTGAAAAGAAGCAAAAG
GGTCAAGCTTTGCAATTCTGA
>LEDON1_13.PE140                       321 CDS /transl_table=1 /gene_family="HOG000224989" /locus_tag="LDBP
ATGGTGAACTATCCGAAGAAGAAGGTGATGCACTGCGGCGACGCGCGCTGCAACGCGCAC
AAGTCGTTCAAGGTGGTGCAGTACAAGGCCGGTAAGGCCCGCCTTTTTGCTCGCGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGTGGTCAGACCAAGCCCGTCTTCCACAAG
AAGGCCAAGACTACCAAGAAGATTGTGCTGAAACTCCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTCGTCCTCAAGCGCACGAAGCATTTTGAGCTGAACGACAAGAAGAAGACAGGC
AACAAGGACCCCACCTGGTAA
>LEDON1_33.PE338                       321 CDS /transl_table=1 /gene_family="HOG000224989" /locus_tag="LDBP
ATGGTGAACTATCCGAAGAAGAAGGTGATGCACTGCGGCGACGCGCGCTGCAACGCACAC
AAGTCGTTCAAGGTGGTGCAGTATAAGGCCGGCAAGGCCCGCCTTTTTGCTCGCGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGTGGTCAGACCAAGCCGGTCTTCCACAAG
AAGGCCAAGACGACCAAGAAGATTGTGTTGAAACTCCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTTGTCCTCAAGCGCACGAAGCACTTTGAGCTGAACGACAAGAAGAAGACCGGC
AACAAGGACCCCACCTGGTAA
>LEINF1_33.PE298                       321 CDS /locus_tag="LinJ33.3020" /gene_family="HOG000224989" /codon_
ATGGTGAACTATCCGAAGAAGAAGGTGATGCACTGCGGCGACGCGCGCTGCAACGCACAC
AAGTCGTTCAAGGTGGTGCAGTATAAGGCCGGCAAGGCCCGCCTTTTTGCTCGCGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGTGGTCAGACCAAGCCCGTCTTCCACAAG
AAGGCCAAGACTACCAAGAAGATTGTGCTGAAACTCCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTTGTCCTCAAGCGCACGAAGCACTTTGAGCTGAACGACAAGAAGAAGACCGGC
AACAAGGACCCCACCTGGTAA
>LEINF1_4.PE64                         321 CDS /locus_tag="LinJ03.0640" /gene_family="HOG000224989" /codon_st
ATGGTGAACTATCCGAAGAAGAAGGTGATGCACTGCGGCGACGCGCGCTGCAACGCGCAC
AAGTCGTTCAAGGTGGTGCAGTACAAGGCCGGCAAGGCCCGCCTTTTTGCTCGCGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGTGGTCAGACCAAGCCCGTCTTCCACAAG
AAGGCCAAGACTACCAAGAAGATTGTGCTGAAACTCCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTTGTCCTCAAGCGCACGAAGCATTTTGAGCTGAACGACAAGAAGAAGACAGGC
AACAAGGACCCCACCTGGTAA
>LEMAJ1_13.PE167                       321 CDS /transl_table=1 /gene_family="HOG000224989" /locus_tag="LMJF
ATGGTGAACTACCCGAAGAAGAAGGTGATGCACTGCGGCGACGCGCGCTGCAACGCGCAC
AAGTCGTTCAAGGTGGTGCAGTACAAGGCCGGCAAGGCCCGCCTTTTCGCTCGGGGTAAG
CGTCGTTACGATCGCAAGCAGTCTGGTTATGGCGGTCAGACCAAGCCTGTCTTTCACAAG
AAGGCCAAGACGACCAAGAAGATTGTGCTGAAGCTCCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTTGTCCTCAAGCGCACGAAGCACTTTGAGCTGAACGATAAGAAGAAGACGGGC
AACAAGGACCCCACCTGGTAA
>LEMAJ1_33.PE368                       321 CDS /transl_table=1 /gene_family="HOG000224989" /locus_tag="LMJF
ATGGTGAACTACCCGAAGAAGAAGGTGATGCACTGCGGCGACGCGCGCTGCAACGCGCAC
AAGTCGTTCAAGGTGGTGCAGTACAAGGCCGGCAAGGCCCGCCTTTTTGCTCGGGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGCGGTCAGACCAAGCCTGTCTTTCACAAG
AAGGCCAAGACGACCAAGAAGATTGTGCTGAAGCTCCAGTGCTCTGGTTGCAAGTCTATC
CGTCAGGTTGTCCTCAAGCGCACGAAGCACTTTGAGCTGAACGACAAAAAAAAGACCGGC
AACAAGGATCCCACCTGGTAA
>LEMEX1_13.PE157                       321 CDS /transl_table=1 /gene_family="HOG000224989" /locus_tag="LMXM
ATGGTGAACTATCCGAAGAAGAAGGTGATGCACTGCAGCGACGCGCGCTGCAACGCGCAC
AAGTCGTTCAAGGTGGTGCAGTACAAGGCCGGCAAGGCCCGCCTTTTTGCTCGCGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGTGGCCAGACCAAGCCCGTCTTCCACAAG
AAGGCCAAGACGACCAAGAAGATTGTGCTGAAGCTGCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTTGTCCTCAAGCGCACGAAGCACTTTGAGCTGAACGACAAGAAGAAGACGGGC
AACAAGGACCCCACCTGGTAA
>LEMEX1_31.PE337                       321 CDS /transl_table=1 /gene_family="HOG000224989" /locus_tag="LMXM
ATGGTGAACTATCCGAAGAAGAAGGTGATGCACTGCAGCGACGCGCGCTGCAACGCGCAC
AAGTCGTTCAAGGTGGTGCAGTACAAGGCCGGTAAGGCCCGCCTTTTTGCTCGCGGTAAG
CGTCGTTACGACCGCAAGCAGTCTGGTTATGGTGGCCAGACCAAGCCCGTCTTCCACAAG
AAGGCCAAGACGACCAAGAAGATTGTGCTGAAGCTGCAGTGCTCTGGTTGCAAGTCTATC
CGCCAGGTTGTCCTCAAGCGCACGAAGCACTTTGAGCTGAACGACAAGAAGAAGACGGGC
AACAAGGACCCCACCTGGTAA
>LOXAF130_2.PE17                       318 CDS /gene="ENSLAFG00000017385" /gene_family="HOG000224989" /prot
GTGAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCCCAC
AAAGTGACACAGTACAAGAAAGGCAAAGATTCTCTATATGCCCAGGGAAAGCGGCGTTAT
GACAGGAAGCAGAGTGGATACGGTGGGCAGACTAAGCCGATTTTCCGGAAGAAGGCTAAA
ACTACAAAGAAGATTGTGTTGAGGCTTGAATGTGTTGAGCCCAACTGCAGATCTAAGAGA
ATGCTGGCTATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAGGGC
CAAGTGATCCAGTTCTAA
>MACMU1099214739774.PE3                321 CDS /gene="ENSMMUG00000008286" /gene_family="HOG000224989" /pro
ATGGTCAACGTGCCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTCTTTGTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>MACMU11_76.PE10                       321 CDS /gene="ENSMMUG00000031717" /gene_family="HOG000224989" /prot
ATGGTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>MACMU14_2.PE20                        321 CDS /gene="ENSMMUG00000031273" /gene_family="HOG000224989" /prote
ATGGTGAACGTCCCTAAAACCCGTCGGACGTTCTGTAAGAAGTATGACAAGCACCAGCCC
CACAAAGTGACCCAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCCAGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCACACTAAGCTGATTTTCTGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGTGTTGAGCCCAACCACAGATCTGAG
AGAATGCTGGCTACTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGACGAGAAAG
GGCCAAGTGATCCAATTCTAA
>MACMU16_56.PE49                       321 CDS /gene="ENSMMUG00000029950" /gene_family="HOG000224989" /prot
ATGGTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAGGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCAGCGT
TATGATAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTAGCTATTAAAAGATGTAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>MACMU4_119.PE3                        321 CDS /gene="ENSMMUG00000029458" /gene_family="HOG000224989" /prote
ATCGTCAACGTACCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTCTTTGTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>MACMU5_184.PE4                        321 CDS /gene="ENSMMUG00000021281" /gene_family="HOG000224989" /prote
ATGGTTAACGTCCCTAAAACCCACTGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGCTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>MACMUX_102.PE36                       318 CDS /gene="ENSMMUG00000019576" /gene_family="HOG000224989" /prot
GTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCCCAC
AAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCGTTAT
GACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCTAAA
ACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAGAGA
ATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAGGGC
CAAGTGATCCAGTTCTAA
>MACMUX_45.PE2                         321 CDS /gene="ENSMMUG00000032470" /gene_family="HOG000224989" /protei
ATGGTCAACGTGCCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTATTTGTATGCCCAGGGAAAGAGGCGC
TATGATCAGAAGCAGAGTGGCTGTGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTAGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>MAIZE_3.PE12909                       318 CDS /gene="GRMZM2G125527" /gene_family="HOG000224989" /protein_i
ATGGTGAACGTTCCTAAGACCAAGAAGACGTACTGCAAGAACAAAGAGTGCAAGAAGCAC
ACACTCCACAAGGTGACTCAGTATAAGAAGGGCAAGGATAGCCTGTCTGCCCAGGGAAAG
CGCCGTTATGACCGCAAGCAGTCAGGATATGGTGGTCAGACCAAGCCTGTCTTCCACAAG
AAGGCCAAGACCACCAAGAAGATTGTTCTGAAGCTGCAGTGCCAGAGCTGCAAGCACTAC
TCACAGCACGCCATCAAGAGATGCAAGCATTTTGAGATTGGTGGAGACAAGAAGGGCAAG
GGCACATCTCTTTTCTAA
>MAIZE_8.PE8439                        318 CDS /gene="GRMZM2G009412" /gene_family="HOG000224989" /protein_id
ATGGTGAACGTTCCTAAGACCAAGAAGACCTACTGCAAGAACAAGGAGTGCAAGAAGCAC
ACTCTCCACAAGGTTACTCAGTACAAGAAGGGTAAGGATAGCCTGTCTGCCCAGGGAAAG
CGCCGTTATGACCGCAAGCAGTCAGGATATGGTGGCCAGACCAAGCCTGTCTTCCACAAG
AAGGCCAAGACCACCAAGAAAATCGTATTGAAGCTGCAGTGCCAGAGCTGCAAGCACTAC
TCACAGCACGCAATTAAGAGGTGCAAGCATTTTGAGATTGGTGGAGACAAGAAGGGCAAG
GGAACATCTCTCTTCTAA
>MAIZE_8.PE8441                        315 CDS /gene="GRMZM2G009412" /gene_family="HOG000224989" /protein_id
GTGAACGTTCCTAAGACCAAGAAGACCTACTGCAAGAACAAGGAGTGCAAGAAGCACACT
CTCCACAAGGTTACTCAGTACAAGAAGGGTAAGGATAGCCTGTCTGCCCAGGGAAAGCGC
CGTTATGACCGCAAGCAGTCAGGATATGGTGGCCAGACCAAGCCTGTCTTCCACAAGAAG
GCCAAGACCACCAAGAAAATCGTATTGAAGCTGCAGTGCCAGAGCTGCAAGCACTACTCA
CAGCACGCAATTAAGAGGTGCAAGCATTTTGAGATTGGTGGAGACAAGAAGGGCAAGGGA
ACATCTCTCTTCTAA
>MOUSE12.PE488                         321 CDS /gene="ENSMUSG00000049751" /gene_family="HOG000224989" /protei
ATGGTCAACGTACCAAAAACCCGAAGGACTTTCTGTAAGAAATGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAAGGAAAGCGGCGC
TACGATCGCAAGCAGAGTGGCTACGGTGGGCAGACAAAGCCAATCTTTCGAAAGAAGGCC
AAAACCACAAAGAAGATTGTGCTCAGGCTTGAGTGTGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGCGACAAGAAGAGGAAG
GGCCAAGTGATCCAGTTCTAA
>MOUSE12.PE489                         321 CDS /gene="ENSMUSG00000049751" /gene_family="HOG000224989" /protei
ATGGTCAACGTACCAAAAACCCGAAGGACTTTCTGTAAGAAATGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAAGGAAAGCGGCGC
TACGATCGCAAGCAGAGTGGCTACGGTGGGCAGACAAAGCCAATCTTTCGAAAGAAGGCC
AAAACCACAAAGAAGATTGTGCTCAGGCTTGAGTGTGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGCGACAAGAAGAGGAAG
GGCCAAGTGATCCAGTTCTAA
>MOUSE12.PE490                         321 CDS /gene="ENSMUSG00000049751" /gene_family="HOG000224989" /protei
ATGGTCAACGTACCAAAAACCCGAAGGACTTTCTGTAAGAAATGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAAGGAAAGCGGCGC
TACGATCGCAAGCAGAGTGGCTACGGTGGGCAGACAAAGCCAATCTTTCGAAAGAAGGCC
AAAACCACAAAGAAGATTGTGCTCAGGCTTGAGTGTGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGCGACAAGAAGAGGAAG
GGCCAAGTGATCCAGTTCTAA
>MYOLUGS_6268.PE5                      321 CDS /gene="ENSMLUG00000013891" /gene_family="HOG000224989" /pro
ATGGTGAATGTGCCTAAAAACCGAAAAACCTTCTGTAAGAAGTGTGGAAGGCATCGGTCT
CACAAAGTGACCCAGTATAAGAAGGGGAAGGATTCCCTCTACGCCCAGGGAAAGAGGCGC
TACGATAGGAAGCAGAGTGGTTACGGTGGGCAGACAAAGCCGATTTTCCGAAAGAAAGCG
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAATGTTCCGACGCTAACTGCAGATCAAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>OSTLU_11.PE94                         312 CDS /codon_start=1 /gene_family="HOG000224989" /evidence="3: Infer
ATGGTGAACGTGCCGAAATCTAAGAAGACGTTCTGCAAGGGGTGCAAGAAGCACTCCGCG
CACAAGGTGACGCAGTACAAGACGGGCAAGGCGAGCCTGTACGCGCAAGGGAAGCGTCGT
TACGATTCCAAACAAGCGGGGTACGGTGGCCAAACCAAGCCGGTGTTCCACAAGAAGGCG
AAGACGACGAAGAAGATTGTCTTGCGCTTGCAGTGCGGTACGTGCAAACAAGTCCACATG
CACCCGATCAAGCGTTGCAAGATGTTCGAAATCGGCGGTGACAAGAAGAAGCACGTGACG
ACGAACTACTAG
>OTOGAGS_940.PE4                       321 CDS /gene="ENSOGAG00000004551" /gene_family="HOG000224989" /prot
ATGGTGAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAGCCC
CACAAAGTGACACAGTACAAGAAGGGCAAGGACTCTCTCTATGCTCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCAATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAGTGTGTGGAGCCAAACTGCAGATCTAAG
AGAATGCTAGCTATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGTCAAGTGATACAGTTCTAA
>PANTR14_50.PE7                        321 CDS /gene="ENSPTRG00000006315" /gene_family="HOG000224989" /prote
ATGGTCAACGTACCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTCTTTGTATGCCCAGGGAAGGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGACAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PANTRX_101.PE23                       321 CDS /gene="ENSPTRG00000022105" /gene_family="HOG000224989" /prot
ATGGTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CATAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTACGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PHINF1_4589.PE78                      312 CDS /gene="PITG_05171" /gene_family="HOG000224989" /protein_id=
ATGGTGAACATGCCGAAGGAACGCCGCACTTATTGCAAGGGCAAGAAGTGCCAGAAGCAC
ACGGTGCACAAGATCACCCAGTACAAGGCCGGTAAGGCCTCCAAGTACGCCCAGGGTGCT
CGTCGTTATAACGACAAGCAGAAGGGTTTCGGTGGTCAGACCAAGCCCGTGTTCCACAAG
AAGGCGAAGACCACCAAGAAGATCACGCTGCGTATGGAGTGCAAGGAGTGCAAGGTCAAG
AAGCAGCTGCCCATGAAGCGCACGAAGCACTTTGAGCTTGGTGAGAAGAAGAAATCCGCT
GGCCACCAGTAC
>PHPAT1_643.PE183                      318 CDS /gene="ESTEXT_GWP_GW1.C_220261" /gene_family="HOG000224989"
ATGGTGAACGTTCCGAAAACCAAGAAGTCCTTCTGTCCAGGGAAGGCGTGCAAGAAGCAC
ACCCTCCACAAGGTCACCCAGTACAAGAAGGGAAAGGATAGTTTGTACGCACAAGGTAAG
AGGAGATATGACAGGAAACAATCAGGATACGGAGGTCAGACCAAGCCTGTCTTCCACAAG
AAGGCTAAGACTACCAAGAAGATTGTACTGAGGTTACAGTGCCAGGCTTGCAAGCACGTG
ACACAACATCCTATCAAGCGATGCAAGCACTTCGAGATCGGAGGAGACAAGAAGGGCAAG
GGAACACAACTCTTCTAG
>PICPG_3.PE189                         321 CDS /locus_tag="PAS_chr3_0194" /gene_family="HOG000224989" /produc
ATGGTTAACGTTCCTAAGACTAGAAAGACCTTTTGCAAAGGTAAGCAATGCCGTAAGCAC
ACTCAACACAAGGTTACCCAATACAAGGCTGGTGCTGCTTCCCTGTTCGCTCAGGGTAAG
AGACGTTATGACCGTAAGCAATCTGGTTACGGTGGTCAAACCAAGCAGATTTTCCACAAG
AAAGCTAAGACTACCAAGAAGGTTGTTTTGCGTTTGGAATGTGTTGTCTGTAAGACCAAG
GCTCAGTTGGCTTTAAAGAGATGTAAGCACTTCGAGCTAGGTGGTGACAAGAAACAAAAG
GGTCAAGCTCTGCAATTCTAG
>PIG1_192.PE4                          321 CDS /gene="ENSSSCG00000005005" /gene_family="HOG000224989" /protein
ATGGTCAACGTACCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGAAAACATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTCTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAACAGAGTGGCTATGGCGGGCAAACAAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGTGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCAATTAAGAGATGCAAGCATTTTGAACTTGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PONPY14_51.PE5                        321 CDS /gene="ENSPPYG00000005788" /gene_family="HOG000224989" /prote
ATGGTCAATGTACCTAAAACCCGAAGAACCTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACACAGTATAAGAAGGGCAAGGATTCTTTGTATGCCCAGGGAAGGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAGACCACAAAGAAGATTGTGCTAAGGCTGGAATGTGTTGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PONPY17_68.PE32                       321 CDS /gene="ENSPPYG00000008627" /gene_family="HOG000224989" /prot
ATGGTCAACGTTCCTAAAACTCGCTGGACTTTCTCTAAGAAGTGCGGCAAGCACCAACCC
CACAAAGTGACACAGTACGAGAAGGGTAAGGATTCTCTATATGCCCAGGGAAAGTGGCGT
TACGACAGGAAACAGAGTGGCTATGGTGGGCAGACTAAGCCGATTTTCCGGAAAAAGGCT
GAAACCACAAAGAAGACTGTGCTAAGGCTTGAGTGCATTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PONPY18_19.PE1                        318 CDS /gene="ENSPPYG00000008977" /gene_family="HOG000224989" /prote
ATGGTTAACGTCCCTAAAACCCACCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCTT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCAATTTTCCGGAAAAAGGCT
AAAACTACGAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCCAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCCGTTC
>PONPY1_54.PE3                         318 CDS /gene="ENSPPYG00000000378" /gene_family="HOG000224989" /protei
GTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCCCAT
AAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCGTTAT
GACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCTAAA
ACTACAAAGAAGATTGTGCTAAGGCTTGAGTGTGTTGAGCCCAACTGCAGATCTAAGAGA
ATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAGGGC
CAAGTGATCCAGTTCTAA
>PONPYX_101.PE18                       321 CDS /gene="ENSPPYG00000025837" /gene_family="HOG000224989" /prot
ATGGTTAACGTCCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CATAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTCTATGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAAACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTAAGGCTTGAGTGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATTAAAAGATGCAAGCATTTTGAACTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PTEVAGS_3158.PE8                      321 CDS /gene="ENSPVAG00000001569" /gene_family="HOG000224989" /pro
ATGGTGAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGTGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAAGACTCTCTGTATGCGCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGTTATGGTGGGCAGACTAAGCCGATTTTCCGCAAAAAGGCT
AAAACTACAAAGAAGATTGTCTTGAGGCTTGAATGCGTTGAGCCCAACTGCAGATCTAAG
AGAATGCTGGCTATAAAGAGATGCAAGCATTTTGAACTGGGAGGAGATAAAAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>PTEVAGS_3998.PE3                      321 CDS /gene="ENSPVAG00000013479" /gene_family="HOG000224989" /pro
ATGGTCAATGTGCCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAGGGAAAAAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACGAAGCCGATTTTCCGGAAGAAGGCG
AAAACCACAAAGAAGATTGTGCTGAGGCTTGAATGTGTGGAGCCTAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTTGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>RABIT11_41.PE2                        321 CDS /gene="ENSOCUG00000025979" /gene_family="HOG000224989" /prote
ATGGTGAACGTTCCGAAAACCCGCCGGACCTTCTGTAAGAAGTGTGGCAAGCACCAGCCC
CACAAGGTGACACAGTATAAGAAGGGCAAAGACTCTCTCTATGCCCAGGGAAAGCGGCGT
TATGATAGGAAGCAGAGTGGCTATGGGGGACAGACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAGTGTGTGGAGCCCAACTGCAGATCCAAG
AGAATGTTGGCTATTAAGAGATGTAAACACTTTGAATTGGGAGGAGATAAGAAGAGAAAG
GGGCAAGTGATCCAGTTCTAA
>RABIT16_24.PE11                       321 CDS /gene="ENSOCUG00000017531" /gene_family="HOG000224989" /prot
ATGGTGAACGTTCCGAAAACCCGCCGGACCTTCTGTAAGAAGTGTGGCAAGCACCAGCCC
CACAAGGTGACACAGTATAAGAAGGGCAAAGACTCTCTGTATGCCCAGGGAAAGCGGCGT
TATGATAGGAAGCAGAGTGGCTATGGGGGACAGACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAGTGTGTGGAGCCCAACTGCAGATCCAAG
AGAATGTTGGCTATTAAGAGATGTAAACACTTTGAATTGGGAGGAGATAAGAAGAGAAAG
GGGCAAGTGATCCAGTTCTAA
>RABIT17_71.PE3                        321 CDS /gene="ENSOCUG00000027946" /gene_family="HOG000224989" /prote
ATGGTCAATGTACCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAGGGGAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAAGCT
AAAACCACGAAGAAGATTGTGCTACGGCTTGAATGTGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGTGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>RABIT2_31.PE5                         321 CDS /gene="ENSOCUG00000015459" /gene_family="HOG000224989" /protei
ATGGTCAATGTACCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAGGGGAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAAGCT
AAAACCACGAAGAAGATTGTGCTACGGCTTGAATGTGTTGAGCCCAACTGCAGATCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGTGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTAA
>RABITX_89.PE19                        321 CDS /gene="ENSOCUG00000010855" /gene_family="HOG000224989" /prote
CAGGTGAACGTTCCGAAAACCCGCCGGACCTTCTGTAAGAAGTGTGGCAAGCACCAGCCC
CACAAGGTGACACAGTATAAGAAGGGCAAAGACTCTCTCTATGCCCAGGGAAAGCGGCGT
TATGATAGGAAGCAGAGTGGCTATGGGGGACAGACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAGTGTGTGGAGCCCAACTGCAGATCCAAG
AGAATGTTGGCTATTAAGAGATGTAAACACTTTGAATTGGGAGGAGATAAGAAGAGAAAG
GGGCAAGTGATCCAGTTCTAA
>RAT1.PE826                            318 CDS /gene="ENSRNOG00000032062" /gene_family="HOG000224989" /protein_i
ATGGTGAACGTTCCTAAGACCCGCCAGACATTCTGCAAGAAATGTGGGAAGCACCAACCC
CATAAGGTGACGCAATACAAGAATGGCAAGGATTCTTTGTATGCCCAGGGAAAGCAGCGT
TATGACAGGAAACAGAGTGGCCACGGCGGGCAGACTAAGACCATTTTCTGCAAAAAGGCT
AAAACTACAGAGAAGATTGTGCTGAGACTGGAGTGCGTTAAGCCCAACTGCAGATCTAAG
AGGATGCTGCCTATTAAGAGATGCAAGCCTTTTGAACTGGGAGGTGACAAGAAGAGAAAG
GATCCAGTTCTAAGGTTT
>RAT6.PE618                            321 CDS /gene="ENSRNOG00000031022" /gene_family="HOG000224989" /protein_i
ATGGTCAACGTACCTAAAACCCGAAGGACTTTCTGTAAGAAATGTGGCAAGCACCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCCCAAGGAAAGCGGCGC
TACGACCGGAAGCAGAGTGGCTATGGCGGGCAAACAAAGCCAATTTTTCGAAAGAAGGCC
AAAACCACAAAGAAGATTGTGCTCAGGCTTGAGTGTGTTGAGCCCAACTGCAGATCTAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTGGGAGGCGACAAGAAGAGAAAG
GGTCAAGTGATCCAGTTCTAA
>SORBI_1.PE216                         317 CDS /gene="Sb01g001840" /gene_family="HOG000224989" /protein_id="S
ATGGTGAACGTTCCTAAGACCAAGAAGACCTACTGCAAGAACAAGGAGTGCAGGAAGCAC
ACTCTCCACAAGGTTACTCAGTACAAAAAGGGTAAGGATAGCCTAGCTGCTCAGGGAAAG
CGGCGTTATGACCGCAAGCAGTCAGGATATGGTGGTCAGACCAAGCCCGTCTTCCACAAG
AAGGCCAAGACCACCAAGAAGATTGTGCTGAAGCTGCAGTGCCAGAGCTGCAAGCACTAC
TCGCAACACCCGATCAAAAGGTGCAAGCATTTTGAAATTGGTGGAGACAAGAAGGGCAAG
GGAACGTCTCTTTTCTA
>SORBI_3.PE2031                        317 CDS /gene="Sb02g022390" /gene_family="HOG000224989" /protein_id="
ATGGTGAACGTTCCTAAGACCAAGAAGACCTACTGCAAGAACAAGGAGTGCAAGAAGCAC
ACTCTCCACAAGGTGACTCAGTACAAGAAGGGTAAGGATAGCCTGTCTGCCCAGGGAAAG
CGCCGTTATGACCGCAAGCAGTCAGGATATGGTGGTCAGACCAAGCCTGTCTTCCACAAG
AAGGCTAAGACCACCAAGAAGATTGTGCTGAAGCTGCAGTGCCAGAGCTGCAAGCACTAC
TCACAGCACGCAATCAAGAGGTGCAAGCATTTTGAGATTGGTGGAGACAAGAAGGGCAAG
GGAACATCTCTTTTCTA
>SORBI_3.PE3602                        315 CDS /gene="Sb02g034975" /gene_family="HOG000224989" /protein_id="
GTGAACGTTCCTAAGACCAAGAAGACCTACTGCAAGAACAAGGAGTGCAAGAAGCACACT
CTCCACAAGGTGACTCAGTACAAGAAGGGTAAGGATAGCCTGTCTGCCCAGGGAAAGCGC
CGTTATGACCACAAGCAGTCAGGATATGGTGGTCAGACCAAGCCTGTCTTCCACAAGAAG
GCCAAGACCACCAAGAAGATTATGCTGAAGCTGCAGTGCCAGAGCTGCAAGCACTACTCA
CAACACGCAATCAAGAGGTGCAAGCATTTTGAGATTGGTGGAGACAAGAAGGGCAAGGGA
ACATCTCTTTTCTAA
>TRBRU1_13.PE300                       321 CDS /locus_tag="Tb11.02.0740" /gene_family="HOG000224989" /codon
ATGGTCAACTACCCGAAGAAAAAGAAGATGCACTGCCCTGATGAGCGGTGCAACGCTCAC
AAGAGCTTCAAGGTTGTGCAGTACAAGGCTGGCAAGGCGCGCCTGTACGCCCGAGGTAAG
CGTCGCTACGACCGCAAGCAGTCTGGTTATGGTGGTCAGACAAAGCCCATCTTTCACAAA
AAGGCGAAGACGACCAAGAAGATTGTTCTGAAGCTTCAGTGTTCTAACTGCAAATCGATT
ATCCAGAACGTGCTGAAGCGCACGAAGCACTTCGAGCTGAACGACAAAAAGAAGACTGGC
AACAAGGACCCCACTTGGTAG
>TUPGBGS_5190.PE2                      321 CDS /gene="ENSTBEG00000004681" /gene_family="HOG000224989" /pro
ATGGTCAATGTACCTAAAACTCGAAGGACTTTCTGTAAGAAATGTGGCAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAGGATTCCCTGTATGCTCAAGGGAAGAGGCGC
TACGACCGGAAGCAGAGTGGCTATGGTGGGCAGACAAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATTGTCCTAAGGCTTGAGTGTGTTGAACCGAACTGCAGATCCAAG
AGGATGCTGGCCATTAAAAGATGCAAACATTTTGAACTGGGGGGAGATAAGAAGAGAAAG
GGCCAGGTGATCCAGTTCTAA
>TURTRGS_3540.PE3                      321 CDS /gene="ENSTTRG00000007651" /gene_family="HOG000224989" /pro
ATGGTCAATGTACCTAAAACCCGAAGGACTTTCTGTAAGAAGTGTGGAAAGCATCAGCCT
CACAAAGTGACCCAGTATAAGAAGGGCAAAGATTCCCTGTATGCCCAGGGAAAGAGGCGC
TATGATCGGAAGCAGAGTGGCTATGGTGGGCAAACAAAGCCAATTTTCCGGAAGAAGGCT
AAAACCACAAAGAAGATCGTACTGAGGCTTGAATGTGTTGAGCCCAACTGCAGGTCCAAG
AGGATGCTGGCCATTAAGAGATGCAAGCATTTTGAACTCGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAATTCTAA
>TURTRGS_574.PE5                       321 CDS /gene="ENSTTRG00000012779" /gene_family="HOG000224989" /prot
ATGGTGAACGTTCCTAAAACCCGCCGGACTTTCTGTAAGAAGTGCGGCAAGCACCAACCC
CACAAAGTGACACAGTACAAGAAGGGCAAGGATTCTCTGTATGCCCAGGGAAAGCGGCGT
TATGACAGGAAGCAGAGTGGCTATGGTGGGCAGACTAAGCCGATTTTCCGGAAAAAGGCT
AAAACTACAAAGAAGATTGTGCTGAGGCTTGAATGTGTTGAGCCGAACTGCAGATCTAAG
AGAATGCTGGCTATTAAGAGATGCAAGCATTTTGAGCTGGGAGGAGATAAGAAGAGAAAG
GGCCAAGTGATCCAGTTCTGA
>YEASTVIII.PE229                       321 CDS /gene="YHR141C" /gene_family="HOG000224989" /protein_id="YHR
ATGGTTAACGTCCCAAAGACCAGAAAGACCTACTGTAAGGGTAAGACCTGTCGTAAGCAC
ACTCAACACAAGGTTACTCAATACAAAGCTGGTAAGGCTTCCTTGTTCGCTCAAGGTAAG
AGACGTTATGACCGTAAACAATCTGGTTTCGGTGGTCAAACCAAGCCTGTTTTCCACAAG
AAAGCTAAGACTACCAAGAAGGTTGTTTTGAGATTGGAATGTGTCAAATGTAAGACTAGA
GCCCAATTAACCTTGAAGAGATGTAAGCACTTCGAATTGGGTGGTGAAAAGAAGCAAAAG
GGTCAAGCTTTGCAATTCTGA
>YEASTXIV.PE184                        321 CDS /gene="YNL162W" /gene_family="HOG000224989" /protein_id="YNL1
ATGGTTAACGTTCCAAAGACCAGAAAGACCTACTGTAAGGGTAAGACCTGTCGTAAGCAC
ACTCAACACAAGGTTACTCAATACAAAGCTGGTAAGGCTTCCTTGTTTGCCCAAGGTAAG
AGACGTTATGACCGTAAACAATCTGGTTTCGGTGGTCAAACCAAGCCTGTTTTCCACAAG
AAAGCTAAGACTACCAAGAAGGTTGTTTTGAGATTGGAATGTGTCAAATGTAAGACCAGA
GCCCAATTGACCTTGAAGAGATGCAAGCACTTCGAATTGGGTGGTGAAAAGAAGCAAAAG
GGTCAAGCTTTGCAATTCTGA
>ZYGRO_7.PE206                         321 CDS /locus_tag="ZYRO0G05192g" /gene_family="HOG000224989" /old_loc
ATGGTTAACGTTCCAAAGACCAGAAAGACCTACTGCAAGGGTAAGACCTGCCGTAAGCAC
ACCCAACACAAGGTTACTCAGTACAAGGCTGGTAAGGCTTCCTTGTTCGCTCAAGGTAAG
AGACGTTATGACCGTAAGCAAAGAGGTTTCGGTGGTCAAACCAAACCTATCTTCCGTAGA
AAGGCAAAGACTACTAAGAAGGTCGTTTTGAGACTGGAGTGTGTCCAATGTAAGACCAGA
GCCCAATTGAGTTTGAAGAGATGCAAGCACTTCGAATTGGGTGGTGAAAAGAAACAAAAG
GGCCAAGCTTTGCAATTCTAA
